### ISSUE TITLE
Packages structure

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#1]
In Matlab we have the (Basis-)Toolbox and the Reporting Engine.
How should the package structure look like in R? E.g. 
* All-in-One package or 
* Toolbox and Reporting Engine or
* Reporting Engine basic and Reporting Engine advanced or ...

**Comment by msevestre** [comment]
@Yuri05 Any more thoughts on that?

**Comment by Yuri05** [comment]
_My_ opinion: All-in-one package. Thus `OSPSuite-R`-package should include both the current "Basic toolbox" functionality as well as the "Reproting Engine"-functionality

**Comment by PavelBal** [comment]
The TLF-functionality will be part of the reporting engine? In this case I also vote for all-in-one package - R-Toolbox should not only provide methods to simulate models, but also create standard graphics etc.

**Comment by Yuri05** [comment]
no, TLF should become a standalone package (which is a prereq for ospsuite-r)

**Comment by msevestre** [comment]
To me it seems that the ReportingEngine and OSPSUite-R are different beasts to be honest. I also believe that they will have different release cycle.

My vote would be to separate them

**Comment by PavelBal** [comment]
Yes, then I also vote for separating.

**Comment by msevestre** [comment]
two packages
