### ISSUE TITLE
getContainer vs getContainers

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#100]
@msevestre 
For each getter-function, you implemented two public versions - get one (e.g. `getContainer`) and get all (e.g. `getContainers`). Do you think this is the right way?

I don't like it. There are two functions providing almost the same result, but have to be accessed differently (`getContainers()[[idx]]` vs `getContainers()`). This is a) just increasing the amount of publicly available functions and b) it is easy to accidentially select the wrong one (e.g. by autocomplete).

I would just implement the `getContainers()` (and all others). No big deal for a user to check if there are multiple outputs.

**Comment by msevestre** [comment]
@PavelBal I see your point.
However the semantic of those methods are different. Maybe the `getParameter` should be renamed to `getSingleParameter`. 

> No big deal for a user to check if there are multiple outputs.

My goal is exactly to avoid this. Having the user code spread with ifs everywhere to make sure he did not mess up the path. 

I honestly do not know if we will need this method at all. I could imagine that sometime you want to get a parameter and update the value right away. If you forget to check that there is only one, you might update the WRONG parameter

Maybe the method should throw an exception if the parameter is not found also

e.g. 

```
par <-getSingleParameter(c("Organism", "Liver", Vol*"), sim)

# HERE I KNOW THAT PAR WAS FOUND and was unique according to my search criteria. Do need to check anything
par$value <- 5

# In theory you can also do
getSingleParameter(c("Organism", "Liver", Vol*"), sim)$value <-5
```

So what about we renamed them for now and delete them if we realize they are not required?

**Comment by PavelBal** [comment]
Hm, how about `getParameter()` and `getAllParameters()`? Or `getParametersMatching()`... I just think that getting single parameter is a more common task, so I would keep the name of the according function simple.

Regarding exceptions: I would return `NULL` for single parameter, and just an empty list for multiple parameters. Both can then be checked by `length(result)`. Throwing an exception is too harsh as I can think of use-cases where I don't know whether the parameter exists or not.

**Comment by msevestre** [comment]
>Regarding exceptions: I would return NULL for single parameter, and just an empty list for multiple parameters.

This is what is happening now. Ok I will rename to `getAllParametersMatching` :)  that way this is almost the same name as in .NET
