### ISSUE TITLE
Use cat instead of print in the $print() method of objects

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#101]
If using `print()`, the returned value is a list:

```
  public = list(
    print = function(...) {
      print(paste0("Parameter '", self$path, "' has a value of ", self$value))
      invisible(self)
    }
  )
```

```
> param
[[1]]
[1] "Parameter 'S1|Organism|Weight' has a value of 73.0000002396407"

```

Instead, using `cat` produces imo a more tidy output:

```
  public = list(
    print = function(...) {
      cat(paste0("Parameter '", self$path, "' has a value of ", self$value))
      invisible(self)
    }
  )
```

```
> param
[1] "Parameter 'S1|Organism|Weight' has a value of 73.0000002396407"

```

**Comment by msevestre** [comment]
@PavelBal Yeah absolutely. This method was just to debug. Not sure if we will need it or not

**Comment by PavelBal** [comment]
I would like to have the `$print()` method for almost all of the classes (not for wrapper or entity)

**Comment by msevestre** [comment]
ok. The one for parameter needs improvement (with unit for example) and maybe type of parameters etc.. Maybe more of a table in fact
name
value
dimension
unit

etc..
