### ISSUE TITLE
`SimulationBatch`- initialize on creation?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1029]
I think it makes sense to trigger initialization of a `SimulationBatch` upon it's creation and not on the first run. This would ensure that changes to the simulation **after** creation of the batch are not reflected in the batch and would be more consistent compared to the current behavior.

Right now, changes to the simulation object that are made **after** batch creation but **before** the first run are reflected, changes made after the first run are not reflected. This is hard to anticipate and took me quite some time to understand. Example:

1) Load simulation, create batch, run batch, **clear** simulation output schema and run the batch once more - the new output schema is not considered (and actually the expected behavior):

```
# Load the simulation from file - adjust the path accordingly
simulation <- loadSimulation(file.path(getwd(), "../Models/Simulations", "Vehicle.pkml"))
paramPath <- c("Organism|Tumor|Intracellular|k1", "Organism|Tumor|Intracellular|k2")

# Create simulation batch from simulation with original output schema
simBatch <- createSimulationBatch(simulation = simulation,
                                  parametersOrPaths = paramPath)
# 1 - Run simulation batch
simBatch$addRunValues(parameterValues = c(1e-4, 1e-4))
results <- runSimulationBatches(simBatch)

> results
[[1]]
[[1]]$`7080c7af-be22-4d34-a35e-9d51684a343a`
SimulationResults: 
   Number of individuals: 1 
```

Clear output schema and run the batch - results still generated ( == output schema used in the batch has not been updated)

```
# 2 - Clear output schema of the simulation and add new run
simulation$outputSchema$clear()
simBatch$addRunValues(parameterValues = c(1e-4, 1e-4))
results <- runSimulationBatches(simBatch)

> results
[[1]]
[[1]]$`4f4d0a42-603c-4a3a-9cbf-0d810bd70382`
SimulationResults: 
   Number of individuals: 1 
```

2) Load simulation, create batch, **clear** simulation output schema and run the batch - the new output schema is applied to the batch and no results are generated:

```
simulation <- loadSimulation(file.path(getwd(), "../Models/Simulations", "Vehicle.pkml"))
simBatch <- createSimulationBatch(simulation = simulation,
                                  parametersOrPaths = paramPath)
simulation$outputSchema$clear()
# Run simulation batch
simBatch$addRunValues(parameterValues = c(1e-4, 1e-4))
results <- runSimulationBatches(simBatch)

> results
[[1]]
[[1]]$`337f0e05-e290-4f06-8dbd-773bd3533206`
SimulationResults: 
   Number of individuals: 0 
```

**Comment by PavelBal** [comment]
This is actually important for Parameter identification. @abdelr could you look into it?

**Comment by msevestre** [comment]
Note to self: This means ensuring that the simulation is cloned when the simulation batch is created

**Comment by PavelBal** [comment]
Seems to work!
