### ISSUE TITLE
Cache already created parameter objects

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#103]
As discussed in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/67

**Comment by msevestre** [comment]
@PavelBal Please let's wait with that until we understand how parameters will be used.
It won't be often that people will retrieve 20+ parameters a 1000 times. 
Cache is great, but it comes with having to deal with cache invalidation. When do we release those objects.. etc. 

So we know we can improve here. Let's just not prematurely optimize a non-issue

**Comment by PavelBal** [comment]
OK.

**Comment by msevestre** [comment]
closing for now
