### ISSUE TITLE
toUnit/toBaseUnit fail to convert inputs from mass units smaller than "mg"

### ISSUE THREAD

**Issue by ReneGeci** [Open-Systems-Pharmacology/OSPSuite-R#1033]
i would like to convert input values of different unit types to BaseUnits for "Dose per body weight" (ie to "kg/kg")

but toUnit and toBaseUnit fail to convert input units that are smaller than "mg/[...]" (ie "µg/kg", "ng/kg"...)

```
> toBaseUnit("Dose per body weight", 10, unit  = "kg/kg")
[1] 10
> 
> toBaseUnit("Dose per body weight", 10, unit  = "mg/kg")
[1] 1e-05
> 
> toBaseUnit("Dose per body weight", 10, unit  = "µg/kg")
Error in rClr::clrCall(dimensionTask, "ConvertToBaseUnit", dimension,  : 
  Type:    OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Unit 'µg/kg' is not defined in dimension 'Dose per body weight'.
Method:  Double[] convertToBaseUnit(OSPSuite.Core.Domain.UnitSystem.IDimension, System.String, System.Nullable`1[System.Double], Double[])
Stack trace:
   bei OSPSuite.R.Services.DimensionTask.convertToBaseUnit(IDimension dimension, String displayUnit, Nullable`1 molWeight, Double[] valuesInDisplayUnit)
   bei OSPSuite.R.Services.DimensionTask.ConvertToBaseUnit(String dimensionName, String displayUnit, Double valueInDisplayUnit)

> 
> toBaseUnit("Dose per body weight", 10, unit  = "ng/kg")
Error in rClr::clrCall(dimensionTask, "ConvertToBaseUnit", dimension,  : 
  Type:    OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Unit 'ng/kg' is not defined in dimension 'Dose per body weight'.
Method:  Double[] convertToBaseUnit(OSPSuite.Core.Domain.UnitSystem.IDimension, System.String, System.Nullable`1[System.Double], Double[])
Stack trace:
   bei OSPSuite.R.Services.DimensionTask.convertToBaseUnit(IDimension dimension, String displayUnit, Nullable`1 molWeight, Double[] valuesInDisplayUnit)
   bei OSPSuite.R.Services.DimensionTask.ConvertToBaseUnit(String dimensionName, String displayUnit, Double valueInDisplayUnit)

```

even though, the direct conversion of dimension "Mass" to these units is supported:

```
> toBaseUnit("Mass", 10, unit  = "kg")
[1] 10
> 
> toBaseUnit("Mass", 10, unit  = "mg")
[1] 1e-05
> 
> toBaseUnit("Mass", 10, unit  = "µg")
[1] 1e-08
> 
> toBaseUnit("Mass", 10, unit  = "ng")
[1] 1e-11
```

**Comment by PavelBal** [comment]
@ReneGeci we can schedule a meeting where I cal walk you through, if you like.

**Comment by ReneGeci** [comment]
thanks, for the quick response!

i agree @msevestre and will talk to @PavelBal 

guess it would be nice if it would at least also support the units used in 
[Database-for-observed-data ](https://github.com/Open-Systems-Pharmacology/Database-for-observed-data)

**Comment by IndrajeetPatil** [comment]
See https://github.com/Open-Systems-Pharmacology/OSPSuite.Dimensions/pull/28

@ReneGeci Feel free to make another PR if you want to support some other conversions I did not cover.

**Comment by ReneGeci** [comment]
thanks @IndrajeetPatil! didnt see you already solved this :)

**Comment by msevestre** [comment]
Hum. Me neither. I just merged @ReneGeci PR.
Is there anything more than the two entries added by @ReneGeci . Can you rebase your PR on master @IndrajeetPatil

**Comment by IndrajeetPatil** [comment]
> Is there anything more than the two entries added by @ReneGeci .

Yes.

>  Can you rebase your PR on master @IndrajeetPatil

Done.
