### ISSUE TITLE
`.getSuiteVersion` returns only 11 for version 11.1

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1041]
I do not really understand how this is implemented:

```
  version <- getNamespaceVersion("ospsuite")
  first <- head(unlist(gregexpr(pattern = "\\.", version)), 1)
  return(unname(substr(version, 1, first - 1)))
```

But it returns 11 for 11.1. This might be the cause why PKSim is not loaded.

**Comment by msevestre** [comment]
No this is correct
But or you have 11 and 11.1 you will have problems
If you path the path to 11.1, that should work however

**Comment by msevestre** [comment]
The idea is to be able to update PKSim and Mobi without having to alos update r etc.. the .Y in X.Y is the update number.  The use case was for when we do small bug fixes . This is not the case with this update

**Comment by PavelBal** [comment]
Oh boi, that's complicated...
