### ISSUE TITLE
Create a Wiki entry for how to use snapshot testing in R

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#1043]

**Comment by IndrajeetPatil** [comment]
I tried to create a Wiki for this, but the format turned out to be completely insufficient for including what I think should be included in a document like this.

So I have created a slide deck instead:
https://indrajeetpatil.github.io/intro-to-snapshot-testing/

I'll leave it up to you to decide if you want to further boil it down to a leaner Wiki document, or just rely on the slide deck instead.

**Comment by PavelBal** [comment]
Awesome.

Let's add a very condensed info about how to update/revie snapshots (so basically we know what to do if tests are failing because of the snapshots) to coding standards (or where do we have such info) and a link to the esqlabs-fork: https://esqlabs.github.io/intro-to-snapshot-testing/#/title-slide

**Comment by PavelBal** [comment]
https://esqlabs.github.io/intro-to-snapshot-testing/#/title-slide

Done

**Comment by IndrajeetPatil** [comment]
For the posterity, the most up-to-date version will always be found here:
https://indrajeetpatil.github.io/intro-to-snapshot-testing/

**Comment by IndrajeetPatil** [comment]
Also, of interest: https://indrajeetpatil.github.io/dry-r-package-development

**Comment by PavelBal** [comment]
> Also, of interest: https://indrajeetpatil.github.io/dry-r-package-development

Nice! Thank you!

**Comment by IndrajeetPatil** [comment]
Here is another one on automation infrastructure for package development:

https://indrajeetpatil.github.io/preventive-r-package-care
