### ISSUE TITLE
Don't run simulation each time for tests; use a stored example instead

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#1056]
Current code I am using in tests, which makes the test stochastic:

```r
populationCharacteristics <- createPopulationCharacteristics(
  species = Species$Human,
  population = HumanPopulation$Asian_Tanaka_1996,
  numberOfIndividuals = 50,
  proportionOfFemales = 50,
  weightMin = 30,
  weightMax = 98,
  weightUnit = "kg",
  heightMin = NULL,
  heightMax = NULL,
  ageMin = 0,
  ageMax = 80,
  ageUnit = "year(s)"
)

# Create population from population characteristics
result <- createPopulation(populationCharacteristics = populationCharacteristics)
myPopulation <- result$population

# Load simulation
simFilePath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
sim <- loadSimulation(simFilePath)

set.seed(123)
populationResults <- runSimulation(
  simulation = sim,
  population = myPopulation
)

myDataComb <- DataCombined$new()
myDataComb$addSimulationResults(populationResults)
```

Better to use a stored example. @PavelBal Can you please suggest an example to use for this test?

Currently, `plotPopulationTimeProfile()` is severely under-tested because I haven't been able to create many test cases.

**Comment by PavelBal** [comment]
From the example above, just store the results in a csv file

`exportResultsToCSV(populationResults, "./SimResults_pop.csv")`

And then load them for the tests the same way you are loading individual results:

`populationResults <- importResultsFromCSV(simulation = sim, filePaths = system.file("extdata", "SimResults_pop.csv", package = "ospsuite"))`

**Comment by Yuri05** [comment]
I agree, for the tests which do not check the population run itself but only the plots it would be better to use stored population results. Just one remark: in order to make the population run results deterministic, it is sufficient to pass the random seed to the `createPopulationCharacteristics `function: 

![grafik](https://user-images.githubusercontent.com/25061876/182124502-dc87398f-acc0-48b9-bb2b-7911963ffb78.png)
