### ISSUE TITLE
Nighty failing because of some snapshots outdated

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#1060]
@IndrajeetPatil @PavelBal 
Can we fix this please?

![image](https://user-images.githubusercontent.com/1041237/182963543-08ca5d15-ca2f-430f-a1ed-ad41aa75f08b.png)

  Execution halted
Running the tests in 'tests/vdiffr.[rR]' failed.
Last 13 lines of output:
  < <polyline points='38.79,109.89 567.20,109.89 ' style='stroke-width: 0.53; stro
  : ke: #FFFFFF; stroke-linecap: butt;' />                                        
  < <polyline points='112.41,532.29 112.41,36.15 ' style='stroke-width: 0.53; stro
  : ke: #FFFFFF; stroke-linecap: butt;' />                                        
  < <polyline points='211.62,532.29 211.62,36.15 ' style='stroke-width: 0.53; stro
  : ke: #FFFFFF; stroke-linecap: butt;' />                                        
  < <polyline points='310.82,532.29 310.82,36.15 ' style='stroke-width: 0.53; stro
  : ke: #FFFFFF; stroke-linecap: butt;' />                                        
  < <polyline points='410.02,532.29 410.02,36.15 ' style='stroke-width: 0.53; stro
  : ke: #FFFFFF; stroke-linecap: butt;' />                                        
  < <polyline points='509.23,532.29 509.23,36.15 ' style='stroke-width: 0.53; stro
  : ke: #FFFFFF; stroke-linecap: butt;' />                                        
    </g>

**Comment by IndrajeetPatil** [comment]
As soon as #1054 is merged, this should be fixed. 

Just waiting a review and approval.
