### ISSUE TITLE
unnecessary files in .tar.gz packages

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#1066]
![grafik](https://user-images.githubusercontent.com/25061876/183650015-a33f4eb7-e498-49d6-a4ee-70c0193bea54.png)

zip package is ok
![grafik](https://user-images.githubusercontent.com/25061876/183650233-719ca2bd-a7b7-4151-8348-a3f0cfe59582.png)

**Comment by IndrajeetPatil** [comment]
We just need to tweak this regex in `.Rbuildignore` to cover these files:

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/7f589a7b3a971828eef8c7bde467e7abb8e927d8/.Rbuildignore#L3

**Comment by IndrajeetPatil** [comment]
This should do the trick:

```dcf
(^appveyor)(.*)(.yml$)
```
