### ISSUE TITLE
`DataCombined` - allow specifying dataType (observed or simulated)

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1067]
Add a method to specify type of the data - "observed" or "simulated".

This will allow to manually add data (e.g. by creating `DataSet` objects) and use it in `plotObservedVsSimulated`, or plot it as simulated data in profile plots.

DataCombined$setDataType(name, dataType).

**Comment by IndrajeetPatil** [comment]
> Add a method to specify type of the data - "observed" or "simulated".

But the methods themselves make this distinction already: `$addDataSets()` (for observed) or `$addSimulationResults()` (for simulated).

> This will allow to manually add data (e.g. by creating `DataSet` objects) 

Why not just use the existing `$addDataSets()` method here?

**Comment by PavelBal** [comment]
> Why not just use the existing $addDataSets() method here?

Exactly, if I manually create two `DataSet` objects and add them to `DataMapping`, I cannot use this data mapping in `plotObservedVsSimulated`. There is no way to create "simulated" results.

**Comment by IndrajeetPatil** [comment]
You mean, _in an existing group_, which already has one observed and one simulated data, you want to add only additional observed data, correct? 

If yes, then this should work:

```r
myDataCombined$addDataSets(dataSet2, groups = "myExistingGroup")
```

**Comment by PavelBal** [comment]
No, _only_  add data through `DataSet` and use it as simulated values:

```
simData <- DataSet$new(name = "Simulated")
simData$setValues(xValues = c(0, 2, 4), yValues = c(0, 4, 8))


obsData <- DataSet$new(name = "Observed")
obsData$setValues(xValues = c(1, 3, 3.5, 4, 5), yValues = c(1.9, 6.1, 7, 8.2, 1))

myDC <- DataCombined$new()
myDC$addDataSets(c(simData, obsData), groups = "myGroup")

plotIndividualTimeProfile(myDC)
plotObservedVsSimulated(myDC)
```

**Comment by Felixmil** [comment]
According to this, the `addDataSets()` could have a new argument: `types` that would be a character vector the same length of `dataSets` argument to setup de dataCombined in one go, for exemple:

```r
...
myDC <- DataCombined$new()
myDC$addDataSets(c(simData, obsData), types = c("sim", "obs") , groups = "myGroup")
```

Under the hood, it would use the same  `DataCombined$setDataType(name, dataType)` you suggested @PavelBal.

Would it make sense ?

**Comment by PavelBal** [comment]
@Felixmil Ok this sound more complex. I would not pursue it for now and revisit when doing the complete re-implementation of `DataCombined`.

**Comment by Felixmil** [comment]
The goal is to create simulationResult directly from code

**Comment by PavelBal** [comment]
Why not just write a function `setDataType(name, dataType)`, which changes the content of the column `dataType´ in `private$.dataCombined`? And also updates `private$.dataType`.

**Comment by Felixmil** [comment]
Because the whole process of transforming dataSets to dataframe that is used when $addDataSets is called is Observed Data specific. These cannot be reused for simulation data.
Take a look at:

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/0dbfc9ba324aece14567eaa455f53a383cd9641a/R/data-combined.R#L91-L131

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/0dbfc9ba324aece14567eaa455f53a383cd9641a/R/utilities-data-set.R#L49C7-L76

**Comment by PavelBal** [comment]
It's not about adding the data, it's just abour setting the type in the final data frame..

**Comment by Felixmil** [comment]
Well, for the data to be in the final data frame, it must be added to it first.
The only way to add data that was "manually" created and not imported from csv is `DataCombined$addDataSets()`.
`DataCombined$addDataSets()` can only add object of `DataSet` class.
`DataSet` was designed to contain observedData only.
