### ISSUE TITLE
`plotResidualsVsTime` and `plotResidualsVsSimulated` - residuals are inverted

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1077]
Residuals are now calculated as observed - simulated, though it should be simulated - observed (as defined here https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/parameter-identification#mapping-simulation-outputs-to-observed-data).

**Comment by IndrajeetPatil** [comment]
Hmm, I just followed what we are doing in the reporting engine. I guess it also needs to be changed there then?

https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/3a3aa9ac469643a0a50db34ca4b4aafdeae71250/R/utilities-goodness-of-fit.R#L189-L194

**Comment by PavelBal** [comment]
Interesting... Yes, indeed, I think it should also be changed there. @Yuri05
