### ISSUE TITLE
Output of the `calculateResiduals()` function

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1092]
I have some comments/questions about the `calculateResiduals()` function resp. its output.

- Observed values are stored in the colum `yValues`, simulated in `predictedValues`. Could we rename the columns to `yValuesObserved` and `yValuesSimulated`, to make it more obvious?
- Why do we need the columns  `yValuesLower` and `yValuesUpper` in this user-oriented function? I would be (and actually am) confused about what these columns are about.
- The dimensions `Concentration (molar)` and `Concentration (mass)` are substituted by `Concentration`, which actually not a valid dimension and therefore could not be further used by the user. I think this substitution should be performed by the functions that require it, and not in the output.
- I think including the name of the data set could be useful, especially when e.g. multiple observed data are mapped to one simulated data (or vice versa)
- `yErrorType` and `yErrorUnit` is probably also required by the plotting functions?

**Comment by IndrajeetPatil** [comment]
- [ ] Observed values are stored in the colum `yValues`, simulated in `predictedValues`. Could we rename the columns to `yValuesObserved` and `yValuesSimulated`, to make it more obvious?
- [ ] Why do we need the columns  `yValuesLower` and `yValuesUpper` in this user-oriented function? I would be (and actually am) confused about what these columns are about.
- [ ] The dimensions `Concentration (molar)` and `Concentration (mass)` are substituted by `Concentration`, which actually not a valid dimension and therefore could not be further used by the user. I think this substitution should be performed by the functions that require it, and not in the output.
- [ ] I think including the name of the data set could be useful, especially when e.g. multiple observed data are mapped to one simulated data (or vice versa)
- [ ] `yErrorType` and `yErrorUnit` is probably also required by the plotting functions?

This is unrelated to `calculateResiduals()`

> The dimensions `Concentration (molar)` and `Concentration (mass)` are substituted by `Concentration`, which actually not a valid dimension and therefore could not be further used by the user. I think this substitution should be performed by the functions that require it, and not in the output.

This is coming from `.unitConverter()`, and should be a separate issue:

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/f289841e9111db7a67a3e15c85b62156db56b929/R/utilities-units.R#L565-L592

**Comment by IndrajeetPatil** [comment]
Output with #1090 

``` r
library(ospsuite)
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000
options(tibble.width = Inf)

# simulated data
simFilePath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
sim <- loadSimulation(simFilePath)
simResults <- runSimulation(sim)
outputPath <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"

# observed data
obsData <- lapply(
  c("ObsDataAciclovir_1.pkml", "ObsDataAciclovir_2.pkml", "ObsDataAciclovir_3.pkml"),
  function(x) loadDataSetFromPKML(system.file("extdata", x, package = "ospsuite"))
)
names(obsData) <- lapply(obsData, function(x) x$name)


# Create a new instance of `DataCombined` class
myDataCombined <- DataCombined$new()

# Add simulated results
myDataCombined$addSimulationResults(
  simulationResults = simResults,
  quantitiesOrPaths = outputPath,
  groups = "Aciclovir PVB"
)

# Add observed data set
myDataCombined$addDataSets(obsData$`Vergin 1995.Iv`, groups = "Aciclovir PVB")

calculateResiduals(myDataCombined, scaling = tlf::Scaling$lin)
#> # A tibble: 13 x 13
#>    group         name           xValues xUnit xDimension yValuesObserved yUnit 
#>    <chr>         <chr>            <dbl> <chr> <chr>                <dbl> <chr> 
#>  1 Aciclovir PVB Vergin 1995.Iv    13.4 min   Time                35.0   µmol/l
#>  2 Aciclovir PVB Vergin 1995.Iv    29.1 min   Time                20.0   µmol/l
#>  3 Aciclovir PVB Vergin 1995.Iv    44.7 min   Time                14.1   µmol/l
#>  4 Aciclovir PVB Vergin 1995.Iv    58.1 min   Time                11.0   µmol/l
#>  5 Aciclovir PVB Vergin 1995.Iv    87.2 min   Time                 7.51  µmol/l
#>  6 Aciclovir PVB Vergin 1995.Iv   119.  min   Time                 5.88  µmol/l
#>  7 Aciclovir PVB Vergin 1995.Iv   179.  min   Time                 4.03  µmol/l
#>  8 Aciclovir PVB Vergin 1995.Iv   239.  min   Time                 3.05  µmol/l
#>  9 Aciclovir PVB Vergin 1995.Iv   360   min   Time                 1.63  µmol/l
#> 10 Aciclovir PVB Vergin 1995.Iv   541.  min   Time                 0.871 µmol/l
#> 11 Aciclovir PVB Vergin 1995.Iv   720   min   Time                 0.544 µmol/l
#> 12 Aciclovir PVB Vergin 1995.Iv   901.  min   Time                 0.435 µmol/l
#> 13 Aciclovir PVB Vergin 1995.Iv  1440   min   Time                 0.326 µmol/l
#>    yDimension    yErrorValues yErrorType       yErrorUnit yValuesSimulated
#>    <chr>                <dbl> <chr>            <chr>                 <dbl>
#>  1 Concentration        6.64  ArithmeticStdDev µmol/l              45.6   
#>  2 Concentration        3.81  ArithmeticStdDev µmol/l              19.2   
#>  3 Concentration        2.83  ArithmeticStdDev µmol/l              14.3   
#>  4 Concentration        2.29  ArithmeticStdDev µmol/l              12.9   
#>  5 Concentration        1.74  ArithmeticStdDev µmol/l              11.0   
#>  6 Concentration        1.20  ArithmeticStdDev µmol/l               9.45  
#>  7 Concentration        0.979 ArithmeticStdDev µmol/l               7.15  
#>  8 Concentration        0.653 ArithmeticStdDev µmol/l               5.41  
#>  9 Concentration        0.435 ArithmeticStdDev µmol/l               3.12  
#> 10 Concentration        0.218 ArithmeticStdDev µmol/l               1.38  
#> 11 Concentration        0.326 ArithmeticStdDev µmol/l               0.624 
#> 12 Concentration        0.326 ArithmeticStdDev µmol/l               0.288 
#> 13 Concentration        0.326 ArithmeticStdDev µmol/l               0.0325
#>    residualValues
#>             <dbl>
#>  1        10.5   
#>  2        -0.833 
#>  3         0.130 
#>  4         1.94  
#>  5         3.54  
#>  6         3.58  
#>  7         3.12  
#>  8         2.37  
#>  9         1.49  
#> 10         0.512 
#> 11         0.0801
#> 12        -0.148 
#> 13        -0.294
```

<sup>Created on 2022-08-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
