### ISSUE TITLE
Restore interpolation for residuals calculation

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1093]
Interpolation of simulated results has been disabled in one of the pull requests. This should be re-enabled as specified here https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/804

Currently there are two issues - values are not interpolated, and observed values beyod simulated time are mapped to the last simulated value. This *extrapolation* should be avioded and observed values beyod simulated time frame should be ignored.

```
simFilePath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
sim <- loadSimulation(simFilePath)

simData <- importResultsFromCSV(sim, "d:/SimResults.csv")

obsData <- DataSet$new(name = "Observed")
obsData$setValues(xValues = c(1, 3, 3.5, 4, 5), yValues = c(1.9, 6.1, 7, 8.2, 1))
obsData$xUnit <- "min"
obsData$yDimension <- ospDimensions$`Concentration (molar)`

myDC <- DataCombined$new()
myDC$addSimulationResults(simData, groups = "myGroup")
myDC$addDataSets(obsData, groups = "myGroup")

dc_df <- myDC$toDataFrame()

> dc_df
# A tibble: 8 × 15
  name                                                                      group   dataType  xValues xUnit xDimension yValues yUnit  yDimension            yErrorVa…¹ yErro…² yErro…³ Indiv…⁴ molWe…⁵  lloq
  <chr>                                                                     <chr>   <chr>       <dbl> <chr> <chr>        <dbl> <chr>  <chr>                      <dbl>   <dbl>   <dbl>   <int>   <dbl> <dbl>
1 Observed                                                                  myGroup observed      1   min   Time          1.90 µmol/l Concentration (molar)         NA      NA      NA      NA     NA     NA
2 Observed                                                                  myGroup observed      3   min   Time          6.10 µmol/l Concentration (molar)         NA      NA      NA      NA     NA     NA
3 Observed                                                                  myGroup observed      3.5 min   Time          7    µmol/l Concentration (molar)         NA      NA      NA      NA     NA     NA
4 Observed                                                                  myGroup observed      4   min   Time          8.20 µmol/l Concentration (molar)         NA      NA      NA      NA     NA     NA
5 Observed                                                                  myGroup observed      5   min   Time          1    µmol/l Concentration (molar)         NA      NA      NA      NA     NA     NA
6 Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood) myGroup simulated     0   min   Time          0    µmol/l Concentration (molar)         NA      NA      NA       0    225.    NA
7 Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood) myGroup simulated     2   min   Time          4    µmol/l Concentration (molar)         NA      NA      NA       0    225.    NA
8 Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood) myGroup simulated     4   min   Time          8    µmol/l Concentration (molar)         NA      NA      NA       0    225.    NA
```

The resulting residuls are:

resDf_lin <- calculateResiduals(dataCombined = myDC, scaling = "lin")
```
> resDf_lin
# A tibble: 5 × 12
  group   xValues xUnit xDimension yValues yValuesLower yValuesHigher yErrorValues yUnit  yDimension            predictedValues residualValues
  <chr>     <dbl> <chr> <chr>        <dbl>        <dbl>         <dbl>        <dbl> <chr>  <chr>                           <dbl>          <dbl>
1 myGroup     1   min   Time          1.90           NA            NA           NA µmol/l Concentration (molar)               0         -1.90 
2 myGroup     3   min   Time          6.10           NA            NA           NA µmol/l Concentration (molar)               4         -2.10 
3 myGroup     3.5 min   Time          7              NA            NA           NA µmol/l Concentration (molar)               8          1    
4 myGroup     4   min   Time          8.20           NA            NA           NA µmol/l Concentration (molar)               8         -0.200
5 myGroup     5   min   Time          1              NA            NA           NA µmol/l Concentration (molar)               8          7    
```

**Comment by IndrajeetPatil** [comment]
As for the first issue-

> values are not interpolated

I am not sure if this is an issue to begin with.

If you look at the changes in observed versus simulated plots (`tests/testthat/_snaps/plot-observed-vs-simulated/` files) in [this PR](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/1054/files), where

- the "Added" plots correspond to _without_ interpolation
- the "Deleted" plot correspond to _with_ interpolation

They look virtually identical. Given that the code complexity is far lower for an algorithm without interpolation, there has to be some excellent reason why interpolation _must be_ performed.

<img width="1026" alt="Screenshot 2022-08-17 at 14 36 57" src="https://user-images.githubusercontent.com/11330453/185126709-15997023-c45f-4a93-a76e-8132eff5c8ea.png">
<img width="1023" alt="Screenshot 2022-08-17 at 14 37 10" src="https://user-images.githubusercontent.com/11330453/185126750-d05dad98-c3f1-4735-aec5-b385b67f3664.png">
<img width="1021" alt="Screenshot 2022-08-17 at 14 37 22" src="https://user-images.githubusercontent.com/11330453/185126765-15314487-68c3-4716-8e09-1e3e0029db01.png">

**Comment by PavelBal** [comment]
The need for interpolation becomes obvious from the following example:

```
simFilePath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
sim <- loadSimulation(simFilePath)

simData <- simData <- withr::with_tempdir({
  df <- dplyr::tibble(
    IndividualId = c(0, 0, 0),
    `Time [min]` = c(0, 2, 4),
    `Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood) [µmol/l]` = c(0, 4, 8)
  )
  readr::write_csv(df, "SimResults.csv")
  importResultsFromCSV(sim, "SimResults.csv")
})

obsData <- DataSet$new(name = "Observed")
obsData$setValues(xValues = c(1, 3, 3.5, 4, 5), yValues = c(1.9, 6.1, 7, 8.2, 1))
obsData$xUnit <- "min"
obsData$yDimension <- ospDimensions$`Concentration (molar)`

myDC <- DataCombined$new()
myDC$addSimulationResults(simData, groups = "myGroup")
myDC$addDataSets(obsData, groups = "myGroup")
```

This is the time profile plot:

![image](https://user-images.githubusercontent.com/25903040/185416244-40b92360-0308-4f61-b8d5-e6ae0b489ba2.png)


And this is the corresponding residuals-vs-time plot:

![image](https://user-images.githubusercontent.com/25903040/185416411-3f74c89a-304b-484b-9ee9-7c232e7183b9.png)

It is very confusing that in the residuals-vs-time, the second residual is negative, though in the time profile plot the observed value is above the simulated line. Also the third point lies on the simulated line in the time profile plot, but has a rather high residual.

**Comment by IndrajeetPatil** [comment]
> It is very confusing that in the residuals-vs-time, the second residual is negative, though in the time profile plot the observed value is above the simulated line

But as specified [here](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1077), we are computing residuals as` simulated - observed`. 
So the residual at `Time = 3 min` should be negative, right?
