### ISSUE TITLE
How to: update vignettes, update docs

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1106]
What is our approach to:

- update vignettes,
- Update html docs

I see we do not build them locally and upload, are they automatically re-created by AppVeyor?

**Comment by msevestre** [comment]
vignettes are built on nightly and not on every PR
HTML are built once on release (by hand. we could not find a good way to do it automatically)

**Comment by PavelBal** [comment]
So:

- No need to trigger vignette building locally and sync files
- How to trigger html build?


The nightly and "standard" appveyor files differ significantly. Could we synch them and mark the required diffs (e.g. comment them)? @svavil could you please create an issue for this?

**Comment by PavelBal** [comment]
@msevestre @Yuri05 @svavil @IndrajeetPatil 

So, how to update the documentation? I have added two vignettes and would like to review (and share) them, but I do not know how to trigger the update. There was a PR https://github.com/Open-Systems-Pharmacology/OSPSuite-R/commit/36c01122b9f9aafa5559d9572268dbc2d14af1fe

> So that we can always have a look at the recent version of the docs and don't need to wait for the next release before we can update docs.

But I do not really know how to do it.

**Comment by msevestre** [comment]
or do yu mean updating the website?

**Comment by Yuri05** [comment]
@PavelBal 
I could update the website, unfortunately the new data combined vignettes crash when I'm trying to create them locally (as you know from the last PR 😉 )

To update the dev version of the website: 
* get the package source locally
* git delete **docs/dev** folder and commit
* in R: switch to the package root directory and call **pkgdown::build_site()**
* git add **docs/dev** folder and commit

As soon as the PR with this changes is merged, dev docu will be available at <docu-website>/dev

**Comment by IndrajeetPatil** [comment]
What Yuri said 👆

Probably worth adding this to the [Wiki](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/wiki/Generate-or-update-%7Bpkgdown%7D-website-for-the-package). Adding both the release and the development websites was one of the last things I did, and so didn't get to update the document to note down this new workflow.
