### ISSUE TITLE
loadSimulation: Optional: Cache simulation by path,

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#111]
Default is ?  DO NOT LOAD FROM CACHE or LOAD FROM CACHE ? :)

**Comment by Yuri05** [comment]
My opinion: default `LOAD FROM CACHE`

**Comment by KatrinCoboeken** [comment]
agree with Juri

**Comment by PavelBal** [comment]
For clarification:


```
pathName <- "../sim1.pkml"
sim1 <- loadSimulation(pathName)
sim2 <- loadSimulation(pathName)
```

`sim1 `and `sim2` would be the same object if cached. Following:

```
paramFromSim1 <- getParameter(paramPath, sim1)
paramFromSim2 <- getParameter(paramPath, sim2)
paramFromSim1$value
> 0
setParametersValues(paramFromSim2 , value = 1)
paramFromSim1$value
> 1
```

**Comment by msevestre** [comment]
Correct. All instances of parameters etc.. belonging to the simulation would be the same if cached.

I am ok with this as long as we document the usage of the flag clearly

**Comment by PavelBal** [comment]
For that, I would like to have the path stored in the simulation class, see https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/131

**Comment by PavelBal** [comment]
- Use environments as they hash the entries.

**Comment by PavelBal** [comment]
We have to think this through. Which cached simulation is returned by default, if two objects with the same path exist (created with `fromCache = FALSE`)? Example:

```
sim1 <- loadSimulation(pathtToPKML, fromCache = TRUE)
sim2 <- loadSimulation(pathToPKML, fromCache = FALSE)
```

`sim1 `and `sim2` are now two different simulation objects created from the same PKML. Now:
`
sim3 <- loadSimulation(pathToPKML, fromCache = TRUE)`
?

**Comment by msevestre** [comment]
I think we need to revisit this.
Why do we need this cache at the first place?
And especially, why is this the default behavior?
I do not see any use case, when using object reference as we do now, where this behavior is useful or expected

Because we have it, I am ok the leave it. But the default should be load from cache false

@Yuri05 @KatrinCoboeken @PavelBal 

Please feedback

**Comment by msevestre** [comment]
all right going to change this. Load from cache false
