### ISSUE TITLE
Bug in docu: Parameter$new()

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#1113]
https://www.open-systems-pharmacology.org/OSPSuite-R/reference/Parameter.html?q=rhs#details-1

The highlighted part in the description of Parameter$new() is somehow wrong in place
![grafik](https://user-images.githubusercontent.com/25061876/187874692-2e56b2c7-f6a8-4e5a-b3fc-1b58e1159802.png)

**Comment by PavelBal** [comment]
Will update in next commit.

**Comment by PavelBal** [comment]
This has been fixed here
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/commit/48daca03d32f299c9f416b9fe87af930b56e543d#diff-6e3c0816c487abd312c0d7548654ac855041fb1a7b38f6877da80806f71e5e20
