### ISSUE TITLE
Installation script: provide option for installation with unit tests

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#1126]
here, all osp packages should be installed with tests (if the option was set by user), e.g.
`install.packages(packagePaths$ospsuite.utils, repos = NULL, INSTALL_opts = "--install-tests")`

_Originally posted by @Yuri05 in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/1118#discussion_r969934537_

**Comment by Yuri05** [comment]
so https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1137 will be also included then? I can live with it :)

**Comment by PavelBal** [comment]
`...` will be only passed to the osp packages - tlf, ospsuite.utils, and osusuite. `lib` will be passed to all `install.packages()` calls.

**Comment by PavelBal** [comment]
Or woul you also like to install the tests for CRAN package?

**Comment by Yuri05** [comment]
>Or woul you also like to install the tests for CRAN package? 

no :)
