### ISSUE TITLE
Add unit conversion utilities

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#113]
I'd suggest to have some methods that have various parameters

## When a quantity is available (for example: parameter, output, molecule etc..)
convertToDisplayUnit(quantity) => convert the current value to displayUnit
convertToDisplayUnit(quantity, values) => convert the values to values in displayUnit

convertToBaseUnit(quantity, values) => convert the values in displayUnit to base unit

convertToUnit(quantity, values, unit) => convert the values in base values to the unit given as parameters

## When a quantity it not available (do we have this use case)

convertToBaseUnit(dimension, valuesInDisplayUnit, displayUnit) => convert the values in displayUnit to base unit

convertToUnit(dimension, values, unit) => convert the values in base values to the unit  

/cc @PavelBal @Yuri05 @KatrinCoboeken 

Thoughts?

What is missing is how do we deal with MW. I want to have a solution that is easy and clear and does not bring pain like what we have at the moment in the toolbox

**Comment by PavelBal** [comment]
I don't understand the "values" argument. What exactely are the inputs of these functions?

**Comment by msevestre** [comment]
I think this has been implemented already. issue with MW still remains but this is another topic
