### ISSUE TITLE
DataCombined Transformations (Y-ScaleFactor): adjust arithmetic error scaling

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#1131]
But this is in fact an error in the formula: for the arithmetic error it should be then 
`newErrorValue = rawErrorValue * abs(yScaleFactor)`

With this correction I think we can allow negative scale factors indeed

**Comment by PavelBal** [comment]
Duplicate of https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1130
