### ISSUE TITLE
`plotObservedVsSimulated`: no tick labels in log scale

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1144]
```
sim <- loadSimulation(system.file("extdata", "Aciclovir.pkml", package = "ospsuite"))

simData <- simData <- withr::with_tempdir({
  df <- dplyr::tibble(
    IndividualId = c(0, 0, 0),
    `Time [min]` = c(0, 2, 4),
    `Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood) [µmol/l]` = c(0, 4, 8)
  )
  readr::write_csv(df, "SimResults.csv")
  importResultsFromCSV(sim, "SimResults.csv")
})

obsData <- DataSet$new(name = "Observed")
obsData$setValues(xValues = c(1, 3, 3.5, 4, 5), yValues = c(1.9, 6.1, 7, 8.2, 1))
obsData$xUnit <- "min"
obsData$yDimension <- ospDimensions$`Concentration (molar)`

myDC <- DataCombined$new()
myDC$addSimulationResults(simData, groups = "myGroup")
myDC$addDataSets(obsData, groups = "myGroup")

obsData2 <- DataSet$new(name = "Observed 2")
obsData2$setValues(xValues = c(0, 3, 4, 4.5, 5.5), yValues = c(2.9, 5.1, 3, 8.2, 1))
obsData2$xUnit <- "min"
obsData2$yDimension <- ospDimensions$`Concentration (molar)`

myDC$addDataSets(obsData2, groups = "myGroup")

plotObservedVsSimulated(myDC)
```

![image](https://user-images.githubusercontent.com/25903040/192252900-200380c4-cba1-4af8-b012-1472e4b354ea.png)

**Comment by Felixmil** [comment]
The bug seem to come from the `updatePlot` methods in `xAxis` and `yAxis` objects:
https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/bfa759a74f2ef726b13759f2a02f6daf1d38c724/R/plotconfiguration-axis.R#L284

**Comment by Felixmil** [comment]
The plot is missing because of the default ticks `self$prettyTicks()` defined in `{tl}`  [here](https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/e30924b5dcd2665c015c1683acdec80be72eaa84/R/tlf-env.R#L168).
The default breaks are set to these values:
``` 
1e-10 1e-09 1e-08 1e-07 1e-06 1e-05 1e-04 1e-03 1e-02 1e-01 1e+00 1e+01 1e+02 1e+03 1e+04 1e+05 1e+06 1e+07 1e+08 1e+09 1e+10
```
However, the sample data here are all between 1 and 10. So the limits that are passed to the plotting function are contained within  two major breaks which are the only ones to be labelled.

**Comment by Felixmil** [comment]
This must be solved in `{tlf}`.
Opened an [issue](https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/417) in the repo with what I could find and a potential solution.
