### ISSUE TITLE
saveSimulation as .pkml or .pksim5 file as counterpart to loadSimulation

### ISSUE THREAD

**Issue by HenrikCordes** [Open-Systems-Pharmacology/OSPSuite-R#1167]
Dear @Open-Systems-Pharmacology/rdev,

I was wondering if we have / or planed a counterpart function to the loadSimulation.R, something like saveSimulation.R?
I imagin it to save a current sim to a pkml file [ saveSimulation(sim, path) ]
If I understood correctly, currently only simulation results (PK curves) can be stored.

Some background:
For an internal application, I would like to load a "generic" PBPK model and replace some PhysChem values etc with values I get from a database. 
Ideally I could save save the updated models pkml oder even better pksim files. 
Alternatively, could I also generate building blocks and import them into PK-Sim?  

Thank youf for helping out! 

Best,
Henrik

**Comment by Yuri05** [comment]
@HenrikCordes When saving a **modified** simulation to pkml, please be aware of https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/398

**Comment by HenrikCordes** [comment]
Hi @Yuri05, 
thank you for the heads up! 

My current take would be so save the updated simulation as .pkml and in addition the new / set parameters as table. 
This a user can "redo" the setting in PK-Sim if needed and compare the results via the .pkml export / import to MoBi.

Thank you,
Henrik
