### ISSUE TITLE
Nightly builds fail

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#1171]
Since couple of days nigthly builds started failing (without any code changes)

![grafik](https://user-images.githubusercontent.com/25061876/209795535-b434da3d-9fcf-42f1-81c1-d83415579c6a.png)

**Comment by rwmcintosh** [comment]
![image](https://user-images.githubusercontent.com/261477/210361813-d6bdd976-13c5-4d94-bac2-da36ef53e692.png)

The error log shows a package installation error - `purrr`

**Comment by rwmcintosh** [comment]
A new version of purrr was released Dec 20 which requires a new version of rlang. We can probably specify the previous version

https://cran.r-project.org/web/packages/purrr/index.html

**Comment by rwmcintosh** [comment]
A new release should come out soon

https://github.com/tidyverse/purrr/pull/1017

**Comment by rwmcintosh** [comment]
> A new version of purrr was released Dec 20 which requires a new version of rlang. We can probably specify the previous version
> 
> https://cran.r-project.org/web/packages/purrr/index.html

It's not the new versions of rlang, it's because the library `purrr` was configured to only build 64 bit.

Do we still need to support a 32 bit version? I'm not sure on usage, but the CI test is checking to make sure that both 64 bit and 32 bit versions can be installed.

**Comment by msevestre** [comment]
32 bit? That will definitely not work. Are you sure? We have not been supporting 32 bit for years now

**Comment by rwmcintosh** [comment]
Yeah, it's probably just that the tests are trying to load 32 bit dll and with purrr, the latest release did not compile a 32 bit version
If we just turn off this part of the testing, then everything will probably work again.

![image](https://user-images.githubusercontent.com/261477/210427362-3274c8f4-de47-45e4-913b-3ed7592a0a81.png)
