### ISSUE TITLE
Cannot install package anymore

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#1175]
The last package version I have installed is 11.1.168
Now I tried to install the latest nigthly (11.1.181) and failed both under R 3.6 and R 4.1 (under Windows):
```

> install.packages("C:/Temp/11.1beta/ospsuite_11.1.181.zip")
Warning in install.packages :
  package ‘C:/Temp/11.1beta/ospsuite_11.1.181.zip’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

**Comment by PavelBal** [comment]
Cannot reproduce:

```
> install.packages("D:/Downloads/ospsuite_11.1.181.zip", repos = NULL, type = "win.binary")
Installing package into ‘D:/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
package ‘ospsuite’ successfully unpacked and MD5 sums checked
```

**Comment by PavelBal** [comment]
Lol: 

```
> install.packages("D:/Downloads/ospsuite_11.1.181.zip")
Installing package into ‘D:/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘D:/Downloads/ospsuite_11.1.181.zip’ is not available (for R version 3.6.3)
```

so it does not work if I do not specify the `repos` argument. I have no idea what it does and why.

**Comment by PavelBal** [comment]
Looks like you have to specify `repos = NULL` if you want to install from a local zip. Are you sure it worked without the argument before?

> repos	
character vector, the base URL(s) of the repositories to use, e.g., the URL of a CRAN mirror such as "https://cloud.r-project.org". For more details on supported URL schemes see url.

>Can be NULL to install from local files, directories or URLs: this will be inferred by extension from pkgs if of length one.

**Comment by Yuri05** [comment]
@PavelBal you are right, `repos = NULL` did the trick. 
Pretty weird to force the user for that (when I pass a local zip file, I obviously want to use it and not any remote repos), but that's R

**Comment by PavelBal** [comment]
> Pretty weird [...] but that's R

I cannot disagree :D
