### ISSUE TITLE
Decouple the R package from PK-Sim

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1176]
I have a dream of a self-sufficient R package that would not require a PK-Sim installation, especially would not require matching versions of the Core libraries.

It would make us even more flexible in terms of releasing new versions of R package where we could introduce new features in Core that are required by R without the need to have a (unreleased) portable version of Pk-sim.

I have identified the files from PK-Sim that are required for the functionalities `initPKSim()`, `createIndividualCharacteristics()`, `createPopulationCharacteristics()`, and `createPopulation()`:

```
-a---          02/12/2022    21:02         434688 Castle.Core.dll
-a---          02/12/2022    21:02         351232 Castle.Windsor.dll
-a---          02/12/2022    21:02        5341648 DevExpress.Data.v21.2.dll
-a---          02/12/2022    21:02         525824 FluentNHibernate.dll
-a---          02/12/2022    21:02          89088 MarkdownLog.dll
-a---          02/12/2022    21:02         700336 Newtonsoft.Json.dll
-a---          02/12/2022    21:02         212992 Newtonsoft.Json.Schema.dll
-a---          02/12/2022    21:02        4200448 NHibernate.dll
-a---          02/12/2022    21:02        2097152 OSPSuite.Assets.Images.dll
-a---          06/01/2023    13:17          50437 OSPSuite.Dimensions.xml
-a---          02/12/2022    21:02          10752 OSPSuite.Infrastructure.Castle.dll
-a---          02/12/2022    21:02          19456 OSPSuite.Infrastructure.Export.dll
-a---          02/12/2022    21:02          36352 OSPSuite.Infrastructure.Reporting.dll
-a---          02/12/2022    21:02          90112 OSPSuite.Infrastructure.Serialization.dll
-a---          06/01/2023    13:17           7032 OSPSuite.PKParameters.xml
-a---          02/12/2022    21:02         791040 OSPSuite.Presentation.dll
-a---          02/12/2022    21:02          13312 OSPSuite.Presentation.Serialization.dll
-a---          02/12/2022    21:02         125440 OSPSuite.TeXReporting.dll
-a---          02/12/2022    21:02         174080 PKSim.Assets.dll
-a---          02/12/2022    21:02          76288 PKSim.CLI.Core.dll
-a---          02/12/2022    21:02        1442304 PKSim.Core.dll
-a---          02/12/2022    21:02         728064 PKSim.Infrastructure.dll
-a---          02/12/2022    21:02        1094144 PKSim.Presentation.dll
-a---          06/01/2023    21:03          22016 PKSim.R.dll
-a---          06/01/2023    21:03       30658560 PKSimDB.sqlite
-a---          02/12/2022    21:02        1631744 SQLite.Interop.dll
-a---          02/12/2022    21:02         355328 System.Data.SQLite.dll
```

I think we should just provide the libraries as part of the package. These are 50 MiB, of which 30 are the sqlite-DB, and I do not see a problem in increasing the package size by 50 MiB. The package would become fully autonomous and even would make development easier as we will not require PK-Sim for e.g. rebuilding the vignettes or running tests.

I really think this is a rather simple solution that can be implemented right now. For the future, we could spend some time and analyze if we could refactor PK-Sim code a bit so not of the above listed libraries are required (e.g. loading them later).

@msevestre @Yuri05

**Comment by Yuri05** [comment]
PK-Sim libs are not yet migrated to .NET core, this would be the first prerequisite.

**Comment by Yuri05** [comment]
I think you would need ven less DLLs, **PKSim.CLI.Core.dll** and **PKSim.Presentation.dll** are not required (theoretically :))

**Comment by PavelBal** [comment]
> PK-Sim libs are not yet migrated to .NET core, this would be the first prerequisite.

Well it is only required to run it under Linux, right? This would be of course the next step, but for now we could achieve at least self-sufficiency under Windows, without breaking anything (Linux does not support those functions anyways)

> I think you would need ven less DLLs, PKSim.CLI.Core.dll and PKSim.Presentation.dll are not required (theoretically :))

I would also think that e.g. `OSPSuite.Assets.Images.dll` is not required. But with the current implementation, it does not work without any of the listed libraries (I simply started with an empty folder and was trying to load PK-Sim and adding ddls that it could not find).

**Comment by Yuri05** [comment]
> Well it is only required to run it under Linux, right? This would be of course the next step, but for now we could achieve at least self-sufficiency under Windows, without breaking anything

If the package stil lcan be loaded under Linux - fine. Otherwise: only after PK-Sim libs were migrated

>Linux does not support those functions anyways

Only because PK-Sim core does not run under Linux now :)

>I would also think that e.g. OSPSuite.Assets.Images.dll is not required. But with the current implementation, it does not work without any of the listed libraries

Hmm. Probably some dependencies which should not be there :)

**Comment by PavelBal** [comment]
> If the package still can be loaded under Linux then - fine. Otherwise: only after PK-Sim libs were migrated

Could you maybe try this? Just copy the above mentioned libraries into the "lib" folder of the installed package (I could send you the files so you do not have to pick them by yourself) and e.g. run some tests. I am pretty sure it will not break anything as these libraries are only loaded when trying to access the PK-Sim functions (creating individuals/populations).

**Comment by Yuri05** [comment]
If you send me a **CentOS**-package with added libs - can do

**Comment by PavelBal** [comment]
[ospsuite_centOS7.tar.gz](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/10385825/ospsuite_centOS7.tar.gz)

Total package size is 22MB, acceptable, I would say.

**Comment by msevestre** [comment]
My gut feel is that this is a very bad idea

**Comment by PavelBal** [comment]
> My gut feel is that this is a very bad idea

I knew it :D Why?

**Comment by msevestre** [comment]
I'll think about it more and we can discuss live. I am not sure that you are really solving any problem by doing this (for each new version of core, you will have to match the version of PKSim etc.) but you create a build that is much more difficult to create (where will you get the pksim.dll from for instance?)
We can discuss about this tomorrow
