### ISSUE TITLE
Move functions operating on simulation to utilities-simulation

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#118]
I propose to move the functions `load-simulation` and `run-simulation` to the script called `utilities-simulation` to be consistent with container and parameter.

**Comment by msevestre** [comment]
I fear that the utilties-simulation file will become too large if we put everything in one file. 
Let's think about it a bit more before going one way or the other

**Comment by PavelBal** [comment]
Let's see how many functions we will get in future.
