### ISSUE TITLE
Cannot change x axis tick size in a default plot configuration

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1184]
```
oneObsDC <- readRDS(getTestDataFilePath("oneObsDC"))

plotConfig <- DefaultPlotConfiguration$new()
print(plotConfig$xAxisLabelTicksSize)
plotIndividualTimeProfile(oneObsDC, plotConfig)

plotConfig$xAxisLabelTicksSize <- 8
plotIndividualTimeProfile(oneObsDC, plotConfig)

plotConfig$xAxisLabelTicksSize <- 16
plotIndividualTimeProfile(oneObsDC, plotConfig)
```

`plotConfig$xAxisLabelTicksSize`
 is ignored - all plots look the same
 
 
![image](https://user-images.githubusercontent.com/25903040/214009232-4cde1980-22bf-416e-acce-12404da2a266.png)

Tried to change xAxisSize with `plotConfig$xAxisSize <- 16` and still the same.

@pchelle or am I trying the set the wrong parameter? I want to change the size of axis tick labels (the numbers "0, 5, 10" etc)

**Comment by pchelle** [comment]
`DefaultPlotConfiguration` is an object from the `{ospsuite}` package that does internally a conversion to the `PlotConfiguration` object defined by the `{tlf}` package.
In `{tlf}`, the parameter is `PlotConfiguration$xAxis$font$size`

**Comment by pchelle** [comment]
I am suspecting the error to be here:
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/9aed57eaf4b28de254fb2d9cfe604f24fcc175db/R/utilities-plotting.R#L585
where the field `xAxisFont` from `generalPlotConfiguration` may be always `NULL` while the object `xAxisFont` created a few lines above should be the actual argument to provide: 
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/9aed57eaf4b28de254fb2d9cfe604f24fcc175db/R/utilities-plotting.R#L571

**Comment by PavelBal** [comment]
@pchelle thanks!
