### ISSUE TITLE
`DataSet`- setting error type does nothing

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1194]
```
ds <- DataSet$new(name = "ds")
ds$setValues(xValues = c(1,2),
             yValues = c(1,2))

print(ds$yErrorType)

# Now change error type - nothing happens
ds$yErrorType <- "ArithmeticStdDev"
print(ds$yErrorType)

```

**Comment by svavil** [comment]
This is something that might be intended: whenever no error column is present in the dataset, the error type is `NULL` and cannot be changed.

**Comment by PavelBal** [comment]
No required after https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1193 is fixed.
