### ISSUE TITLE
Simulation is an Entity but does not have a path

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#122]
Our `Simulation` class inherits from `Entity`, but calling

```
sim <- loadSimulation(pathToPkml)
sim$path
```

results in an error

```
 Error in rClr::clrCallStatic(typename, methodName, self$ref) : 
  Type:    System.MissingMethodException
Message: Could not find a suitable static method EntityPath on type OSPSuite.Core.Domain.EntityExtensions for method parameters ModelCoreSimulation
Method:  Void ThrowMissingMethod(System.Type, System.String, System.String, System.Type[])
Stack trace:
   bei Rclr.ReflectionHelper.ThrowMissingMethod(Type classType, String methodName, String modifier, Type[] types)
   bei Rclr.ClrFacade.InternalCallStaticMethod(Type classType, String methodName, Boolean tryUseConverter, Object[] arguments)
   bei Rclr.ClrFacade.CallStaticMethod(String typename, String methodName, Object[] arguments) 
```

This leads to errors e.g. when defining a generic error message of type "Parameter with path `path` not found under container `container`", when the simulation is the container.

**Comment by msevestre** [comment]
A simulation is not an entity. It should be ObjectBase

**Comment by PavelBal** [comment]
Yet it inherits from `Entity`
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/cf439c338a1084311f33da906f1fb8248e71b607/R/simulation.R#L8

Should be fixed, then?

**Comment by msevestre** [comment]
Yes I am talking about the core hierarchy. This is a mistake in the R implementation
