### ISSUE TITLE
Display LLOQ in time profiles

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1220]
To be defined

...

- Add horizontal lines that represent the LLOQ
- Must be same color than the points since they are related to a group
- Points bellow LLOQ should be different than the ones above since their value is an artifact (1/2 of LLOQ). Ideally they should be the same shape of above LLOQ's but in an empty version.

**Comment by Yuri05** [comment]
That's how it's shown in PK-Sim: dotted line for LLOQ and open symbols for the data points below LLOQ
![grafik](https://user-images.githubusercontent.com/25061876/224382294-49ca4f12-cb5e-48ae-bc71-28345bff367d.png)

**Comment by Felixmil** [comment]
Is there any already implemented feature here or in tlf that targets this use ?

**Comment by Felixmil** [comment]
Has to be implemented in {tlf} first: https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/422

**Comment by Yuri05** [comment]
I think it's currently implemented only in the Reporting Engine; not in tlf.

**Comment by Yuri05** [comment]
> would it be acceptable to have only color to differentiate groups ?

I would say: no. It should be possible to differentiate by colour and symbol.
Example below: 2 data sets with differnet LLOQ in the same plot in PK-Sim

![grafik](https://user-images.githubusercontent.com/25061876/224970234-41308a3c-3222-4ffa-a8f1-d5880b3d5ba2.png)

**Comment by Felixmil** [comment]
> > would it be acceptable to have only color to differentiate groups ?
> 
> I would say: no. It should be possible to differentiate by colour and symbol. Example below: 2 data sets with differnet LLOQ in the same plot in PK-Sim
> 
> ![grafik](https://user-images.githubusercontent.com/25061876/224970234-41308a3c-3222-4ffa-a8f1-d5880b3d5ba2.png)

How does it work with 8+ groups ?

**Comment by Yuri05** [comment]
@Felixmil I suggest that you discuss this topic with @pchelle , who is just about to replace the standard R shapes with the unicode symbols in the TLF.

**Comment by PavelBal** [comment]
Suggestion - highlight values below LLOQ in some other way, e.g. by applying a semi-transparent square around it with a slightly bigger size? Don't know if this can be implemented in ggplot.

**Comment by Yuri05** [comment]
I have commented in the associated TLF issue: https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/422#issuecomment-1476211129

**Comment by Felixmil** [comment]
Make an option available to the user of osps to display the lloq
