### ISSUE TITLE
`plotObservedVsSimulated()` - allow fold distance of 1

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1229]
Currently: 

```
Error in plotObservedVsSimulated(myCombDat, foldDistance = 1) : 
  Parameter 'foldDistance' should be >1! Following values have
         been passed: '1'.
```

1 should be allowed, e.g. if the user does not want to add any fold lines.

**Comment by Felixmil** [comment]
Would it be ok to have `plotObservedVsSimulated()` default fold_distance value set to `NULL` (when the user don't want fold lines).

If a value or vector  is passed, then it must be greater than 1.

**Comment by PavelBal** [comment]
Yes agree.
