### ISSUE TITLE
`.encodeUnit()` bug

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1235]
The change introduced in this PR https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/1227/files introduced a bug when executing scripts from PowerShell (something about "String is not proper UTF8). I could fix it by changing the code of the function to:

```
.encodeUnit <- function(unit) {
  unit <- enc2utf8(unit)
  mutants <- "\xc2\xb5|\xce\xbc|\xb5"
  if (stringr::str_detect(unit, pattern = mutants)){
    mu <- ospsuiteEnv$muSymbol
    unit <- stringr::str_replace(unit, rawToChar(as.raw(c(0xce, 0xbc))), mu)
    unit <- stringr::str_replace(unit, rawToChar(as.raw(c(0xc2, 0xb5))), mu)
    unit <- stringr::str_replace(unit, rawToChar(as.raw(0xb5)), mu)
  }
  return(unit)
}
```

I guess the `rawToChar` and `as.raw` are important.

**Comment by Felixmil** [comment]
can you try replacing the 3rd line to:

```r
mutants <- enc2utf8("\xc2\xb5|\xce\xbc|\xb5")
```

**Comment by PavelBal** [comment]
> I cannot reproduce this. Can you try replacing the 3rd line to the following ?

Yes works as well. Can you create a PR?
