### ISSUE TITLE
plotPopulationTimeProfile - support mean+ sd

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1259]

**Comment by PavelBal** [comment]
And geometric

**Comment by PavelBal** [comment]
Proposal: add to the signature of `plotPopulationTimeProfile()` an argument `aggregation`, with values `geometric`, `arithmetic`, `quantiles`.

```
plotPopulationTimeProfile <- function(dataCombined,
                                      defaultPlotConfiguration = NULL,
                                      quantiles = c(0.05, 0.5, 0.95),
                                       aggregation = "quantiles")
```

If `aggregation` is not `quantiles`, value of the argument `quantiles` is simply ignored.

**Comment by Yuri05** [comment]
@pchelle In case RE would switch to this function one day: can you please check what is missing in the function signature (e.g. time ranges etc.)?
