### ISSUE TITLE
`xValuesLimits` in `DefaultPlotConfiguration` is not available

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1272]
Description and NEWS say that the DefaultPlotConfiguration has `xValuesLimits` field. However, the field is called `xAxisValuesLimits`, if I am not mistaken.

**Comment by PavelBal** [comment]
@PavelBal Check if this works at all... I have a feeling it doesn't.

**Comment by Felixmil** [comment]
related to #1262

**Comment by Felixmil** [comment]
> Description and NEWS say that the DefaultPlotConfiguration has `xValuesLimits` field. However, the field is called `xAxisValuesLimits`, if I am not mistaken.

In NEWS:
> - `DefaultPlotConfiguration`'s `xLimits` and `yLimits` arguments are deprecated and replaced by `xAxisLimits` and 
  `yAxisLimits`. Use them to zoom in the plot while preserving all data points.
  Use `xValuesLimits` and `yValuesLimits` to filter out data point outside of these range. 
  More detailed explanations [here](https://ggplot2.tidyverse.org/reference/coord_cartesian.html#ref-examples)

**Comment by PavelBal** [comment]
No, `xValuesLimits` does NOT exist.
