### ISSUE TITLE
Profiling shows excessive time spent in `lifecycle::signal_stage()`: improvement or artifact?

### ISSUE THREAD

**Issue by svavil** [Open-Systems-Pharmacology/OSPSuite-R#1284]
I am not sure if this is expected or unexpected behavior. Consider the following profiling setup: 

```
sim <- loadTestSimulation("MinimalModel")
simResults <- importResultsFromCSV(
  simulation = sim,
  filePaths = getTestDataFilePath("Stevens_2012_placebo_indiv_results.csv")
)
dc <- DataCombined$new()
profvis::profvis({
  for (i in 1:100) {
    dc$addSimulationResults(simResults)
  }
})
```

On my local machine, 98 ms out of total 628 ms are spent within the `lifecycle::signal_stage()` function, called from either `purrr::flatten_dbl()` or from `purrr::imap_dfr()`. I would expect that the `signal_stage()` function would quickly warn about possible deprecated functions, and not take 1/6 of the processing time. Is it an artifact of the way I profile the code? Is it something that can be removed by changing the way we call `flatten_dbl()` or `imap_dfr()`?

**Comment by Yuri05** [comment]
Can you reproduce when executing e.g. 100000 times instead of 100?
With timespans in ms range I'm always sceptical - could be an artifact indeed

**Comment by PavelBal** [comment]
Somehow I cannot reproduce this...

But the core requires 6000-8000 ms and not ~600 ms on my machine! Actually on two different machines... @Yuri05  Could you profile this on your machine and let me know how much time it takes?
