### ISSUE TITLE
`DataCombined` - adding data sets or simulation results should not create tables

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1285]
This is a major performance flaw. Each time a new data set is added, the whole thing is converted to data frame, calling `simulationResultsToDataFrame()` or `dataSetToDataFrame()`. This is INSANELY slow! `DataCombined` should just hold the references to the added data objects and only create the data frames when requested (toDataFrame).

**Comment by PavelBal** [comment]
For profiling use:

```
sim <- loadTestSimulation("MinimalModel")
simResults <- importResultsFromCSV(
  simulation = sim,
  filePaths = getTestDataFilePath("Stevens_2012_placebo_indiv_results.csv")
)
dc <- DataCombined$new()
profvis::profvis({
  for (i in 1:100) {
    dc$addSimulationResults(simResults)
  }
})
```

**Comment by msevestre** [comment]
Aren't you just postponing the time when it's being done? It will have to be done anyways

**Comment by Yuri05** [comment]
@PavelBal I this issue a duplicate of #1287 and can be closed now?
