### ISSUE TITLE
Unversion `docs/` folder

### ISSUE THREAD

**Issue by Felixmil** [Open-Systems-Pharmacology/OSPSuite-R#1301]
Since the website is generated through github actions, do we really need to version the `docs/` folder on our repository ?

It can be useful to run `pkgdown::build_site()` when working on documentation but we don't need to send it to GitHub right ?

This would require to execute few git commands and a new entry in the `.gitignore`.

**Comment by PavelBal** [comment]
So the files in `docs` are actually not used? Then I agree.

**Comment by Felixmil** [comment]
@Yuri05 Does the github action "only" build the website from `docs/` or does it also run `pkgdown::build_site()`

**Comment by Yuri05** [comment]
Actually there are no GH-Actions in the repo.
The site is built from the **docs** folder of the **develop** branch whenever it's updated.
pkgdown::build_site() is usually run locally for that.
So in the current setup the docs folder is used and cannot be unversioned.

![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/assets/25061876/9d95be9c-5f0f-4a82-b69a-c65e054b4b2e)

**Comment by Felixmil** [comment]
Thanks for the clarification.

pkgdown::build_site() should then be executed for each PR.
Maybe we can set a PR checklist ?
