### ISSUE TITLE
Reduce default size for x & y ticks label size

### ISSUE THREAD

**Issue by Felixmil** [Open-Systems-Pharmacology/OSPSuite-R#1308]
I find that x & y ticks label that are bigger than the axis title label is a bit weird to the eye.

Here is a comparison of plot when I tried to change the default size (for `x/yAxisLabelTicksSize` set in `DefaultPlotConfiguration`.

| **x/yAxisLabelTicksSize = NULL** | **x/yAxisLabelTicksSize = 8** |
|------------------------------|---------------------------|
|![image](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/assets/34234913/714e9643-84d6-4952-a1c7-707b9be03916)| ![image](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/assets/34234913/4023e4ec-58ac-43b9-8933-e3052ff0ced8)|

Maybe `9` could be a good value also.

**Comment by PavelBal** [comment]
lol. yes, 8 should be sufficient.

**Comment by Felixmil** [comment]
@Yuri05 @pchelle what do you think of this ?

**Comment by PavelBal** [comment]
Make a PR for 8 ;)
