### ISSUE TITLE
Save path of the pkml file in the simulation

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#131]
I think it is a good idea to store the path to the pkml file as a property of the "Simulation" class.

Question - can we get it from .NET object, or should it be implemented as part of the R6 class?

If accepted, the `$print()` method should also return the path to the file.

**Comment by msevestre** [comment]
This is not available in the .net class.
If you think this is required, we can define in the class. This is not required to implement the cache however as the path will be the key of the entry.  O reason to save it in the object

**Comment by PavelBal** [comment]
No it is not required for caching. For me as a user it would be helpful to be able to see where the simulation comes from.

**Comment by msevestre** [comment]
Ok let's put it in the simulation object.
Let's not call in path however;-) otherwise this will be highly confusing ;-)
Suggestion?

**Comment by Yuri05** [comment]
>Suggestion?

`FileSource`. Empty if a simulation created NOT from file, otherwise full path to the pkml

**Comment by msevestre** [comment]
SourceFile maybe?
I don't think we will have the case of a simulation created not from file. Or how can it happen?

**Comment by msevestre** [comment]
this has been fixed in #142
