### ISSUE TITLE
R CMD Check Warnings

### ISSUE THREAD

**Issue by Felixmil** [Open-Systems-Pharmacology/OSPSuite-R#1325]
## Symptoms

Here is the warning that is repeated several time during `R CMD Check` execution:

```
 Error: .onLoad failed in loadNamespace() for 'ospsuite', details:
   call: rClr::clrCallStatic("OSPSuite.R.Api", paste0("Get", taskName))
   error: Type:    RDotNet.EvaluationException
 Message: Error: object '.slotNames' not found
 
 Method:  RDotNet.SymbolicExpression Parse(System.String, System.Text.StringBuilder, RDotNet.REnvironment)
 Stack trace:
    at RDotNet.REngine.Parse(String statement, StringBuilder incompleteStatement, REnvironment environment)
    at RDotNet.REngine.<Defer>d__59.MoveNext()
    at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source)
    at RDotNet.REngine.Evaluate(String statement, REnvironment environment)
    at RDotNet.S4Object..ctor(REngine engine, IntPtr pointer)
    at RDotNet.SymbolicExpressionExtension.AsS4(SymbolicExpression expression)
    at Rclr.RDotNetDataConverter.CreateClrObj(Object obj)
    at Rclr.RDotNetDataConverter.ConvertToR(Object obj)
    at Rclr.ClrFacade.marshallDataToR(Object obj, Boolean tryUseConverter)
    at Rclr.ClrFacade.Cal
```

This is a problem because this will stop `R CMD Check` verifications steps before it can detect **real** warnings and errors.

## Cause

I investigated (with the help of @georgeDaskalakis) and found out that this is caused by this function:
```r
.initializeDimensionAndUnitLists <- function() {
  # This initializes the two lists in the parent environment which is the package environments
  ospDimensions <<- .getDimensionsEnum()
  ospUnits <<- .getUnitsEnum()
}
```
In particular the `<<-` used here.

.getDimensionsEnum() and .getUnitsEnum() both call `rClr::clrCall()` at some point:

```r
.getDimensionsEnum <- function() {
  enum(allAvailableDimensions())
}

allAvailableDimensions <- function() {
  dimensionTask <- .getNetTaskFromCache("DimensionTask")
  rClr::clrCall(dimensionTask, "AllAvailableDimensionNames")
}
```

During `R CMD Check` the package is loaded several times. Each time the package is loaded, `ospDimensions` and `ospUnits` are initialized by calling a .NetTask and **overwrites** the previous values. 
I'm not really sure of what happens here, this problem 

### Make them functions instead of variables

I was able to avoid this warning by turning these variables into function. This way, the .NetTask is only called when necessary (instead of each time the package is loaded).

```r
ospDimensions <- function(){
  .getDimensionsEnum()
}

ospUnits <- function(){
  .getUnitsEnum()
}
```

The downside is that we'd now need to use `ospDimensions ()` and `ospUnits()` (notice the `()`) to access the values _i.e_ ` ospUnits$Time$h` would become ` ospUnits()$Time$h` and this would be a breaking change for other packages and existing scripts.

### Make use of package internal data

`ospUnits` and `ospDimensions` can be defined as internal data with:
```r
ospDimensions <- .getDimensionsEnum()
ospUnits <- .getUnitsEnum()
usethis::use_data(ospDimensions, ospUnits, internal = TRUE)
```
This will save the object as `sysdata.rda` in `R/` folder.
Then, when the package is loaded, these objects will be available in the package namespace just like before.
The downside is that this small script should be run each time the .dll core is updated (with potential new units / correction)

**Comment by PavelBal** [comment]
Let's wait for the new R<->.NET bridge, this is something in the .NET code (however I do not understand why this error is not thrown when loading the package regularly).

Are there any differences on how packages are loaded via `R CMD Check` vs `library()`?

**Comment by Felixmil** [comment]
> Are there any differences on how packages are loaded via `R CMD Check` vs `library()`?

I could not make sense of what happens in R CMD Check 🙈

I think the second proposed solution is good. Do the Dimensions and Units change often ? Are these lists stored in the dll core ?

**Comment by Felixmil** [comment]
> Let's wait for the new R<->.NET bridge

I still proposed PR #1326 because using `<<-` is just bad (relative environment assignment 👿) and took the opportunity to solve several Warnings and Notes so that we get a clear view on package sanity in the future.

**Comment by PavelBal** [comment]
Dimensions and units are parsed from the file `inst\lib\OSPSuite.Dimensions.xml`. Instead of saving the two lists as `.rd`, we could write an R parser for this XML and read it on package init. Should be easy to do, we only need names of dimensions and their units.

**Comment by Felixmil** [comment]
@georgeDaskalakis was against this:
> In order not to a) duplicate functionality already present in core (we will still need to parse this, associate dimensions with units and so on, it is not just about reading this) and b) losing the further functionalities regarding dimensions and units offered by DimensionTask

**Comment by PavelBal** [comment]
I am talking only about populating the enums `ospDimensions` and `ospUnits`, not removing the whole functionality.

**Comment by Felixmil** [comment]
> I am talking only about populating the enums `ospDimensions` and `ospUnits`, not removing the whole functionality.

It would solve the encoding problem on Appveyor so I will try that.

**Comment by georgeDaskalakis** [comment]
Even if this parser is quite straightforward, still, since this is functionality duplication of what happens in Core, I would keep an issue in this repo, to remind us that this is temporary and should be checked again with the new R<->.NET bridge and changed back to doing this in a consistent way.

**Comment by PavelBal** [comment]
> Even if this parser is quite straightforward, still, since this is functionality duplication of what happens in Core, I would keep an issue in this repo, to remind us that this is temporary and should be checked again with the new R<->.NET bridge and changed back to doing this in a consistent way.

@Felixmil When you implement the parsing in R (to fix the problems for now), please create an issue to revert it back to .NET implementation when new R<->NET bridge is available.

**Comment by Felixmil** [comment]
Done, I also refactored the code a bit so it will be easier to revert to the original implementation using Core Tasks.
