### ISSUE TITLE
Tutorial examples for setParametersValue not "explicit"

### ISSUE THREAD

**Issue by Laura-Villain** [Open-Systems-Pharmacology/OSPSuite-R#1329]
As I was following the introduction to the R package, I found two examples not "helpfull" to understand as a beginner: 

1) 
![image](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/assets/149374454/398e5087-6fc5-4dae-b72b-908d2bf10f59)
From what I understand, we don't see any change, as the dose of 350 mg is too small to be shown in kg. However, I would suggest: 

- A first example where we can see the impact of the function 
- A comment saying why we don't see any difference 

It might be also interesting to specify that it is equivalent to simply assigning a new $value 
ex: `doseParam$value <- toBaseUnit(doseParam, 350, "mg")`

2)
![image](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/assets/149374454/a6a5377d-a837-4e22-8fe0-395ad3f614f2)

As the dose is set at 0.00 kg at first, the "scaling" gives us a value of still 0.00
I think it is not super explicit to understand the behavior of this function 

Another remark is that I find (as a beginner) confusing to have a rounded value appear. For example, I would have expected to find something like 3.5* 10E-4 kg in the first case. If the value is rounded to 0.00 kg, then there is no way to know if we are really at 0, or just smaller than 0.01 kg.

**Comment by PavelBal** [comment]
We might want to change the behavior of the print function, see ussies https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1246  https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1123


@Laura-Villain Feel free to propose a fix and create a pull request :)

**Comment by Laura-Villain** [comment]
@PavelBal here is a suggestion: https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/1330
