### ISSUE TITLE
getXXX: "stopIfNotFound"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#133]
I propose to add the option to the `getParameter/getContainer` etc. to stop if no entity can be found under the supplied path. 
The argument `stopIfNotFound` is set to `FALSE` by default, and the functions return `NULL` or an empty list. If `stopIfNotFound == TRUE`, the function stops with an error.

I think it is a useful feature as most of the time I definitely **want** to get that parameter/container, and if it is not found it means that the provided path is wrong.

**Comment by PavelBal** [comment]
So, should we implement it with `stopIfNotFound == TRUE` by default?

**Comment by msevestre** [comment]
Let's go that way since @Yuri05 does not mind :)

**Comment by PavelBal** [comment]
@msevestre 

We have `getXXX `and `getAllXXXMatching`. I would only throw an error for the `getXXX` methods. What do you think?

**Comment by msevestre** [comment]
Agreed.
