### ISSUE TITLE
Add instructions how to install from GitHub

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1335]
I believe it should be this:

```
install.packages("remotes")
install.packages("https://github.com/Open-Systems-Pharmacology/rClr/releases/download/v0.9.2/rClr_0.9.2.zip",
                 repos = NULL,
                 type = "binary"
)

remotes::install_github("Open-Systems-Pharmacology/OSPSuite-R@*release")
```

**Comment by Felixmil** [comment]
I wonder if it is still necessary to list these dependencies in the README ?

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/ad05513cb42f9540ba5aa91a0386245fd13a186b/README.md?plain=1#L51-L65

All CRAN dependencies will automatically be installed anyway so I think it creates more noise than information here.

**Comment by PavelBal** [comment]
In this case no. I would remove the list of dependencies, especially because they are probably outdated and are hard to maintain.
