### ISSUE TITLE
Efficient computation vignette needs visual representation

### ISSUE THREAD

**Issue by Felixmil** [Open-Systems-Pharmacology/OSPSuite-R#1344]
Hi all,

I was going through the [Efficient Calculation](https://www.open-systems-pharmacology.org/OSPSuite-R/articles/efficient-calculations.html) vignette and though it would be useful to have some kind of visual representation of the processes described in this document.

Here is a draft:

![simulation_life-cycle_diagrams_v2](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/assets/34234913/ce557372-0642-46e7-8686-9dbe646b640a)

- Is it a good representation of the processes ?
- Any suggestion for addition/improvement ?

**Comment by PavelBal** [comment]
I like the proposal. Feel free to create a PR with the changes to the vignette.

**Comment by Yuri05** [comment]
very nice suggestion - I like the pictures!
would just change the image like below (otherwise it looks like simulation2 issomehow based on the simulation1)
![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/assets/25061876/a5f9ce3f-b7cc-425e-b930-298e8f6b9c17)

**Comment by Felixmil** [comment]
> (otherwise it looks like simulation2 issomehow based on the simulation1)

I agree in some way but in the code, loading and parametrization of simulation2 happens after loading of simulation1. By implementing your suggestion I'm afraid it could be understood as a parallel process.

Maybe we can vote on this ? Use reactions button: 👍 for Yuri's suggestion, 👎 for original.

Would very like @msevestre to check this also 👀

Thanks a lot !
