### ISSUE TITLE
Having both `runSimulation` and `runSimulations` is confusing

### ISSUE THREAD

**Issue by Felixmil** [Open-Systems-Pharmacology/OSPSuite-R#1380]
Several user feedback this is confusing and not really usual in the vectorized paradigm of R. 

I think `runSimulations()` should be default and always return a named list of results but with better names because right now most use cases I saw use `[[index]]` to access simulation results, which makes code more complicated to understand.

Also, are these `id` really essential ? Couldn't we just use the name of the Simulation object to name the list ?

Here is an example of what I suggest:

```r
simPath <- system.file("extdata", "simple.pkml", package = "ospsuite")
sim1 <- loadSimulation(simPath)
sim2 <- loadSimulation(simPath)

results <- runSimulations(sim1)
results
#> $sim1
#> SimulationResults: 
#>    Number of individuals: 1 

results <- runSimulations(list(sim1, sim2))
results
#> $sim1
#> SimulationResults: 
#>    Number of individuals: 1 
#> 
#> $sim2
#> SimulationResults: 
#>    Number of individuals: 1 
```

**Comment by PavelBal** [comment]
`runSimulation` is deprecated and actually `runSimulations` should be used all the time.

The IDs are really important to be able to tract which results belong to which simulation. Imagine you are loading simulations in a loop and putting them into a list, without assigning to variables. Then, you would not have any variable name for the results list entry :)

**Comment by Felixmil** [comment]
I added a depreciation message in #1382 and replaced all uses of `runSimulation` in vignettes, examples and tests in #1382.

Regarding IDs, what about allowing users to pass a named list to `runSimulations()`, it would look like this:

```r
simPath <- system.file("extdata", "simple.pkml", package = "ospsuite")
sim1 <- loadSimulation(simPath)
sim2 <- loadSimulation(simPath)

results <- runSimulations(list(default_aciclovir = sim1,
                               modified_aciclovir = sim2)
                          )

#> $default_aciclovir 
#> SimulationResults: 
#>    Number of individuals: 1 
#> 
#> $modified_aciclovir 
#> SimulationResults: 
#>    Number of individuals: 1 
```

And of course, if users do not pass any name in the list then simulation id is used.

Event if the simulationResults list is named, user would still be able to check the simulation id with: `results$default_aciclovir$simulation$id`

**Comment by Felixmil** [comment]
I'm also proposing an implementation in #1383.
