### ISSUE TITLE
Use `%||%` from base R

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1402]
In R 4.4.0, `%||%` is supported natively. Currently, we are re-exporting it from `purrr::`%||%`

> L %||% R newly in base is an expressive idiom for the phrases if(!is.null(L)) L else R or if(is.null(L)) R else L.

In one of the future releases, we should make `ospsuite-r` depend on R >= 4.4.0 and use the base function for this.

**Comment by Yuri05** [comment]
At least for us, the code should work with R 4.3

**Comment by PavelBal** [comment]
Yes, "in one of the future releases", I hope you will upgrade to >=4.4.0 before 2030 :-P

**Comment by pchelle** [comment]
I noticed the issue is the same as #1486 
Closing this one as the other provides more info about `%||%`
