### ISSUE TITLE
`pksim_minimal` is not up to date??

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1407]
Core version in `pksim_minimal` is 12.0.231, but the version in inst/lib is 12.0.277? How is it possible?

**Comment by PavelBal** [comment]
Nevermind

**Comment by msevestre** [comment]
Explain lol



--


*Michael Sevestre*

*Design2Code Inc.*


Email ***@***.***

Website www.design2code.ca

**Comment by PavelBal** [comment]
At the end, the error was on my side (ospsuite-r did not update properly in `renv`), and I was mislead by the fact that `Core` can have a version different from `PKSim.R`. I always assumed they have same versions.
