### ISSUE TITLE
ospsuite addins

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite-R#1412]
RStudio provides an [Addins](https://rstudio.github.io/rstudio-extensions/rstudio_addins.html) feature that users could leverage when writing scripts.

I drafted below 2 simple functions for potential addins that could be used as starting point for discussing of such features.
> [!IMPORTANT]
> Feel free to comment

**Comment by pchelle** [comment]
## Selecting and copying a unit

### Example

![image](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/assets/45343665/edbb5c77-5acc-482a-8196-dfcd29b8f8bb)

### Code

```r
unitPicker <- function() {
  ui <- miniPage(
    gadgetTitleBar("OSP Unit Picker", left = NULL),
    miniContentPanel(
      selectInput(
        inputId = "dimension",
        label = span(icon("folder-open"), " Dimension"),
        choices = names(ospsuite::ospUnits)
      ),
      selectInput(
        inputId = "unit",
        label = span(icon("folder-tree"), " Unit"),
        choices = as.character(ospsuite::ospUnits$`Abundance per mass protein`)
      ),
      actionButton(
        inputId = "copy",
        label = "Copy",
        icon = icon("copy")
      )
    )
  )

  server <- function(input, output, session) {
    # Update available units based on selected dimension
    observeEvent(input$dimension, {
      updateSelectInput(
        session = session,
        inputId = "unit",
        choices = as.character(ospsuite::ospUnits[[input$dimension]])
      )
    })
    # Copy the unit wrapped with quotes in your current R script position
    observeEvent(input$copy, {
      rstudioapi::insertText(paste0('"', input$unit, '"'))
    })
    observeEvent(input$done, {
      stopApp()
    })
  }

  runGadget(ui, server)
}
```

**Comment by pchelle** [comment]
## Get parameter from path by browsing a simulation tree

### Example

| Step 1 | Step 2 | Step 3 |
|--------|--------|--------|
| ![image](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/assets/45343665/ad6a2d47-c278-484b-a251-3d27d59bbc65) | ![image](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/assets/45343665/7f308846-ddfd-4663-bac9-18f690f90073) | ![image](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/assets/45343665/96ef8772-d81d-4d03-8aa3-01c639579d2d) |

### Code

```r
simulationPathAddin <- function() {
  # Get object from selected text in RScript
  # Can add validation of the object type at this stage
  selectedText <- rstudioapi::getSourceEditorContext()$selection[[1]]$text
  uiSimulation <- get(selectedText)
  simulationTree <- ospsuite::getSimulationTree(uiSimulation)

  ui <- miniPage(
    gadgetTitleBar("Simulation Test", left = NULL),
    miniContentPanel(
      # Print the selected text and simulation name to check
      htmlOutput("selectedText"),
      htmlOutput("simulationName"),
      br(),
      span(
        icon("square-check"), strong(" Selected Path:"),
        verbatimTextOutput("selectedPath"),
        actionButton(
          inputId = "copy",
          label = "Copy",
          icon = icon("copy")
        ),
        br(),
        span(icon("folder-tree"), " Simulation Tree"),
        # Print simulation paths as an interactive tree leveraging shinyTree package
        shinyTree(
          "tree",
          themeIcons = FALSE,
          themeDots = FALSE,
          theme = "proton"
        )
      )
    )
  )

  server <- function(input, output, session) {
    output$selectedText <- renderPrint({
      span(
        icon("arrow-pointer"),
        " Selected text: ",
        strong(selectedText)
      )
    })
    output$simulationName <- renderPrint({
      span(
        icon("id-card"),
        " Simulation name: ",
        strong(uiSimulation$name)
      )
    })
    
    # Get path from selected shiny tree node
    getPath <- reactive({
      treeNames <- get_selected(input$tree, format = "names")
      if (length(treeNames) == 0) {
        return()
      }
      treeNames <- treeNames[[1]]
      ospsuite::toPathString(attr(treeNames, "ancestry"), treeNames)
    })
    
    output$tree <- renderTree({
      simulationTree
    })
    output$selectedPath <- renderPrint({
      getPath()
    })
    
    # Copy the path wrapped with example text in your current R script position
    observeEvent(input$copy, {
      if (is.null(getPath())) {
        return()
      }
      printedText <- paste0(
        'param <- getParameter("',
        getPath(),
        '", container = ', selectedText, ")"
      )
      rstudioapi::insertText(printedText)
    })

    # When the Done button is clicked, return a value
    observeEvent(input$done, {
      stopApp()
    })
  }

  runGadget(ui, server)
}
```

**Comment by PavelBal** [comment]
Nice! Should we maybe have a separate package `ospsuite.addins`?

**Comment by pchelle** [comment]
Great idea ! 
This way only the addins will need to support the extra interactive dependencies such as `rstudioapi`, `shiny`, `shinyTree` or `miniUI`.
And we can centralize in the repo what user would like as addins.

**Comment by pchelle** [comment]
@PavelBal 
Following up on that I drafted a [repo](https://github.com/pchelle/OSPSuite.Addins) with a few addins.

**Comment by Yuri05** [comment]
@pchelle Very nice, great enhancements!
@KatrinCoboeken @AnnikaRPS FYI

**Comment by PavelBal** [comment]
@Felixmil @rengelke @Laura-Villain 

Check this out, especially @Laura-Villain present it to our users? Would it substitute our unit converter?

**Comment by pchelle** [comment]
> @Felixmil @rengelke @Laura-Villain
> 
> Check this out, especially @Laura-Villain present it to our users? Would it substitute our unit converter?

The unit converter is now implemented as an addin.

I also forked my repo as an Open-Systems-Pharmacology [repo](https://github.com/Open-Systems-Pharmacology/OSPSuite.Addins). It'll be more visible to users this way.

**Comment by Laura-Villain** [comment]
> @Felixmil @rengelke @Laura-Villain
> 
> Check this out, especially @Laura-Villain present it to our users? Would it substitute our unit converter?

Substitute, I don't know (as in a reproducible code it's always nice to have the option to write a code), but I definitely think that it will help a lot of people that are not super comfortable with R, and I can present that soon 
Especially to find the path. @pchelle I don't know if that is too much to ask, but maybe it would be also nice to have a way to search things in path (like getAllParametersMatching but where you can find a keyword like "grep" would do, and not case sensitive?)

**Comment by pchelle** [comment]
> Especially to find the path. @pchelle I don't know if that is too much to ask, but maybe it would be also nice to have a way to search things in path (like getAllParametersMatching but where you can find a keyword like "grep" would do, and not case sensitive?)

The addin: View Simulation Tree / `runSimulationTree()` allows you to check, select and copy to your keyboard the paths of a pkml simulation file. The shiny app display the paths as a tree and includes a search bar that can be used to search keywords.

**Comment by pchelle** [comment]
For potential users, I was planning to deploy pkgdown documentation and record in vignettes [tutorial videos](https://github.com/Open-Systems-Pharmacology/OSPSuite.Addins/issues/1) showing usage of the current addins.

**Comment by pchelle** [comment]
For new Addins feature requests, let's now use the appropriate Github repo: 
https://github.com/Open-Systems-Pharmacology/OSPSuite.Addins/issues
