### ISSUE TITLE
💡Automatically include Core and PKSim minimal in package

### ISSUE THREAD

**Issue by Felixmil** [Open-Systems-Pharmacology/OSPSuite-R#1422]
Using github action, we could rather easily get latest Core and PKSim .dll files and include them in the package.

## Now
- Core is updated manually (mostly by @rwmcintosh) in this repo
- Portable PKSim installation is decoupled and requires manual steps, resulting in frequent errors on user side (when they update the package after a Core update but do not get latest portable PKSim).

## Proposition
- Store all required `.dll` files in the package
- Add a dev script in the package so that developers can make sure they have the latest `.dll` locally.
- When a PR is created or merged, latest `.dll` files are downloaded and pushed into the package before running the tests.

## Good stuff
- Guarantee to have the right `.dll` installed with the package
- Less manual steps (both for devs and users)
- One step further full reproducibility 

## Limitations:
- `.dll` files cannot really be versionned so the dev script to update the core will always result in commiting/pushing files, even if they are identical.

**Comment by Felixmil** [comment]
Any comment on this @PavelBal, @rwmcintosh, @Yuri05, @msevestre  ?

**Comment by rwmcintosh** [comment]
I'd say this script belongs to the PK-Sim repository. There should be a nuget or something that bundles/resolves the required PK-Sim assemblies that CI can publish.

**Comment by rwmcintosh** [comment]
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2905
