### ISSUE TITLE
Release workflow

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/OSPSuite-R#1432]
We will replace the current strategy of storing .NET and native DLLs in the repository with a strategy where they are downloaded during the build process.

Everything will work from "latest" for our first step. After that is working we will need to address release versioning. So a tag can be created and when building the tag we need to be able to build OSPSuite-R with the same version of PK-Sim (not the current latest).

**Comment by PavelBal** [comment]
This will be done in the rSharp PR, right?

**Comment by rwmcintosh** [comment]
We aren't going to need this issue anymore. We still commit binaries rather than pull them at build time, for now.
