### ISSUE TITLE
Show progress when simulation is running

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#145]
How can we show some progress in the console? no UI but maybe some "." or a number or whatever.
At least optional?

Thoughts? @Yuri05 @PavelBal 

How is this done in other packages?

**Comment by PavelBal** [comment]
There is `txtProgressBar` in the base R, or the package [progress](https://cran.r-project.org/web/packages/progress/). I will look into them.

Because of validation etc, it is probably better to stick with the base functions...

**Comment by msevestre** [comment]
@PavelBal @Yuri05 I do not know how this can work to be honest.
@PavelBal Do you know if this is possible to pass a function from R to .NEt as a callback. BEcause somehow the .NET layer should be the one calling setTxtProgressBar so that the progresss updates as expected... Hard to tell

**Comment by Yuri05** [comment]
I would be very cautious with progress bar. If running in a non-interactive mode (batch; cloud/cluster) those must be switched off.

**Comment by msevestre** [comment]
ok I have a very simple progerss with number that can be turned on and off (let see if we need this at all)
