### ISSUE TITLE
Remove submodules for PKParameters and Dimensions

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1453]
If I understand it correctly, both the `OSPSuite.Dimensions.xml` and `OSPSuite.PKParameters.xml` are now downloaded with other PK-Sim dependencies. Should the submodules be removed then?

**Comment by Yuri05** [comment]
I think yes

**Comment by PavelBal** [comment]
Let's do it in a separate PR then.
