### ISSUE TITLE
Skipped test - test-data-combined

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1454]
```
# `loadDataSetsFromExcel()` does not work for non-Windows platforms
skip_on_os("linux")
skip_on_ci()
```

With .NET8, do we expect these tests to work? @Yuri05 @rwmcintosh @benjaperez1983 

`skip_on_ci()` can be removed in general, or are they also critical for GHA? @Felixmil

**Comment by Felixmil** [comment]
I think we'll need to review them one by one. I suggest that we first get no failure with current active test then proceed.

**Comment by PavelBal** [comment]
Not skipped any more - all passing.
