### ISSUE TITLE
Add CodeCov Token as environment variable

### ISSUE THREAD

**Issue by Felixmil** [Open-Systems-Pharmacology/OSPSuite-R#1462]
Test coverage action is failing because of missing codecov token in environment. 

`{covr}` will look at the `CODECOV_TOKEN` in environment variables (cf [documentation](https://covr.r-lib.org/reference/codecov.html)). 

It just need to be copied from Codecov and added as variable for github actions.

I would add OSP codecov token as organization-wise variable.

**Comment by Yuri05** [comment]
Added organization **SECRET** CODECOV_TOKEN
