### ISSUE TITLE
Disable pages-build-deployment workflow

### ISSUE THREAD

**Issue by Felixmil** [Open-Systems-Pharmacology/OSPSuite-R#1463]
This workflow is for building default jekyll website for github pages. But we don't need it and it keeps failing.

**Comment by Yuri05** [comment]
I changed the setting for the GH pages to "GH actions". Should disable the Workflow
![grafik](https://github.com/user-attachments/assets/ee32a9ae-02c8-4f74-8583-11ccdd633102)

**Comment by Felixmil** [comment]
After double checking, I think we don't want to pause this action, because it is what publishes the github Pages website when a change occurs.

However, I think it wasn't configured correctly: we need to keep `Deploy from a branch` but then pick the `github-pages` branch as source (no subfolders).

**Comment by Yuri05** [comment]
changed
