### ISSUE TITLE
No .9000 in the version?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#1467]
Should be now set to 12.1.0.**9000** ?
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/4f317736f47f1fd489a4022f43434ab3926b8963/DESCRIPTION#L4

**Comment by Felixmil** [comment]
Yes. But we bumped to 12.1.0 in the main rSharp PR, thinking we would directly pre-release that but we had few additional PR in the meantime. I should create the pre-release today and then add the .9000 get back to dev mode.
