### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#1474]
Latest installation instruction suggests using this:
```
install.packages("pak")
pak::pak("Open-Systems-Pharmacology/OSPSuite-R@*release")
```
What is the advantage over `remotes::install_github("Open-Systems-Pharmacology/OSPSuite-R@*release")`?

With the **remotes** package, I can e.g. select during the installation which other packages I would like to upgrade, if they are already installed:
<img width="600" src="https://github.com/user-attachments/assets/c869b495-0a1b-462d-89ea-5f9694aca5e1">

With the **pak** package, I have only 2 options - either upgrade everything or abort the whole installation:
<img width="600" src="https://github.com/user-attachments/assets/a08a5b20-3f16-4c50-9fbc-71922b489b35">

**Comment by Felixmil** [comment]
I find that pak is better than remotes in most cases.

However it is indeed more convenient tu use remotes for individual dependency updates. This is not really necessary usually but it is better in our cases with all our internal dependencies and versions that are not always aligned.

Also, I noticed that if .Net dependencies are not installed, the warning coming from rSharp when using remotes but not with pak.

I will revert instruction to use remotes
