### ISSUE TITLE
Tests are missing in the Linux package

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#1478]
Testthat tests are missing in the Linux package

**Comment by Felixmil** [comment]
What do you mean ?
Tests are not supposed to be present in libraries:
[![](https://r-pkgs.org/diagrams/package-files.png)](https://r-pkgs.org/diagrams/package-files.png)

**Comment by PavelBal** [comment]
I think we had this discussion already :) Actually for validation purposes, supplying the tests with the package would be a good idea. Is this doable?

**Comment by Yuri05** [comment]
> But I can also change the building workflow to include tests with:
> 
> ```r
> devtools::build(...,  args=c("--preclean", "--install-tests"))
> ```

Please do. Having testthat-tests included in (at least) the Linux version is mandatory on our side due to the internal package validation procedure.

**Comment by Felixmil** [comment]
Proposed in [this PR](https://github.com/Open-Systems-Pharmacology/Workflows/pull/40)
