### ISSUE TITLE
Do not use persistable in quantity. Instead use OutputSelection

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#148]
At the moment, we are exposing the "persitable" property in a quantity to decide whether an entry should be added to the list of output or not. I think this is not the right abstraction anymore. Instead, we should use the same concept as PK-Sim and MoBi (e.g. OutputSettings) to decide which entity should be exported. This will also ensure that the building blocks are consistent when reimported in PKSim

SimulationSettings as the following properties
* Solver
* Output Schema
* Output Selections

Output selection is the one that we need for this entry. But we will need to expose solver and output schema anyways. OutputSelection is a list of QuantitySelection. A quantity selection can be created directly from a quantity. We will have to expose all the methods for those

@Yuri05 @PavelBal Thoughts?

**Comment by PavelBal** [comment]
Sounds good to me. As long as we can select the outputs from R...

**Comment by msevestre** [comment]
Yes. See description above. We'll need to expose method to add/ remove the QuantitySelection
