### ISSUE TITLE
getXXXMatching... Why are we returning a list and not an array?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#150]
@PavelBal I think this is new. We used to return an array if I am not mistaken but now it's a list. Any reason for that?

**Comment by PavelBal** [comment]
Everything in R is a list that is not an atomic vector (https://adv-r.hadley.nz/vectors-chap.html) - so we always had lists. Or am I mistaken?

**Comment by msevestre** [comment]
I used to be able to access the result using res[1] (sapply returns a vector and lapply returns a list)

Since we implemented multiples path, the uniqueEntities returns a list and not a vector
So I need to access the element using res[[1]]

Is there a reason why we are returning a list and not a simple array?

**Comment by msevestre** [comment]
I am going to double check the commit to be sure. Maybe I am full of shit ;-)

**Comment by msevestre** [comment]
ok you are correct. Thanks for pointing this out.
