### ISSUE TITLE
utilities-molecules

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#159]
Though species (or molecules) are quantities like parameters, I thing for convenience we should still have at least the methods
- `setMoleculesStartValues`
Probably also
- 'getMolecule' / 'getAllMoleculesMatching'

No I am not sure how to call these methods - should it be `setMoleculesStartValues` as they are called in current MoBi, or `setMoleculesInitialConditions` as they will probably be called in OSMOSES?

**Comment by msevestre** [comment]
I think we should stick with the current nomenclature because OSMOSES will be released much later than the toolbox

Mauybe we should juste name it setMoleculeValues? What's the current nomenclature at the moment in Matlab or R?

**Comment by PavelBal** [comment]
> Maybe we should just name it setMoleculeValues? What's the current nomenclature at the moment in Matlab or R?

`setSpeciesInitialValue`. But I don't like the "species" as it is called "Molecules" in MoBi. So yes, maybe just `setMoleculeStartValues` (consistent with MoBi's BB).

**Comment by msevestre** [comment]
ok sounds good. And I agree that we need those access methods even though it's all Quantity at the end of the day. `Quantity` is simply too abstract

**Comment by PavelBal** [comment]
@msevestre Can we have a container task `AllMoleculesMatching`? `AllQuantitiesMatching` returns molecules AND parameters..

**Comment by msevestre** [comment]
ok. I think we will need the other methods however setMoleculeStartValues because depending on the mode (Amount or Concentration), the start value is either directly in the MoelculeAmount or defined as parmaeter "StartValue" of the MoleculeAmount
