### ISSUE TITLE
Replace "simple.pkml" simulation by something what is actually a simulation

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#166]
Can we replace the "simple.pkml" by, e.g. "S1" from the test suite? This simple model is so simple that it even does not produce any results when simulating, and writing examples with it turns out to be very painful.

**Comment by msevestre** [comment]
Sure. However you should see results if you set the parmaeters as variable (it's done in one of the tests)
I did not want to add a 5MB + file to the package. Maybe you could creaet a simple.pkml that is a simple model with some species instead?

**Comment by msevestre** [comment]
I have updated simple.pkml to have output as well.
I am hesitant to put  a 6MB file in a package for now. We do not need a full blown pbpk to support what we do
If you need to update the file, simp;ly load it in MoBi and add what is missing./ There should be outputs, Table parameters etc..

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/66231981-d182f380-e6b5-11e9-98de-62bef9e12f9b.png)
