### ISSUE TITLE
Allow user to set parameter value in a specific unit

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#171]
Right now, the quantity class exposes the value {get;set} method wich allows to set or retrieve a value in base unit

However, I am wondering if we should not expose a way to set a value in the desire `displayUnit` as we do in PKSim and MoBi

For example. No one will want to set height in dm. But this is our internal unit
should we allow something like 

`quantity.value <- "175 cm"`

Or something similar?

We have the concept of `valudInDisplayUnit` also. Maybe too confusing for  a user 

Thoughts
@PavelBal @Yuri05 @KatrinCoboeken

**Comment by PavelBal** [comment]
I would prefer having methods like

- `toUnit(quantity, value, targetUnit)` which returns  the `value ` which is given in default units of the `quantity` in the unit specified by `targetUnit`.
-  `toBaseUnit(quantity, value, originUnit)` returns the `value` given in `originUnit` in the base unit of the `quantity`.

**Comment by Yuri05** [comment]
we could also provide the method `quantity.SetValue(value, unit)`.
This would convert `value` from `unit` to the internal unit (or crash if not convertable)
