### ISSUE TITLE
Quantities' paths include simulation name, but the ouputs do not.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#172]
Simulation results return values for a quantity path that does not include the name of the simulation, e.g.
`"Organism|ArterialBlood|Plasma|Caffeine|Concentration in container"`.

However, the paths of the quntities always come with the simulation name. To allow retrieving the results with passed quantities, the name must be somehow removed.

@msevestre I can do it in R by removing the part of the string before the first occurence of `|`, or do you see some better way (coming from .NET?)?

**Comment by msevestre** [comment]
There are some methods to deal with this in .NET. I'll find it and let you know

**Comment by msevestre** [comment]
this was fixed with the new addition of the method in quantity
