### ISSUE TITLE
At the moment, getResults will silently ignore wrong inputs when retrieveing results

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#173]
see  https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/169#discussion_r325844778 for  a discussion

@KatrinCoboeken @Yuri05 Please feedback

**Comment by Yuri05** [comment]
I would throw an error (at least as per Default) in such a case

**Comment by msevestre** [comment]
I think this is implemented as well
