### ISSUE TITLE
Do we need two methods to retrieve results ?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#174]
see getResultsValues vs getPopulationResultsValues

The methods are exactly equivalent with the exception that getResultsValues checks that there is only one individual in the `SimulationResults` object.

Also we should probably think about a better name for `getResultsValues`

**Comment by msevestre** [comment]
FYI: @PavelBal @Yuri05

**Comment by PavelBal** [comment]
Proposal for the name?

**Comment by msevestre** [comment]
I don't know :) That's why we need to think about it. Once we know how this is getting used, we might get a better feel. Results are already values by definition. So getResultsValues is a bit too abstract for my liking. 
Maybe something like `getResultsBy`, or  `getResultsByPath` .. No idea

**Comment by PavelBal** [comment]
We already have `SimulationResults` as a class, so in the current context "results" is an abstract object that is produced when running a simulation. And from these `results` we extract `values` for certain entities.

I am also not happy with `getResultsValues` but I think we cannot use `getResults...`.

**Comment by msevestre** [comment]
At the moment, if i am using the getREsultsValue method with population results, it does nto show any error because `errorGetResultValuesPopulationSimulation` is not defined lol

Suggestion:
* Let's only keep one method. The check for only one value does not help (especially since we can use the same method to simulate ind and pop sim, no reason to treat the results differently)

* Rename the method to `getOutputValues`. Why? Because we have the `addOutput` which takes the same type of parameter (quantitiesOrPaths). At least this is consistent from a naming point of view

**Comment by msevestre** [comment]
closed with #183
