### ISSUE TITLE
Basic UseCase: Run Model with changed parameter and get results

### ISSUE THREAD

**Issue by KatrinCoboeken** [Open-Systems-Pharmacology/OSPSuite-R#18]
Almost all Uses cases Need something like this 

- load model

- change Parameter /SpeciesInitial Value  (do we Need 2 different functions for this, Parameter identifier like the paths in MoBi)

- run the model

- get timeprofile for certain output

- get timeprofile of

**Comment by PavelBal** [comment]
@msevestre We did not approach  SpeciesInitialValue so far...

**Comment by msevestre** [comment]
Isn't it defined as a parameter ? Can't remember off the top of my head

**Comment by KatrinCoboeken** [comment]
In the old Matlab Toolbox, it is something which is very similar to a parameter.

**Comment by msevestre** [comment]
Sorry I meant in the pkml model (MoBi). I can't remember if we have a parameter for a start value or if it is another type of object. Either way we'll make sure it can be set in a similar way

**Comment by Yuri05** [comment]
Initial values are not parameters.
But OSPSuiteCore already provides functionality for varying initial values:

      /// <summary>
      ///    Runs population and returns the results.
      /// </summary>
      /// <param name="simulation"></param>
      /// <param name="populationData">Data table with non-table parameter values for variation</param>
      /// <param name="agingData">Data table with table parameter values for variation</param>
      /// <param name="initialValues">Data table with (molecule) initial values</param>
      /// <returns>
      ///    Simulation results.
      ///    <para></para>
      ///    Only results for successfull individuals are stored.
      ///    <para></para>
      ///    For failed individuals, pairs {IndividualId, ErrorMessage} are stored
      /// </returns>
      Task<PopulationRunResults> RunPopulationAsync(IModelCoreSimulation simulation, DataTable populationData, DataTable agingData = null, DataTable initialValues = null);

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/7364a6f17d34f09c6191a14450d50d3c605af3d1/src/OSPSuite.Core/Domain/Services/IPopulationRunner.cs#L33-L47

**Comment by msevestre** [comment]
Sure. But we also be able to vary it at the simulation level (e.g for a single individual simulation such as we do for parameters). Two different use cases

**Comment by msevestre** [comment]
Fixed with #180
