### ISSUE TITLE
Quantity$setValue - default with base unit?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#186]
The current behavior of setting a value of a quantity using its default units by 
`quantity$value <- 5`

and setting the value in a certain unit by 

`quantity$setValue(5, unit)` 

is a bit confusing. I suggest to implemente `setValue()` that it is possible to set the value in default units without providing the unit:

```
    setValue = function(value, unit = NULL) {
      validateIsNumeric(value)

if (!is.null(unit)){
 validateHasUnit(self, unit)
value <- rClr::clrCallStatic(withDimensionExtensions, "ConvertToBaseUnit", self$ref, value, unit)
}

     
      self$value <- value
    }
```

**Comment by msevestre** [comment]
Yeah sure.

**Comment by msevestre** [comment]
done in #188
