### ISSUE TITLE
.NET Interface to OSPSuite.Core

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#2]
It should be possible to call OSPSuite.Core (e.g. CreateIndividual, CreatePopulation) from R.

.NET bridge which support both .NET Framework and .NET Core would be of advantage (in case OSPSuite.Core will be migrated to .NET Core in the future)

**Comment by PavelBal** [comment]
[rDotNet](https://cran.r-project.org/web/packages/rDotNet/index.html) is one possible solution.

**Comment by Yuri05** [comment]
@PavelBal does rDotNet support both .NET Framework and .NET Core?

**Comment by msevestre** [comment]
it would be enough to know if it works with .NET standard

**Comment by PavelBal** [comment]
If .NET standard == .Net Framework (the current state?), then yes, it does support it. It might have some limitations, though - so far, I only tested it with the functionality needed for PKSimCreateIndividual.

We surely should also concider other solutions, if there are any.

**Comment by msevestre** [comment]
.NET Standard is a set of interface

.Net Framework and .NET core implements those interface. 

So if rDotNet works with .NET standard, we know it will work with .NET framework and .NET core (Version 2.0 of .NET standard)

**Comment by PavelBal** [comment]
Another solution:
https://github.com/jmp75/rClr

**Comment by PavelBal** [comment]
Quote from the GitHub of rClr mentioned in the post above:

>As of May 2019, on Windows Clr requires the .NET Framework (4.6.1+, 4.7.2+ recommended). Groundwork towards running on .NET Core started but it is unclear how to embed the .NET Core runtime into R.

**Comment by PavelBal** [comment]
@Yuri05 @msevestre I think we can close this issue.
