### ISSUE TITLE
Basic UseCase: set relative parameter

### ISSUE THREAD

**Issue by KatrinCoboeken** [Open-Systems-Pharmacology/OSPSuite-R#20]
set one or a group of parameters relative to a fixed value.
This is used e,g, within the parameteridentifaction, to adjust a relative value instead of an absolute value.

**Comment by PavelBal** [comment]
I wouldn't write an extra method for this.

The relative value can always be defined manually (e.g. by getting the intial value before performing changes).

**Comment by msevestre** [comment]
Let's have an example of how this is intended to be used. 
@Yuri05 Can you provide?  Especially, will PI be running out of the .NET implementation?

**Comment by msevestre** [comment]
@KatrinCoboeken @Yuri05 I still don't understand why we need this. Is this really basic use case?

**Comment by KatrinCoboeken** [comment]
There are many use case where a Parameter is changed relative to it's original value. I would say in i use currently in activity specific code setRelativeParameter more often than setParameter. E.g.  for questions like what happens when you increase the Parameter xyz about 10% or a more complex sensitivity analyses or in a parameter identifications where you want to fit a factor to a group of parameters.
Of course it can be done like Pavel suggested manually. But to have a function for it is very convenient, saves work and avoids mistakes.

**Comment by PavelBal** [comment]
Well, we could write a helper function `scaleParametersValues`, which would take the percentage (or fraction) by which the parameter would be increased relative to its current value. BUT, I would implement the increase always relative to the **actual** value, not some intital value... Meaning:

```
param <- getParameter("Organism|Parameter1", sim)
param$value # 1
scaleParametersValues(param, 1.2)
param$value # 1.2
scaleParametersValues(param, 1.4)
parm$value # 1.68 and NOT 1.4!!
```

Does it make sense?
