### ISSUE TITLE
Do SimulationResults really need the simulation reference?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#202]
Maybe I am missing something, but atm the reference to the simulation object is only used when calculating PK parameters or exporting results to CSV.

I just do not really like the idea of being used to provide a simulation object when loading results from csv. And most of the time it will be impossible to create exactly the simulation as it was used for creating the saved results.

**Comment by msevestre** [comment]
> And most of the time it will be impossible to create exactly the simulation as it was used for creating the saved results.

Why would you want to load results for a simulation that you do not have anymore? What's the use case?

As far as I remember,the simulation as not a reference but you wanted it to be a reference because it was weird to have to specify a simulation to export or calculate pk 

It is definitely required to calculate pk because it gives us access to MW, application schema etc..

**Comment by msevestre** [comment]
>As far as I remember,the simulation as not a reference but you wanted it to be a reference because it was weird to have to specify a simulation to export or calculate pk

I might be wrong about that :)

**Comment by PavelBal** [comment]
> I might be wrong about that :)

Thats right, I just did not understand why the simulation is needed. Makes sense for PK parameters calculation.

> Why would you want to load results for a simulation that you do not have anymore? What's the use case?

I could ask "why would you want to load results if you have a simulation, as you could just simulate?" :) I am thinking of a workflow where I do simulations, save the results, and process them later (e.g. in separate scripts). This way I would not have the simulation. Otherwise I really do not see a use case for saving and loading the results..

**Comment by msevestre** [comment]
>I could ask "why would you want to load results if you have a simulation, as you could just simulate?" :) I

Sure. But we have an answer here: The usecase is the simulation is performed on a cluster (linux, no UI)  but the analysis should be still performed still in R in a convenient way. So the workflow is
* Setup everything in R
* Export the simulation for Cluster calculation
* Cluster calculates the heavy duty population for example on 100s of nodes
* Reload the results
* Keep working

**Comment by PavelBal** [comment]
> Export the simulation...

How do we do that?

**Comment by msevestre** [comment]
saveSimulation in utilities-simulation.R
Dumps the simulation to pkml (can be loaded back in MoBi or PKSim even)

**Comment by PavelBal** [comment]
Ah ok. Well, makes sense.
