### ISSUE TITLE
'SimulationRunOptions' not found

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#205]
```
> library("ospsuite")
> t <- SimulationRunOptions$new()
Error: object 'SimulationRunOptions' not found

```

**Comment by msevestre** [comment]
I can reproduce

**Comment by Yuri05** [comment]
error still there

**Comment by msevestre** [comment]
Make sure you uninstall the package completely and reinstall it.

Cannot reproduce on two installs. Also tests are running instantiating the
object

**Comment by Yuri05** [comment]
>Make sure you uninstall the package completely and reinstall it.

Will try. However with the new version installed above the old: another error (masked enum) has gone, but this error didn't

**Comment by msevestre** [comment]
This is so weird. What is different with this class name...I am not sure.
I might try to rename it to RunOption or something like that and see if if
makes a difference

@pavelbal. Any idea what is going on?

**Comment by Yuri05** [comment]
ok, deinstalled the package and installed again. Still the same error.
I am testing under R **3.5.2** - maybe that's make the difference?

**Comment by msevestre** [comment]
No that's what I have on my machine

**Comment by Yuri05** [comment]
That's the package you are using, correct? https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-r/builds/28528174/artifacts (version 1.0.57)

**Comment by PavelBal** [comment]
Well we are not supposed to create objects outside of the package! `Population$new()` or `Simulation$new `also do not work.

Objects should be created from within `utilities-xxx`.

**Comment by Yuri05** [comment]
@PavelBal Can you please adjust the test script https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/tests/dev/script.R accordingly?
Otherwise https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/ba8e002368efd0a1538e0118416fe526b6e8ec19/tests/dev/script.R#L65 crashes

**Comment by msevestre** [comment]
>Well we are not supposed to create objects outside of the package

What? Of course we can create object outside of the package. Why wouldn't we be able to create object?

There is nothing to adjust in the script. Calling new should work. Maybe we need to export the class in that case but I don't understand why since we don't have to export other classes

**Comment by msevestre** [comment]
Simulation$new() does not work because you need a ref to a .net object. The object in question behaves differently

**Comment by PavelBal** [comment]
> What? Of course we can create object outside of the package. Why wouldn't we be able to create object?

I must be misunderstanding something, can you give me an example of creating an object that works?

**Comment by msevestre** [comment]
Well this class should work
It's a R6 class that is supposed to be exposed to the end user to specify options for the simulation. It is optional but the user should be able to create it to override the default behavior

This class is not a .net class (it is a wrapper to one but the internal class is not used).

The call works on my machine and in the tests. It just does not work in Juri's

**Comment by msevestre** [comment]
Why do you say "we are not supposed to". Where does this limitation come from?

We said we didn't want to have rclr call everywhere and that they should be encapsulated in classes if possible. But this is something different here

**Comment by PavelBal** [comment]
> The call works on my machine and in the tests. It just does not work in Juri's

It doesn't on mine, too.

> Why do you say "we are not supposed to". Where does this limitation come from?

Class definitions are not exported.

**Comment by PavelBal** [comment]
OK you have to add `@export` to definition of `SimulationRunOptions`. No idea why it works for you without - you sure you are not sourcing everything?

**Comment by msevestre** [comment]
Yes I am positive
Then let's add export to this class. Weird that you can use a class even if it is not exported. But you cannot instantiate it.

**Comment by PavelBal** [comment]
OK I'll add the export with the upcming PR for https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/133
