### ISSUE TITLE
Return NA or NAN when path is not found?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#212]
This is more a philosophical question than anything but it can have serious implication probably

if I ask for the population results for a output path that does not exist, should I get an array of NaN or NA
(the array is populated to ensure that we do not have to check that the array have the right lenght)

**Comment by PavelBal** [comment]
I would say `NA`.

`NA` means there is no value, and this is exactly the case. `NaN` is a product of e.g. 0/0, so more or less some erroneous arithmetical evaluation.

**Comment by msevestre** [comment]
I agree. That's why I used NA instead of NaN

**Comment by Yuri05** [comment]
I have no opinion on this. As long as there is no different handling of NA and NaN in the code: for me it's the same.

**Comment by msevestre** [comment]
There are differences between NA and NaN in R
that's why there are two methods. is.na and is.nan
```
> t <- c(5, NA, NaN, NA)
> is.na(t)
[1] FALSE  TRUE  TRUE  TRUE
> is.nan(t)
[1] FALSE FALSE  TRUE FALSE
```

Na is broader as a NaN value is also na. 
I think working with Na is best in general

**Comment by msevestre** [comment]
Well we return NA so let's close it
