### ISSUE TITLE
Update readme to be clearer if required in order to get started

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#213]
At the moment, libs are copied during build time
The reason was to ensure we have a way to selectively copy what we need for windows and linux (easy to do with a script)

@PavelBal You mentioned that you expect people to download the code and compile the package. I had assume that in general, people would just install the package. Can you explain?

**Comment by msevestre** [comment]
FYI @Yuri05

**Comment by PavelBal** [comment]
\>90-95% of users will indeed just download the compiled package.

It is just my personal oppinion that if we do open-source, we should do it right, which includes a clean and documented way to download and build from source. Otherwise we will never get people to participate in development (and the R packages are probably the most likely case where externals could contribute).

**Comment by msevestre** [comment]
Well in that case we are good I believe. I have simplified the life of everyone by making a script that does everything for you and even documented the readme
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/README.md#update-packages

If this is not clear, please update.

**Comment by PavelBal** [comment]
Is it really necessary to have all the nuget packages on private `https://ci.appveyor.com/nuget/open-systems-pharmacology-ci `? At least explain that one have to add this nuget feed and it would require a password..

**Comment by msevestre** [comment]
Packages will be released in GitHub and it won't be necessary after 

Maybe it's better if the dll are in GitHub after all.
The script will always replace them with the correct version Linux vs Windows
By default it will be the window version

**Comment by msevestre** [comment]
@PavelBal CLosing. On windows, no step is required. On linux well it does not work anymore
