### ISSUE TITLE
Observer: Quantity type not set

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#217]
when getting quantities in the ospsuite-R: quantity type for observes is not set.

![grafik](https://user-images.githubusercontent.com/25061876/68941751-04390500-07a7-11ea-8c14-c99903ab3ca8.png)

**Comment by PavelBal** [comment]
Yes, we also discussed in here:
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/158

**Comment by Yuri05** [comment]
duplicate of #158. closing
