### ISSUE TITLE
Sensitivity Calculation

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#220]
Provide the wrapper function(s) to [PK-Sim/MoBi sensitivity calculations.](https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/sensitivity-analysis)

Inputs:
* Model
* [OPTIONAlL] List of model parameters
* List of PK-Parameters
* List of model outputs
* [OPTIONAlL] Number of steps
* [OPTIONAlL] Variation range
* [OPTIONAL] Population table
  **Maybe it's better to define a _separate_ function for the population sensitivity - to be discussed.**

Outputs:
* For each model output of interest: `dPK-Parameter(i)/dModel-Parameter(j)`
  * If `Population table` is given: for every individual of the population

Remarks:
* If the input `List of model parameters` is empty: calculate sensitivities for **all effectively used non-formula parameters**
  * information if parameter is effectively used in the model or not is provided by SimModel after model finalization
  * parameters with value = 0 and table parameters must be excluded from sensitivity calculations (same as in PK-Sim/MoBi, s. [here](https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/sensitivity-analysis#selection-of-interesting-input-parameters))
* If `Number of steps` is empty: use default (2)
* If `Variation range` is empty: use default (0.1)
* The output of the function will be later used e.g. for creation of [sensitivity plots in the TLF](https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/14))

**Comment by msevestre** [comment]
@Yuri05 
>information if parameter is effectively used in the model or not is provided by SimModel after model finalization

I have no idea what that means here.

**Comment by msevestre** [comment]
Especially: What range should be used in that case?

**Comment by msevestre** [comment]
Are we assuming that 
Number of steps
Variation range

are the same for every parameter?

**Comment by Yuri05** [comment]
effectively used:
https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/2d478758d11d8f9f8df234701a5624108e434784/src/OSPSuite.SimModel/ParameterProperties.cs#L103

**Comment by Yuri05** [comment]
What we will also need: extend parameter properties in OSPSuite.Core with `IsCategorical `and save this info in the PK-Sim DB. All categorical parameters must be excluded from sensitivity calculations

**Comment by msevestre** [comment]
@Yuri05 . Yep. I think we have an issue somewhere for that in Core

**Comment by Yuri05** [comment]
>Are we assuming that
Number of steps
Variation range

>are the same for every parameter?

Good question. If parameter list is empty, obviously yes. 
If parameter list is not empty: we could define optional steps/range per parameter, which would override the global settings.

@KatrinCoboeken @twendl @sfrechen Thoughts?

**Comment by msevestre** [comment]
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2

**Comment by Yuri05** [comment]
>Open-Systems-Pharmacology/OSPSuite.Core#2

Yep, now we will need this

**Comment by msevestre** [comment]
I'd suggest using only one parameter for now for number of steps and range. This will facilitate the code  as we won't have to have to manage them on R side

**Comment by Yuri05** [comment]
>I'd suggest using only one parameter for now for number of steps and range. This will facilitate the code as we won't have to have to manage them on R side

You mean only the "global" number of steps and range and not additionaly per sensitivity parameter?

**Comment by msevestre** [comment]
yes. Otherwise we need to expose the value for each parameter selection. From r Point of view, the api could simply be

createSensitivity(simulatio, list_of_parameters, number_of_steps, range) with the last 3 parameter optional. The problem is that there is a timing issue otherwise as we cannot retrieve the list of parameters until we call simmodel.

Couldn't we do it as in pksim and alsways have to specify which parameter to vary?

**Comment by Yuri05** [comment]
>Couldn't we do it as in pksim and alsways have to specify which parameter to vary?

Unfortunately no

**Comment by msevestre** [comment]
May I ask why?

**Comment by Yuri05** [comment]
In the Reporting Engine the requirement is to estimate the sensitivity of all relevant independent parameters. If all those parameters would be explicitly included, the starting script would become just huge as you can imagine. And in case of model changes (e.g. new parameters) it must be adjusted.

**Comment by msevestre** [comment]
makes sense :) thanks

**Comment by msevestre** [comment]
@Yuri05 Re effectively used.
How am I supposed to you this? I do not have a simmodel instance when I create the sensitivity analysis

I am confused

**Comment by Yuri05** [comment]
But you have a modelcore simulation, right? So you could create something like FillUsedInSim-Method, which would load and finalize SimModel-simulation and obtain IsUsed-info from it?

**Comment by msevestre** [comment]
No idea what you are talking about :)
