### ISSUE TITLE
$print method of Quantity and QuantitySelection failing

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#222]
`private$printLine(self$path, getQuantityTypesStringFromInt(self$quantityType))`

should read 

`private$printLine(self$path,getQuantityTypeAsString(self$quantityType))`

Also write tests covering the $print-methods of our classes.

**Comment by msevestre** [comment]
Assuming you mean calling the print method in tests? I don't want us to spend time trying to parse the output of the print method. We would do it in an ideal world but we have no time

Calling the print method somehow would ensure that we would catch those refactoring errors at least

**Comment by PavelBal** [comment]
No, just checking no errors are thrown.

**Comment by PavelBal** [comment]
Fixed with https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/223
