### ISSUE TITLE
Add optional TLF Support

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#229]
If the TLF package is installed, we should provide some out of the box plot capabilities for SImulationResults

I am not sure what the best API would be but we should aim at getting nice plots in very few lines of configuration

e.g.
```
plotTimeProfile(quantities, results, plotConfiguration)
```

the PlotConfiguration could even be the one coming from TLF or something slightly adjusted for the OSP need. To discuss with @abdullahhamadeh and @pchelle 

@PavelBal will take over implementation to see what might be unclear from a user point of view. THis will be a good test

**Comment by msevestre** [comment]
@Yuri05 
We should list a few fundamental plots that we want to support. Other plots can be added later

**Comment by Yuri05** [comment]
@KatrinCoboeken @DiedrichC @ju-rgen @sfrechen @AndreDlm @twendl Please comment on this

**Comment by PavelBal** [comment]
I will need input on which plots to implement (especially what are to corresponding methods in the TLF library).

Also I am struggling to think of appropriate naming of the methods in osps-r package. Any ideas? E.g. for `plotTimeProfile`, we obviously need some naming distinct from the methods used in TLF.

**Comment by msevestre** [comment]
@PavelBal Yes. Let's wait for the feedback that @Yuri05 asked on Dec 5th
I'd suggest to only add a simple timeProfile method with the most basic capabilities for now
Usage of TLF and ggplot should be optional in OSPSuite.Core. Therefore, a message should be shown if TLF is not found

**Comment by ju-rgen** [comment]
For linetype the option "noline" should be available, as users asked for displaying just symbols without a line.

**Comment by ju-rgen** [comment]
Assumptions:
When I understood the background configuration right, there can be specified the color of the drawing area/innerBackground, right? 
This can also be used to define a theme !?

**Comment by ju-rgen** [comment]
Questions to themes:
Is an example for a user definition of theme available? 
How can themes be shared by colleagues?

**Comment by pchelle** [comment]
Background configuration accounts for color of inner background, outer background, the frame line of the inner background, the grid and the watermark.
I need to add some documentation about it in the vignette, this may be helpful to understand how the themes work.

**Comment by pchelle** [comment]
There are a few options for creating and sharing themes.
Using only R, the easiest may be to use Theme$new() which initializes a new theme with default values. Then, you can modify the theme features you need to update.

The second option (that I actually prefer) is to use a .json file with all the theme features.
The R variable you obtain by reading the file using jsonlite::fromJSON() can be directly used as input of the theme: Theme$new(themesProperties = )

**Comment by pchelle** [comment]
Here is the .zip containing the features of defautlTheme, tlfTheme and bwTheme
[default-themes.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/4059768/default-themes.zip)

**Comment by ThomasGaub** [comment]
Added some thougts about this to TLF-Library specification of Timeprofile plots

**Comment by msevestre** [comment]
This needs to be specified in detail. too abstract for v10

**Comment by msevestre** [comment]
@PavelBal @StephanSchaller @Yuri05

**Comment by IndrajeetPatil** [comment]
Follow up in #674
