### ISSUE TITLE
Add vignettes

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#230]
We already have a good documentation of single methods. However we are missing the glue, e.g how to run a specific use case from start to finish
For these workflows, we can leverage the vignette concept from R. We have worked already quite extensively with vignettes for the TLF project. WE should add the same here

@pchelle Can you help @PavelBal if he has any questions?

**Comment by pchelle** [comment]
No problem. Always happy to help.
A trick to remember is that if you use other packages within your vignette, they need to be at least in the suggested packages of the DESCRIPTION file. This can be done with usethis::use_package(.., type="Suggest").

**Comment by msevestre** [comment]
@PavelBal Any idea when you can start working on these?

**Comment by msevestre** [comment]
@PavelBal Please feedback

**Comment by PavelBal** [comment]
Sorry, didn't see the notification.

Will start on monday (16.12.).
