### ISSUE TITLE
Add quick access to covariates in population 

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#232]
Age, Height, Weight, BMI

**Comment by msevestre** [comment]
@Yuri05 @PavelBal @PavelBal @abdullahhamadeh 
Thinking about this, I am not sure it makes sense.
If you just get the values, they will be returned in "BASE" unit. For example height will be in dm

What you should do for this is in fact get the parameter "Age", "BMI" etc.. from the simulation. Retrieve the correspondign parameters from the population using 
```R
# Returns the variability values defined in the population for parameterPath
getValues(parameterPath)
```

and convert the values in display unit

**Comment by msevestre** [comment]
In fact, with the code I am going to push, getting the values is going to be a few lines of code

```R
library(ospsuite)

sim <- loadSimulation("C:/projects/OSPSuite-R/tests/data/S1.pkml")
pop <- loadPopulation("C:/projects/OSPSuite-R/tests/data/pop_10.csv")

#Returns instance of BMI, AGE, Weight, height etc..
demographyParameters <- getAllParametersMatching(c("Organism|BMI", "Organism|Age", "Organism|Weight", "Organism|Height"), sim)

#Example of usage. Return the values in the population using a reference to the parameter and convert in displayUnit (e.g. the unit defined in the pkml file for this parameter)

demographyValues <- lapply(demographyParameters , function(p) toUnit(p, pop$getValues(p), p$displayUnit))
```

WE could potentially think about defining those predefined path such as "Organismi|Age" etc.. as constants . But I think this might not even be required since the demography stuff is going to be very much isolated. 

Thoughts?

**Comment by msevestre** [comment]
Note: there is also one issue with the BMI unit
Unit 'kg/m²' is not defined in dimension 'BMI' used by 'BMI'. 
but the units available are "kg/m²"  "kg/dm²"

This is another bug that I will fix separately

**Comment by msevestre** [comment]
update: Last line can be written
```
demographyValues <- lapply(demographyParameters , function(p) toDisplayUnit(p, pop$getValues(p)))
```

**Comment by Yuri05** [comment]
>WE could potentially think about defining those predefined path such as "Organismi|Age" etc.. as constants .

Like from me. I would define constants for (at least) parameter paths for:
* Age
* Weight
* Height
* BMI
* BSA
* GA
* Ontogeny factor AGP
* Ontogeny factor Albumin

Additionaly I would define 2 functions retrieving:
* All Enzyme names available in the simulation
* For a given enzyme name: paths for
  * Ontogeny factor
  * Ontogeny factor GI
  * Ref conc
  * t1/2 (liver)

**Comment by msevestre** [comment]
>All Enzyme names available in the simulation

How do you do that?

I am assuming you also mean Protein not enzymes? Or do you want to differentiate by protein type ? (This could be done with an enum also)

But I am just not sure, at the pkml level, how to retrieve this information

**Comment by Yuri05** [comment]
Yes, I mean _proteins_ (no need to diff by type).

My first thought was to take all top-level containers with Container Type in {_Enzyme_, _Transporter_, _Protein_, etc.}. However for some reason Container Type is not set for all protein properties container in a simulation (probably a bug).

Alternatively we could retrieve names of all top-level containers where all protein-specific parameters (Reference conc. etc.) are present
<img width="350" src="https://user-images.githubusercontent.com/25061876/70325349-118b6180-1832-11ea-82e5-8cb0c37879e5.png">

**Comment by msevestre** [comment]
>Alternatively we could retrieve names of all top-level containers where all protein-specific parameters (Reference conc. etc.) are present

Hum I don't really like this idea.  What I just realized is that we have the build configuration as well available (at least on the  .NET side). Can we retrieve the information from there? (e.g. from the MoleculeBuildingBlock)

**Comment by Yuri05** [comment]
>Can we retrieve the information from there? (e.g. from the MoleculeBuildingBlock)

Theoretically yes. However we should then at least check that the corresponding container is available in the simulation (or set to is present in MSV for at least one container).
Otherwise it could happen that a molecule is available in the molecules-BB, but not in the simulation
Like here: [S4.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/3932520/S4.zip)
(just set all Enzymes/Transporters=not present everywhere)

**Comment by msevestre** [comment]
yeah/ There is this information directly I believe .All PresentMoleculeNames or sthg like that
