### ISSUE TITLE
Issue with HasUnit and BMI 

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#233]
Unit 'kg/m²' is not defined in dimension 'BMI' used by 'BMI'.
but the units available are "kg/m²" "kg/dm²"

**Comment by PavelBal** [comment]
Also does not work for "µl". Maybe a problem with Unicode?

**Comment by msevestre** [comment]
yes something like this. No idea how we can solve this. this feels like a rClr bug to be honest

**Comment by PavelBal** [comment]
Can you somehow debug if rClr is able to send unicode at all?

**Comment by msevestre** [comment]
@Yuri05 This is an issue with the way special characters such as ² or µ are passed between R and .NET

I have put some breakpoints in ospsuite `hasUnit` method

```
      public bool HasUnit(string unitName)
      {
         Console.WriteLine(unitName);
         Console.WriteLine(_units.Keys.ToString("'", ", "));
         return _units.Contains(unitName);
      }
```

This is what I get in R
```
kg/m?
, kg/m�, ', kg/dm�, 
```
so the symbols are somehow different

I have no idea what we should do here

**Comment by msevestre** [comment]
@Yuri05 @PavelBal I am going to try to match the unit by index. I can verify in R first that the unit exists. And then set the value using the unit index. A little bit crazy but eh..
