### ISSUE TITLE
Usage of Path: With or without Simulation Name

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#235]
At the moment, parameter$path returns the path of the parmaeter with the simulation name. However this cannot really be used anywhere are most of the time, the path without the sim name is required

Should we have parmaeter$path return the path without the simulation name and maybe add another property fullPath or something that returns the path with the simulation name?

Thoughts @Yuri05 @PavelBal

**Comment by Yuri05** [comment]
>Should we have parmaeter$path return the path without the simulation name

yes

>maybe add another property fullPath or something that returns the path with the simulation name

do we need it at all? any use cases where path without sim name is not sufficient?

**Comment by msevestre** [comment]
I am thinking about multiple simulation scenarios. It may make sense to have a way to differentiate between two parameter having the same path in that case... Because it's highly unlikely, I don't think it should be the default behavior of path to use the simulation name.

Willl update
