### ISSUE TITLE
Redirect print in tests to another output

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#237]
@PavelBal Any idea if it's possible to have a silent print in the test or redirect the output somewhere else? With the print test that we have going, it's very hard to see what's going on in the test explorer because the output of the print is mixed with the test results

![image](https://user-images.githubusercontent.com/1041237/70401248-d0937880-19fc-11ea-9aad-3328f87492c1.png)

Any idea how to improve this? 
Maybe we should use vignette for printing instead of unit test?

**Comment by PavelBal** [comment]
Try out

`expect_error(capture.output(distributedFormula$print()), NA)`,

i.e., surronding the piece of code producing an ouput with `capture.output()`.

Found here: https://stackoverflow.com/questions/28665099/suppress-output-of-stationarity-test-that-is-printed-to-screen

**Comment by msevestre** [comment]
Do you mean you tried it out or it should be tried out?

**Comment by PavelBal** [comment]
Sorry, wrong wording. It does work, I tried it out.
