### ISSUE TITLE
Basic UseCase: get properties of parameters/ouptuts

### ISSUE THREAD

**Issue by KatrinCoboeken** [Open-Systems-Pharmacology/OSPSuite-R#24]
get following properties for Parameters/Outputs
- Unit
- isFormula (is this a formula or a static Parameter)
- Formula (string of formula)
- is table Parameter (is this a table Parameter?)
- full path

**Comment by msevestre** [comment]
Example of output

```R
distributedParameter <- getParameter("Organism|Liver|Volume", sim)
formulaParameter <- getParameter("Organism|Weight", sim)
constantParameter <- getParameter("Organism|Age", sim)

print(distributedParameter)
print(formulaParameter)
print(constantParameter)
```

Output

```
> print(distributedParameter)
Parameter: 
  Path: S1|Organism|Liver|Volume
  Value: 2.3766 [l]
  isDistributed: TRUE

> print(formulaParameter)
Parameter: 
  Path: S1|Organism|Weight
  Value: 73.00 [kg]
  isFormula: TRUE
  formula: Weight_blood + Weight_tissue

> print(constantParameter)
Parameter: 
  Path: S1|Organism|Age
  Value: 30.00 [year(s)]
  isConstant: TRUE
```

Question: 
* Is this enough?
* Would you expect the parmaeter Volume to be a constant parameter (e,g, to say IsConstant  =true). Right now, the formula is a distributed parameter and as such IsConstant returns false.
* Would you want to see the value of each flag for each parameter (e.g isConstant: true, isTable: false etc..) or just the only value that matters

@Yuri05 @KatrinCoboeken @PavelBal

**Comment by PavelBal** [comment]
> Would you want to see the value of each flag for each parameter (e.g isConstant: true, isTable: false etc..) or just the only value that matters

Yes, I would like to have it that way.
