### ISSUE TITLE
Add option to return paths without simulation name

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite-R#240]
In the getAllXXXMatching functions, the paths returned are of the form:

simulationName|Organism|Spleen|Plasma|compoundName 

often it is more useful if the path excludes the "simulationName|" prefix.

**Comment by msevestre** [comment]
This has been changed in the latest version
Can you try again and let me know if this is indeed the case?

**Comment by abdullahhamadeh** [comment]
Ok, the simulation name is removed in the latest version.  
But is there still an option to get the full path as you suggested in #235?  Could be needed for the workflow when dealing with multiple population/simulation combinations.

**Comment by msevestre** [comment]
It's there too. If you look. Called fullPath.
Probably available in ?Entity.
But hard to find because documentation of base class does not migrate to child class
e.g. ?Quantity does not show it.

**Comment by msevestre** [comment]
nothing to change here
