### ISSUE TITLE
getAllMoleculeParameters: misleading documentation?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#241]
The documentation states 

> @return A list of global parameters defined for \code{moleculeName} if the molecule exists in the \code{simulation}.
#' Otherwise an empty list is returned

However, only a set of pre-defined parameters is returned, and not **all** global ones, or is there something I miss?

Either way, I don't really undestand the purpose of this function.

**Comment by msevestre** [comment]
I agree that the name is misleading. I thought all global parameters. it should be changed
And why we need this function, I am not quite sure but this was an explicit request from @Yuri05

**Comment by msevestre** [comment]
see **https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/232#issuecomment-562495196**

**Comment by msevestre** [comment]
To be honest, I am not sure if it belongs here on in the reporting engine....
Easy to move

**Comment by msevestre** [comment]
@Yuri05 Do we need this at all?

**Comment by Yuri05** [comment]
Yes. At least we need ontogeny factors (that's where it started). And we deliver them, why not to deliver the rest (half-lives, RefConc etc.)

**Comment by msevestre** [comment]
@Yuri05 Ok. But the name is misleading. We only return a subset of parameters as @PavelBal rightfully explained

**Comment by msevestre** [comment]
Renaming to `getStandardMoleculeParameters`
