### ISSUE TITLE
Method "allMoleculeNames" of the class "Simulation"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#243]
What exactly should it return? I have a simulation of the Aciclovir-model (example PK-Sim model), and the output is 

`character(0)`

**Comment by msevestre** [comment]
IT should return the name of all "Compound" used in the simulation. How old is this aciclovir model?

**Comment by PavelBal** [comment]
It is in the "PK-Sim examples" folder of the current (8) installation.

**Comment by msevestre** [comment]
ok this returns the name of all Endogenous molecule (e.g. present and Xenobiotic = false) from the system.
Typically stuff like enzyme, proteins  Enzyme, Protein, Transporter, FcRn etc.

Should we rename it ?

In fact we have access to many of those methods. I am not sure which one is useful

```
 public virtual IReadOnlyList<string> AllPresentFloatingMoleculeNames() =>
         AllPresentMoleculeNames(m => m.IsFloating);

      public virtual IReadOnlyList<string> AllPresentXenobioticFloatingMoleculeNames() =>
         AllPresentMoleculeNames(m => m.IsFloating && m.IsXenobiotic);

      public virtual IReadOnlyList<string> AllPresentEndogenousStationaryMoleculeNames() =>
         AllPresentMoleculeNames(m => !m.IsFloating && !m.IsXenobiotic);

      public virtual IReadOnlyList<string> AllPresentEndogenousMoleculeNames() => AllPresentMoleculeNames(m => !m.IsXenobiotic);

```

I am not sure what we should expose. But the name is indeed misleading

@Yuri05 Suggestions

**Comment by msevestre** [comment]
what about this for R
```R
 #' @description
    #' Returns all endogenous molecule names defined in the simulation.
    #' This is a typically a molecule that is individual specific such as en Enzyme, Protein, Transporter, FcRn etc.
    allEndogenousMoleculeNames = function() {
      rClr::clrCall(private$.buildConfiguration, "AllPresentEndogenousStationaryMoleculeNames")
    },
    #' @description
    #' Returns all xenobiotic molecule names defined in the simulation.
    #' This is typically a molecule that is being simulated such as Compound, Inhibitor, DrugComplex.
    allXenobioticMoleculeNames = function() {
      rClr::clrCall(private$.buildConfiguration, "AllPresentXenobioticFloatingMoleculeNames")
    },
```

**Comment by PavelBal** [comment]
> what about this for R

Sounds good. However, this could be misleading for models that models some "endogenous" stuff (like glucose). @StephanSchaller what do you think?

**Comment by msevestre** [comment]
In that case in glucose floating or not? If yes, it won't be returned (as we are only dealing with Stationary here)

**Comment by PavelBal** [comment]
Glucose is floating. This is exactly what I mean - a user could expect to have it (or to mark molecules as "endogenous") returned. Why not call it

`allStationaryMoleculeNames`

and

`allFloatingMoleculeNames`

?

**Comment by StephanSchaller** [comment]
What is the use-case for this function?

When does a molecule receive the tag "Xenobiotic"?

**Comment by msevestre** [comment]
Xenobiotic is set to true when it's administered in PK-Sim

**Comment by msevestre** [comment]
>What is the use-case for this function?

Retrieve the name of all Enzymes for example. Pretty handy if you want to be able to create individuals dynamically

**Comment by msevestre** [comment]
```
allStationaryMoleculeNames

and

allFloatingMoleculeNames
```
sure. But this is not the same This is probably easier to comprehend however

**Comment by msevestre** [comment]
done
```R
  #' @description
    #' Returns the name of all stationary molecules defined in the simulation.
    #' This is a typically a molecule that is individual specific such as en Enzyme, Protein, Transporter, FcRn etc.
    allStationaryMoleculeNames = function() {
      rClr::clrCall(private$.buildConfiguration, "AllPresentStationaryMoleculeNames")
    },
    #' @description
    #' Returns the name of all floating molecules defined in the simulation.
    #' This is typically a molecule that is being simulated such as Compound, Inhibitor, DrugComplex.
    allFloatingMoleculeNames = function() {
      rClr::clrCall(private$.buildConfiguration, "AllPresentFloatingMoleculeNames")
    },
```

**Comment by msevestre** [comment]
Going to reopen beacause the proposed implementation is somewhat useless

For example metabolite are also by default Stationary. But we don't really care about those

FOr example the test fails because suddently, Caffeine-CYP1A2-MM Metabolite is returned
 "AADAC"                        
[3] "CYP3A5"                        "CYP2C9"                       
[5] "CYP1A2"                        "Caffeine-CYP1A2-MM Metabolite"
[7] "OATP1B1"                       "ABCB1" 

So I don't think that allStationaryMoleculeNames is what we want. Or not only what we want

**Comment by msevestre** [comment]
I have added more options 
```R
#' @description
    #' Returns the name of all endogenous stationary molecules defined in the simulation. (e.g. with the flag IsStationary = TRUE)
    #' This is a typically a molecule that is individual specific such as en Enzyme, Protein, Transporter, FcRn etc.
    allEndogenousStationaryMoleculeNames = function() {
      rClr::clrCall(private$.buildConfiguration, "AllPresentEndogenousStationaryMoleculeNames")
    },
    #' @description
    #' Returns the name of all xenobiotoc floating molecules defined in the simulation. (e.g. with the flag IsStationary = FALSE)
    #' This is typically a molecule that is being explicitely simulated such as Compound, Inhibitor, DrugComplex.
    allXenobioticFloatingMoleculeNames = function() {
      rClr::clrCall(private$.buildConfiguration, "AllPresentXenobioticFloatingMoleculeNames")
    },
    #' @description
    #' Returns the name of all stationary molecules defined in the simulation. (e.g. with the flag IsStationary = TRUE)
    allStationaryMoleculeNames = function() {
      rClr::clrCall(private$.buildConfiguration, "AllPresentStationaryMoleculeNames")
    },
    #' @description
    #' Returns the name of all floating molecules defined in the simulation. (e.g. with the flag IsStationary = FALSE)
    allFloatingMoleculeNames = function() {
      rClr::clrCall(private$.buildConfiguration, "AllPresentFloatingMoleculeNames")
    },
```
These are instance methods for advanced scenario anyways. But at least they are available

**Comment by StephanSchaller** [comment]
> for advanced scenario anyways

agreed... thus, keeping the very "technical" names should be fine as well.
