### ISSUE TITLE
"Dimension Dimensionless per time not available in DimensionFactory."

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#246]
Please, please, please, finally add this dimension to the XML.

**Comment by msevestre** [comment]
Isn't inverse time? 

Why do you need this?

**Comment by msevestre** [comment]
And what does it have to do with ospsuite-r?

**Comment by PavelBal** [comment]
> Isn't inverse time?

No! See https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/827, https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/440, https://github.com/Open-Systems-Pharmacology/MoBi/issues/379

> And what does it have to do with ospsuite-r?

Because I cannot load models that have this dimension (and yes, my models still have this dimension)

**Comment by msevestre** [comment]
Ok so that's a bug that was fixed 
Open your pkml file and search replace dimension per time with InversedTime (check spelling before doing so). You should be good to go

**Comment by PavelBal** [comment]
So, I have to do it every time I export a pkml? Why not just add 

```
  <Dimension name="Dimensionless per time" baseUnit="/min">
      <BaseRepresentation lengthExponent="0" massExponent="0" timeExponent="-1" electricCurrentExponent="0" temperatureExponent="0" amountExponent="0" luminousIntensityExponent="0" />
      <Units>
        <Unit name="/min" factor="1" />
      </Units>
    </Dimension>
```

To OSPSuite.Dimensions.xml?

**Comment by msevestre** [comment]
you should not have it with a new version of MoBi.
We should not add it to the list because it will be visible in the list of dimension and it does not make sense.
If you have it again when exporting a new model from mobi to pkml, then the bug is not fixed

**Comment by PavelBal** [comment]
Yes, I still have it.

The project itself is rather old (pre-OSPS).

**Comment by msevestre** [comment]
yeah nothing we can do in that case. At any rate, this also apply for all other dimensions that were misleadingly created by MoBi.

**Comment by PavelBal** [comment]
> yeah nothing we can do in that case.

You mean, the bug cannot be fixed?

> At any rate, this also apply for all other dimensions that were misleadingly created by MoBi.

Yes.

**Comment by msevestre** [comment]
The bug is fixed in Mobi. But old project won't work. We could potentially try to do a project conversion here but this needs to be done in MoBi

**Comment by msevestre** [comment]
I am going to push a fix so that pkml will be converted even when there is this dimension. Can you let me know what other stupid wrong conversions you have found as well. I will submit a PR and you can comment their
