### ISSUE TITLE
Make population file input to getOutputValuesTLF optional

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite-R#256]
Does the model file have default parameters in lieu of those that would come from the population file?

If yes, then need to make population file input to getOutputValuesTLF optional for when we run a mean model.  

If not, then somehow need to input the individual's (rather than the population's) data.

**Comment by msevestre** [comment]
Population is already optional in the method. I am not sure what else is needed here

**Comment by msevestre** [comment]
closing. Please reopen if something is not clear
