### ISSUE TITLE
Implement SimulationRunOptions$print()

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#261]
No print method available.

**Comment by msevestre** [comment]
going to do this unless you have done it already?

**Comment by PavelBal** [comment]
Done it, is in the current PR.

**Comment by msevestre** [comment]
PR for vignettes?

**Comment by PavelBal** [comment]
Yes

**Comment by msevestre** [comment]
ok let's reference this in the commit so that it's linked
something like Fixes #261 

Best is to create separate branches here as the vignettes is a WIP and this can be fixed indepedentently

**Comment by msevestre** [comment]
I am going to copy your code so that I can close the issue
