### ISSUE TITLE
Package for Linux

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#264]
[ospsuite_9.0.18.zip](https://github@Yuri05/Open-Systems-Pharmacology/OSPSuite-R/files/4103308/ospsuite_9.0.18.zip)

@Yuri05 Package muss man zunaechst entzippen und dann insallieren
```
install.packages("~/Desktop/ospsuite_9.0.18/ospsuite", repos = NULL, type = "source")
```

Es ist wichtig, das LIB Path im Pfad hinzuzufuegen. Es muss noch per hand gemacht werden.
Kannst Du noch mal aufschreiben, wie es ging?

**Comment by msevestre** [comment]
export LD_LIBRARY_PATH=/my/funcy/path/:$LD_LIBRARY_PATH

**Comment by Yuri05** [comment]
@msevestre Link to ospsuite_9.0.18.zip is broken...

**Comment by msevestre** [comment]
[ospsuite_9.0.18.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/4103371/ospsuite_9.0.18.zip)
