### ISSUE TITLE
Entity$parentContainer

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#266]
Can we somehow get the parent container of an entity? Would be very helpful.

**Comment by msevestre** [comment]
The problem is that you would get another instance of the R instance probably. E.g. if child1 and child2 are both children from container,

child1.parent and child2.parent wouldn't be the same instance in R (but the same in .net).

Why do you need this?

**Comment by PavelBal** [comment]
> child1.parent and child2.parent wouldn't be the same instance in R (but the same in .net).

I see. That's unfortunate.

> Why do you need this?

Could do some cool stuff like, e.g., setting initial conditions such that the concentration of a molecule would be equal in all compartments. Let's say, for molecule `a` the start amount would be 

`targetConcentration * getParameter("Volume", a$parentContainer)`

Of course, for this one I could to the other way around - iterate through the containers, get the volume, and then the molecule in this container....
