### ISSUE TITLE
Add getValueAt and addPoints to Table Formula

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#271]
I would like to have methods to conveniently edit table formulas, with methods like:

-getAllPoints(TableFormula)

-getValueAt(xValue) - returns the value y at point x. If no exact point X exists, the value should be interpolated as it is done in MoBi

-addValues(xVals, yVals) - adds x-y pairs to existing values. If an x value already exists, it will be overwritten.

-setTableValues(xVals, yVals) - removes old values and adds new

**Comment by msevestre** [comment]
Don't we have this methods in the object already? We agreed that we would not create utility method that do nothing else than calling the object methods

**Comment by PavelBal** [comment]
We have `allPoints`, which covers `getAllPoints(TableFormula)`. We don't have something similar for `getValueAt(xValue)`, only `addPoint` (so sinlge point only, nothing for `addValues(xVals, yVals)`).

**Comment by msevestre** [comment]
shouldn't we stick with the nomenclarture and use addPoints and not `addValues`. ? Any reason why you want to go way from the Point nomenclature even used in MoBi?

**Comment by msevestre** [comment]
ok going to go with the following
`setPoints`, `addPoints`, `valueAt`

I have removed addPoint
