### ISSUE TITLE
roxygen2 docs with link does not create link

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#274]
@PavelBal 
#' Retrieve all sub containers of a parent container (simulation or container instance) matching the given path criteria
#'
#' @param paths A vector of strings representing the paths relative to the \code{container}
#' @param container A Container or Simulation used to find the containers
#' @seealso \code{\link{loadSimulation}} and \code{\link{getContainer}} to create objects of type Container or Simulation

This does not work. Can you let me know if it worked before?

**Comment by PavelBal** [comment]
Cannot confirm - I do get links on my machine.

**Comment by msevestre** [comment]
Where are the links? Maybe we are talking about something else?

**Comment by PavelBal** [comment]
![image](https://user-images.githubusercontent.com/25903040/73670706-075ad780-46aa-11ea-8807-92e922b60c54.png)


No?

**Comment by msevestre** [comment]
Interesting
![image](https://user-images.githubusercontent.com/1041237/73670880-03ae5d00-4678-11ea-8b7d-c8fab5fb9399.png)


The links are not active for me.. WTF

**Comment by PavelBal** [comment]
Maybe check your roxygen-options for build??

![image](https://user-images.githubusercontent.com/25903040/73671634-a2a07c80-46ab-11ea-9a60-28c07a90d3e4.png)

**Comment by msevestre** [comment]
it's the same as yours. I don't really care if it does not work on my machine. But it should work when someone insalls the package with install.package. 

@abdullahhamadeh Can you let me know if links are working for you?

**Comment by msevestre** [comment]
That's the same on a fresh install of RStudio on ubuntu
![image](https://user-images.githubusercontent.com/1041237/73674893-753dd980-467f-11ea-9b10-f4c0bb93a474.png)

**Comment by PavelBal** [comment]
No idea, I tried it a couple of times and it still works. We must check if the release version (created by AppVeyor?) has the links or not.

**Comment by msevestre** [comment]
@Yuri05 Can you open the link from the documentation?

**Comment by Yuri05** [comment]
@msevestre That works for me (ospsuite 9.0.57)

**Comment by PavelBal** [comment]
Is the bug still present?

**Comment by msevestre** [comment]
works for Juri and you. Not for me. Well too bad for me :)
