### ISSUE TITLE
Function to extract a individual data from a population file

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite-R#285]
Need a function of the form

pathNamesValuesList <- function(populationFilePath,individualID)
where 
- populationFilePath is the path to a population csv
- individualID could be a vector of integers 
- pathNamesValuesList is a list where each element has a path field (string), a value field (numeric) and a units field.

**Comment by msevestre** [comment]
Any reason why you are needing populationFilePath as opposed to population object?

**Comment by abdullahhamadeh** [comment]
A population object probably would work better - only need to load it once.

**Comment by msevestre** [comment]
sounds good
