### ISSUE TITLE
Function to set parameters of a simulation object by path

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite-R#286]
Need a function of the form 

setSimulationParameters <- function(simulationObject,pathNamesValuesList)

where:
- simulationObject is a simulation previously loaded from pkml
- pathNamesValuesList is a list where each element has a path field (string), a value field (numeric) and a units field (see #285).
- returns simulationObject but with parameters updated from pathNamesValuesList

**Comment by msevestre** [comment]
I'd suggest to NOT Return the simulationObject. This methods as side effect. Method with sideeffect typically have no return values

**Comment by abdullahhamadeh** [comment]
But the original simulation object will be updated, right?  We are sending a pointer in essence.

**Comment by msevestre** [comment]
yes. That's what I mean with sideeffect. If we were to return a simulation, it could look as if we were cloning the simulation pass as parameter...which we are not, We are in fact MODIFYING the input parameters (side effect)

**Comment by PavelBal** [comment]
I don't understand... Isn't it what `setParameterValues` does?

**Comment by msevestre** [comment]
No this methods takes parameter instances (unless I am mistaken). One we call the other probably. This is more a convenience method to set all values at once (e.g. from an individual row in a pop file)

**Comment by msevestre** [comment]
We will used the existing ParmaeterValue that we have in core and in R already (with path, value and percentile). Value will be assumed to always be in base unit (as it is the way those parameters are created in the first place). It will be the responsability of the caller to set the value in base unit if he/she so desires to manipulate  the entities

**Comment by msevestre** [comment]
e.g. parameter will be an list of ParameterValue instead of a list with two lists
