### ISSUE TITLE
no error given when loading non-existent population-filename

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/OSPSuite-R#301]
I have tested all the steps in package (Vignette) OSP-suite using an inhouse compound, (in R "browseVignettes()" ). So far I could repeat every example, with only 1 bug:

After loading  "popFilePath <- file.path(dataPath, paste0("xxx.csv"), fsep = .Platform$file.sep)"
where "xxx.csv",does not exist, I  expected an error, which didn't happen.

Bug?

**Comment by msevestre** [comment]
Can't reproduce

Loading a pop file that does not exist returns an exception
```
population <- loadPopulation("tests/data/popxx_10.csv")
Error in rClr::clrCall(populationTask, "ImportPopulation", csvPopulationFile) : 
  Type:    OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Error: Could not find file 'C:\projects\OSPSuite-R\tests\data\popxx_10.csv'.
Method:  Void LogToR(OSPSuite.Infrastructure.Import.Services.IImportLogger)
Stack trace:
   at OSPSuite.R.Extensions.ImportLoggerExtensions.LogToR(IImportLogger importLogger)
   at OSPSuite.R.Services.PopulationTask.ImportPopulation(String fileFullPath)
```

@Incei 
How do you load the population file?

**Comment by msevestre** [comment]
```
popFilePath <- file.path(dataPath, paste0("xxx.csv"), fsep = .Platform$file.sep)
```

This does not load anything, right?
you need to do 
```
popFilePath <- file.path(dataPath, paste0("xxx.csv"), fsep = .Platform$file.sep)
population <- loadPopulation(popFilePath )
```

**Comment by Incei** [comment]
That is correct, ok, so if for assigning a non-existing file in a path, it is not a problem then when no errors occur, then we can close this issue. 

When trying to load it, obviously it will not find it :). However creating a non-existing path/file ( I thought) should also give an error.
Thanks for the check

**Comment by msevestre** [comment]
>so if for assigning a non-existing file in a path, it is not a problem then when no errors occur, 

yeah this is standard R code. It allows to create a path that is consistent, without too many "/" etc also using the platform specific separator.

The file may or may not exist. For example it could be a way to create a path to save a file at a specific location. All good here
