### ISSUE TITLE
Export error-checks

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#305]
We have implemented some cool error checks, maybe we should export them so they can be used outside of the package?

**Comment by msevestre** [comment]
TLF and reporting engine are using the very same code (copy paste). I wish we could have a validaton package that everyone could use.But until then, I would NOT export those function because it will create serious conficts (or not but I know that having two methods with the same name can be a big pain in R)

**Comment by PavelBal** [comment]
> having two methods with the same name can be a big pain in R

True. But this will also be a problem with a separate validation package?

Maybe we could rename the methods by adding a suffix like `osps`?

**Comment by msevestre** [comment]
>True. But this will also be a problem with a separate validation package?

no. in that case, each packae would reference the same validation package and we would be good to go.

Let's postpone for now

**Comment by Yuri05** [comment]
Let's do it **after** OSPSuite 9 is released.

**Comment by PavelBal** [comment]
One way of avoiding copy-paste is to use `ospsuite:::`-prefix to access non-exported methods. `R CMD check` will complain but we are not aiming for CRAN, so not a big deal as I see it.

FYI @abdullahhamadeh

**Comment by PavelBal** [comment]
@IndrajeetPatil Here's the original issue.

@msevestre Indra also proposed to outsource the error checks to a separate package `ospValidateR` (or smthing like this) that can be used by the various packages we have. Should we go for it? We could export the checks as well as the messages that could be used across the packages.

**Comment by Yuri05** [comment]
should we define the error checks as a **submodule** instead?
while it's good idea to outsource (avoid code duplicaton) - every new package brings additional complexity (installation, release-management, etc.). So if the code is not of value **as standalone**, but only when used by other packages - submodule might be a better alternative.

**Comment by PavelBal** [comment]
@Yuri05  What do you mean by "submodule"?

**Comment by IndrajeetPatil** [comment]
Like these: https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/.gitmodules

So we will have a git submodule with all the error check functions.

**Comment by IndrajeetPatil** [comment]
Yeah, that's also a good alternative to creating a separate package to import.

**Comment by PavelBal** [comment]
OK, then I also think it is even better than having a separate package.

**Comment by IndrajeetPatil** [comment]
Here are a few functions that can be added to the submodule. Feel free to edit the list as you come across other internal functions that might be for other packages in the ecosystem:

- [ ] Printable
- [ ] validateIsNumeric
- [ ] validateIsString
- [ ] validateEnumValue
- [ ] validateIsSameLength
- [ ] validateIsOfType
- [ ] validateIsLogical
- [ ] getContainerTask
- [ ] toList

**Comment by msevestre** [comment]
I am not so sure about this. Submodules are installed in a folder I believe. as far as I know, the R code must be in the R folder?
@IndrajeetPatil Is this correct? We could probably install the submodule directly in the R folder

**Comment by msevestre** [comment]
@IndrajeetPatil It looks like we are exporting more that just validation stuff? toList etc.. Why not. We have a bunch more utility function such as  the `%||%` etc...  `ifNotNull`

do we also want to put method using .NET object such as `getContainerTask`... I am not so sure about those. In fact, this should be a private method and if it's being used outside of ospsuiteR, someone is not working at the right abstraction level

**Comment by msevestre** [comment]
I am not even sure that one can add a submodule to an existing directory

see try here
```
C:\projects\tata (master -> origin)
λ git submodule add https://github.com/Open-Systems-Pharmacology/build-scripts.git R/
'R' already exists in the index

C:\projects\tata (master -> origin)
λ git submodule add https://github.com/Open-Systems-Pharmacology/build-scripts.git R2/
Cloning into 'C:/projects/tata/R2'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 54 (delta 1), reused 1 (delta 0), pack-reused 48
Unpacking objects: 100% (54/54), done.

```

**Comment by msevestre** [comment]
So the 1M $ question is: Can we have R code not directly in the R folder? anyone?

**Comment by PavelBal** [comment]
> do we also want to put method using .NET object such as getContainerTask... I am not so sure about those. In fact, this should be a private method and if it's being used outside of ospsuiteR, someone is not working at the right abstraction level

"Someone" just sometimes needs more low-level access than the ospsuite-r abstraction provides ;) But I agree, this should not be exposed more than it is now.

**Comment by msevestre** [comment]
@PavelBal This was for you :))

**Comment by msevestre** [comment]
but for real, waht's missing?

**Comment by PavelBal** [comment]
> but for real, waht's missing?

I am using a `ContainerTask` to get the `IsExplicitFormulaByPath` property. I guess we did not expose the "...ByPath" methods, but that's ok.

> So the 1M $ question is: Can we have R code not directly in the R folder? anyone?

@IndrajeetPatil Any experience here?

**Comment by Yuri05** [comment]
is it possible to store the R code in a **subfolder** of the R-folder?

**Comment by IndrajeetPatil** [comment]
I have _never_ seen submodule usage in R packages in the wild, so my hunch is that it is not possible to store the R code in a subfolder of the R-folder. But let me do a bit more digging (can't find anything in Hadley's [R packages](https://r-pkgs.org/) bible).

Worst case scenario, we have another package. But given that this would be a low-level dependency, (I am assuming) it would be a stable release from the get go and shouldn't cause us to enter any tricky dependency management issues?

**Comment by IndrajeetPatil** [comment]
Going through the code, I see that, in order to not gain `{ospsuite}` as a dependency, `{tlf}` duplicates a significant amount of code, which is, of course, not ideal.

So, I think, we should seriously consider doing this split (ospsuite -> ospsuite + validation) soon.

**Comment by IndrajeetPatil** [comment]
If we like this name, someone with the right permissions can create the repo for this package, and then I can start moving the functions to this new package repo.

**Comment by msevestre** [comment]
done https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils

**Comment by msevestre** [comment]
rdev team as manage access to the repo. @IndrajeetPatil Please do your magic

**Comment by IndrajeetPatil** [comment]
Haha, perfect

Closing in favor of https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/issues/1

**Comment by IndrajeetPatil** [comment]
The initial working version of this package is ready:
https://www.open-systems-pharmacology.org/OSPSuite.RUtils/reference/index.html

**Comment by msevestre** [comment]
the version is off
![image](https://user-images.githubusercontent.com/1041237/140328717-5dac3fd7-e92a-4b82-bd66-b64a41461754.png)

**Comment by IndrajeetPatil** [comment]
What do you mean by the version is *off*? 

I am keeping it in sync with the version of `{ospsuite}`. If not, what should it be? I can just change it.
