### ISSUE TITLE
Getting started example

### ISSUE THREAD

**Issue by lkuepfer** [Open-Systems-Pharmacology/OSPSuite-R#308]
A illustrative and explanatory "getting started" example should be provided.

**Comment by msevestre** [comment]
Did you check the vignettes? Lots of examples here already

Or do you mean we should update the readme?

**Comment by lkuepfer** [comment]
I found it very hard to get used to the “R” thinking.
For me, the osp vignette was not instructive.

////////////////////

Bayer AG
Research & Development, Pharmaceuticals
Systems Pharmacology & Medicine II
Building B106, 106
51368 Leverkusen, Germany
Tel:       +49 214 30-22745
Mobile: +49 173 24-79088
E-mail:  lars.kuepfer@bayer.com
Web:    http://www.bayer.com
Datenschutzhinweise<https://www.bayer.de/de/datenschutzhinweise-fuer-ausgewaehlte-verarbeitungstaetigkeiten.aspx> // Data privacy information<https://www.bayer.com/en/data-privacy-information-for-specific-processing-activities.aspx>

/// Vorstand: Werner Baumann, Vorsitzender | Liam Condon, Wolfgang Nickl, Stefan Oelrich, Heiko Schipper
/// Vorsitzender des Aufsichtsrats: Werner Wenning
/// Sitz der Gesellschaft: Leverkusen | Amtsgericht Köln, HRB 48248

**Comment by msevestre** [comment]
Fair enough.
What would you change in the vignettes to make them easier to understand?
/cc @PavelBal 

This is not just a migration from the Matlab to the R toolbox. (for that we had the old R Toolbox). This is a complete redesign using also a complete different way of accessing parameters, variables. etc.. This goes away from the DCI Table approach and allows to use objects. For example, a parameter is an object and it has a unit, a name. To change the value of parmaeter, you just do parameter.value<-5

**Comment by lkuepfer** [comment]
„This is not just a migration from the Matlab to the R toolbox. (for that we had the old R Toolbox). This is a complete redesign using also a complete different way of accessing parameters, variables. etc.. This goes away from the DCI Table approach and allows to use objects. For example, a parameter is an object and it has a unit, a name. To change the value of parmaeter, you just do parameter.value<-5”

Why that? What is the reason for that change?


////////////////////

Bayer AG
Research & Development, Pharmaceuticals
Systems Pharmacology & Medicine II
Building B106, 106
51368 Leverkusen, Germany
Tel:       +49 214 30-22745
Mobile: +49 173 24-79088
E-mail:  lars.kuepfer@bayer.com
Web:    http://www.bayer.com
Datenschutzhinweise<https://www.bayer.de/de/datenschutzhinweise-fuer-ausgewaehlte-verarbeitungstaetigkeiten.aspx> // Data privacy information<https://www.bayer.com/en/data-privacy-information-for-specific-processing-activities.aspx>

/// Vorstand: Werner Baumann, Vorsitzender | Liam Condon, Wolfgang Nickl, Stefan Oelrich, Heiko Schipper
/// Vorsitzender des Aufsichtsrats: Werner Wenning
/// Sitz der Gesellschaft: Leverkusen | Amtsgericht Köln, HRB 48248

**Comment by msevestre** [comment]
>Why that? What is the reason for that change?

Mostly to avoid code duplication. The matlab code was **litterally** duplicating hundreds (if not thousands) of line of code already implemented in MoBi and PKSim. Know the toolbox uses the same code. Also we are working at a much higher level. We use the PKML and not the xml. e.g. we have exactly the same concepts as in MoBi (Container, parameter). 

On a few examples that I have manually migrated, the code has been reduced significantly. No need to mess around with InitStruct etc... 

Last but not least, you can save any changes into your pkml and import back into MoBi. Full circle :)

**Comment by msevestre** [comment]
But for the why ,  I'll leave @Yuri05 answer:)

**Comment by Yuri05** [comment]
>Why that? What is the reason for that change?

It is called "progress" :stuck_out_tongue_winking_eye:

**Comment by Yuri05** [comment]
@lkuepfer 

Current approach in the Matlab toolbox - working with the `low-level representation` of a model (_SimModel-XML_) - has a lot of major drawbacks:
* this model format was primarily designed for **parameter variation and simulation of a model** - nothing else. It contains a very limited information about all the biological properties of a model. And even the available information must be extracted from entity paths, which is absolutely perverse
* this is one way approach: modified models cannot be read back into PK-Sim/MoBi
* it does not allow any extensions (e.g. if one day we would like to implement not only parameter/initial values variation but also e.g. structural changes or whatever - with the current approach it would be virtually impossible)
* with the new approach (working with the `high-level representation` of a model - PKML) we have access to all biological properties of a model in a very convenient way
* with the new approach we have access to all the functionality implemented in the OSPSuite core (like sensitivities calculation, PK values calculation, etc.). At the moment if this kind of functionality is required in Matlab - it's reimplemented in the Matlab toolbox, which is also completely perverse
* with the new approach we have a very easy way of parallelization for the tasks like population calculation/sensitivity analysis. 

The major reason why this technology change was not done much earlier: the toolbox must run both under Windows and Linux. Matlab however does not provide access to .NET components (=OSPSuite core) under Linux.

**Comment by PavelBal** [comment]
Close?

**Comment by IndrajeetPatil** [comment]
Yeah, I think this can be closed.
