### ISSUE TITLE
generateRCodeForPKML

### ISSUE THREAD

**Issue by lkuepfer** [Open-Systems-Pharmacology/OSPSuite-R#309]
A R-equivalent to generatematlabCodeForXML should be provided to avoid confusion with paths etc.

**Comment by Yuri05** [comment]
I would realize it in _MoBi_ (just another "Export XXX for R" applied to a simulation).
One possibility would be to export based on selections made in the simulation, e.g.
* Use parameters selected as favorites for variation
* Use outputs selected for calculation

In this scenario, no additional UI is required.

Another possibility would be to use a UI like in the current Matlab implementation. 
The first option (no UI) is sufficient from my point of view.

**Comment by Yuri05** [comment]
@lkuepfer Can you provide an example for the **output** (generated matlab script) of `generateMatlabCodeForXML`?

**Comment by lkuepfer** [comment]
Freundliche Grüße / Best regards,

Dr. Lars Kuepfer
Scientist Systems Pharmacology

////////////////////

Bayer AG
Research & Development, Pharmaceuticals
Systems Pharmacology & Medicine II
Building B106, 106
51368 Leverkusen, Germany
Tel:       +49 214 30-22745
Mobile: +49 173 24-79088
E-mail:  lars.kuepfer@bayer.com
Web:    http://www.bayer.com
Datenschutzhinweise<https://www.bayer.de/de/datenschutzhinweise-fuer-ausgewaehlte-verarbeitungstaetigkeiten.aspx> // Data privacy information<https://www.bayer.com/en/data-privacy-information-for-specific-processing-activities.aspx>

/// Vorstand: Werner Baumann, Vorsitzender | Liam Condon, Wolfgang Nickl, Stefan Oelrich, Heiko Schipper
/// Vorsitzender des Aufsichtsrats: Werner Wenning
/// Sitz der Gesellschaft: Leverkusen | Amtsgericht Köln, HRB 48248

**Comment by PavelBal** [comment]
> Use outputs selected for calculation

They are already selected in the PKML, or do you mean to generate code that would retrieve these outputs?

**Comment by lkuepfer** [comment]
Yes. I am routinely using generatematlabcodeforxml.m  and not having this possibility would significantly hamper working with the toolbox.

////////////////////

Bayer AG
Research & Development, Pharmaceuticals
Systems Pharmacology & Medicine II
Building B106, 106
51368 Leverkusen, Germany
Tel:       +49 214 30-22745
Mobile: +49 173 24-79088
E-mail:  lars.kuepfer@bayer.com
Web:    http://www.bayer.com
Datenschutzhinweise<https://www.bayer.de/de/datenschutzhinweise-fuer-ausgewaehlte-verarbeitungstaetigkeiten.aspx> // Data privacy information<https://www.bayer.com/en/data-privacy-information-for-specific-processing-activities.aspx>

/// Vorstand: Werner Baumann, Vorsitzender | Liam Condon, Wolfgang Nickl, Stefan Oelrich, Heiko Schipper
/// Vorsitzender des Aufsichtsrats: Werner Wenning
/// Sitz der Gesellschaft: Leverkusen | Amtsgericht Köln, HRB 48248

**Comment by msevestre** [comment]
What does `generatematlabcodeforxml.m` do aside from allowing the selection of outputs?

**Comment by lkuepfer** [comment]
[SIM.txt](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/4254955/SIM.txt)

**Comment by PavelBal** [comment]
Does it make sense without a GUI?

**Comment by lkuepfer** [comment]
Probably no ;-)!

////////////////////

Bayer AG
Research & Development, Pharmaceuticals
Systems Pharmacology & Medicine II
Building B106, 106
51368 Leverkusen, Germany
Tel:       +49 214 30-22745
Mobile: +49 173 24-79088
E-mail:  lars.kuepfer@bayer.com
Web:    http://www.bayer.com
Datenschutzhinweise<https://www.bayer.de/de/datenschutzhinweise-fuer-ausgewaehlte-verarbeitungstaetigkeiten.aspx> // Data privacy information<https://www.bayer.com/en/data-privacy-information-for-specific-processing-activities.aspx>

/// Vorstand: Werner Baumann, Vorsitzender | Liam Condon, Wolfgang Nickl, Stefan Oelrich, Heiko Schipper
/// Vorsitzender des Aufsichtsrats: Werner Wenning
/// Sitz der Gesellschaft: Leverkusen | Amtsgericht Köln, HRB 48248

**Comment by StephanSchaller** [comment]
> Probably no ;-)!

A shiny app comes to mind that can read the pkml and create tree-views of the model just like generatematlabcodeforxml.m … of course, you can have a GUI in MoBi, but using it on the PKML which you use in R anyway makes it more consistent.

**Comment by msevestre** [comment]
Why not simply have a dump generated from mobi that shows how to access the favorite parameters and manipulate the outputs?

No UI in this package. If someone wants to create another package to do so, why not.

**Comment by Christoph27** [comment]
I agree with Lars that a function "generateRCodeForPKML" would be very useful. 
As the current generatematlabCodeForXML it should generate the pathes of selected state variables, observers, parameters and initial conditions as well as indicate if the selected object is a number or given by an equation.

**Comment by ThomasGaub** [comment]
> Why not simply have a dump generated from mobi that shows how to access the favorite parameters and manipulate the outputs?

This will not really  help in the cases there "generateRCodeForPKML" is needed. For the standard cases (were it is not easy to define what is standard) I can easily copy paths from older projects. 
The benefit from 'generateRCodeForPKML' is that in regular happening non standrad cases I can get the correct paths fast with out the risk of typos, navigating in another application and coping names and having a goog starting point for my scripts.

**Comment by StephanSchaller** [comment]
> The benefit from 'generateRCodeForPKML' is that in regular happening non standrad cases I can get the correct paths fast with out the risk of typos

I do agree.

Maybe we can try translating the Matlab routine to R? This can't be too much work, right? ;-)

**Comment by msevestre** [comment]
Sorry but that would work without any problem in MoBi since we are using pkml in R. Selection of output, parameters etc...could all be done in MoBi

Or what do you mean with non standard case?

**Comment by ThomasGaub** [comment]
If we can generate an R-Script out of Mobi  containing Manuplating selected Parameters, and geting selected outputs to do addition post processing steps, this will be sufficient for me.
This can not be solved by a standard script giving some general exampels.

**Comment by lkuepfer** [comment]
I usually leave the MoBi-File as is and changes e.g. doses or parameters form Matlab.
I therefore frequently use generateMatlabCodeforXML. In particular to avoid typos!

////////////////////

Bayer AG
Research & Development, Pharmaceuticals
Systems Pharmacology & Medicine II
Building B106, 106
51368 Leverkusen, Germany
Tel:       +49 214 30-22745
Mobile: +49 173 24-79088
E-mail:  lars.kuepfer@bayer.com
Web:    http://www.bayer.com
Datenschutzhinweise<https://www.bayer.de/de/datenschutzhinweise-fuer-ausgewaehlte-verarbeitungstaetigkeiten.aspx> // Data privacy information<https://www.bayer.com/en/data-privacy-information-for-specific-processing-activities.aspx>

/// Vorstand: Werner Baumann, Vorsitzender | Liam Condon, Wolfgang Nickl, Stefan Oelrich, Heiko Schipper
/// Vorsitzender des Aufsichtsrats: Werner Wenning
/// Sitz der Gesellschaft: Leverkusen | Amtsgericht Köln, HRB 48248

**Comment by msevestre** [comment]
This was my suggestion. Setup the stuff of interest in MoBi and export the r code from the simulation. That would be an easy starting point

What the code should be however. No idea. We will generate code that is not even required because for example all selected output of a simulation are already available. 

If someone could draft the r code that should be implemented,  (and copying from Matlab does not make sense because everything is different) then we could implement the export

**Comment by lkuepfer** [comment]
I was rather promoting the 'generateRCodeForPKML' idea… Switching back and forth from MoBi and R anytime a new modifications is required will be troublesome

////////////////////

Bayer AG
Research & Development, Pharmaceuticals
Systems Pharmacology & Medicine II
Building B106, 106
51368 Leverkusen, Germany
Tel:       +49 214 30-22745
Mobile: +49 173 24-79088
E-mail:  lars.kuepfer@bayer.com
Web:    http://www.bayer.com
Datenschutzhinweise<https://www.bayer.de/de/datenschutzhinweise-fuer-ausgewaehlte-verarbeitungstaetigkeiten.aspx> // Data privacy information<https://www.bayer.com/en/data-privacy-information-for-specific-processing-activities.aspx>

/// Vorstand: Werner Baumann, Vorsitzender | Liam Condon, Wolfgang Nickl, Stefan Oelrich, Heiko Schipper
/// Vorsitzender des Aufsichtsrats: Werner Wenning
/// Sitz der Gesellschaft: Leverkusen | Amtsgericht Köln, HRB 48248

**Comment by ThomasGaub** [comment]
Ok, that was not my undestanding. 
The essential part will be more the parameter manipulation

**Comment by msevestre** [comment]
We have a method (not public yet) that analysis the simulation and gives you intellisence to create the path

For example sim$organism$liver etc....
I'll put some screenshots and you might realize, that the UI might not required if the goal is just to avoid typos

Also the new toolbox works with wildcards. No need to use full path

**Comment by msevestre** [comment]
>I can sketch th code based on the existing Matlab solution on Monday

This will be a waste of your time. Everything has changed. Please use the OSPSuite-R to create a script that should be generated automatically (either from MoBi or from a UI R tool that someone would have to write)

**Comment by msevestre** [comment]
here is the method that @abdullahhamadeh wrote for the Reporting Engine
I renamed it to `exploreSimulation`. The gist is to explore the simulation and create a tree like structure that can be navigated by the user using intellisense

![image](https://user-images.githubusercontent.com/1041237/75559156-f84d1800-5a10-11ea-92ae-329fed5b851c.png)


![image](https://user-images.githubusercontent.com/1041237/75559179-00a55300-5a11-11ea-80a6-299854ed5eb8.png)

![image](https://user-images.githubusercontent.com/1041237/75559218-11ee5f80-5a11-11ea-8113-1a5d24e770b3.png)


As you can see, there is full auto complete at any step of the way.
To get the path as string, you can do

`path<- tree$Organism$Kidney$Interstitial$pH$path `

e.g. adding $path at the end to retrieve the path. This is a fantastic way to traverse the structure

The only drawback at the moment: It takes quite some time to create the tree structure (for a fairly big simulation almost 60sec). But this only needs to be done once (or it can even be saved as rdata and loaded)

**Comment by msevestre** [comment]
IF this approach is of interested, we could try to see if we can speed up the implementation a bit
/cc @abdullahhamadeh

**Comment by PavelBal** [comment]
@msevestre This looks great!! Want-want-want :D

**Comment by msevestre** [comment]
PR was submitted #318 
I managed to reduce time to load to 4s for a big simulation

**Comment by msevestre** [comment]
The method is now called `getSimulationTree`
Very efficient and user friendly way to navigate in the simulation structure removing all changes of a typo. Maybe a UI is not required after all
