### ISSUE TITLE
HistogramPlotConfiguration and Population class don't fit together

### ISSUE THREAD

**Issue by ThomasGaub** [Open-Systems-Pharmacology/OSPSuite-R#310]
Histogramplots are mainly used to show distribution of population parameters. Unfortunatly the ospsuite toolbox population object has to be manually transformed into a dataframe useable in HistogramPlotConfiguration and plotHistogram.
It would be helpfull if the population object exposes a dataframe useable by HistogramPlotConfiguration and plotHistogram 
or
 HistogramPlotConfiguration and plotHistogram should use the population object

**Comment by ThomasGaub** [comment]
also helpfull for Bos-Whisker plots if population is easier to access

**Comment by msevestre** [comment]
@ThomasGaub Is this enough to have a data frame with one column per parameter?

**Comment by ThomasGaub** [comment]
Exactly what was needed thanks
