### ISSUE TITLE
Can't get parameters for individualId = 0

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite-R#312]
pop$getParameterValuesForIndividual(individualId = 0) gives an error

**Comment by msevestre** [comment]
What's the error?

**Comment by abdullahhamadeh** [comment]
![Screenshot 2020-02-26 14 23 47](https://user-images.githubusercontent.com/18409098/75379823-03cf0080-58a4-11ea-8047-2bf335a9db6d.png)

**Comment by abdullahhamadeh** [comment]
![Screenshot 2020-02-26 14 30 29](https://user-images.githubusercontent.com/18409098/75380270-b737f500-58a4-11ea-9200-bb6428f09f1c.png)

Individual 0 exists

**Comment by msevestre** [comment]
I can reproduce. Will fix it nw
