### ISSUE TITLE
setParameterValues vs setSimulationParameterValues

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#315]
I have no idea whats the difference? The one receives parameter objects, the other paths? Why then not call the second one `setParameterValuesByPath`?

And I actually though there was a reason we agreed to only accept parameter objects and not paths.

**Comment by msevestre** [comment]
it is called setSimulationPArameterValues because a simulation is required as object. It is imporant to have a simulation because you need a top container

This is very useful in conjunctiuon with createIndividual as you do not have to create instances of parmaeters yourself. CreateIndividual gives you paths and values and you can use them strainght away to update your simulation

**Comment by PavelBal** [comment]
Hm, ok, in my opinion the naming is very confusing... `setParameterValuesByPath` would make it more clear.

For createIndividual, I just use 

```
setParameterValues(parameters = getAllParametersMatching(paths = individual$distributedParameters$paths, container = simulation),
                       values = individual$distributedParameters$values)
```

so `setSimulationParameterValues ` is somehow redundand, but ok.

**Comment by msevestre** [comment]
>setParameterValues(parameters = getAllParametersMatching(paths = individual$distributedParameters$paths, container = simulation),
                       values = individual$distributedParameters$values)

The order is not guaranteed here. In theorie, getAllParametersMatching could return another order than the values. The other one guarantee the order

We can definitely rename the other method if you have a better name. However this only works for a simuation

**Comment by PavelBal** [comment]
As mentioned, my preference is `setParameterValuesByPath`. What do @Yuri05 @StephanSchaller think?

**Comment by StephanSchaller** [comment]
@PavelBal , maybe you can give me a short update / intro on the Package on Monday and I can then comment ;-)

**Comment by msevestre** [comment]
I am okay with Pavel suggestions. We get more precise with the path but
lose the fact that it's for simulation.

This should be the method used to set value from path. What you are doing
Pavel may lead to arrays that are not sorted as you expect (at least
theoretically)

**Comment by PavelBal** [comment]
@msevestre Don't you think it belongs to `utilities-parameters`? I wouldn't look for it in `utilities-simulaiton`...

**Comment by msevestre** [comment]
Fair enough. I just renamed the methods.
