### ISSUE TITLE
Formula of the parameter "Solubility table" - what is it?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#322]
Just a default PBPK-model exported from PK-Sim:

```
> param
Parameter: 
  Path: Organism|Lumen|Stomach|DefaultCompound|Solubility table
  Value: 0.00 [kg/l]
  Value overrides formula: FALSE
> param$formula$isConstant
[1] FALSE
> param$formula$isDistributed
[1] FALSE
> param$formula$isExplicit
[1] FALSE
> param$formula$isTable
[1] FALSE
```

If everything is FALSE - what kind of formula is it?

**Comment by msevestre** [comment]
good question

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/76903832-19b55d00-6875-11ea-948e-0215f6280195.png)

**Comment by msevestre** [comment]
That's one of this Table as a function of ph

**Comment by msevestre** [comment]
so the type is `TableFormulaWithXArgument`

**Comment by msevestre** [comment]
Formula: 
  isTableWithXArgument: TRUE
> print(param)
Parameter: 
  Path: Organism|Lumen|Stomach|C1|Solubility table
  Value: 0.00 [kg/l]
  isTableWithXArgument: TRUE
  Value overrides formula: FALSE
