### ISSUE TITLE
add Linux (Ubuntu) build

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#325]

**Comment by msevestre** [comment]
What is this?

**Comment by Yuri05** [comment]
at the moment only Windows packages are created. 
Ubuntu package should be created as well.

**Comment by msevestre** [comment]
Yeah but that's what Dominik was supposed to do right?

**Comment by Yuri05** [comment]
That was the "universal" setup from source (where all the C++ libs are compiled on the target system during installation etc.).
As long as we don't have this: we could at least provide the _binary_ Ubuntu package

**Comment by msevestre** [comment]
What was the command to create a xtar from a folder again?

**Comment by Yuri05** [comment]
`tar czf xyz.tar.gz myFolder`

**Comment by msevestre** [comment]
@Yuri05 It does not quite work for me with this command. It creates a tar ball that has a full folder structure 

Here is what I call
```
tar czf C:/tests/build/temp/ospsuite_9.0.46.tar.gz C:/tests/build/temp/ospsuite
```

and the tar file has test/build/temp/ospsuite etc... in it. Can I have it just start at ospsuite?

**Comment by msevestre** [comment]
ok found it i think
```
tar czf C:/tests/build/temp/ospsuite_9.0.46.tar.gz -C C:/tests/build/temp ospsuite
```

**Comment by msevestre** [comment]
fixed
