### ISSUE TITLE
Error propagation in the "population" mode

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#326]
If some (or even all) simulations of a population calculation crash: no error is thrown.
[testdata3.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/4291947/testdata3.zip)
Example: simulation attached will crash for all individuals due to bad solver settings.
In individual mode: exception is thrown. But in population mode: no exception and returned results contain no individuals.

I see here 3 options:
a) the error is thrown as soon as one of the individuals in the pop cannot be simulated
b) no error is thrown; the **caller** must check that the number of individuals in the output table equals to the number of input individuals
c) if the error is thrown or not can be set via simulation options

Thoughts?

```
> sim <- loadSimulation("C:/testdata/S2.pkml")
> population <- loadPopulation("C:/testdata/humans-Population.csv")
> individualResults <- runSimulation(sim)
Error in rClr::clrCall(simulationRunner, "Run", simulation$ref, options$ref) : 
  Type:    OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Error solving ODE at time t=3: The solver took 4 internal steps but could not reach output time (TOO_MUCH_WORK)
Method:  Void RunSimulation()
Stack trace:
   bei OSPSuite.SimModel.Simulation.RunSimulation()
   bei OSPSuite.Core.Domain.Services.SimModelManager.simulate()
   bei OSPSuite.Core.Domain.Services.SimModelManager.doIfNotCanceled(Action actionToExecute)
   bei OSPSuite.Core.Domain.Services.SimModelManager.RunSimulation(IModelCoreSimulation simulation, SimulationRunOptions simulationRunOptions)
   bei OSPSuite.R.Services.SimulationRunner.<>c__DisplayClass15_0.<RunAsync>b__0()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()

> populationResults <- runSimulation(sim, population)
> populationResults
SimulationResults: 
  Number of individuals: 0

```

**Comment by Yuri05** [comment]
@msevestre @PavelBal @abdullahhamadeh @pchelle @sfrechen

**Comment by PavelBal** [comment]
My favorite is option a). If something cannot be simulated, there is some problem that the used has to solve.

**Comment by msevestre** [comment]
I am not sure  that I like any of the options

In PKsim we support the fact that a few individuals may not run.  e.g. you run a pop run for 1000 individuals and one does not work, why would we throw an error?

**Comment by Incei** [comment]
Hi, I sort of agree with Michael, but there should still be some kind of warning right? What about:

- For the pop-sims, if an individual sim crashes, which we support, why not throw a 'live' warning that this invididual-id could not be run as info, but still continue the rest of the individuals. 

(If ALL the simulations crash, the user will find out anyways due to the large amount of warnings popping up, and will check..)
