### ISSUE TITLE
population run crashes under Linux

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#328]
using the example from #324.
Running an individual simulation works, but running it with the pop crashes:

```
> sim <- loadSimulation("/mnt/c/testdata/S1.pkml")
> population <- loadPopulation("/mnt/c/testdata/humans-Population.csv")
> individualResults <- runSimulation(sim)
> individualResults
SimulationResults:
  Number of individuals: 1
> populationResults <- runSimulation(sim, population)

=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================
/proc/self/maps:
```

**Comment by msevestre** [comment]
Is this also because you didn't set the path or is it something else? I am confused

**Comment by Yuri05** [comment]
No, it's because current ospsuite packages crashes under Linux for pop calculations.

Just tried the following: 
* overridden SimModel/FuncParser/Solver in the installed R package with the versions corresponding to ospsuite_9.0.18 (last version I tried under Linux, which worked): still crash
* after that overridden all other OSPSuite dlls in the installed R package with their versions from 9.0.18 (all the higghlighted dlls below): it worked. 
![grafik](https://user-images.githubusercontent.com/25061876/75981292-82e7b880-5ee4-11ea-9f59-cd278b767af9.png)

**Comment by Yuri05** [comment]
ok, it was the step from ospsuite 9.0.37 to 9.0.38.
9.0.37 runs under Linux, 9.0.38 crashes.

9.0.38 was an upgrade of OSPSuiteCore libs from 9.0.79 to 9.0.81:
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/commit/ef5a9ed189cbbc87320006a4669871400030f355#diff-82908a57b027eeb2de617b0c5ccc3725
So something in the Core seems to make trouble

**Comment by Yuri05** [comment]
hmm, looking at the changes in OSPsuite.Core 9.0.80 and 9.0.81 - I see absolutely nothing which would result in such a crash.
@msevestre Any ideas?

**Comment by msevestre** [comment]
nope

![image](https://user-images.githubusercontent.com/1041237/75986117-78fd8f80-5ebb-11ea-8588-bf499eb6ec01.png)

CPP export was the big change??? issue with SimModel?

**Comment by Yuri05** [comment]
>CPP export was the big change 

No, very small change. And does not interfere at all with the pop calculation

**Comment by msevestre** [comment]
I have no idea

**Comment by Yuri05** [comment]
Ok, it's not deterministic. So I can also run pops with the latest ospsuite 9.0.46 or with 9.0.38, but in some cases it crashes. Seems to depend on the order of commands I enter in R.

In some cases it seems reproducible. E.g.: I forget to load the ospsuite library before the first call. Then I load it, repeat the calls and continue: run pop crashes

```
> sim <- loadSimulation("/mnt/c/testdata/S1.pkml")
Error in loadSimulation("/mnt/c/testdata/S1.pkml") :
  could not find function "loadSimulation"
> library("ospsuite")
> sim <- loadSimulation("/mnt/c/testdata/S1.pkml")
> population <- loadPopulation("/mnt/c/testdata/humans-Population.csv")
> populationResults <- runSimulation(sim, population)

=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
```

Another scenario (crashes sometimes): I forget to load a population before I run it:

```
> library("ospsuite")
> sim <- loadSimulation("/mnt/c/testdata/S1.pkml")
> populationResults <- runSimulation(sim, population)
Error in validateIsOfType(population, Population, nullAllowed = TRUE) :
  object 'population' not found
> populationResults
Error: object 'populationResults' not found
> population <- loadPopulation("/mnt/c/testdata/humans-Population.csv")
> populationResults <- runSimulation(sim, population)

=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
```
