### ISSUE TITLE
Reset formula for "isFixedValue == TRUE"?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#329]
Is there a way to reset the value of a parameter which has been overridden to its initial formula?

**Comment by msevestre** [comment]
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/R/quantity.R#L145

`reset` or `$isFixedValue <- FALSE`

**Comment by PavelBal** [comment]
Cool.
