### ISSUE TITLE
error loading ospsuite-R package

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/OSPSuite-R#331]
I get the following error when trying to load the package after install:

The DLL is in the library. I have installed the rClr and ospsuite-R packages as provided prom GitHub.
Not sure why it can't load the dll.
Also tried installing .net core runtime and visual studio.

```
> library(ospsuite)
Lade nötiges Paket: rClr
Loading the dynamic library for Microsoft .NET runtime...
Loaded Common Language Runtime version 4.0.30319.42000

Error: package or namespace load failed for ‘ospsuite’:
 .onLoad in loadNamespace() für 'ospsuite' fehlgeschlagen, Details:
  Aufruf: rClr::clrCallStatic("OSPSuite.R.Api", "InitializeOnce", apiConfig$ref)
  Fehler: Type:    System.DllNotFoundException
Message: Die DLL "OSPSuite.FuncParserNative.dll": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden.
Method:  IntPtr CreateParsedFunction()
Stack trace:
   bei OSPSuite.FuncParser.ParsedFunctionImports.CreateParsedFunction()
   bei OSPSuite.FuncParser.ParsedFunction..ctor()
   bei OSPSuite.Core.Services.ExplicitFormulaParser..ctor(IEnumerable`1 variableNames, IEnumerable`1 parameterNames)
   bei OSPSuite.Core.Domain.Formulas.FormulaWithFormulaString.<>c.<.cctor>b__15_0(IEnumerable`1 v, IEnumerable`1 p)
   bei OSPSuite.Core.Domain.Formulas.ExplicitFormula.createFormulaParser(IEnumerable`1 references)
   bei OSPSuite.Core.Domain.Formulas.ExplicitFormula.CalculateFor(IEnumerable`1 usedOb
In addition: Warning messages:
1: Paket ‘ospsuite’ wurde unter R Version 3.6.3 erstellt 
2: Paket ‘rClr’ wurde unter R Version 3.5.2 erstellt 
´´´

**Comment by msevestre** [comment]
You probably do not have the latest Vc++ redistributable installed 

Which version of the OSPSuite-R package did you install?

Can you see under the install dir for the package, then under inst/lib if the dll is present?
OSPSuite.FuncParserNative.dll

**Comment by msevestre** [comment]
Donwload here
https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by PavelBal** [comment]
> Can you see under the install dir for the package, then under inst/lib if the dll is present?
OSPSuite.FuncParserNative.dll

Yepp dlls are present. He installs the same package that works for me. I probably have all the resits, but am not sure which one is required.

**Comment by msevestre** [comment]
>Also tried installing .net core runtime and visual studio. 

Not required. you need to make sure you have the vc++ reuntime available as well as .net 4.7.2

**Comment by msevestre** [comment]
both dependencies will be installed with the setup BTW

**Comment by StephanSchaller** [comment]
DLL are present, and ospsuite-R Version is: ospsuite_0.1.0.zip

**Comment by StephanSchaller** [comment]
> both dependencies will be installed with the setup BTW

The OSPSuite Setup?
I also installed it (fresh machine).

**Comment by StephanSchaller** [comment]
> Donwload here
https://aka.ms/vs/16/release/vc_redist.x64.exe

Yes, works now! Thanks.
We should probably also list this as requirements for the package?

**Comment by PavelBal** [comment]
Great! I can update the readme of the repository tomorrow.

**Comment by msevestre** [comment]
>ospsuite_0.1.0.zip

This is absolutely wrong here. Where did you get that package from?

**Comment by msevestre** [comment]
the latest version is 9.0.46. to be downloaded here
https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-r/builds/31191104/artifacts

**Comment by msevestre** [comment]
Which setup did you install? V8 does not have the required stuff. You need v9
Please confirm

**Comment by StephanSchaller** [comment]
kk...I installed V8

**Comment by msevestre** [comment]
ok user issue
