### ISSUE TITLE
Read in values of table parameter

### ISSUE THREAD

**Issue by moPellowe** [Open-Systems-Pharmacology/OSPSuite-R#332]
I’m looking for a function that reads in the values of a table parameter. Perhaps a function called readPoints() that grabs the x and y values of the table and stores them in an array as shown below?

![Capture](https://user-images.githubusercontent.com/57540473/76444409-4ad7ee00-639a-11ea-81d8-be8a916a1118.PNG)

**Comment by PavelBal** [comment]
Try this:
`allPoints <- dissolution_data_formula$allPoints`

It returns a list of `ValuePoint`objects, each of which has the properties `$x` and `$y`.

**Comment by moPellowe** [comment]
How exactly do I retrieve the $x and $y properties? I tried the following:
```
> library(ospsuite)
> simFilePath <- file.path(getwd(), paste0("Simulation 1.pkml"), fsep = .Platform$file.sep)
> sim <- loadSimulation(simFilePath)
> parameter <- getParameter("Applications|Administration Protocol - Oral|Formulation - Table|Fraction (dose)", sim)
> formula <- parameter$formula
> allPoints <- formula$allPoints
> allPoints
[[1]]
  x= 0, y= 0, restartSolver= FALSE

[[2]]
  x= 60, y= 0.2, restartSolver= FALSE

[[3]]
  x= 180, y= 0.45, restartSolver= FALSE

[[4]]
  x= 420, y= 0.798, restartSolver= FALSE

[[5]]
  x= 900, y= 0.9954, restartSolver= FALSE

> point1 <- allPoints[1]
> point1
[[1]]
  x= 0, y= 0, restartSolver= FALSE

> point1$x
NULL
> 
```

**Comment by msevestre** [comment]
try allPoints[[1]] ?

**Comment by msevestre** [comment]
(simple index only works with standard type such as number, strings etc.. I believe)

**Comment by moPellowe** [comment]
That worked. Thanks!

**Comment by msevestre** [comment]
@PavelBal Let's add a section in the vignettes for this. I think this should be enough

**Comment by PavelBal** [comment]
@msevestre I think this can be closed now? We have a section about table formulas in the vignettes.
