### ISSUE TITLE
Need a resetParameterPaths for sensitivity analysis 

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite-R#342]
For sensitivityAnalysis <- SensitivityAnalysis$new(simulation = sim, variationRange = vRange)
we have a function sensitivityAnalysis$addParameterPaths(variableParameterPaths)

Need a function that removes all the added paths, eg sensitivityAnalysis$resetParameterPaths()

such that 

sensitivityAnalysis$parameterPaths() returns NULL

**Comment by msevestre** [comment]
Can't you just create a new instance of the object? 

It's doable or course but in the meantime

**Comment by abdullahhamadeh** [comment]
I want to avoid launching a new instance on the cores to speed up the parallel SA

Also, I noticed there is a addDynamicPKParameters() function for SA.  This is going to go?

**Comment by msevestre** [comment]
Yes this is going to to.
Creating an instance of an object is cheap. Don't worry about that

**Comment by msevestre** [comment]
I should say; it should have been gone already. Good catch

**Comment by abdullahhamadeh** [comment]
Is it costlier to instantiate a SA object for a large model (say a 20mb model like in example 03) that for a small one?

Currently, for each individual, I create an instance of the SA and the SA run options on each core.  If I eliminate those then each core shouldn't be doing much more than updating the simulation with the individual's parameter and then running a pure SA for the given variation parameters.

**Comment by msevestre** [comment]
Don't you have to create one instance of SA per node anyways? e.g. at some points you have to call 
```
results <- runSensitivityAnalysis(sensitivity, sensitivityAnalysisOptions)
```

and this needs to happen on each core. That means that you need an instance of sensitivity on each core. Or am I misunderstanding something


?is it costlier to instantiate a SA object for a large model (say a 20mb model like in example 03) that for a small one?

No exactly the same. There is absolutely nothing that happens until you call `runSensitivityAnalysis`
The SensitivityAnalysis used in R is a wrapper around this objec there

```

   public class SensitivityAnalysis
   {
      public ISimulation Simulation { get; }

      public int NumberOfSteps { get; set; } = Constants.DEFAULT_SENSITIVITY_NUMBER_OF_STEPS;

      public double VariationRange { get; set; } = Constants.DEFAULT_SENSITIVITY_VARIATION_RANGE;

      private readonly HashSet<string> _parameterPaths = new HashSet<string>();

      public SensitivityAnalysis(ISimulation simulation)
      {
         Simulation = simulation;
      }

      public void AddParameter(IParameter parameter) => AddParameterPath(parameter.ConsolidatedPath());

      public void AddParameters(IEnumerable<IParameter> parameters) => parameters.Each(AddParameter);

      public void AddParameterPath(string parameterPath) => _parameterPaths.Add(parameterPath);

      public void AddParameterPaths(IEnumerable<string> parameterPaths) => parameterPaths.Each(AddParameterPath);

      public string[] ParameterPaths => _parameterPaths.ToArray();
   }
```

There is absolutely nothing going on

What can be costlier is to retrieve the list of allPotentialVeriablesParaemters in a simulation. **This should only be done once**
