### ISSUE TITLE
get isRHS Flag

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#355]
Code will
```
parameter$isRHS
```
Return TRUE OR FALSE if a parameter is RHS

```
parameter$isRHS <- value
```

if value = false. Will set RHS to NULL. This will be persistent IN THE SIMULATION until loaded again
if value = TRUE and the flag is FALSE => will return an error

@PavelBal Thoughts?

**Comment by msevestre** [comment]
Relates to #306

**Comment by PavelBal** [comment]
Cool!
