### ISSUE TITLE
Different behavior of MoBi and R when an observer evalutates to NaN with the initial conditions

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#357]
I have an observer for "Gastric retention" of the drug, defined as `M / Total_oral_drug_mass`. As `Total_oral_drug_mass` is 0 at the beginning of the simulation, the value of the observer as NaN. After oral administration (at time = 0), the value of `Total_oral_drug_mass` becomes positive and the observer can be evaluated, which happens in MoBi.

However, in R the value of the observer stays `NaN`. Here is an example of running the simulation directrly exported from MoBi (where the observer works):

```
simulation <- loadSimulation(simPath)
addOutputs("Dapagliflozin|Total oral drug mass", simulation)
addOutputs("Organism|Lumen|Stomach|Dapagliflozin|Gastric retention", simulation)
simulationResults <- runSimulation(simulation = simulation)
getOutputValues(simulationResults,
                quantitiesOrPaths = "Organism|Lumen|Stomach|Dapagliflozin|Gastric retention"
)
Error in simulationResults$getValuesByPath(path, individualIds, stopIfNotFound) : 
  getOutputValues: No results exists for path 'Organism|Lumen|Stomach|Dapagliflozin|Gastric retention' for individual IDs '0'!
```

Setting the value of `Total_oral_drug_mass` to any positive number before running the simulation allows the evaluation of the observer:

```
setParameterValuesByPath( parameterPaths = "Dapagliflozin|Total oral drug mass", values = 1,simulation = simulation)
simulationResults <- runSimulation(simulation = simulation)
getOutputValues(simulationResults,
                quantitiesOrPaths = "Organism|Lumen|Stomach|Dapagliflozin|Gastric retention"
)
$data
    IndividualId Time Organism|Lumen|Stomach|Dapagliflozin|Gastric retention
1              0    0                                           0.0000000000
2              0    1                                           0.9355877042
3              0    2                                           0.8789033294
...
```

**Comment by PavelBal** [comment]
I just tried to construct a simle example with only one parameter and event, but it does not work. I could send you the simulation I am using.

**Comment by msevestre** [comment]
What version of MoBi are you using? v8 or v9?
I see absolutely no reason for a difference here from the code point of view. R does not process anything rather moves everything to core.

>I just tried to construct a simle example with only one parameter and event, but it does not work

Meaning you cannot reproduce the issue?

**Comment by msevestre** [comment]
@Yuri05 Any idea?

**Comment by Yuri05** [comment]
First of all I would define the observer as `Total_oral_drug_mass>0 ? M / Total_oral_drug_mass : 0` @PavelBal 
Apart from this: maybe rClr cannot handle NaNs?
@PavelBal If you define an observer in a dummy model e.g. like `Time = 0 ? 0/0 : 1` - does it work?

**Comment by msevestre** [comment]
>Apart from this: maybe rClr cannot handle NaNs?

NaN is not used anywhere in R. The simulation is just read and calculated
Or do you mean that the output value has a NaN in the first entry and therefore everything is NaN ?

@PavelBal First let me know v8 and v9. Then you can send me your sim..you know how :)

**Comment by Yuri05** [comment]
>Or do you mean that the output value has a NaN in the first entry and therefore everything is NaN ?

Yes. Maybe rClr .NET-Array_to_R-Array conversion has problems with NaN conversion and produces wrong numbers.

**Comment by PavelBal** [comment]
> Meaning you cannot reproduce the issue?

Unfortunately, yes, I cannot reproduce (with other models).

> First of all I would define the observer as

Yepp, did this after I ran into the problem.

> If you define an observer in a dummy model e.g. like Time = 0 ? 0/0 : 1 - does it work?

I tried a dummy model with observer defined as `1/A`, with `A` having the initial value 0 and being set to 2 by a event at `t = 0`. The first value of the observer in R was Inf, the others were 0.5.. So no idea.

> Or do you mean that the output value has a NaN in the first entry and therefore everything is NaN ?

The first simulated value of the dummy model is `Inf`.

> First let me know v8 and v9. Then you can send me your sim..you know how :)

Both 9.

**Comment by Yuri05** [comment]
>I tried a dummy model with observer defined as 1/A, with A having the initial value 0 and being set to 2 by a event at t = 0. The first value of the observer in R was Inf, the others were 0.5.. So no idea.

Can you try with 0/0 (to get NaN and not inf) instead?

**Comment by msevestre** [comment]
ok this is an error in R code indeed. We convert the code from NaN to NA and something is not quite right :)
