### ISSUE TITLE
9.0.62: Linux setup contains unnesessary files

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#363]
9.0.62 Setup for Linux (both Ubuntu and CentOS) suddenly includes PK-Sim setup (9.0.61 was OK)
![grafik](https://user-images.githubusercontent.com/25061876/79043227-5c611f80-7bfe-11ea-88ce-53e0e8ba41ea.png)

![grafik](https://user-images.githubusercontent.com/25061876/79043249-6d119580-7bfe-11ea-80ea-4130caa43877.png)

**Comment by msevestre** [comment]
Interesting. I am downloading pksim and install it to ensure that we can create vignettes

I guess the setup is attached somehow
