### ISSUE TITLE
how to install OSPsuite in R?

### ISSUE THREAD

**Issue by ckcho0625** [Open-Systems-Pharmacology/OSPSuite-R#365]
The release version of the package comes as a binary *.zip file together with the installation of the OSPS and can be found in the installation folder of the OSPS (default: `C:\Program Files\Open Systems Pharmacology\ospsuite_X.X.X.zip`). The package `rClr` can be downloaded from [here](https://github.com/Open-Systems-Pharmacology/rClr/releases) and installed from binary *.zip. 

I read installation manual, i tried to install rClr and R6. R6 was successfully installed in R-studio, but rClr was not installed until now. according to above explanation, we are able to find installation folder in C:\Program Files\Open Systems Pharmacology pathway, but i didn't find  ospsuite_X.X.X.zip file although i previously downloaded rClr zip uploaded in this site. So, how can i install rClr file? I want to simulate PBPK/PD combination model through R-studio program. 
Thank you for your appreciation.

**Comment by PavelBal** [comment]
The OSPSuite package will be released with Version 9. Until then, you have to

- Install rClr from RStudio (so just install it as a normal package, without unzipping).
- Download and install the ospsuite-package from [here](https://ci.appveyor.com/api/buildjobs/pa4oyhurwjaj0mpr/artifacts/ospsuite_9.0.63.zip).
