### ISSUE TITLE
Fields "dimension" and "unit" for "QuantityPKParameter"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#378]
`QuantityPKParameter` has only a value, but it is not clear in which unit the value is. Would be good to also have fields `dimension` and `unit`.

**Comment by PavelBal** [comment]
OK, `PKParameter` has it, but `QuantityPKParameter` not... Anyways it is confusing, why a `QuantityPKParameter` does not inherit `PKParameter`, or why are there two classes at all..

**Comment by msevestre** [comment]
Naming is not easy. But PKParameter is a definition of a PKPArameter (CMax, tMax etc..)

QuantityPKPArameter is an instance of a PKParameter VALUE for a given output.
For example CMax for venous blood plasma

**Comment by PavelBal** [comment]
`PKParameterDefinition` and `PKParameterValue`? :D

Anyway, dimension and unit for `QuantityPKParameter` would be great.

**Comment by msevestre** [comment]
issue is that then the names are not the same as in OSPSuite.core. 

@Yuri05 Happy to rename if you think this is better. Now is the time

**Comment by Yuri05** [comment]
Would NOT rename.

**Comment by msevestre** [comment]
Adding dimension and unit would require changes in CORE. I think this is a good idea but not possible for now

What you can do if you want to 
```
t_max <- pkParameterByName("t_max")
t_max$displayUnit
t_mas$dimension
```

**Comment by PavelBal** [comment]
Maybe as a workaround implement exactly this for now? As active fields of the class `QuantityPKParameter`.

**Comment by msevestre** [comment]
the display unit is what will be used when exporting to csv. The unit should be however the core unit. It's not something we have now

Why do you need this BTW?

**Comment by PavelBal** [comment]
I personally don't need it, but writing the vignettes I realized that is ambiguous. For example, when the user retrieves the C_max and calls its value:

```
> c_max$name
[1] "C_max"
> c_max$quantityPath
[1] "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
> c_max$values
[1] 50.25272
```

No idea what these 50 are. Without knowing the unit, this information is of very limited use for the user.

**Comment by msevestre** [comment]
Fair enough. Let's see if we can at least get the baseunit in. This is what matters the most at that stage (e.g. knowing that it is in umol/l)
