### ISSUE TITLE
Export pk-analysis.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#379]
Would it not make more sense to export (and also load from) PK-analysis in the same format as PK-Sim does?

**Comment by msevestre** [comment]
It is the same format. PKSim and r are rising the same code that is now in core

Can you explain?

**Comment by PavelBal** [comment]
Exporting PK-Analyses from PK-Sim as described here https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-simulations#pk-analysis-view

produces a completely different output than calling `exportPKAnalysesToCSV` from R.

**Comment by PavelBal** [comment]
Also I do not understand why is it necessary to have the simulation object to load the analysis from csv.

**Comment by msevestre** [comment]
but it's export to Excel here in PKSIm that you are referring too

**Comment by PavelBal** [comment]
Yes, export of PK-Analysis in general... In PK-Sim it is excel, in R it is csv, and the contenst also differ. I would expect that I can load the analysis in R after in has been exported from PK-Sim.

**Comment by msevestre** [comment]
this is not the same use case.  WE also support pk analysis as csv in PKSim (import for sure, export maybe). This is the context in which this is used

**Comment by msevestre** [comment]
The simulation is required so that we can retrieve the molweight and correct the right dimension when importing a pkParameter. Otherwise, no way to convert from umol to mg etc..

**Comment by msevestre** [comment]
FYI
![image](https://user-images.githubusercontent.com/1041237/82332610-9d91df80-99b3-11ea-8bf2-b300140f646a.png)

**Comment by PavelBal** [comment]
> this is not the same use case. 

Obviously, I do not understand the use case :D As a modeller, I would expect the features in PK-Sim and R being identical.

> WE also support pk analysis as csv in PKSim (import for sure, export maybe).

There is an option to import pk analysis in PK-Sim?

**Comment by msevestre** [comment]
Simulation REsults and PK Analysis are what we create from R. That way you can import export no problem

**Comment by msevestre** [comment]
> I would expect the features in PK-Sim and R being identical.

In this case, they truly are. WE are using the same code. 
Export to XLS is something different that is not supported in R. If we support it, then it will be the same as PKSim

**Comment by PavelBal** [comment]
OK this is new for version 9, right? I don't think I ever saw ver.9 of PK-Sim... I must admit I have no idea what this can be used for (importing pk-analysis to PK-Sim, what would one do with it?), therefore will only mention the option of export/import in the vignette..

**Comment by msevestre** [comment]
>OK this is new for version 9, right? 

No this has been here forever. Only for pop simulation

**Comment by msevestre** [comment]
And this is here so that you can load PK Analysis calculated for example in R, Matlab or using your own PK Parameter that PKSim does not support
Once loaded, you have access to it in all the pop plots. Pretty neafty

**Comment by PavelBal** [comment]
> Only for pop simulation

OK, I see...
