### ISSUE TITLE
Wrong dimension of user defined PK parameter

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#380]
Defined PK parameter as 
`F_tend <- ospsuite::addUserDefinedPKParameter("F_tend", standardPKParameter = StandardPKParameter$C_trough, displayUnit = "%")`

Expectation is: parameter dimension is recognized as `Fraction`. But:
```
> F_tend$dimension
[1] "F_tend"
>
```

**Comment by msevestre** [comment]
I can reproduce
