### ISSUE TITLE
Documentation of "SensitivityAnalysis" mentiones "ospsuiteEnv", which is not exported.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#386]
The documentation of the constructor of `SensitivityAnalysis` mentions `ospsuiteEnv`:

```
...
    #' @param numberOfSteps Number of steps used for the variation of each parameter (optional, default specified in \code{ospsuiteEnv$sensitivityAnalysisConfig})
    #' @param variationRange Variation applied to the parameter (optional, default specified in \code{ospsuiteEnv$sensitivityAnalysisConfig})
...
```

I don't think it is a good idea, as the documentation is visible to the user, but `ospsuiteEnv` is not exported.

**Comment by msevestre** [comment]
sure. Can you change it as part of your documentation update? I think we are using ospsuiteEnv in the doc a few times.

**Comment by msevestre** [comment]
also in
SimulationRunOptions
SensitivityAnalysisRunOptions
SensitivityAnalysis



or should we expose this env? if yes how do we do this?

**Comment by PavelBal** [comment]
Looking at the contents of the env I would not expose the whole env. Actually, Only parameters of the senstivity analysis may be of interest to expose. Maybe write a method that would return the value of a property of the env? Could be useful also e.g. to see which `packageVersion` is defined, but the user will not be able to change anything. E.g.

```
getOSPSuiteSetting <- function(settingName){
return (ospsuiteEnv[[settingName]]
}
```

(well and add a check for key not in the env...)

**Comment by msevestre** [comment]
> Actually, Only parameters of the senstivity analysis may be of interest to expose.

I somewhat disagree with this. These entries are all user-defined parameters

# Default values for the formatNumerics() helper function
ospsuiteEnv$formatNumericsDigits <- 5
ospsuiteEnv$formatNumericsSmall <- 2

# Number of cores to use for simualtions and sensitivity. Default to number of cores on the machine - 1
ospsuiteEnv$numberOfCores <- parallel::detectCores() - 1

# Specificies the default behavior fo progress visualization. By default FALSE
ospsuiteEnv$showProgress <- FALSE

# Default number of steps a new SA instance
ospsuiteEnv$sensitivityAnalysisConfig$numberOfSteps <- 2

# Default variation range for a new SA instance
ospsuiteEnv$sensitivityAnalysisConfig$variationRange <- 0.1

# Represents the threshold of sensitivity that we want to achieve.
# A value of 0.9 will select all parameters contributing to 90% total sensitivity
ospsuiteEnv$sensitivityAnalysisConfig$totalSensitivityThreshold <- 0.9

**Comment by PavelBal** [comment]
My preference is still to expose them in terms of reading them out, but not changing them. E.g. it is usefull to read out the OSPSVersion, but should not be editable.

**Comment by msevestre** [comment]
Well default threshold, number of digits etc should absolutely be changeable by the user no? Why do we have this default otherwise?

**Comment by PavelBal** [comment]
I would say, default is so the user does not have to specify these values for most of the time. If he wants other "default", he can create a variable for it and pass it every time the method is called.

So far, I never had the change the defaults from ospsEnv, or had a wish to do so. But sure, we can also make defaults editable. But in this case we would probably need two envs - one for the the defaults the user can specify (and which is exposed), and one hidden (`$packageName`, `$packageVersion`, `$containerTask` and so on).
