### ISSUE TITLE
SensitivityAnalysis: calling `addParameterPaths` on a SA with no defined paths

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#388]
If a SA-object has been created without specifying any parameters, all constant parameters are tested.

When calling `addParameterPaths` on such a SA, **only** the added parameters will be tested. If this the intended behavior?

If yes, a note to documentation should be added, because intuitively I would expect that the added parameters will be tested in addition to all constant.s

**Comment by msevestre** [comment]
@PavelBal Yes this is the intended behavior. Either you let the system do its magic. Or you add the parameter you want to vary

**Comment by msevestre** [comment]
@PavelBal Please be my guest re update docs since you are already updating usage of vector vs list

**Comment by PavelBal** [comment]
Will be documented with the next PR.
