### ISSUE TITLE
allPKParameterSensitivitiesFor not giving all sensitivities when totalSensitivityThreshold= 1

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite-R#391]
Example:
[import_SA_res.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/4675224/import_SA_res.zip)

Interested in pk parameter `t_max` and output path  `Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)`

For individual 3, `allPKParameterSensitivitiesFor `returns results for all the parameters:
```
Organism-Lung-Volume
Organism-Heart-Volume
Organism-Kidney-Volume
Organism-Muscle-Volume
Organism-Liver-Volume
```

Whereas for individual 4 `allPKParameterSensitivitiesFor `returns results for only:
```
Organism-Liver-Volume
Organism-Muscle-Volume
```

I thought perhaps the default behavior was that any parameters to which sensitivity is zero are not printed, but here `allPKParameterSensitivitiesFor` returns some parameters with 0 sensitivity for individual 3 but not for individual 4:

```
[1] "Individual 3:"
[[1]]
PKParameterSensitivity: 
  Parameter path: Organism-Lung-Volume
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 0

[[2]]
PKParameterSensitivity: 
  Parameter path: Organism-Heart-Volume
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 0

[[3]]
PKParameterSensitivity: 
  Parameter path: Organism-Kidney-Volume
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 0

[[4]]
PKParameterSensitivity: 
  Parameter path: Organism-Muscle-Volume
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 0

[[5]]
PKParameterSensitivity: 
  Parameter path: Organism-Liver-Volume
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 0

[1] "Individual 4:"
[[1]]
PKParameterSensitivity: 
  Parameter path: Organism-Liver-Volume
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: -0.441176470588235

[[2]]
PKParameterSensitivity: 
  Parameter path: Organism-Muscle-Volume
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 0.161764705882353
```

**Comment by msevestre** [comment]
@abdullahhamadeh There is no concept of individual in the sensitivity of OSPSuite-R so this is something that **has** to come from the way the Sensititvy is configured/started etc..

I am suspecting that the simulations, with the specific individual parameters, may have different values (maybe some parameters are 0 for id4 and not for Ind3)

Can you please do the following:
1/ Load the ind3 into your simulation. Save Simulation to pkml file
2/ Load the ind4 into your simulation. Save simulation to another pkml file

Attach the two pkml simulations here.

**Comment by abdullahhamadeh** [comment]
> Attach the two pkml simulations here.

[inds34pkml.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/4677978/inds34pkml.zip)

**Comment by msevestre** [comment]
@abdullahhamadeh Can I ask why your expectation is that the sensitivity outcome for different simulations would have the exact same numbers of parameters? 

I don't see why this have to be like this since you are starting with a different set of parameters. Maybe in case of ind4, Organism-Lung-Volume. Organism-Heart-Volume. Organism-Kidney-Volume are not sensitive enough?

**Comment by abdullahhamadeh** [comment]
It was my understanding that setting totalSensitivityThreshold = 1 would return all sensitivity results (even if sensitivity is zero), and wrote the sensitivity plot functions accordingly.  Is it not the case?

**Comment by msevestre** [comment]
This is the case.
Also running the sensitivity in MoBi (and most certainly in R) returns much more parameters
![image](https://user-images.githubusercontent.com/1041237/82832470-2f548d80-9e89-11ea-857a-489fdd10c8be.png)

I am a bit lost here as to what is being called and how. 

Can you export the sensitivity as csv for the two simulations?

**Comment by msevestre** [comment]
Just ran the code for Ind4
```
library(ospsuite)

sim <- loadSimulation("C:/tests/9.0/ospsuite-r/ind4.pkml", loadFromCache = FALSE)

sensitivity <- SensitivityAnalysis$new(sim)

print(sensitivity)

sensitivityAnalysisOptions <- SensitivityAnalysisRunOptions$new(showProgress = TRUE)

results <- runSensitivityAnalysis(sensitivity, sensitivityAnalysisOptions)

exportSensitivityAnalysisResultsToCSV(results, "C:/tests/9.0/ospsuite-r/sa.csv")

pkSensitivities <- results$allPKParameterSensitivitiesFor(pkParameterName = "t_max", outputPath = "Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)")
for (pkSensitivity in pkSensitivities) {
    print(pkSensitivity)
}

length(pkSensitivities)

```
I am getting exactly the same order as MoBi and the same values

**Comment by msevestre** [comment]
>It was my understanding that setting totalSensitivityThreshold = 1 would return all sensitivity results 

Coming back to this. I don't think this is the case. It will stop once sensitivity = 1


In your case, something is wrong with Ind3 since ALL values that you are showing are 0

**Comment by msevestre** [comment]
I am running the simulation for Ind3 now

**Comment by msevestre** [comment]
This is what I get for Ind3
```
PKParameterSensitivity: 
  Parameter path: Organism-pH (blood cells)
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: -4.58333333333333
PKParameterSensitivity: 
  Parameter path: Organism-pH (intracellular)
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 4.47916666666666
PKParameterSensitivity: 
  Parameter path: Rifampicin-Lipophilicity
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 2.5625
PKParameterSensitivity: 
  Parameter path: Rifampicin-Reference pH
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 0.833333333333333
PKParameterSensitivity: 
  Parameter path: Rifampicin-pKa value 0
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: -0.666666666666666
PKParameterSensitivity: 
  Parameter path: Organism-Lumen-Effective surface area variability factor
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: -0.666666666666666
PKParameterSensitivity: 
  Parameter path: Organism-Lumen-UpperJejunum-Effective surface area enhancement factor
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: -0.666666666666666
PKParameterSensitivity: 
  Parameter path: Rifampicin-Specific intestinal permeability (transcellular)
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: -0.666666666666666
PKParameterSensitivity: 
  Parameter path: Organism-SmallIntestine-Volume
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 0.625
```
So none of the parameter listed above are part of the SA. That's why you get 0 if you call them


Are you now saying that `allPKParameterSensitivitiesFor` returns those parameters with 0? I don't see how it's possible


Now if you look at the csv, we see


QuantityPath | Parameter | PKParameter | Value
-- | -- | -- | --
Organism\|PeripheralVenousBlood\|Rifampicin\|Plasma   (Peripheral Venous Blood) | Organism-Heart-Volume | t_max | 0

so loading the parameter from CSV and assuming that the order of SA parameters will be the same on each individual is probably the mistake here. There is absolutely no reason for me to expect that each individual simulation is sensitive to the same set of parameters

**Comment by msevestre** [comment]
Lastly this is the code that calculates the allPKParameterSensitivitiesFOr

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.Core/Domain/SensitivityAnalyses/SensitivityAnalysisRunResult.cs#L43

So not ALL parameters will be returned from this code. I think this is ok

**Comment by msevestre** [comment]
@Yuri05 @abdullahhamadeh In conclusion, I don't think that there is a bug UNLESS `allPKParameterSensitivitiesFor` using Ind3 returns a bunch of 0. But again, I can't reproduce neither in MoBi nor in R

**Comment by abdullahhamadeh** [comment]
> Are you now saying that `allPKParameterSensitivitiesFor` returns those parameters with 0? I don't see how it's possible
 
I think if may be because I explicitly set `parameterPaths = c("Organism|Lung|Volume", "Organism|Heart|Volume", "Organism|Kidney|Volume",  "Organism|Muscle|Volume",  "Organism|Liver|Volume") `?

I ran the following code:

```


pop <- ospsuite::loadPopulation(csvPopulationFile = popFileCsv)
ind3pars <- pop$getParameterValuesForIndividual(3)
ind4pars <- pop$getParameterValuesForIndividual(4)


ospsuite::setParameterValuesByPath(parameterPaths = ind3pars$paths,values = ind3pars$values,simulation = sim)
ospsuite::saveSimulation(simulation = sim,filePath = "./ind3.pkml")
newsa3 <- ospsuite::SensitivityAnalysis$new(simulation = sim,parameterPaths = c("Organism|Lung|Volume", "Organism|Heart|Volume", "Organism|Kidney|Volume",  "Organism|Muscle|Volume",  "Organism|Liver|Volume") )
saro <- ospsuite::SensitivityAnalysisRunOptions$new(showProgress = TRUE)
newsares3 <- ospsuite::runSensitivityAnalysis(sensitivityAnalysis = newsa3,sensitivityAnalysisRunOptions = saro)
newresInd3 <- newsares3$allPKParameterSensitivitiesFor(pkParameterName = "t_max",outputPath = outPlasmaPath,totalSensitivityThreshold = 1)
print("new Individual 3:")
print(newresInd3)




ospsuite::setParameterValuesByPath(parameterPaths = ind4pars$paths,values = ind4pars$values,simulation = sim)
ospsuite::saveSimulation(simulation = sim,filePath = "./ind4.pkml")
newsa4 <- ospsuite::SensitivityAnalysis$new(simulation = sim,parameterPaths = c("Organism|Lung|Volume", "Organism|Heart|Volume", "Organism|Kidney|Volume",  "Organism|Muscle|Volume",  "Organism|Liver|Volume") )
saro <- ospsuite::SensitivityAnalysisRunOptions$new(showProgress = TRUE)
newsares4 <- ospsuite::runSensitivityAnalysis(sensitivityAnalysis = newsa3,sensitivityAnalysisRunOptions = saro)
newresInd4 <- newsares4$allPKParameterSensitivitiesFor(pkParameterName = "t_max",outputPath = outPlasmaPath,totalSensitivityThreshold = 1)
print("new Individual 4:")
print(newresInd4)
```


and the result was:

```
0..0..4..14..19..23..28..33..38..42..47..52..57..61..66..71..76..80..85..90..95
[1] "new Individual 3:"
[[1]]
PKParameterSensitivity: 
  Parameter path: Organism-Lung-Volume
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 0

[[2]]
PKParameterSensitivity: 
  Parameter path: Organism-Heart-Volume
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 0

[[3]]
PKParameterSensitivity: 
  Parameter path: Organism-Kidney-Volume
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 0

[[4]]
PKParameterSensitivity: 
  Parameter path: Organism-Muscle-Volume
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 0

[[5]]
PKParameterSensitivity: 
  Parameter path: Organism-Liver-Volume
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 0

0..4..9..14..19..23..28..33..38..42..47..52..57..61..66..71..76..80..85..90..95
[1] "new Individual 4:"
[[1]]
PKParameterSensitivity: 
  Parameter path: Organism-Liver-Volume
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: -0.441176470588235

[[2]]
PKParameterSensitivity: 
  Parameter path: Organism-Muscle-Volume
  PK-Parameter: t_max
  Output path: Organism|PeripheralVenousBlood|Rifampicin|Plasma (Peripheral Venous Blood)
  Value: 0.161764705882353

```

**Comment by msevestre** [comment]
oh yeah this can definitely be it. in your case, ALL Selected parameters are not sensitive (is this really the case)? If you had at least one parameter with SA !=0, then the 0 parameters would not be visible. 


I don't think one should assume anywhere, that the order of parameters is the same between two simulations, NOR that the same amount of parameters (or the same set of parameters) will be returned

**Comment by abdullahhamadeh** [comment]
In any case, ospsuite has its rules for determining what sensitivities to return.  The bottom line is we need to decide, for reporting engine, do we follow the same rules or not?  

ie we have two choices:

1) If I specify a set of paths to perturb like in my example above, the sensitivity analysis result CSV will include all of those parameters unless they are zero in the simulation.  I can then apply my own threshold that picks the top x% most sensititve parameters _in the CSV_.  If I set x=100 then all the parameters will show up in the sensitivity plot.

2) If I use `allPKParameterSensitivitiesFor` then it may return only a subset of those parameters and only those will show up in the plot.

**Comment by msevestre** [comment]
This is not a discussion for the ospsuite-r repo then. Please copy your comment in an entry in the reporting engine and let @Yuri05 decide. 

My opinion would be that the two tools should behave the same but @Yuri05 might see it otherwise
