### ISSUE TITLE
Errors with rClr in R 3.6.3

### ISSUE THREAD

**Issue by mnneely** [Open-Systems-Pharmacology/OSPSuite-R#393]
Can't get the toolbox to work in R 3.6.3.

`R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

> library(ospsuite)   # PK-Sim R toolbox
Loading required package: rClr
Loading the dynamic library for Microsoft .NET runtime...
Loaded Common Language Runtime version 4.0.30319.42000
 
> initPKSim("C:/Program Files/Open Systems Pharmacology/PK-Sim_portable/PK-Sim 9.0.157")
Error in rClr::clrLoadAssembly(pksimR) :
  Failure in rclr_ms_call_static_method, but could not retrieve an error message`

More output...

`> library("ospsuite")
> pksimFolderPath <- "C:/Program Files/Open Systems Pharmacology/PK-Sim_portable/PK-Sim 9.0.157"
> pksimR <- file.path(pksimFolderPath, "PKSim.R.dll")
> file.exists(pksimR)
[1] TRUE
> rClr::clrLoadAssembly(pksimR)
Error in rClr::clrLoadAssembly(pksimR) :
  Failure in rclr_ms_call_static_method, but could not retrieve an error message
> rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce")
Type not found: PKSim.R.Api
Error in rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce") :
  Type:    System.ArgumentException
Message: Type not found: PKSim.R.Api
Method:  System.Object CallStaticMethod(System.String, System.String, System.Object[])
Stack trace:
   at Rclr.ClrFacade.CallStaticMethod(String typename, String methodName, Object[] arguments)
 `

**Comment by msevestre** [comment]
@mnneely can you try the same code (loading PKSim directly) without loading ospsuite-r first?

* Make sure you close r studio and reopen again
* Do not load ospsuite-r
* Load PKSim via rclr directly as in the code pasted above

Let us know the output

If this does not work
Remove ospsuite-r package completely

Try the same procedure
Report here

**Comment by mnneely** [comment]
I closed Rstudio, reopened, and did not load opsuite-R.  Same output.

`> pksimFolderPath <- "C:/Program Files/Open Systems Pharmacology/PK-Sim_portable/PK-Sim 9.0.157"`
`> pksimR <- file.path(pksimFolderPath, "PKSim.R.dll")`
`> file.exists(pksimR)`
`[1] TRUE`
`> rClr::clrLoadAssembly(pksimR)`
`Error in rClr::clrLoadAssembly(pksimR) : 
  Failure in rclr_ms_call_static_method, but could not retrieve an error message`
`> rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce")`
`Type not found: PKSim.R.Api
Error in rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce") : 
  Type:    System.ArgumentException
Message: Type not found: PKSim.R.Api
Method:  System.Object CallStaticMethod(System.String, System.String, System.Object[])
Stack trace:
   at Rclr.ClrFacade.CallStaticMethod(String typename, String methodName, Object[] arguments)
`

**Comment by mnneely** [comment]
Removing opsuite entirely also did not change output.

`> library(opsuite)`
`Error in library(opsuite) : there is no package called ‘opsuite’`

Above was to verify that I removed opsuite.

`> pksimFolderPath <- "C:/Program Files/Open Systems Pharmacology/PK-Sim_portable/PK-Sim 9.0.157"`
`> pksimR <- file.path(pksimFolderPath, "PKSim.R.dll")`
`> file.exists(pksimR)`
`[1] TRUE`
`> rClr::clrLoadAssembly(pksimR)`
`Error in rClr::clrLoadAssembly(pksimR) : 
  Failure in rclr_ms_call_static_method, but could not retrieve an error message`
`> rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce")`
`Type not found: PKSim.R.Api
Error in rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce") : 
  Type:    System.ArgumentException
Message: Type not found: PKSim.R.Api
Method:  System.Object CallStaticMethod(System.String, System.String, System.Object[])
Stack trace:
   at Rclr.ClrFacade.CallStaticMethod(String typename, String methodName, Object[] arguments)`

**Comment by msevestre** [comment]
@mnneely ok good stuff

Now can you actually use ospsuite-r? 
For example, can you load a pkml simulation (go to pksim, export any simulation to pkml) and load using `sim<-loadSimulation(pathToPkml)`

If this works, then that means that there is something very weird with PKSim on your system. PRobably nothing to do with the version of R. I suspect this is more a dependency that is missing in the PKSim portable package

**Comment by mnneely** [comment]
Yes, after reinstalling opsuite, I was able to run loadSimulation just fine.  I've just talked to two other members of the lab.  All together two of us have had no problems, and two have the problem in this issue. I can verify that on one computer the exact same installation files worked and on another they did not. It's important we get it running for the two of us that can't. Any ideas on what to do next?  Thanks for your help!

**Comment by mnneely** [comment]
Ahh, I found an email saying it only works if PK-Sim 9 is installed.  Where do I get that? We only have 8 on this computer.

**Comment by mnneely** [comment]
Scratch that.  I see that the version launched from the portable folder is v. 9. I've confirmed that I can launch that outside of R and run simulations.

**Comment by mnneely** [comment]
I removed 8.0 completely leaving only the portable.  That didn't work either.

**Comment by msevestre** [comment]
@mnneely This is a very strange issue and will be very hard to solve because we can't reproduce on any of our test machines (either physical or virtual). The fact that it works on some machines and not on others could indicate some issues with dependencies

1/What version of R is running on the computer that are running fine?
2/Can you try to install the PKSim setup. This is not the official v9 (because it's not out yet) but it will be quite close to it

You can download the zip file here
https://ci.appveyor.com/api/buildjobs/80td0ent633915b8/artifacts/setup.zip

unzip and install the msi package. This will install only the pksim version . Please note where this version is installed so that you can use it in R something like c:\program files\ etc...

Let us know

**Comment by msevestre** [comment]
Also can you try to put the portable package in another folder (that is not program file?)
For example `c:\temp\pk-sim`

**Comment by PavelBal** [comment]
@mnneely You have to manually installt the Visual C++ runtime from [here](https://aka.ms/vs/16/release/vc_redist.x64.exe). This won't be necessary after Ver9. is released.

**Comment by msevestre** [comment]
I am assuming this is already installed because you said you can run PKSim v9 and simulate etc... If this is not the case, please do so

**Comment by PavelBal** [comment]
OK another possible error source - make sure that you have the latest versions of PK-Sim and the ospsuiteR. Sometimes I had problems when one of them was outdated.

**Comment by msevestre** [comment]
This is different here. We cannot load PKSim.R.Api right from rclr. That's what I wanted to check as well and the reason I asked to remove ospsuite-r completely.

If you look at the attempt from yesterday, just loading the dll fails

**Comment by mnneely** [comment]
Will try these additional steps if necessary. We are trying to upgrade the computer from Windows 7 to 10 and having technical problems, so I can't access it.  If the problem persists in 10 I'll try what you suggested.  Either way, I'll report back.  Thx for the help!

**Comment by mnneely** [comment]
> 2/Can you try to install the PKSim setup. This is not the official v9 (because it's not out yet) but it will be quite close to it

This solution worked!  A completely fresh install of Windows 10 did not. @PavelBal I was already using the latest versions of rClr and opsuite.  I was using the portable version of PK-Sim 9.0.163 and that did not work.  However, the files installed from @msevestre worked.  FYI, it installed into D:\Open Systems Pharmacology\PK-Sim 9.0.

If any others have this problem, I also did not need to use the initPK() command any longer with this version, as apparently it was correctly specified in the registry.

Thanks for the help.

**Comment by msevestre** [comment]
You will have to uninstall it manually before installing the released
version however just to be sure you do not have an inconsistent state


Good to hear this is solved. That also means we won't have the problem with
the release but may have it with the probable even though I have no idea why

**Comment by mnneely** [comment]
> You will have to uninstall it manually before installing the released version however just to be sure you do not have an inconsistent state

Got it.  Thanks again.  I'll go ahead and close this.

**Comment by svavil** [comment]
I have encountered a similar problem when the newly installed PK-Sim `dll` files were blocked by Windows security subsystems. I had to unblock all the DLL files, and then PK-Sim initialized successfully.
