### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#4]
Use case 1. Running on a Multicore system (Windows or Linux)
https://nceas.github.io/oss-lessons/parallel-computing-in-r/parallel-computing-in-r.html

https://blog.dominodatalab.com/multicore-data-science-r-python/

https://www.glennklockwood.com/data-intensive/r/parallel-options.html

Use case 2. Running on a (Linux) HPC cluster.
http://chtc.cs.wisc.edu/r-jobs.shtml

Use case 3. Running on AWS (Amazone Web Services) (Linux.)

https://blog.sicara.com/speedup-r-rstudio-parallel-cloud-performance-aws-96d25c1b13e2

https://www.r-bloggers.com/building-our-own-open-source-supercomputer-with-r-and-aws/

**Comment by PavelBal** [comment]
Parallelizatioin of?

**Comment by Yuri05** [comment]
of everything which can be at least trivially parallelized:
* splitting of population simulation in parallel tasks
* splitting of sensitivity calculation within a population in parallel tasks
* parallelizing of qualification reports creation
  * simulations (if not using precalculated simulation results)
  * plots generation
  * ...
* ...

**Comment by msevestre** [comment]
All: I still don't really understand the requirements here. It needs to be specified for us to implement

At the moment, population simulation can be parallelized using .NET parallel tasks already

**Comment by ThomasGaub** [comment]
Some First additional Information.
We need a parallelization of poulation / sensitivity runs that we can use and configure using R-scripts. 
This parallelization  should be useable on local machines, HPC Cluster and aws. 
At the moment It looks like for that we need a master and worker process. The master process manging the the split to the parallel worker processes and the merge of results.  
The default should be a parallelization for all avaible cores, but there should be a option to switch this off, and to specify the numebr of cores to use.

**Comment by msevestre** [comment]
Parallelization  will be implemented at the Reporting Engine level. Closing for now
