### ISSUE TITLE
Create (PK-Sim) population

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#40]
Inputs:
 * Species 
 * Population
 * Min Age (can be empty)
 * Max Age (can be empty)
 * Age Unit
 * Min GestationalAge (can be empty)
 * Max GestationalAge (can be empty)
 * Gestational Age Unit
 * Min Weight (can be empty)
 * Max Weight (can be empty)
 * Weight Unit
 * Min Height (can be empty)
 * Max Height (can be empty)
 * Height Unit
 * Min BMI (can be empty)
 * Max BMI (can be empty)
 * BMI Unit
 * Number of Individuals
 * Proportion of females (in %)
 * List of proteins (can be empty)

Outputs:
 \<Number of Individuals\> parameter sets, incl ontogeny information for the proteins of interest

**Comment by PavelBal** [comment]
- Option to export to csv in a format that can be loaded in PK-Sim.

**Comment by Yuri05** [comment]
>Outputs:
<Number of Individuals> parameter sets, incl ontogeny information for the proteins of interest

Thus _proteins of interest_ must be part of the input as well?

**Comment by PavelBal** [comment]
> Thus proteins of interest must be part of the input as well?

It is possible to define ontogenis now, but I never used it and don't really now how it should look like... Need input from someone who actually use(d) it.

**Comment by PavelBal** [comment]
Also `seed` as an input for reproducible results.

**Comment by Yuri05** [comment]
>Also seed as an input for reproducible results.

**Optionally**, right?

**Comment by PavelBal** [comment]
Yes.

**Comment by msevestre** [comment]
I am going to move that to milestone 3 as this requires integration with PKSim. Right now focusing on Core integration only
