### ISSUE TITLE
Update documentation with feedback from user

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#401]

**Comment by PavelBal** [comment]
Where is the feedback? :D

**Comment by msevestre** [comment]
1. Loading a simulation and accessing entities --> Loading simulation tree: It would be cool to have a gif of the simulation tree in action.

1. Changing parameter and molecule start values --> Changing initial values --> Formula types:
Distributed: It's not clear what the following statement really means: "The value of the parameter is given by a distribution." What distribution? As in a probability distribution? And how is the parameter value chosen if it comes from a distribution? For example, the code snippet uses the liver volume as an example. Where does that value come from? What are the factors involved in choosing this value? Does each distribution have its own factors?

1.  a code snippet demonstrating exportResultsToCSV and importResultsFromCSV should be included as well? Just like what you have for PK analyses and sensitivity analysis results.

1. population simulations --> Running population simulation:  Add a code snippet that shows how one can access a single individual's output and plot it. it has been explained, but it would be nice to have an example.

**Comment by msevestre** [comment]
@PavelBal  sorry. I was just filtering some stuff that could implement myself. There are `only`  4 points

**Comment by msevestre** [comment]
and I created a PR with some of the other simple changes that I could implement myself :) . see #402 
Please start from there or merge and create a new branch

**Comment by msevestre** [comment]
@PavelBal We'd like to get ready for the release. This is the last step that we are missing. Can you do that asap?

**Comment by PavelBal** [comment]
Will be done tomorrow (03.06.)
