### ISSUE TITLE
_norm PK Parameters return NaN in multiAdmin-simulations

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#403]
In simulations with multiple administration most `XXX_norm` are not properly calculated
(example: [Bug03.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4743248/Bug03.zip))

<img src="https://user-images.githubusercontent.com/25061876/83982641-9877de80-a928-11ea-9037-291dbe185088.png"></img>
Comparing this to PK-Sim output: here all `XXX_norm` parameters are calculated as well. All other PK parameters have same values as in RE
![grafik](https://user-images.githubusercontent.com/25061876/83982778-89456080-a929-11ea-90e1-4feba8ddde1b.png)

**Comment by Yuri05** [comment]
ok, it's a bug in the ospsuite package, not in RE.  
[03.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/4744818/03.zip)
```
> sim = loadSimulation("S1.pkml")
> simulationResults <- runSimulation(simulation = sim)
> pkAnalysis <- ospsuite::calculatePKAnalyses(results = simulationResults)
> outputPath <- simulationResults$allQuantityPaths[[1]]
> print(outputPath)
[1] "Organism|PeripheralVenousBlood|C1|Plasma (Peripheral Venous Blood)"
> allPkParams <- pkAnalysis$allPKParametersFor(outputPath)
> C_max_tD1_tD2_norm <- pkAnalysis$pKParameterFor(quantityPath = outputPath, pkParameter = "C_max_tD1_tD2_norm")
> C_max_tD1_tD2_norm$values
[1] NaN
>
```

**Comment by msevestre** [comment]
This is probably a bug in core then.
