### ISSUE TITLE
Error changing solver properties

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#405]
When I try to set e.g. `simulation$solver$absTol `or `sim$settings$solver$absTol` the error 
`Property '$solver' is readonly` is shown.
However it seems that the property is set correctly nevertheless (when exporting modified simulation to pkml, AbsTol has the new value.
```
> sim = loadSimulation("C:/MyModel.pkml")
> sim$solver$absTol
[1] 1e-09
> sim$settings$solver$absTol
[1] 1e-09
> sim$solver$absTol=1e-11
Error: Property '$solver' is readonly
> sim$solver$absTol
[1] 1e-11
> sim$settings$solver$absTol
[1] 1e-11
> saveSimulation(sim, "C:/savedModel.pkml")
```       
And: why do we have solver properties **twice** in the simulation?
```
> class(sim$solver)
[1] "SolverSettings" "DotNetWrapper"  "Printable"      "R6"            
> class(sim$settings$solver)
[1] "SolverSettings" "DotNetWrapper"  "Printable"      "R6"     
```

**Comment by Yuri05** [comment]
@AndreDlm FYI

**Comment by msevestre** [comment]
What do you mean with twice? 
once is sim$solver and the other one is sim$settings$solver

so one is simply a shorcut for the other.

**Comment by msevestre** [comment]
(as we have in core)

**Comment by Yuri05** [comment]
yes, but why do we need to expose both in R? Isn't e.g. `simulation$solver` not enough?

**Comment by msevestre** [comment]
Does settings have more properties?

**Comment by msevestre** [comment]
That works
```
s<-sim$solver
s$absTol <- 1e-10
```

So something is weird in the way properties of subobject are being called

**Comment by Yuri05** [comment]
@Sulav1 FYI

**Comment by msevestre** [comment]
Didn't we fix this?

**Comment by Yuri05** [comment]
Doesn't look so, the part with
```
> sim$solver$absTol=1e-11
Error: Property '$solver' is readonly
```
is still present
