### ISSUE TITLE
Nightlies without vignettes

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#408]
The current build (https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-r/build/artifacts) does not contain vignettes.

**Comment by PavelBal** [comment]
I mean the compiled vignettes, so one can browse them via 

`browseVignettes("ospsuite")`

after installing the package.

**Comment by msevestre** [comment]
Do you see any errors in the log?

**Comment by PavelBal** [comment]
I don't know exactly how the builds are generated. Maybe it has something to do with
https://stackoverflow.com/questions/54634056/how-to-include-an-html-vignette-in-a-binary-r-package

**Comment by msevestre** [comment]
Why would it suddenly not work.
It did work before right?

**Comment by PavelBal** [comment]
Actually I never tried installing the version built by AppVeyor and calling the vignettes, so don't know if it ever worked.

**Comment by msevestre** [comment]
@Yuri05 Do you know how to call the vignettes with the package?

**Comment by msevestre** [comment]
browseVignettes("ospsuite") does not even work in R Studio when loading the package
hum

@pchelle How do we load vignette for TLF and RE?

**Comment by Yuri05** [comment]
`browseVignettes(package = "ospsuite") `you mean this? @msevestre

**Comment by Yuri05** [comment]
Works fine for me with the latest 9.0.83 (was also ok with previous builds)

**Comment by PavelBal** [comment]
Strange, does not work for me...

**Comment by pchelle** [comment]
How do you install your `ospsuite` package ?
I think some functions like `devtools::install()` needs an option like build_vignette to be added.
I don't know how it behaves if you directly load from the bundle though.

**Comment by Yuri05** [comment]
@PavelBal I install the zip package from AppVeyour, via RStudio install (created commandline: 
`install.packages("C:/packages/ospsuite_9.0.83.zip", repos = NULL, type = "win.binary")` )

**Comment by pchelle** [comment]
I just tried to install the current version of the package with `devtools::install(build_vignettes = TRUE)`, and got the errors below. Basically, 2 vignettes did not work out.

E  creating vignettes (58.4s)
   --- re-building 'create-individual.Rmd' using rmarkdown
   Quitting from lines 30-43 (create-individual.Rmd) 
   Error: processing vignette 'create-individual.Rmd' failed with diagnostics:
   Could not find an installation of PK-Sim on the machine. Please install the OSPSuite or use 'initPKSim()' to specify the installation path
   --- failed re-building 'create-individual.Rmd'
   
   --- re-building 'create-run-population.Rmd' using rmarkdown
   Quitting from lines 36-57 (create-run-population.Rmd) 
   Error: processing vignette 'create-run-population.Rmd' failed with diagnostics:
   Could not find an installation of PK-Sim on the machine. Please install the OSPSuite or use 'initPKSim()' to specify the installation path

**Comment by pchelle** [comment]
But might be an issue with my laptop

**Comment by pchelle** [comment]
Using the way Juri sent, worked well on my laptop as well.

**Comment by msevestre** [comment]
@pchelle devtools::install builds the vignettte. And you do not have PKSim installed on your machine so that's why

So I think that this is a non issue here when installing the package properly via install.package?

**Comment by PavelBal** [comment]
Works now also by installing through R-Studio - no idea why.
