### ISSUE TITLE
Set default number of cores to MAX_CORES-1

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#410]
Currently the default value in the SimulationRunOptions is 1.
```
> x = ospsuite::SimulationRunOptions$new()
> x$numberOfCores
[1] 1
> parallel::detectCores()
[1] 8
```
Should be changed to OSP-typical default (MAX_CORES-1)

**Comment by PavelBal** [comment]
Cannot reproduce:

```
> x = ospsuite::SimulationRunOptions$new()
> x
SimulationRunOptions: 
  numberOfCores: 11
  checkForNegativeValues: TRUE
  showProgress: FALSE
> x$numberOfCores
[1] 11
```

**Comment by Yuri05** [comment]
I have ospsuite-R 9.0.83 under R 3.5.2. Always get per default only 1 core.
In my Linux-WSL (same versions of ospsuite-R and R) I get MAX-1 Cores as expected.

Some other users (e.g. @AndreDlm) have the same problem.

**Comment by msevestre** [comment]
Can't reproduce either

```
> x = ospsuite::SimulationRunOptions$new()
> x
SimulationRunOptions: 
  numberOfCores: 7
  checkForNegativeValues: TRUE
  showProgress: FALSE
> 
```

@PavelBal 12 CORES!! what?

**Comment by msevestre** [comment]
@Yuri05 
Can you call `getOSPSuiteSetting("numberOfCores")`

@PavelBal Are you calling this from R studio from package dev?

**Comment by msevestre** [comment]
I think this is wrong here

```
    initialize = function(numberOfCores = ospsuiteEnv$numberOfCores,
                              checkForNegativeValues = TRUE,
                              showProgress = ospsuiteEnv$showProgress) {
```

I think the default value should be NULL and set to the env value otherwise
e.g.


and the code
```
  initialize = function(numberOfCores = NULL,
                              checkForNegativeValues = TRUE,
                              showProgress =  NULL) {

  self$numberOfCores <- ifNotNull(numberOfCores, ospsuiteEnv$numberOfCores)
      self$showProgress <- ifNotNull(showProgress, ospsuiteEnv$showProgress)
```

**Comment by msevestre** [comment]
it;s probably the order when the code is evaluated. Defualt value are evaluated once and then they are stale I believe

**Comment by msevestre** [comment]
@pchelle Can you confirm?

**Comment by Yuri05** [comment]
```
> getOSPSuiteSetting("numberOfCores")
[1] 1
```

**Comment by msevestre** [comment]
@Yuri05 Maybe you have one core :)

**Comment by msevestre** [comment]
```
# Number of cores to use for simualtions and sensitivity. Default to number of cores on the machine - 1
ospsuiteEnv$numberOfCores <- parallel::detectCores() - 1
```

**Comment by PavelBal** [comment]
> 12 CORES!! what?

Yes, old laptop... 16 now :D

But on the new machine I also get `getOSPSuiteSetting("numberOfCores") = 1`, although parallel::detectCores() returns 16, and I have no idea why.

**Comment by msevestre** [comment]
can you inspect ospsuiteEnv?

**Comment by msevestre** [comment]
And I thought 12 cores was a lot. What machine has 16?

**Comment by PavelBal** [comment]
Well 8 cores multithreaded...

I think the problem lies somewhere in the timing of calling `parallel::detectCores()`, see https://stackoverflow.com/questions/28900620/parallel-detectcores-giving-incorrect-output-on-a-virtual-machine/28901071

**Comment by PavelBal** [comment]
> can you inspect ospsuiteEnv?

11 there...

**Comment by msevestre** [comment]
can you load the parallel package and see if this fixes the issue as suggested?

**Comment by Yuri05** [comment]
I have 8 cores (also correctly returned by parallel::detectCores()). Explicit loading of parallel doesn't help. Below the calls executed immediately after the start of R-Studio

```
> library("parallel")
> library("ospsuite")
> x = ospsuite::SimulationRunOptions$new()
> x$numberOfCores
[1] 1
> parallel::detectCores()
[1] 8
```

**Comment by PavelBal** [comment]
Been trying putting `library("parallel")` at different places for half an hour now, no use. I do not understand how and why it comes to this.

**Comment by msevestre** [comment]
Ok what about we create  a function instead
```
numberOfCores = function() {parallel::detectCores() -1}
```

And then wherever we invoke it, we use this method instead?

**Comment by Yuri05** [comment]
fine for me (would call it `defaultNumberOfCores`)

**Comment by PavelBal** [comment]
No matter what I do I always get 11 cores on the 16-cores machine.... No idea any more.

**Comment by PavelBal** [comment]
[ospsuite_9.0.0.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/4786390/ospsuite_9.0.0.zip)


@Yuri05 or @AndreDlm can you try this out? If it works I'll create a  PR.

**Comment by PavelBal** [comment]
The value in the ospsEnv was set upon building the package, so the number that was returned was valid for the machine it was built on, not the one on which it runs.

**Comment by Yuri05** [comment]
>can you try this out?

@PavelBal Works for me

**Comment by msevestre** [comment]
so calling it like this would work then?

numberOfCores = function() {parallel::detectCores() -1}

**Comment by msevestre** [comment]
or how did you solve this?

**Comment by PavelBal** [comment]
Yes, will push this evening.

Michael Sevestre <notifications@github.com> schrieb am Di., 16. Juni 2020,
16:18:
