### ISSUE TITLE
CreatePopulation should not return derived parameters

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#416]
@Yuri05 The implementation of `createPopulation` in R `https://docs.open-systems-pharmacology.org/working-with-r/r-introduction#creating-populations` follows exactly the one that was previously available in Matlab.

I think this is a mistake. We are returning distributed parameters but also derived parameters such as blood flow etc. If one updates the values for blood flow spec, the blood flows are therefore not updated and one gets wrong results.

I think this should be amended. It should be done in PKSim but this would require a new version. I'd suggest to patch ospsuite-r instead to remove all derived parameters

**Comment by msevestre** [comment]
FYI @abdullahhamadeh

**Comment by msevestre** [comment]
For reference: here a drop in replacement with the current code in ospsuite-r to achieve the desired results

```
createPopulationWrapper <- function(populationCharacteristics) {

  # This is the original population created with the current chars
  population <- ospsuite::createPopulation(populationCharacteristics)

  # create an individual with similar properites Species and population. WEIGHT AND AGE DO NOT MATTER as long as we can create an invidiual
  individualCharacteristics <- ospsuite::createIndividualCharacteristics(
    species = populationCharacteristics$species,
    population  = populationCharacteristics$population,
    weight = 70,
    age=30
  )

  individual<- createIndividual(individualCharacteristics = individualCharacteristics)
  for (derivedParameterPath in individual$derivedParameters$paths) {

    if(population$has(derivedParameterPath))
      rClr::clrCall(population$ref, "Remove", derivedParameterPath)

    if(population$has(derivedParameterPath))
      print(paste("DID NOT REMOVE", derivedParameterPath))

  }

  return(population)

}
```

**Comment by Yuri05** [comment]
>I think this is a mistake. We are returning distributed parameters but also derived parameters such as blood flow etc. If one updates the values for blood flow spec, the blood flows are therefore not updated and one gets wrong results.

Yes. I thought those 2 parameter lists were already separated in a population (as it's the case in an individual)...

![grafik](https://user-images.githubusercontent.com/25061876/85986577-c95da780-b9ec-11ea-8242-f75d81af12d7.png)

**Comment by msevestre** [comment]
Nope. It returns the same as what was done in Matlab before. I assume there was a reason for this but upon deeper reflection, I don't think it made sense either

I would vote for patching OSPSuite-r asap and later turn two lists
