### ISSUE TITLE
Provide latest release with OSPS intall

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#421]
Why is the package not a part of the OSPS install any more? I would provide it together with the installation.

**Comment by msevestre** [comment]
I am not sure why this is needed at all. When we dispatch it outside of the install, it allows us to do small bug fixes to the tool without having to update the whole installation package.

I am actually against this request

**Comment by Yuri05** [comment]
>I am not sure why this is needed at all. When we dispatch it outside of the install, it allows us to do small bug fixes to the tool without having to update the whole installation package.

>I am actually against this request

Agree with Michael. By decoupling of OSP Suite setup and R-toolbox we are more flexible (which is also one of the major reasons why it's the same for other components like qualification framework tools etc.)
Also don't see any real advantage in installing ospsuite-R with an OSP setup (in fact it would just save 2 zip packages which must be installed by user manually in R later on)

**Comment by PavelBal** [comment]
Then provide a link to the latest release on the release page of the suite. Right now it is not obvious for the user where to get the package, especially becase it was in the setup folder before.

**Comment by msevestre** [comment]
done
![image](https://user-images.githubusercontent.com/1041237/95870803-ed928980-0d3a-11eb-8ad8-fe2ca1e5cd0e.png)
