### ISSUE TITLE
Export of population to CSV

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#423]
I could not find a method to export a population to CSV. Can we expose a corresponding method from PK-Sim (probably need the `PKSim.Core.Services.PopulationExportTask`?)

As a quick fix, any advise how to create an instance of `PopulationExportTask` from R?

**Comment by msevestre** [comment]
That you can't without adding some code in PKSim.R

But what about converting the population as data frame (populationAsDataFrame is something like this is in utility-population) and save as csv?

**Comment by Yuri05** [comment]
As a workaround:
```
pop_df = populationAsDataFrame(population = pop)
write.csv(pop_df, file = "pop.csv", row.names = FALSE)
```

**Comment by msevestre** [comment]
In fact I think this should become a method in OSPSuite-R 
We cannot export without more context from Core otherwise (as we verify units, dimensions etc..)
