### ISSUE TITLE
Not displaying some documented functions

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite-R#426]
Using `help(package = ospsuite)`, you can get the list of all the documented methods and objects in the package, even if they are not exported.
Adding `#' @keyword internal` prevent the display for the user, but the function documentation is still accessible if the user ask specifically for it (e.g. `help(ApiConfig, package = ospsuite)`)

**Comment by Yuri05** [comment]
fixed
