### ISSUE TITLE
R-Toolbox bug? getAllParametersMatching()

### ISSUE THREAD

**Issue by HenrikCordes** [Open-Systems-Pharmacology/OSPSuite-R#428]
Dear all,

not sure if its the right category for this post.

However, I want to access the relative expression values of a gen (Gene1) in multiple organs in a simulation. 

Let's have a look at a single organ (Liver) first:

In the xml there are 3 reasonable paths for this (same for Periportal). 
1. "Organism|Liver|Pericentral|Intracellular|Gene1|Relative expression"
2. "Organism|Liver|Pericentral|Intracellular|Gene1|Relative expression (normalized)"
3. "Organism|Liver|Pericentral|Intracellular|Gene1|Relative expression out."

The first path is just sitting there and the ID is not used in any formula or anywhere in the xml file.
The second path is used in a formula and connected to the path 3. together with ontogeny factor, reference concentration and local protein container volume.  

As expected from the xml file, altering the value of path 1. does not influence the simulation outcome.
Path 2. and 3. both have an influence on the observed PK (in my case also the same)

I would tend to alter the value in path 2. since to my understanding it is based on the values in the PK-Sim internal expression database and other information on expression levels should be included at this point. Path 3 is a formula including other parameters I might not want to change.

**Is there another opinion to this in the community?** 
 

Now lets take a look at changing multiple expression levels in different organs.
Rather than putting in each and every path by hand I would have liked to extract the path with respect to sub-string matching or regular expression.

getAllParametersMatching("**|Intracellular|Gene1|Relative expression.", sim)
List of parameters # this is however useless since the parameter does not affect the simulation 

getAllParametersMatching("**|Intracellular|Gene1|Relative expression out.", sim)
List of parameters

getAllParametersMatching("**|Intracellular|Gene1|Relative expression (normalized)", sim)
NULL # Here not all parameters are found

**I'm puzzled by this behavior of getAllParameterMatching(), maybe the special characters are causing an exception?** 
(Also the Version with one * instead of ** does not work.)

Kind regards,
Henrik

**Comment by msevestre** [comment]
@HenrikCordes This is where it belongs :)

**Comment by PavelBal** [comment]
> I would tend to alter the value in path 2. since to my understanding it is based on the values in the PK-Sim internal expression database and other information on expression levels should be included at this point.

Yepp, this is the preferred way.

> getAllParametersMatching("**|Intracellular|Gene1|Relative expression (normalized)", sim)
NULL # Here not all parameters are found

Definitely a bug, can reproduce.

**Comment by PavelBal** [comment]
`getAllParametersMatching("**|Intracellular|Gene1|Relative expression (*)", sim)`

works.

`getAllParametersMatching("**|Intracellular|Gene1|Relative expression *)", sim)`

error:

```
Error in rClr::clrCall(task, method, container$ref, enc2utf8(path)) : 
  Type:    System.ArgumentException
Message: parsing "^.*(\\|)?Intracellular\|DIO\|Relative expression [^|]*)$" - Too many )'s.
Method:  System.Text.RegularExpressions.RegexNode ScanRegex()
Stack trace:
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
   at OSPSuite.R.Services.ContainerTask.allEntitiesMatching[T](IContainer container, String path)
   at OSPSuite.R.Services.ContainerTask.AllParametersMatching(IContainer container, String path)
   at OSPSuite.R.Services.ContainerTask.AllParametersMatching(IModelCoreSimulation simulation, String path)
```

**Comment by msevestre** [comment]
@HenrikCordes 

>"Organism|Liver|Pericentral|Intracellular|Gene1|Relative expression (normalized)"

This is the ONLY way to do it properly. This will change in the upcoming version as we realized that this is causing more confusions than good. But for now, this is the parameter you should change


>(Also the Version with one * instead of ** does not work.)

What does this mean? * and ** have different semantic and are clearly not meant to be interchangeable

**Comment by HenrikCordes** [comment]
Thank you @msevestre  and @PavelBal  for your swift feedback on the matter!

As discussed in the earlier post, I'll go on with modifying the "*|Relative expression (normalized)" parameters than.

@msevestre regarding "*" and "**", here I think the "*" is intended to replace single characters and the "**" is intended to replace chunks / whole parts of the path string. I just meant that both are not working to only return the "(normalized expression)" paths when using getAllParametersMatching().

Its probably the best to go with @PavelBal 's approach to first get all the related gene expression paths 
>> getAllParametersMatching("**|Intracellular|Gene1|Relative expression (*)", sim)
and than use string matching / grep to retrieve the desired "(normalized)" strings. 

Thank you both again for the discussion and your feedback!

Best,
Henrik

**Comment by msevestre** [comment]
Let's not close this . There is still a bug

**Comment by PavelBal** [comment]
This is a bug in Core.

**Comment by msevestre** [comment]
Bug is fixed in Core. Fix coming in R  in the next few minutes
