### ISSUE TITLE
Update documentation on population simulations

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#430]
We did not update the docu after the behavior of `createPopulation` has been changed to return a list instead of a `Population`-object.

**Comment by msevestre** [comment]
@Yuri05 Can you generate the documentation for the R section in the website again?

**Comment by IndrajeetPatil** [comment]
I think this is already done [here](https://www.open-systems-pharmacology.org/OSPSuite-R/reference/createPopulation.html)?

![image](https://user-images.githubusercontent.com/11330453/172371368-73837401-8fde-4167-b316-6dd022940f24.png)

**Comment by IndrajeetPatil** [comment]
Is this still an issue, @PavelBal?

**Comment by PavelBal** [comment]
I guess its done, yes
