### ISSUE TITLE
RStudio crashing after saving workspace - OSPSuite-R

### ISSUE THREAD

**Issue by Chrizsly** [Open-Systems-Pharmacology/OSPSuite-R#431]
Dear all,

When working with the R package OSPsuite and using functions e.g. loadSimulation or runSimulation, and the workspace in R is saved, RStudio keeps on crashing. Running the same piece of code in the R Gui works just fine. 

Proposed workaround: don't save the current workspace in R, but refer to the documentation (https://docs.open-systems-pharmacology.org/working-with-r/r-introduction#running-a-simulation) on how to store and re-load simulation results. This is especially helpful for time-intense population simulations. 

Thanks and best,

**Comment by msevestre** [comment]
@Chrizsly THis is correct. Our data model is using .NET object under the hood that cannot be serialized by R Studio
This should definitely be in the documentation! Thanks for pointing this out

@Chrizsly Do you feel like creating a PR for the doc?
