### ISSUE TITLE
Unit test fails under Linux (but the test code seems to run as expected)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#435]
This unit test fails under Linux:
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/415013fb337189ebd0134bc52a74f330142ceb3e/tests/testthat/test-user-defined-pk-parameter.R#L4-L9

Executed via test_that (`test_package("ospsuite")`) the test produces the result below
```

── 13. Failure: It print a user defined pk parameter (@test-user-defined-pk-para
`capture.output(userDefinedPKParameter$print())` threw an error.
Message: comparison (1) is possible only for atomic and list types
Class:   simpleError/error/condition
Backtrace:
 1. userDefinedPKParameter$print()
 3. ospsuite:::getEnumKey(StandardPKParameter, self$standardPKParameter)
 4. base::which(enum == value)
```
However when I execute the test code **manually**, it behaves as expected: the last action throws an exception:
```
> userDefinedPKParameter <- addUserDefinedPKParameter(name = "MyAUC", standardPKParameter = StandardPKParameter$AUC_tEnd)
> userDefinedPKParameter$startTime <- 50
> userDefinedPKParameter$endTime <- 80
> capture.output(userDefinedPKParameter$print())
Error in enum == value :
  comparison (1) is possible only for atomic and list types
```

Thus I really wonder why the test case expectation (`expect_error(capture.output(userDefinedPKParameter$print()), NA)`) fails...

**Comment by Yuri05** [comment]
>` expect_error(foo(), NA)` expects *no* error (thus `NA`).

Ok, I thought `expect_error `would... well, expect an error. Then it's a bug of printing functionality in Linux

**Comment by PavelBal** [comment]
In general the better practice would not only to test for errors, but also for the content of the thrown error.

**Comment by Yuri05** [comment]
So, the code below (taken from the test case)
```
userDefinedPKParameter <- addUserDefinedPKParameter(name = "MyAUC", standardPKParameter = StandardPKParameter$AUC_tEnd)
userDefinedPKParameter$startTime <- 50
userDefinedPKParameter$endTime <- 80
userDefinedPKParameter$print()
```
crashes under Linux with
```
UserDefinedPKParameter:
  Name: MyAUC
  DisplayName: MyAUC
  Dimension: AUC (molar)
  DisplayUnit: µmol*min/l
Error in enum == value :
  comparison (1) is possible only for atomic and list types
    █
 1. └─userDefinedPKParameter$print()
 2.   ├─private$printLine(...) user-defined-pk-parameter.R:61:6
 3.   └─global::getEnumKey(StandardPKParameter, self$standardPKParameter) user-defined-pk-parameter.R:61:6
 4.     └─base::which(enum == value) enum.R:35:2
```

Under Windows it runs apparently.

This line crashes:
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/a2c8352731e39d218206e4d72178eede3c73cc9f/R/user-defined-pk-parameter.R#L61

Trying to call getEnumKey directly under Linux produces this error then:
```
> getEnumKey(StandardPKParameter, userDefinedPKParameter$standardPKParameter)
Error in enum == value :
  comparison (1) is possible only for atomic and list types
    █
 1. └─global::getEnumKey(StandardPKParameter, userDefinedPKParameter$standardPKParameter)
 2.   └─base::which(enum == value) enum.R:35:2
```

And under Windows:
```
> userDefinedPKParameter <- addUserDefinedPKParameter(name = "MyAUC", standardPKParameter = StandardPKParameter$AUC_tEnd)
> userDefinedPKParameter$startTime <- 50
> userDefinedPKParameter$endTime <- 80
> userDefinedPKParameter$print()
UserDefinedPKParameter: 
  Name: MyAUC
  DisplayName: MyAUC
  Dimension: AUC (molar)
  DisplayUnit: µmol*min/l
  StandardPKParameter: AUC_tEnd
  StartTime: 50
  StartTimeOffset
  EndTime: 80
  EndTimeOffset
  StartApplicationIndex: 
  EndApplicationIndex: 
  NormalizationFactor
  ConcentrationThreshold
> getEnumKey(StandardPKParameter, userDefinedPKParameter$standardPKParameter)
[1] "AUC_tEnd"
```

And finally:
under Windows:
```
> userDefinedPKParameter$standardPKParameter
[1] 9
```
under Linux:
```
> userDefinedPKParameter$standardPKParameter
An object of class "cobjRef"
Slot "clrobj":
<pointer: 0x466d360>

Slot "clrtype":
[1] "OSPSuite.Core.Domain.PKAnalyses.StandardPKParameter"
```
@PavelBal @msevestre Any ideas what's `userDefinedPKParameter$standardPKParameter` is 9 under Windows but some CLR-Wrapper under Linux?

**Comment by PavelBal** [comment]
@Yuri05 Can you call

`rClr::clrGet(userDefinedPKParameter$ref, "StandardPKParameter")`

under Linux and see what it returns? It should return an integer, but no idea why it returns something else under Linux.

**Comment by Yuri05** [comment]
```
> rClr::clrGet(userDefinedPKParameter$ref, "StandardPKParameter")
An object of class "cobjRef"
Slot "clrobj":
<pointer: 0x25c1e90>

Slot "clrtype":
[1] "OSPSuite.Core.Domain.PKAnalyses.StandardPKParameter"
```

**Comment by PavelBal** [comment]
Looks like rClr under Linux cannot properly handle enums (facepalm).

**Comment by Yuri05** [comment]
> Looks like rClr under Linux cannot properly handle enums (facepalm).

nice, nice.
Could we e.g. provide an ExtensionMethod `StandardPKParameterAsInt ` (or smthg like that) for the `UserDefinedPKParameter `which would be then called from R instead of `userDefParameter.StandardPKParameter`?

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/09b783bf84505405ac45594dd4b3f05d26340426/src/OSPSuite.Core/Domain/PKAnalyses/UserDefinedPKParameter.cs#L44

Alternatively I would just disable the one test under Linux.

Are there any other NET calls in ospsuite-R which get/set enums?

**Comment by PavelBal** [comment]
Seems to work
