### ISSUE TITLE
Cannot calculate PK-Parameters of a population when one individual simulation failed

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#436]
@Yuri05 @PavelBal 
I believe this is a major issue and we should come up with a way to deal with this

Scenario: 
* I run a simulation of 4000 Individuals. The simulation runs literally takes a couple of hours
* One simulation out of 4000 (for individual Id # 1521) crashes
* The exported CSV results do not have any entry for 1521 
* Calculating the PK Analyses for this pop simulation crashes because of index mismatch

We had this discussion for the RE. I think we should fix this as it can lead to a lot of frustration

**Comment by PavelBal** [comment]
I would be ok with just ignoring these values.

**Comment by Yuri05** [comment]
We already discussed this previously (https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/284) and proposed to define an _failure_threshold_ (max. acceptable percentage of failed individuals per population). 
If the number of failed simulations is below this threshold - just ignore the crashed simulations. If above: throw an exception and cancel the whole run

**Comment by msevestre** [comment]
This is not what I am talking about, or at least it's not obvious to me that it is the same
The pop sim runs ok. I get 3999 results for 4000 individual. However calculating PK crashes because it expects 4000 results. We need to support results files that are not complete when we calculate pk parameters

**Comment by msevestre** [comment]
and when it takes many hours to run... THAT SUCKS :)

**Comment by PavelBal** [comment]
@msevestre This cannot be solved in R, right? I am having the same issue now... Do you have some experience how to deal with it?

**Comment by msevestre** [comment]
What I did was identified the individual and swap it with another one. If you have multiple like this, or if some stuff is random...then it will be more complicated

This is such a pain. I think we should fix this asap. I'll tackle this after relexp redesign

**Comment by PavelBal** [comment]
>What I did was identified the individual and swap it with another one

How did you do that? `calculatePKAnalyses` takes on object of `SimulationResults`, which then has a mismatch of ID with the index of the individual. How can you swap it there?

**Comment by msevestre** [comment]
I swap at the population level
e.g. I identified the individual crashing
removed it from the pop
and ran the stuff again

**Comment by msevestre** [comment]
in hindsight: I would identify the wrong individual: for example 354
In the pop, copy 354 with 353
in the results copy 353 results to 354
then calculate the PK. If you have a big enough pop, having 2 identical individuals will have no effect on stats etc.

**Comment by msevestre** [comment]
I think that I have it implemented. The PK Values will return NAN for an individual that was not calculated thus insuring that the array will have consistent length
