### ISSUE TITLE
Example of R package that seems to be well organized

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#44]
* Continuous Integration
* Tests
* Man
* Many small functions
* ....

https://github.com/InsightRX/PKPDsim
@PavelBal @pchelle @abdullahhamadeh 

Probably worth studying a bit

**Comment by msevestre** [comment]
another place where to look for inspiration...
https://github.com/tidyverse

**Comment by PavelBal** [comment]
Great, thanks.

**Comment by msevestre** [comment]
Also 
http://r-pkgs.had.co.nz/

**Comment by PavelBal** [comment]
Transferred to wiki.
