### ISSUE TITLE
Misleading method name "addUserDefinedPKParameter"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#440]
This is so strange - from the method name I would not expect it to return a user defined PK-Parameter.

More intuitive workflow would be:

```
myParam <- UserDefinedPKParameter$new(name, standardPKParameter, displayName = NULL, displayUnit = NULL)
myParam$startApplicationIndex <- 4

addUserDefinedPKParameter(myParam)
```

Also, the documentation of `addUserDefinedPKParameter` does not include an `@return` field.

**Comment by Yuri05** [comment]
>from the method name I would not expect it to return a user defined PK-Parameter.

Well... I would expect exactly what it does.

**Comment by msevestre** [comment]
This what we do in many places where a user does not instantiate a .net parameter. Rather it all happens underneath the hood following R conventions.

it could have been split into two
create and then add. But creating without adding has very little meaning so ..... 

Doc updated
