### ISSUE TITLE
Errors with rClr in R.4.0.2

### ISSUE THREAD

**Issue by AyaSaleh90** [Open-Systems-Pharmacology/OSPSuite-R#442]
Hello,

I have R version 4.0.2, and whenever I try to open the ospsuite it gives me this error, although it worked fine with previous version R 3.6.0. 
And I tried to re-install many time with the same error

> library (ospsuite)
Loading required package: rClr
Error: package or namespace load failed for ‘rClr’:
package ‘rClr’ was installed before R 4.0.0: please re-install it
Error: package ‘rClr’ could not be loaded

**Comment by msevestre** [comment]
@AyaSaleh90 Version 4.x of R is not supported yet. If you want to use the ospsuite-r, you need to stick with 3.x

**Comment by AyaSaleh90** [comment]
Ok, thats for fast reply

**Comment by msevestre** [comment]
That should probably be in the readme.
Please feel free to submit a PR To update it  and specify that R version 3.5 but < 4.0 is required

**Comment by msevestre** [comment]
ospsuite-R v10 will support R4.
