### ISSUE TITLE
Enable Batch Simulation Run

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#444]
FYI @Yuri05 @PavelBal @StephanSchaller @abdelr

This is so that one can support batch mode in R as well

Something like this could be defined

```R

# simulation: A simulation loaded from pkml
#parameters: Array of parameter by path or parameter instanced that will be varied

simulationBatch<- SimulationBatch$new(simulation, parameters)

# THEN

simulationBatch.setParameterValues("Organism|P1", 5)

# or
simulationBatch.setParameterValues(c("Organism|P1", "Organism|P2"), c(5, 10))

# and 

res <- simulationBatch.Run()

```

How does that sound?

**Comment by PavelBal** [comment]
I like.

**Comment by abdelr** [comment]
Sounds totally good!!!

**Comment by StephanSchaller** [comment]
> # or
simulationBatch.setParameterValues(c("Organism|P1", "Organism|P2"), c(5, 10))

# and 

res <- simulationBatch.Run()


This can then be run repeatedly without recreating the simulation?

**Comment by msevestre** [comment]
@StephanSchaller Yes this is the whole point. You setup the batch and then you update and run

**Comment by Yuri05** [comment]
sounds good. just needs to be extended with molecules initial values, which can be varied as well, e.g.
`simulationBatch<- SimulationBatch$new(simulation, parameters, initialValues)`

**Comment by Yuri05** [comment]
Also setting scaling factors (for all molecule amounts, not only for those being varied) might be useful, e.g.
`SimulationBatch$SetScalingFactors(paths, factors)`

**Comment by msevestre** [comment]
I am not sure I understand the scaling factor suggestion. How is this used in the context of batch? Does SimModel exposes a method to update them on the fly?

**Comment by msevestre** [comment]
@Yuri05 initialValues ok
How do we identify them? Do we always have SartAmount parameters ? e.g. Liver|Cell|Drug|StartAmount?

**Comment by StephanSchaller** [comment]
> @StephanSchaller Yes this is the whole point. You setup the batch and then you update and run

... and update and run and update and run and update and run ;-)... great then!

**Comment by StephanSchaller** [comment]
> I am not sure I understand the scaling factor suggestion. How is this used in the context of batch?

The might be use-cases where updating scaling factors in between runs might be required.

**Comment by msevestre** [comment]
>... and update and run and update and run and update and run ;-).

lol yes!

>the might be use-cases where updating scaling factors in between runs might be required

Yes I get this .But I do not think we have a way to set those scale factor after the fact...or do we?

**Comment by Yuri05** [comment]
>How do we identify them? Do we always have SartAmount parameters ? e.g. Liver|Cell|Drug|StartAmount?

No,` just Liver|Cell|Drug`

**Comment by Yuri05** [comment]
>Yes I get this .But I do not think we have a way to set those scale factor after the fact...or do we? (this needs to be implemented in SiModel)

Should be possible. You can get all the molecule properties via `Simulation.SpeciesProperties`
https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/08fb0d56cc0ca017f0491ff615267ace2f69d07a/src/OSPSuite.SimModel/Simulation.cs#L518
and then set the scale factor

**Comment by msevestre** [comment]
Two things;
1/ you do not simplify them somehow as part of the finalization process of the simulation?
2/ this is not something that we expose in .net at the moment either and we would have to change the simmodelbatch for this. So unless this is absolutely required, I would postpone this

Initial values no problem

**Comment by Yuri05** [comment]
>1/ you do not simplify them somehow as part of the finalization process of the simulation?

I think they are recached then.. but have to check.

>So unless this is absolutely required, I would postpone this

fine _for me_

**Comment by PavelBal** [comment]
> I think they are recached then.. but have to check.

As far as I remember there were some problems with that : https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/issues/35

But I am not sure if all of them have been fixed.

**Comment by msevestre** [comment]
starting working on this now. Which me luck

As for the interface, I think I will make it a bit lower level and not repeat the path of the parameter all the time. This will requires check that we do not need to do and since our goal is to be fast, lets remove those checks

So: if paramet is c("organism|Liver|v", "organism|kidney|v"), when I cal setParameterValues, I need to pass an array of 2 values
matching parameters order. 

Or do you think there is a use case to specify only a subset of parameters that one set as variable previously? This will be harder to implement because it's not supported currently by ospsuite.core

```R

# simulation: A simulation loaded from pkml
#parameters: Array of parameter by path or parameter instanced that will be varied

simulationBatch<- SimulationBatch$new(simulation, parameters)

# THEN

simulationBatch.setParameterValues( 5)

# or
simulationBatch.setParameterValues(c(5, 10))

# and 

res <- simulationBatch.Run()

```
