### ISSUE TITLE
DotNetWrapper - return pointer address of the ref-object

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#446]
Would be cool if somehow the address or some kind of an ID of the object could be retrieved by. Could be used for hashing objects.

**Comment by msevestre** [comment]
We could expose the GetHashCode method. It's a method available in all .net object

How would you want to use this? Can't you use path?

**Comment by PavelBal** [comment]
I want to store objects in a map, with ability to remove or add new objects. When adding an object, I have to check if it is already in the map. This is only one example. I cannot use the path because the path can be equal - e.g., a parameter from different simulation instances.

**Comment by PavelBal** [comment]
I just found the propert `id`, I think it solves the problem.

**Comment by msevestre** [comment]
This is not for ALL .net object but for ObjectBase object. (which is probably everything you manipulate aside from simulation options etc..)

**Comment by PavelBal** [comment]
All rights... Well, I don't think exposing GetHashCode could do any harm?

**Comment by msevestre** [comment]
Aside from confusing anyone :) If you can leave with the id, which you probably can since all objects in a model have id, then I would keep it like that

**Comment by PavelBal** [comment]
OK, relying on the ID so far.

**Comment by PavelBal** [comment]
OK, I misunderstood the concept of ID. Two simulation objects loaded from the same file will have identical IDs. I have to distinguish between the simulation objects.

**Comment by PavelBal** [comment]
Damn, this just destroyed the whole concept I have been implementing the whole day....

**Comment by msevestre** [comment]
Why do you need TWO different id for the same parameter?!?

**Comment by PavelBal** [comment]
Basic use-case: simulation of drug administration with different doses.

I load a simulation from pkml and set the dose in R. Then I run (or do parameter identification) every simulation, which are now all different (they have different doses, right?), but still have the same IDs for all the objects.

Is `GetHashCode` what I am looking for?

**Comment by msevestre** [comment]
no I think we should add an option to reset ids when laodinga simulation
that way all id's would always be different
In fact I am wondering if this is not something that we should always DO by default because
1/if we say load from cache = flase, then we get another instance and therefore we would expect to have different ids

**Comment by msevestre** [comment]
so I think you can safely stay with Ids for now until we fix this

**Comment by PavelBal** [comment]
>Is GetHashCode what I am looking for?

No? Damn... No I cannot stay with IDs exactly because I am loading multiple simulations from the same file...

**Comment by PavelBal** [comment]
The IDs are loaded from the pkml btw.

**Comment by msevestre** [comment]
yes: here is what I suggest

sim <-loadSimulation(pkml, resetId = TRUE)
sim <-loadSimulation(pkml, resetId = FALSE)

that way you can specify whether you want new Ids or old ids


Hack for now: Before you load from pkml, modify the pkml by adding some random char at the end of  each id

**Comment by msevestre** [comment]
or you can use GetHashCode for now (just call rclr::rclrCall("GetHashCode")
this returns an int. That should do the trick for now

**Comment by PavelBal** [comment]
>or you can use GetHashCode for now (just call rclr::rclrCall("GetHashCode")
this returns an int. That should do the trick for now

Yes, this was my question all the time :D Works (so far).

**Comment by msevestre** [comment]
Lol. Yeah 
I know that we overwrite this value for some objects so that we can compare them. So I'd definitely prefer you work with the id, which is what we are using internally as well. It should be fine as long as you cache parameters however

**Comment by PavelBal** [comment]
No! `GetHashCode` is equal for the root containers of two simulations loaded from the same pkml! I am going crazy here...

**Comment by msevestre** [comment]
ah ah I just realize that we make sure that two object with the same ID have the same hash code lol

**Comment by msevestre** [comment]
so relax. I'll update the toolbox tomorrow to support this feature :)

**Comment by msevestre** [comment]
is there a way for you to load the pkml and modify the id ont he fly  by adding some random chars?

**Comment by PavelBal** [comment]
> ah ah I just realize that we make sure that two object with the same ID have the same hash code lol

Yes I just saw that in .net code and was about to cry.

> so relax. I'll update the toolbox tomorrow to support this feature :)
Would be awesome. I think it's a sign to go home for now.

> is there a way for you to load the pkml and modify the id ont he fly by adding some random chars?

Cannot think of any direct way... Iterating through all the nodes of the simulation and changing the IDs sounds not that efficient.

**Comment by msevestre** [comment]
https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-r/build/artifacts

**Comment by msevestre** [comment]
v10 however. You won't be able to use pksim functions

**Comment by PavelBal** [comment]
Amazing, thanks for the quick fix!

Will it work with the upcoming PK-Sim nightlies?

**Comment by msevestre** [comment]
Yes. For some reasons, appveyor does not support branch with / in the name. So I'll have to rename the feature branch and this should then work

**Comment by msevestre** [comment]
@PavelBal In fact I just realized that the build needs to be successful. It is not the case at the moment in PK-Sim
So I soon as I get a build working....it will be all right. we are almost there (6 tests failing)

**Comment by PavelBal** [comment]
@msevestre Great, thank you. Good thing there is an option to have a project-specific library in R ;)

**Comment by PavelBal** [comment]
@msevestre There is no compatible PK-Sim version yet, correct? Just to make sure I am not missing anything.

**Comment by msevestre** [comment]
I think any nightly build is compatible @PavelBal . Only I can only download a SUCCESSFUL build from the R script to run the tests. This is why I commented this stuff out. But it should work with the latest nightly

**Comment by PavelBal** [comment]
I'm getting this when trying to init PK-Sim, any idea?:

```
> initPKSim("d:\\Work\\OSPS\\PKSim10\\")
Error in rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce") : 
  Type:    System.Reflection.ReflectionTypeLoadException
Message: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Method:  System.RuntimeType[] GetTypes(System.Reflection.RuntimeModule)
Stack trace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Rclr.ClrFacade.GetType(String typename)
   at Rclr.ClrFacade.CallStaticMethod(String typename, String methodName, Object[] arguments)

Type:    System.IO.FileNotFoundException
Message: Could not load file or assembly 'Microsoft.Extensions.Options, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
Method:  
Stack trace:


Type:    System.IO.FileNotFoundException
Message: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one
```

**Comment by PavelBal** [comment]
Do I have to update the .net runtime or something?

**Comment by msevestre** [comment]
@msevestre It seems that we are missing some dlls in PKSim. It looks like Microsoft.Extensions.Logging.Abstractions has now dependencies on other packages.
I'll have to check with georgios and abdel

**Comment by msevestre** [comment]
Ok I am going to update PKSim build to add those dlls as dependencies

**Comment by msevestre** [comment]
@PavelBal Merged in develop. Compatible with latest build from PKSim 10.0.44 and higher
