### ISSUE TITLE
Get simulation object of Entities

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#448]
I would like to have a method to get the `Simulation` object of the `Entity` - is it possible?

**Comment by msevestre** [comment]
This is not available in .NET. 
This could potentially be made available at the Entity level if loaded from a simulation. 
but...why do you need this? It feels like an info that a parameter should not need to have

**Comment by PavelBal** [comment]
For parameter identification, I define a mapping of observed data to model outputs (Quantities). At different steps of the workflow I need to track back which simulation a certain Quantity output belongs to, so I can get the right results.

I have solved this for now by storing simulation objects in a map where the keys are the IDs of `Simulation$root` container, and when I need to find a simulation belonging to a Quantity, I recursively retrieve the ID of its most upper parent container... It works, but it would be easier with just getting this object.

**Comment by msevestre** [comment]
I think you need the concept of an IndentificationPArmaeter that would have a ref to a sim and a parameter.
You should hvae both items available because the parameter is loaded from a simulation and therefor at some point, you have the info readily available

**Comment by PavelBal** [comment]
For the parameters it is actually not required, because changing the value of the parameter does not require a simulation.

But yes, writing a class that holds the information about the entity and the corresponding simulation is a way. Going to try it out with root ID for now. I just like hash maps :D

**Comment by PavelBal** [comment]
Solved with a HashMap and ID of the simulations.
