### ISSUE TITLE
OutputSchema - errors in messages

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#451]
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/976bd5ca2a4813d115b7a4d32ff9019acd009661/R/output-schema.R#L12-L18

should be `private$throwPropertyIsReadonly("intervals") `

In

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/976bd5ca2a4813d115b7a4d32ff9019acd009661/R/output-schema.R#L22

and 

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/976bd5ca2a4813d115b7a4d32ff9019acd009661/R/output-schema.R#L26

the names of the properties should not be capitalized (i.e., `timePoints` and `endTime`), and also in the following lines, as the names of the fields in R are in lower case.

**Comment by msevestre** [comment]
The name of the props are the name or the .net methods which are capitalized so this should stay as is 

Agreed with first point
