### ISSUE TITLE
OutputSchema: adding time points when no interval is present

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#452]
I do not know if it is a bug or a feature or just a not specified use case.

When adding time points via `$addTimePoints` after removing all intervals by calling `$clear`, the resulting time points are added without an interval.

```
> testSim <- loadSimulation(file.path(runConfiguration$modelFolder, runConfiguration$modelFile))
> testSim$outputSchema$intervals
[[1]]
Interval: 
  Name: Output interval
  Start time: 0.00 [min]
  End time: 150.00 [min]
  Resolution: 1.00 [pts/min]
```

Now clear the outputs:

```
> testSim$outputSchema$clear()
> testSim$outputSchema$intervals
list()
```

and add some points

```
> testSim$outputSchema$addTimePoints(c(1,2,3,4))
> testSim$outputSchema$timePoints
[1] 1 2 3 4
> testSim$outputSchema$intervals
list()
```

So the time points are there, but they do not belong to any interval. I would expect that some "default" interval is created, and the outputSchema cannot be without a single interval. This is also what the description of the method suggests:

```
    #' @description
    #' Adds the time points to the schema
    #' @param timePoints Time points to add to the interval
```

**Comment by msevestre** [comment]
It's a feature. Interval always give you a set of points. Here you can specify only single unique points

**Comment by PavelBal** [comment]
I think it should be better explained that time points and intervals exist concurrently. So just retrieving the intervals might not be sufficient as the time points may specify values that are outside of the intervals.

Also `#' @param timePoints Time points to add to the interval` is wrong in that case. It should be "Time points to add to the output schema" or something like this.

**Comment by msevestre** [comment]
Please submit a pr
