### ISSUE TITLE
loadSimulation - loadFromCache not clear

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#456]
The documentation states:

```
loadFromCache	
If TRUE, an already loaded pkml file will not be loaded again, but the simulation object will be retrieved from cache. This is the default behavior. If FALSE, new object will be created. Default value is FALSE

addToCache	
If TRUE, the loaded simulation is added to cache. If FALSE, the returned simulation only exists locally. Default is TRUE
```

For `loadFromCache`, the default behavior is not clear. If the default behavior is `FALSE` (which it is), the the default `addToCache` does not make any sense, does it?

**Comment by msevestre** [comment]
by default, you do not load from cache but you add to cache so that next time you load if you load from cache, it's available.

Makes sense to me...

**Comment by PavelBal** [comment]
OK, but the docu still must be updated.

**Comment by msevestre** [comment]
Yes. I didn't see this. ;-)
