### ISSUE TITLE
runBatchSimulations

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#460]
This is something different from Enable #444 but I am not sure which one is more "batch simulations".

A function that takes a set of `Simulation` objects, runs them in .NET in parallel, and returns a set of `SimulationResults`.

```
sim1 <- loadSimulation(path1)
sim2 <- loadSimulation(path2)
sim3 <- loadSimulation(path3)

simulationResults <- runBatchSimulations(c(sim1, sim2, sim3), simulationRunOptions)
```

**Comment by PavelBal** [comment]
@Yuri05 Without going into details - maybe you know what the problem is and can quickly give a hint:

When loading the same pkml file twice (or two different files which are identical copies of each other) into two simulation objects and trying to run the concurrently in .NET (Abdel started an implementation of such a method), segfault occurs ("Attempted to read or write protected memory")

```
sim1 <- loadSimulation("sim1.pkml")
sim2 <- loadSimulation("sim1.pkml")

results <- runInParallel(c(sim1, sim2))
-> Memory access error
```

Two simulations loaded from two different files (with different contents - so the simulations must be somehow different) works. Once I was able to get the error about SimModel being not finalized - so it seems that the same SimModel object is used in case when the loaded simulations are identical. Is this a known behavior and can it be overcome?

**Comment by msevestre** [comment]
What does runInParallel do? 
Are you using the latest version of ospsuite-r with resetId set to true by default
Then the object are completely independent.

**Comment by PavelBal** [comment]
```
      public SimulationResults[] RunConcurrently(SimulationRunnerConcurrentOptions options)
      {
         var tasks = new List<Task<SimulationResults>>();
         foreach (var setting in options.SimulationsWithPopulations)
         {
            if (setting.Population != null)
               tasks.Add(RunAsync(setting.Simulation, setting.Population, options.simulationRunOptions));
            else
               tasks.Add(RunAsync(setting.Simulation, options.simulationRunOptions));
         }
         Task.WaitAll(tasks.ToArray());
         return tasks.Select(t => t.Result).ToArray();
      }
```

`options` is just a pair of simulation/population objects. So it runs `RunAsync` for each simulation. Yes, the simulations have different ID, but somehow it seems that the SimModels are the same...

**Comment by msevestre** [comment]
Code is oudated. RunAsync only takes one parameter now

>it seems that the SimModels are the same...
Impossible

But maybe there is some global stuff going on in SimModel....but I don't think so

Are you sure you have loaded them using resetId = true?

**Comment by PavelBal** [comment]
if the code is outdated we'll try to rebase and see if it helps.

Yes, also debugging in core shows that the simulation objects have different IDs. Weird

**Comment by msevestre** [comment]
>if the code is outdated we'll try to rebase and see if it helps.

It won't but at least it will be easier to reason about
You should be able to reproduce the behavior in .NET
Create a test,
Load the same simulation twice
It should crash
Then we can investigate

**Comment by msevestre** [comment]
BTW
>  tasks.Add(RunAsync(setting.Simulation, setting.Population, options.simulationRunOptions));
I am pretty sure that this will induce too much // and will in fact bit slower than running the simulation sequentially. The population runner already // the run to the max. Trying to run more simulation will create what we called over parallelization. 

I would be in favor to only allow this for Individual Simulation

**Comment by PavelBal** [comment]
@abdelr FYI

**Comment by PavelBal** [comment]
This is implemented.
