### ISSUE TITLE
Performance: avoid creation of new Quantity-objects in getOutputValues

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#462]
In one particular scenario I have identified a bottleneck in the performance of retrieving the output values of simulated results.

I am simulating a steady-state of the model. For this, I first retrieve all quantities that are described by an ODE - first all molecules, and then all parameters and sorting the parameters that are state variable:

```
  quantities <- getAllMoleculesMatching("Organism|**", container = simulation)
  # Get all state variable parameters
  allParams <- getAllParametersMatching("**", container = simulation)
... extract param$isStateVariable ...
```

This already takes almost 4 minutes, and the majority of time is spent on creating the quantities, in particular in creating the quantities' formula objects:

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/44d8471562ff53db5fd7134f26f9d3237766a36b/R/quantity.R#L93-L97

Once identified all quantities (lets call them `allQuantities`), these are used as outputs in the simulation.  Simulating and getting the results consumes 53 seconds, of which only 20 seconds are for the simulation itself - the other 30 seconds are spent on getting the results. Once again, much time is spent on creating `Quantity`-objects, including here:

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/44d8471562ff53db5fd7134f26f9d3237766a36b/R/utilities-simulation-results.R#L81-L85

However, creating Quantity-objects is not necessary if a list of quantities is provided instead of paths. By re-writing the method I could improve the time from 53 to 40 seconds - which is not negligible if the scenario is performed multiple times (e.g. in a parameter identification).

I will submit a PR.

**Comment by msevestre** [comment]
>This already takes almost 4 minutes

That I find very surprising. How large is your model?
Also `getAllParametersMatching(**)` looks like you want all parameters. Don't we have a more optimized function for this?

**Comment by PavelBal** [comment]
> That I find very surprising. How large is your model?

Yes this is crazy. Well, the model is quite large - the exported pkml is 50mb...

`getAllMoleculesMatching("Organism|**", container = simulation)` takes 20 seconds, with quite some time spent on creating/accessing the formulas (returns 3800 elements):

![image](https://user-images.githubusercontent.com/25903040/102897026-a70e8900-4467-11eb-84c4-ca2d42025028.png)


And  `getAllParametersMatching(**)` is ridiculously slow (returns 37500 elements) with 3.6 minutes!. 

Retrieving only state variable parameters would be a great improvement, but I did not find how to do it directly.

![image](https://user-images.githubusercontent.com/25903040/102897873-fc976580-4468-11eb-860a-0b404ce077d7.png)

**Comment by msevestre** [comment]
40k parameters lol
What I mean is getAllParameterMatching(**) will try to match every single path by regex. I think it would be faster to load them all and then filter

How do I read this perf graph? I see the number of time a method is called but I don't see the overall time

**Comment by PavelBal** [comment]
> What I mean is getAllParameterMatching(**) will try to match every single path by regex. I think it would be faster to load them all and then filter

But matching is performed in .net, right?

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/44d8471562ff53db5fd7134f26f9d3237766a36b/R/utilities-entity.R#L105-L122

This is fast, definitely not the bottle-neck.

> How do I read this perf graph? I see the number of time a method is called but I don't see the overall time

Those are the ms spent on each line. What I try to show here that a great amount of time in spent on formula-related tasks. For each .net-quantity, an r-Quantity is created and "GetFormula" and "self$isTable" (which calls `self$formula$isTable`) takes about 45 seconds each (in total).

**Comment by msevestre** [comment]
self$isTable is 45s ?? WHAT? We are accessing a boolean variable here

**Comment by msevestre** [comment]
There are cleary some stuff to explore. self$isTable just calls self$formula$isTable. This could be cached. However it seems to be only called once anyway. Maybe the call in .NET takes time (I don't understand how)
