### ISSUE TITLE
Which R versions support the R toolbox? R-3.2.3., R-3.5.3. don't work

### ISSUE THREAD

**Issue by irina-antonescu** [Open-Systems-Pharmacology/OSPSuite-R#465]
Hi,

I tried to install the OSPSuite-R-9.1.4 and rClr_0.8.3 packages in R-3.2.3., R-3.5.3.  without luck.

Which versions of R are compatible with the packages?

The readme file states that the latest supported version is R-3.6.3 but it did not work with any of the two previous versions attempted.

Thanks,
Irina

**Comment by PavelBal** [comment]
Dear Irina,

can you describe what exactly did not work? Did you get some errors while installing rClr or ospsuite-r?

**Comment by irina-antonescu** [comment]
Dear Pavel,

I get a message that the packages are not supported by the respective R version.

> install.packages("rClr_0.8.3")
Installing package into ‘\\FSDKHQ001/USERS403$/ZINA/CitrixWork/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘rClr_0.8.3’ is not available (for R version 3.5.3)
> 
> install.packages("ospsuite")
Installing package into ‘\\FSDKHQ001/USERS403$/ZINA/CitrixWork/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘ospsuite’ is not available (for R version 3.5.3)

I get the same for R version 3.2.3.

Irina

**Comment by msevestre** [comment]
@irina-antonescu The packages are not on CRAN
You need to install them from the zip files provided. Please follow the instructions in the readme
https://github.com/Open-Systems-Pharmacology/OSPSuite-R#under-windows

**Comment by irina-antonescu** [comment]
@msevestre oh, yes, of course :-) it worked now when I did it manually from the zip files in version 3.5.3. - thanks for your help

and thanks to you too @PavelBal
