### ISSUE TITLE
Disable "Windows-only" tests if running under Linux

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#467]
If testthat-tests are running under Linux: the tests which currently run only under Windows should be disabled.
Currently those tests are:
* all tests in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/tests/testthat/test-create-individual.R 
* all tests in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/tests/testthat/test-create-population.R
* the test "It can load a simulation whose name contains unicode characters" in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/tests/testthat/test-unicode-support.R (regarding this one: in fact loading simulations with unicode chars in file names does work under Linux. However such files created under Windows and transferred to Linux make problems, because file names are changed then sometimes - nothing what ospsuite-R can fix here. It happens e.g. even if you zip a file on windows and unzip under Linux)

**Comment by msevestre** [comment]
No idea whether we can filter tests or not based on some criteria..

**Comment by msevestre** [comment]
```
Usage
skip(message)
skip_if_not(condition, message = NULL)
skip_if(condition, message = NULL)
skip_if_not_installed(pkg, minimum_version = NULL)
skip_if_offline(host = "r-project.org")
skip_on_cran()
skip_on_os(os)
skip_on_travis()
skip_on_appveyor()
skip_on_ci()
skip_on_covr()
skip_on_bioc()
skip_if_translated(msgid = "'%s' not found")

```
looks promissng

**Comment by msevestre** [comment]
See vignette("skipping") for more details

**Comment by Yuri05** [comment]
yep, `skip_on_os("linux")` should do
