### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#468]
- If you want to see if a vector contains a single value, any(x == 10) is much faster than 10 %in% x because testing equality is simpler than testing set inclusion.
- unlist(x, use.names = FALSE) is much faster than unlist(x).
- A pernicious source of slow R code is growing an object with a loop. Whenever you use c(), append(), cbind(), rbind(), or paste() to create a bigger object, R must first allocate space for the new object and then copy the old object to its new home. If you’re repeating this many times, like in a for loop, this can be quite expensive. You’ve entered Circle 2 of the R inferno.

From https://adv-r.hadley.nz/perf-improve.html

**Comment by PavelBal** [comment]
@msevestre 

In utilities-parameter-value.R, 

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/e3d0b74700559a6d5f68c16b31ee4e677d51bf6c/R/utilities-parameter-value.R#L10-L18

Is there a reason for not using 

`parameterList$units = getPropertyValues(netParameterValues, "Unit")`

?

**Comment by msevestre** [comment]
@PavelBal nope

**Comment by msevestre** [comment]
Are we using `%in% ` a lot in the code?

Item 3 is definitely something we have to be careful. In most cases, (but clearly not all), we are allocated the array or list BEFORE so that we do not have to resize all the time . But we may have missed some cases

**Comment by PavelBal** [comment]
There are not that much places where we are using the above mentioned, I just went through it while doing the same for my internal package. Creating a PR.

**Comment by PavelBal** [comment]
I hate git...
