### ISSUE TITLE
µtants

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#476]
In the UTF-8 there are [**two** possible representations for the µ-symbol](https://en.wikipedia.org/wiki/Mu_(letter)#Character_encodings ):
![grafik](https://user-images.githubusercontent.com/25061876/109641161-b25def00-7b51-11eb-9d1d-a7fb935a7f4d.png)

At the moment, one of those µ-represantations will crash under Linux (surprisingly, not under Windows):
```
> goodMu=rawToChar(as.raw(c(0xc2, 0xb5)))
> badMu=rawToChar(as.raw(c(0xce, 0xbc)))
> goodUnit=paste0(goodMu,"mol/l")
> badUnit=paste0(badMu,"mol/l")
> goodUnit
[1] "µmol/l"
> badUnit
[1] "μmol/l"
> ospsuite::toBaseUnit("Concentration (molar)", 1, goodUnit, 1)
[1] 1
> ospsuite::toBaseUnit("Concentration (molar)", 1, badUnit, 1)
Error in rClr::clrCall(dimensionTask, "ConvertToBaseUnit", dimension,  :
  Type:    System.Collections.Generic.KeyNotFoundException
Message: Key 'μmol/l' could not be found
Method:  OSPSuite.Core.Domain.UnitSystem.Unit <.ctor>b__11_0(System.String)
```

One possible solution: replace the "problematic" representation of µ with another one in all functions which pass units from R to OSPSuite.Core, e.g. via `str_replace` (package `stringr`):

`str_replace(unit, rawToChar(as.raw(c(0xce, 0xbc))), rawToChar(as.raw(c(0xc2, 0xb5))))`

With this replacement it works under Linux as well.
```
> badMu=rawToChar(as.raw(c(0xce, 0xbc)))
> badUnit
[1] "μmol/l"
> badMu=rawToChar(as.raw(c(0xce, 0xbc)))
> badUnit=paste0(badMu,"mol/l")
> badUnit
[1] "μmol/l"
> ospsuite::toBaseUnit("Concentration (molar)", 1, badUnit, 1)
Error in rClr::clrCall(dimensionTask, "ConvertToBaseUnit", dimension,  :
  Type:    System.Collections.Generic.KeyNotFoundException
Message: Key 'μmol/l' could not be found
Method:  OSPSuite.Core.Domain.UnitSystem.Unit <.ctor>b__11_0(System.String)
Stack trace:
  at OSPSuite.Utility.Collections.Cache`2+<>c[TKey,TValue].<.ctor>b__11_0 (TKey key) [0x00010] in <d99f2f269e8b436c8f0d89aa0c881c42>:0
  at OSPSuite.Utility.Collections.Cache`2[TKey,TValue].get_Item (TKey key) [0x00038] in <d99f2f269e8b436c8f0d89aa0c881c42>:0
  at OSPSuite.Core.Domain.UnitSystem.MergedDimensionFor`1[T].Unit (System.String name) [0x00007] in <8edfd9e865a94a9088b9b6b19449810c>:0
  at OSPSuite.R.Services.DimensionTask.convertToBaseUnit (OSPSuite.Core.Domain.UnitSystem.IDimension dimension, System.String displayUnit, System.Nullable`1[T] molWeight, System.Double[] valuesInDisplayUnit) [0x00016] in <44740e0c142a4f5db51aadcfd5818d56>:0
  at OSPSuite.R.Services.DimensionTask.ConvertToBaseUnit (System.String dimensionName, System.String displayUnit, System.Double valueInDisplayU
> library(stringr)
> badUnitReplaced = str_replace(badUnit, rawToChar(as.raw(c(0xce, 0xbc))), rawToChar(as.raw(c(0xc2, 0xb5))))
> badUnitReplaced
[1] "µmol/l"
> ospsuite::toBaseUnit("Concentration (molar)", 1, badUnitReplaced, 1)
[1] 1
```

**Comment by msevestre** [comment]
What do you mean it works as well?

```
Error in rClr::clrCall(dimensionTask, "ConvertToBaseUnit", dimension,  :
  Type:    System.Collections.Generic.KeyNotFoundException
Message: Key 'μmol/l' could not be found
```

Does not look like it's working

**Comment by Yuri05** [comment]
hmm, true, under Windows (without having UTF-8 as default R-encoding) it does not work...

Then the following suggestion: **get the µ-character from the OSPSuite.Core**. Then just replace all possible µ-represenations with this character (no matter how it's encoding looks like).

Thus something like that:

```
library(stringr)

amountDimension <- rClr::clrCall(rClr::clrCallStatic("OSPSuite.R.Api", "GetDimensionTask"), "DimensionByName", enc2utf8("Amount"))
mumolUnit <- rClr::clrCall(rClr::clrCall(amountDimension, "get_BaseUnit"), "ToString")
mu <- substring(mumolUnit, 1, 1)

adjustedUnit <- str_replace(unit, rawToChar(as.raw(c(0xce, 0xbc))), mu)
adjustedUnit <- str_replace(adjustedUnit, rawToChar(as.raw(c(0xc2, 0xb5))), mu)
adjustedUnit <- str_replace(adjustedUnit, rawToChar(as.raw(0xb5)), mu)

```

This worked for me on all (Windows, Linux) systems
Tested with 3 (=hopefully all) representations of µmol/l:

```
unit1 = rawToChar(as.raw(c(0xc2, 0xb5, 0x6d, 0x6f, 0x6c, 0x2f, 0x6c)))
unit2 = rawToChar(as.raw(c(0xce, 0xbc, 0x6d, 0x6f, 0x6c, 0x2f, 0x6c)))
unit3 = rawToChar(as.raw(c(0xb5, 0x6d, 0x6f, 0x6c, 0x2f, 0x6c)))
```

Created units look like below (left: Windows, right: Linux)
![grafik](https://user-images.githubusercontent.com/25061876/109799620-878c9d00-7c1c-11eb-8ede-656abfd4bfc5.png) ![grafik](https://user-images.githubusercontent.com/25061876/109799692-9bd09a00-7c1c-11eb-91b8-830c914de52e.png)

After applying the proposed adjustment: all 3 units are accepted by OSPSuite.Core

**Comment by msevestre** [comment]
@Yuri05 Is it something that can only be done on Linux? Or does it have to be  done on windows as well?

**Comment by msevestre** [comment]
Let's haved .net return the u character directly and store it as constant in the environment so we don't have to retrieve it all the time

**Comment by Yuri05** [comment]
>Is it something that can only be done on Linux? Or does it have to be done on windows as well?

Would do it everywhere, also on Windows.

>Let's have .net return the u character directly and store it as constant in the environment so we don't have to retrieve it all the time

Yep, sounds good.

**Comment by msevestre** [comment]
I just understood the TITLE. LOL :) @Yuri05

**Comment by PavelBal** [comment]
@msevestre That took quite some time :D
