### ISSUE TITLE
Enums to look up units and dimensions

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite-R#478]
It would be useful at the user level to have enums to easily input units and dimensions when needed, and also for these enums to be loaded automatically with the package.

Examples:

To correctly spell dimensions with worrying about, eg, capitalization:
![image](https://user-images.githubusercontent.com/18409098/109980829-52408780-7cce-11eb-82d4-20138e10665d.png)

To avoid typing superscripts and to know what units are available for any given dimension:
![image](https://user-images.githubusercontent.com/18409098/109980987-7ac88180-7cce-11eb-9f34-512d0a493dd3.png)

To know what base units are used may also be useful:
![image](https://user-images.githubusercontent.com/18409098/109981435-e4e12680-7cce-11eb-8956-724eb72b6026.png)

**Comment by msevestre** [comment]
@abdullahhamadeh `getUnitsForDimension` is in ospsuite-r

**Comment by msevestre** [comment]
@abdullahhamadeh Can you give me an ETA for this?

**Comment by abdullahhamadeh** [comment]
PR #499
