### ISSUE TITLE
Why do we need the hardcoded package version in ospsuite-env.R?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#483]
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/05a49f762fbbde20bf592f1f856583730570b7a8/R/ospsuite-env.R#L10

Why do we need this and where is it used?

If it's later used in e.g. log files etc - I would rather expect the full package version given by `packageVersion("ospsuite")`

**Comment by PavelBal** [comment]
It is only used when looking for PK-Sim installation path:

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/05a49f762fbbde20bf592f1f856583730570b7a8/R/utilities-pksim.R#L159

**Comment by Yuri05** [comment]
OK, so it's actually not the version of the "ospsuite" R package but rather the version of PK-Sim which is expected to be used with the current ospsuite-R.
Should we rename the property `packageVersion `to e.g. `pksimVersion `then?

**Comment by PavelBal** [comment]
Yes, makes sense.

**Comment by msevestre** [comment]
This is not the PKSimVerion. This is the "suite version". They just happen to be the same but if we want to export sthg to MoBi, it will be the same version as well. 
R, PKSim, MoBi, ospsuite.core all share the same version. At the time, I did not know how to retrieve the version from the package . I think this is how it should be done and we should not rename this variable
However, we only need X.Y and not the full version

**Comment by Yuri05** [comment]
>R, PKSim, MoBi, ospsuite.core all share the same version. 

If it will be always like this: should we just get "Major.Minor" OSP Suite **dynamically** from the current r-package vesion?
(thus if `packageVersion("ospsuite")` returns "X.Y.Z" - "X.Y" is assumed to be the OSP Suite version)
