### ISSUE TITLE
Expose DataRepository (observedData) to R

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#486]
It should be possible to load a dataRepository from pkml (as exported by mobi or pksim) 
* Time
* Values
* Error 
* ErrorType (arithmetic vs geemoetric)
* TimeDimension
* ValuesDimension

We should aim at having a similar interface as our TableFormula for consistency sake

Also MetaData should be made available as a list of string, values

@PavelBal @Yuri05 @abdelr @StephanSchaller 
Anything else?

**Comment by PavelBal** [comment]
What about units? Or are the values always in default units?

**Comment by Yuri05** [comment]
>What about units? Or are the values always in default units?

The values are stored always in the internal units, but maybe it makes sense to expose the saved UI units?

>TimeDimension

Isn't the TimeDimension always "Time"? Or do you have "general" XY-data repositories in mind?

> Also MetaData should be made available as a list of string, values

Should we distinguish between **string** and **numeric** values in the metadata? Especially when exposing LLOQ/MW/... numerci would make more sense.

**Comment by msevestre** [comment]
>Isn't the TimeDimension always "Time"? Or do you have "general" XY-data repositories in mind?

In general yes. But since DataRepository does support sthg else, why not allow it to be different. Similar to a TableFormula with Dimension and YDimension, we can have something similar. 

Or we restrict it to observed Data with TIME only as XDimension. 

>Should we distinguish between string and numeric values in the metadata? Especially when exposing LLOQ/MW/... numerci would make more sense.

Yes that's why I wrote list of {string, values}. string would be the key, value would be whatever is saved in the system. As far as I know, values can;t be of different type in a list right?

**Comment by msevestre** [comment]
but what should be the interface of the object
```R
obs$value(s) => numeric array
obs$time(s)  => numeric array
obs$error(s)  => numeric array
obs$valueAt(time) => numeric
obs$metaData$studyId => string/numeric
obs$YDisplayUnit ?
obs$XDisplayUnit ?

```

**Comment by PavelBal** [comment]
```
obs$YDisplayUnit  -> string
obs$XDisplayUnit  -> string
```

**Comment by Yuri05** [comment]
>But since DataRepository does support sthg else, why not allow it to be different. Similar to a TableFormula with Dimension and YDimension, we can have something similar.

Agree. Let's then just turn the "TimeDimension" into "XDimension" or "ArgumentDimension".
