### ISSUE TITLE
exportPopulationToCSV

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#489]
Do we need a function to export a population to SCV, as a counterpart to loading from CSV?

```
#' Export a population to CSV that can be loaded in PK-Sim
#'
#' @param population A \code{Population} object to be exported
#' @param pathToCSV Path to the output file
#'
#' @export
exportPopulationCSV <- function(population, pathToCSV) {
  validateIsOfType(population, "Population")
  validateIsString(pathToCSV)

  popDF <- populationAsDataFrame(population = population$population)
  write.table(popDF, file = pathToCSV, row.names = FALSE)
}
```

**Comment by PavelBal** [comment]
It can be re-loaded again or used in PKSim.

**Comment by msevestre** [comment]
it's alredy in 

#' Saves the population to csv file
#'
#' @param population Population to export to csv (typically imported from file using \code{loadPopulation})
#' @param filePath Full path where the population will be saved.
#'
#' @examples
#' csvPath <- system.file("extdata", "pop.csv", package = "ospsuite")
#'
#' # Load the population
#' population <- loadPopulation(csvPath)
#'
#' # Exports the population
#' exportPopulationToCSV(population, tempfile())
#' @export
exportPopulationToCSV <- function(population, filePath) {
  validateIsOfType(population, Population)
  validateIsString(filePath)
  filePath <- expandPath(filePath)
  df <- populationAsDataFrame(population)
  write.csv(df, file = filePath, row.names = FALSE)
  invisible()
}

**Comment by msevestre** [comment]
you are using write.table, we are write.csv
Any difference?

**Comment by PavelBal** [comment]
`write.table` uses spaces to separate  between entries, `write.scv` is more appropriate, I think. Great!
