### ISSUE TITLE
utilities-dimensions

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#490]
I have written a set of methods to support working with dimension, e.g. to also have the ability to convert the units of numerical data that are not a Quantity object (loaded from excel or...). Anything you think may be useful and should be included into the ospsuite-r?
@msevestre 
/cc @abdullahhamadeh 

```
#' Supported dimensions.
#'
#' @include enum.R
#' 
#' @export
Dimensions <- enum(allAvailableDimensions())
```

```
#' Dimension existence
#'
#' @param dimension String representation of the dimension.
#' @details Check if the provided dimension is supported.
#' @export
existsDimension <- function(dimension) {
```

```
#' Unit existence
#'
#' @param unit String representation of the unit
#' @param dimension String representation of the dimension.
#' @details Check if the unit is valid for the dimension.
#' @export
hasUnit <- function(unit, dimension) {
```

```
#' Get base unit of a dimension
#'
#' @param dimension Dimension for which the base unit is returned.
#'
#' @return String representation of the base unit.
#' @export
getBaseUnit <- function(dimension) {
```

```
#' Calculate factor for converting values of one dimension into another
#'
#' @param dimension1 String representation of the first dimension
#' @param dimension2 String representation fo the second dimension
#' @param mw Double value of the molecular weight of the molecule. Used
#' for conversion between molar and mass concentrations. Can be \code{NULL}
#' for other dimensions (default)
#'
#' @return A numerical factor the values of the first dimensions must be multiplied by to
#' be converted to second dimension. The conversion assumes values being in base units
#' of both dimensions.
#' If the values cannot be transformed between the dimensions, an error is thrown.
#' @export
dimensionsConversionFactor <- function(dimension1, dimension2, mw = NULL) {
```

```
#' Get conversion factor from one unit to another
#'
#' @param fromUnit String name of the unit to convert from
#' @param toUnit String name of the unit to convert to
#' @param dimension Dimension of the units
#'
#' @return Numerical value. A value in \code{fromUnit} multiplied  by the factor
#' corresponds to the value in \code{toUnit}
#' @export
unitConversionFactor <- function(fromUnit, toUnit, dimension) {
```

**Comment by msevestre** [comment]
@PavelBal I think this makes sense. 
Why would you need sthg like `dimensionsConversionFactor ` ?

@abdullahhamadeh . You wanted to send a PR For #478 . Any ETA for this?

**Comment by abdullahhamadeh** [comment]
Thanks @PavelBal 

Right now I have only a static list of units for each dimension.  The available list of units for a given dimension could change in future releases.  Is there a way to get this list dynamically?  In the past I have applied allUnits() to all parameters in a simulation, but there is probably a better way to do this straight from the suite.  Something like a list that can be accessed as `allAvailableUnits[[dimension]]`

**Comment by msevestre** [comment]
@abdullahhamadeh What do you mean with static? as if hard coded?
In that case, it is definitely not what we need
You can iterate through all dimensions and get all units for a dimensions .All of that dynamically

**Comment by abdullahhamadeh** [comment]
Yes, that's what I am looking for: a function that takes the dimension as a string and returns the available units.  What is that function?  The inverse of ospsuite::getDimensionForUnit(...)

**Comment by msevestre** [comment]
@abdullahhamadeh This might not be exported. Well it will be available tonight. getAllUnits(dimension) or sthg like this

**Comment by PavelBal** [comment]
>  Why would you need sthg like dimensionsConversionFactor ?

E.g. between molar and  mass concentrations, amounts and mass.

**Comment by PavelBal** [comment]
Implemented.
