### ISSUE TITLE
Unnecessary Debug output in some plot tasks

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#503]
![grafik](https://user-images.githubusercontent.com/25061876/112729467-881f0780-8f2c-11eb-9089-548502269172.png)

Same in plotPKAnalysis-Task
![grafik](https://user-images.githubusercontent.com/25061876/112729655-9ae60c00-8f2d-11eb-9ad0-9d1b7802e505.png)

**Comment by msevestre** [comment]
@pchelle What's `cols`?

Error in cols() : could not find function "cols"
Calls: loadAgingDataFromCSV ... read_delimited -> col_spec_standardise -> as.col_spec
Execution halted

?

**Comment by pchelle** [comment]
cols est une fonction de readr. Peut etre en essayant `readr::cols()` cela devarait fonctionner ?

**Comment by msevestre** [comment]
yep just tried indeed :) works
