### ISSUE TITLE
Error on accessing ospUnits$Fraction$``

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#506]
When trying to access the first value of the Units of "Fraction":

```
>   ospUnits$Fraction$``
Error: attempt to use zero-length variable name
```

**Comment by msevestre** [comment]
@abdullahhamadeh Can you write something so that '' unit is something like empty
e.g. `ospUnits$Fraction$empty`

**Comment by abdullahhamadeh** [comment]
How about "Dimensionless" instead of "empty"?

**Comment by msevestre** [comment]
IT's not the dimension, that's the value fo the unit. So maybe unitless if you want :)
