### ISSUE TITLE
Using hash for performance improvement

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#517]
Consider using [`hash`](https://cran.r-project.org/web/packages/hash/)

Hashed maps, faster search (O(1)), and MUTABLE -> no copy on add!

**Comment by msevestre** [comment]
Where?

And we need to see if we have issues with stuff not using hash in the first place. Nothing like optimization without any good reason;-)

**Comment by msevestre** [comment]
R6 object behaves differently and are typically not copied... we just need to make sure that those changes are meaningful that's all :)

**Comment by msevestre** [comment]
which BTW does not mean that in issue #462 there is no copy going on. It is just that their behavior is different that the typical R object

**Comment by PavelBal** [comment]
Will be done on demand if profiling reveals performance issues.
