### ISSUE TITLE
create-population NOTE

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#522]
# NOTE THIS IS A WORKAROUND UNTIL THE CODE IN PKSIM IS UPDATED

Just found this one - anyone still aware of this?

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/79bc93da81078f57584951fd4e98f0820cb691e4/R/create-population.R#L20

**Comment by msevestre** [comment]
I have to check. I think Age was required in PKSim and no default was used

**Comment by msevestre** [comment]
this is fixed
