### ISSUE TITLE
Release note about addOutputs

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#525]
Add a note that `addOutputs` does not return the set of added quantities any more.

**Comment by PavelBal** [comment]
utilities-output-selections.

@Yuri05 Please let me know when you are writing release notes for V10 (final), we have to add a note about the change in r function.

**Comment by IndrajeetPatil** [comment]
Was this included in v10? If not, should it make it to v11 docs?

**Comment by IndrajeetPatil** [comment]
*bump*

**Comment by PavelBal** [comment]
V11. Obviously, we forgot about this. What would be the best way to proceed? Update the readme an release description now?
