### ISSUE TITLE
AdvancedR

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#54]
http://adv-r.had.co.nz/

@abdullahhamadeh @pchelle @PavelBal 
Well worth reading!

**Comment by PavelBal** [comment]
Indeed, thanks.

**Comment by msevestre** [comment]
There is actually a newer version. The book was JUST published
http://adv-r.hadley.nz/

**Comment by PavelBal** [comment]
Transferred to wiki.
