### ISSUE TITLE
Allow users to create simulation batch without changing any parameter or molecule start values in createSimulationBatch()

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/OSPSuite-R#540]
Allow users to create simulation batch without changing any parameter or molecule start values, i.e. via:

`createSimulationBatch(simulation = simulation, parametersOrPaths = NULL, moleculesOrPaths = NULL)`

Currently, at least one argument (parametersOrPaths or moleculesOrPaths) must not be NULL.

**Comment by msevestre** [comment]
Why?
If you don't vary anything, there is absolutely no use to the batch as all parameters willl be simplified...

**Comment by sfrechen** [comment]
Well, simply because I want to make use of running a set various simulations (different pkml) in a parallelized fashion...

**Comment by PavelBal** [comment]
@sfrechen Check out the function `runSimulationsConcurrently()`, it does exactly what you need. It takes a set of `Simulatin` objects (created from different pkmls or not, doesnt matter) and runs them in parallel.

**Comment by msevestre** [comment]
@sfrechen Yeah ok. Well I think we could do this but as @PavelBal said... runSimulationsConcurrently is probably what you need

**Comment by msevestre** [comment]
Thanks @PavelBal

**Comment by sfrechen** [comment]
Thanks @PavelBal  and @msevestre 

So, do I get it right that `runSimulationBatches()` and and `runSimulationsConcurrently()`  do the same with the only difference that the first one takes a list of simulation objects generated with `createSimulationBatch()`, where at least one paramater or molecule start value needs to be changed and which were loaded before via `loadSimulation()`, and the second one take a list of simulation objects directly generated/loaded by `loadSimulation()`?

Maybe then the terminology is a bit confusing...?!

What is the difference / advantage / disadvantage of the following two work streams (which should produce the same result): 
- `createSimulationBatch()` -> `simulationBatch$addRunValues()` -> `runSimulationBatches()`
- `loadSimulation()` -> `setParameterValues()` -> `runSimulationsConcurrently()`

**Comment by msevestre** [comment]
I think this is some very good feedback and we should make sure the nomenclature is clear before we release.

**Comment by PavelBal** [comment]
I am also struggling with the terminology "simulation batch". As I see it, it is not a batch but simply a kind of "simplified" model. Don't know how to name it, though.

> What is the difference / advantage / disadvantage of the following two work streams (which should produce the same result):
> 
> createSimulationBatch() -> simulationBatch$addRunValues() -> runSimulationBatches()
> loadSimulation() -> setParameterValues() -> runSimulationsConcurrently()

Working with simulation batch only makes sense if you plan to change parameter values more then once. In this case, setting and running the simulation batch is faster than `setParameterValues()` and `runSimulationsConcurrently()`.

**Comment by msevestre** [comment]
The idea behind batch (which is the internal terminology in .NET) was to be able to create one simulation, load it once, and then only update a subset of parameters (without the need to load it again in memory when calculating).
This had nothing to do with parallelism when it was implemented. It was more an efficient way to set and calculate a given simulation, but sequentially

The later additions added the // dimension on top of this.

setParameterValues etc.. always recreate the simulation from scratch. I am wondering if there is a way to unify both behaviours

**Comment by PavelBal** [comment]
@msevestre Can be closed now, rigth?
