### ISSUE TITLE
extend `setParameterValuesByPath` function

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#541]
Extend the function `setParameterValuesByPath` with an optional argument `ignoreNonExisting ` (or something like that).
The new argument should be **false** per default. 
If set to **true**: `setParameterValuesByPath `should skip non existing parameters with a warning and not exit with error.

Such a behaviour might be required in situations like [here](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/497)

**Comment by msevestre** [comment]
going ot use the nomenclature , stopIfNotFound = TRUE, as this is what we have for other methods
