### ISSUE TITLE
New vignette "Efficient calculations"

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#542]
With the new version of ospsuite-R we have at least 5 ways of executing simulations
* set all values in a simulation "manually" (via `setParameterValues`, `setMoleculeInitialValues`, etc.) and exec `runSimulation(sim)`
* load/create a population table and execute `runSimulation(sim, popTable)`
* `runSimulationsConcurrently`
* Create a `SimulationBatch` and run it with modified parameters/initial values
* `runSimulationBatches`

I would suggest to create a **separate vignette explaining the differences between all these options and especially explaining how to run multiple simulations/parameter variations in the most efficient way depending on the use case**.

The experience shows that especially the Matlab-Toolbox users tend to run multiple simulations/parameter variations very inefficiently (because e.g. it's not clear that the current behaviour with "_load simulation; set parameters; simulate_" is internally different from the Matlab "_initSimulation; setParameters; runSimulation_")

**Comment by msevestre** [comment]
This is a very good idea

**Comment by PavelBal** [comment]
Related to https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/540

**Comment by PavelBal** [comment]
Done
