### ISSUE TITLE
Useful shortcuts

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#55]
* Show all shortcuts: `Alt+Shift+K`
* Reload package:` Cmd + Shift + L`
* Navigate to: `Ctrl + .`
* Generate Doc: ` Ctrl + Shift + D`
* Run unit tests: `Ctrl + Shift + T`
* Navigate to implementation: `Mouse over + F2` or `CTRL + Mouse Click`

**Comment by PavelBal** [comment]
- Un-/Comment line/selection: `Ctrl + Shift + C`

**Comment by msevestre** [comment]
- Multi-select: `CTRL+SHIFT+ALT+M` (I almost had a little cry when i found it!)

**Comment by PavelBal** [comment]
Please refer to the wiki https://github.com/Open-Systems-Pharmacology/OSPSuite-R/wiki/Developer-How-To's
