### ISSUE TITLE
OSPSuite-R ERROR in R4.1.0

### ISSUE THREAD

**Issue by yangpluszhu** [Open-Systems-Pharmacology/OSPSuite-R#551]
I am trying to use the OSPsuite using R4.1.0, following the installation guidelines. However, I get the error that the package cannot be loaded. The error message is as following:
> library('ospsuite')
Loading required package: rClr
Loading the dynamic library for Microsoft .NET runtime...
Loaded Common Language Runtime version 4.0.30319.42000

Error: package or namespace load failed for ‘ospsuite’:
 .onLoad failed in loadNamespace() for 'ospsuite', details:
  call: rClr::clrCall(dimensionTask, "AllAvailableUnitNamesFor", enc2utf8(dimension))
  error: 
Then how to handle?
Thank you for your insights!

Kind regards,
Yang

**Comment by PavelBal** [comment]
Did you install the correct [rClr](https://github.com/Open-Systems-Pharmacology/rClr/releases/tag/v0.9.1)?

Is there a more detailed description of the error that you receive?

**Comment by yangpluszhu** [comment]
I have installed rClr_0.9.1.zip for R4, following the installation guidelines. When library(rClr), no error message occurs.

**Comment by yangpluszhu** [comment]
R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> library(rClr)
Loading the dynamic library for Microsoft .NET runtime...
Loaded Common Language Runtime version 4.0.30319.42000

> library(ospsuite)
Error: package or namespace load failed for ‘ospsuite’:
 .onLoad failed in loadNamespace() for 'ospsuite', details:
  call: rClr::clrCall(dimensionTask, "AllAvailableUnitNamesFor", enc2utf8(dimension))
  error: 
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rClr_0.9.1

loaded via a namespace (and not attached):
[1] compiler_4.1.0 R6_2.5.0       magrittr_2.0.1 tools_4.1.0   
[5] stringi_1.6.2  stringr_1.4.0 
>

**Comment by Yuri05** [comment]
duplicated issue (s. https://github.com/Open-Systems-Pharmacology/Forum/discussions/932)
closing
