### ISSUE TITLE
Integer variables not handled by some functions

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite-R#553]
Sometimes observed data are assumed as integer and not numeric variables by R, which crashes the function `toUnit` with the error message below. It could be helpful to enforce integer variables into numeric within functions such as `toUnit` (using `as.numeric` ?)

```
ospsuite::toUnit("Time", as.integer(c(1,2,3)), "h")

Error in rClr::clrCall(dimensionTask, "ConvertToUnit", dimension, targetUnit,  : 
  Type:    System.MissingMethodException
Message: Could not find a suitable instance method ConvertToUnit on type OSPSuite.R.Services.DimensionTask for method parameters String, String, Int32[]
Method:  Void ThrowMissingMethod(System.Type, System.String, System.String, System.Type[])
Stack trace:
   at Rclr.ReflectionHelper.ThrowMissingMethod(Type classType, String methodName, String modifier, Type[] types)
   at Rclr.ClrFacade.InternalCallInstanceMethod(Object obj, String methodName, Boolean tryUseConverter, Object[] arguments)
```

**Comment by Yuri05** [comment]
`ospsuite::toUnit("Time", as.integer(1), "h")` works though...

**Comment by PavelBal** [comment]
Where do you get values that are integer and not numeric from? Just curious what is the use case.

**Comment by pchelle** [comment]
When reading an observed dataset from a csv file and all the values within a column are integers, R assumes that their class is integer and not numeric. 
Since before plotting the data, we need to convert them to a display unit, it creates this crash on some test examples.

**Comment by pchelle** [comment]
More specifically it is usually the time variable of observed data which includes only integers

**Comment by PavelBal** [comment]
@pchelle could you provide an example csv file and the code how you read it?

**Comment by pchelle** [comment]
To read the observed data, RE function is `readObservedDataFile` but it is based on
```
read.csv(fileName,
      header = TRUE,
      check.names = FALSE,
      encoding = "UTF-8"
    )
```

**Comment by pchelle** [comment]
The example is in the zip
[Itraconazole 600mg MD.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/6832024/Itraconazole.600mg.MD.zip)

**Comment by msevestre** [comment]
@pchelle Fixed. Updating reportingengine with this build
