### ISSUE TITLE
Getter/Setter in R ReferenceClass via active binding functions (e.g. for value checks)

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite-R#56]
@msevestre  @PavelBal @abdullahhamadeh @pchelle:
While it seems not be possible to hide fields in R ReferenceClasses, there is a way to use active binding functions to getter and setter functions, which can be used in a convenient way - **exactly like normal fields**.

See therefore the following example:
**Definition**
```R
ClassWithABF <- setRefClass(
  "ClassWithABF",
  fields = list(
    pFileType = "character",
    #ActiveBindingFunction
    FileType = function(value) {
      if (missing(value)) {
         return( pFileType )
      } else {
        if (value %in% c("Data","Model","Document","Script","Other") ) {
          pFileType <<- value
        }
        else {
          pFileType <<- "Other"
          warning(paste0("Unknown FileType = ", value, "; FileType set to 'Other'."), call. = FALSE)
        }
      }
    }
  ),
  methods = list(
    initialize = function() {
      FileType <<- "Other"
    },
    ToJSONObject = function(){
      classFields <- getRefClass()$fields()
      objFieldValues <- list()
      for (fieldName in names(classFields)) 
        if(classFields[[fieldName]] != "activeBindingFunction"){
          objFieldValues[[fieldName]] <- .self[[fieldName]]
        }
      JSONObj <- toJSON(objFieldValues)
      return(JSONObj)
    }
  )
)
``` 
The "private" field pFileType can (unfortunately) accessed from outside, but we could at least forbide it.
Instead just the Field (via active binding function) FileType should be used from outside - pFileType is _only_ used within the active binding function for FileType.

The only exception is: for serialization (here: ToJSONObject) the "private" field is used and _not_ the "activeBindingFunction"  field.

**Usage**
```R
> x <- ClassWithABF()
> x$FileType <- "Model"
> x
Reference class object of class "ClassWithABF"
Field "privateFileType":
[1] "Model"
Field "FileType":
[1] "Model"
> x$FileType <- "model"
Warning message:
Unknown FileType = model; FileType set to 'Other'. 
> x
Reference class object of class "ClassWithABF"
Field "privateFileType":
[1] "Other"
Field "FileType":
[1] "Other"

> x$ToJSONObject()
{"privateFileType":["Other"]} 
``` 

See also http://charlotte-ngs.github.io/RExperimentsWithS4RC/ExperimentsWithS4AndRef.html

**Comment by msevestre** [comment]
I would like to keep this type of usage to a strict minimum as it makes the code much harder to understand.
I think for our purposes, we can live in most cases with simple public fields that could be encapsulated if required.

The .NET wrapper lib will definitely use those but this will be a very limited set of classes

**Comment by PavelBal** [comment]
Close?

**Comment by msevestre** [comment]
Yep
