### ISSUE TITLE
DataSet - check for valid error values

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#566]
- Arithmetic error must be at least 0
- Geometric error must be at least 1

How to handle this, when converting between error types?

**Comment by msevestre** [comment]
I would not. This is the error prerogative to ensure that the data is consistent. Time must be >0 and we do not check this (or maybe we do). Concentration should be >0 typically and we also do not check this

**Comment by PavelBal** [comment]
Then we at least have to check how MoBi will work when trying to import such a data set (create DataSet with negative error in R and export to PKML).

V9 importer does not allow to import error values violating the above mentioned restrictions.

**Comment by msevestre** [comment]
Sure. But shit it, shit out :)

**Comment by PavelBal** [comment]
Ok then let's not bother.
