### ISSUE TITLE
DataSet: remove error column when new values are defined without new error values

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#567]
```
  dataSet <- DataSet$new()
  dataSet$setValues(xValues= c(1, 2, 3, 4, 5), yValues = c(10, 20, 30, 40, 50), yErrorValues = c(0, 1, 2, 3, 0))
  dataSet$setValues(xValues= c(1, 2, 3, 4, 5), yValues = c(10, 20, 30, 40, 50))
```

In this case, the yErrorColumn must be removed from the DataRepository.

Questions:
- How to remove the error column from the "related" columns of the yValues?
- Do we have to somehow dispose the error column .net object?

@msevestre

**Comment by PavelBal** [comment]
@msevestre Any idea? I would like to finish this...

**Comment by msevestre** [comment]
Can you make a PR first in the changes we discussed last week?
