### ISSUE TITLE
How-To: Setup Ubuntu 18.04 VM with R, RStudio, devtools and .net Core

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#57]
# Install Ubuntu
* Download Ubuntu from https://ubuntu.com/download/desktop
* Tutorial: https://www.youtube.com/watch?v=oyNjjzg-UXo
= >This is a very good intro to get ubuntu installed from scratch

# Setup R and R Studio
* Download R studio from [here](https://www.rstudio.com/products/rstudio/download/#download)
At the time of writing: `rstudio-1.2.1335-amd64.deb`

* Then perform the followign commands
```
sudo apt-get install libopenblas-base r-base
sudo apt-get install gdebi
sudo gdebi rstudio-1.2.1335-amd64.deb
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install libssl-dev
sudo apt-get install libxml2-dev libxslt-dev
```

# Install devtools

* Open R studio
* Enter command

```R
install.packages("devtools")
```

You should be good to go!!

**Comment by msevestre** [comment]
And here is how to install dotnet core

https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current

**Comment by Yuri05** [comment]
any reason why 18.04 and not the latest 19.04?

**Comment by msevestre** [comment]
@Yuri05 Because there is no R Studio install for 19.04. Just did not want to take the risk, especially considering that I just want to have a testable environment...not more

**Comment by PavelBal** [comment]
Cool, thanks.

Actually, R-Studio works fine with Ubuntu 19.04.

**Comment by msevestre** [comment]
Awesome. I'll update to 19.4 later then
Whatever we do with our toolbox should work on older Ubuntu version  (18.04 for sure)

**Comment by PavelBal** [comment]
Added to wiki
