### ISSUE TITLE
rClr: arrays of length = 1 not supported in R?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#58]
It seems that there is no possibility to create arrays with one element in R - they are treated as this one element, not the array, i.e., `c(1) == 1`.

This leads to problems with .NET methods that accept vectors, and we want to pass onle one element, e.g. like [here](https://github.com/Yuri05/OSPSuite.FuncParser/blob/5da587f6393efa21b1e8163db2927b29858cddd0/ConsoleApp1/Program.cs#L23):
`pf.SetParametersNotToSimplify(new[] { "p3" });`

```
> clrCall(pf, "SetParametersNotToSimplify", c("p3"));
Error in clrCall(pf, "SetParametersNotToSimplify", c("p3")) : 
  Type:    System.MissingMethodException
Message: Could not find a suitable instance method SetParametersNotToSimplify on type OSPSuite.FuncParser.ParsedFunction for method parameters String
Method:  Void ThrowMissingMethod(System.Type, System.String, System.String, System.Type[])
Stack trace:
   bei Rclr.ReflectionHelper.ThrowMissingMethod(Type classType, String methodName, String modifier, Type[] types)
   bei Rclr.ClrFacade.InternalCallInstanceMethod(Object obj, String methodName, Boolean tryUseConverter, Object[] arguments)
```

I was thinking about creating .NET array objects and filling them with the one value - we could write wrapper functions in R to translate R-arrays (e.g. `c(1,2,3)` or `c(1)`), but I'm failing creating an array object.

I thought of something like this:

```
Type type = Type.GetType("System.String")
arr = Array.CreateInstance(type, 1)
```

However, calling 

`type = clrCallStatic("System.Type", "GetType", "System.String")`

in R returns an object of `System.RuntimeType` and not `System.Type`, which I cannot use for creating an array.

```
> type
An object of class "cobjRef"
Slot "clrobj":
<pointer: 0x000002142e2b7be0>

Slot "clrtype":
[1] "System.RuntimeType"
```

@msevestre @Yuri05 Any ideas how to create an array object?

**Comment by msevestre** [comment]
I don't think this is an issue. The method we use for that will have to use the params or sthg like that. I'll investigate and get back to you
