### ISSUE TITLE
Get seed of population/individual characteristics

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#587]
As an extension of https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/472.

I think it should be also possible to get the seed that is used to create a certain individual/population if a random seed has been used. When is the seed generated (of none passed) - during creation of characteristics or individiaul/populatoin?

**Comment by msevestre** [comment]
yes that can be exposed
