### ISSUE TITLE
getContainers(path)

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#59]
A function that will retrieve information about the container(s) provided with the path. The syntax could be identicall to that of `getParameter `https://github.com/Open-Systems-Pharmacology/2R/issues/19#issuecomment-512061210

### Output: List of containers matching the given path containing:
- Name
- Type
  - "Reaction"
  - "Physical container"
  - "Logical container"
  - "Molecule"
  - "Parameter"
  - "Neighborhood"
  - "PassiveTransport"
  - "ActiveTransport"
- ...

In case of reactions and/or molecules, should the "Type" be different for global/local instances? I.e., "Glucose" as top-level container and "Organism|Kidney|Intracellular|Glucose" as local instance?

**Comment by msevestre** [comment]
@PavelBal I think it should return a list of `Container` and not `Parameters`
They type will be the one defined in Core. Nothing more or less. More specififcally, Physical and logical are not at the same level as Molecule or Reaction

>In case of reactions and/or molecules, should the "Type" be different for global/local instances? I.e., "Glucose" as top-level container and "Organism|Kidney|Intracellular|Glucose" as local instance?

No. The type will be whatever is prescribed by the model.

**Comment by PavelBal** [comment]
@msevestre Yeah, typo...

> They type will be the one defined in Core

What are those?

**Comment by msevestre** [comment]
see here https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/5ff27d3706368ccd574481be3c46b3cf09d32aaf/src/OSPSuite.Core/Domain/Container.cs#L272
