### ISSUE TITLE
Add libraries to support the importer

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#595]
@msevestre @abdelr In order to use the data importer from R, following libraries must be present

NPOI
NPOI.OOXML
NPOI.OpenXml4Net
NPOI.OpenXmlFormats
ICSharpCode.SharpZipLib

And maybe some of their dependencies?

**Comment by msevestre** [comment]
this is done..albeit not compatible with linux
