### ISSUE TITLE
Result structure: In which format should .NET return the results from a simulation run

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#60]
@PavelBal I'd like you to experiment with the best format for the results that we will return from .NET to R

I realized for example that some primitive types such as array are returned out of the box as array. If I return a List<xx> for example, I could not find a way to iterate over the items.

Ideally we will want to create somekind of a data.frame (or data.table) whatever makes more sense (to discuss), with the path of the output as a property so that one can somehow access the result easily for a given output. 

Maybe we could do something like

`res["organism|liver|int|drug|concentration"]` to get the results but this needs to be defined

@PavelBal Can you define what would be the best structure in R to use the result and what would be the best structure in .NET to ensure that we can create the R structure without too much probleems?

Internally, at the moment, the calculated values for one output are stored in the `QuantityValues` object. See [here](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.Core/Domain/Data/QuantityValues.cs) for code

**Comment by PavelBal** [comment]
As proposed in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/106, what we initialize from pkml sould be called `model`.

Now, in .NET, when the model is *simulated*, does the simulation become a new object? I.e., do different objects exist for each simulation run (probably not, it would consume too much memory?)?.

**Comment by PavelBal** [comment]
For the step of transfering the simulations from .NET to R, we could to like this:

- Return an array of `QuantityValues`
- For each `QuantityValues ` (have to iterate from R):
  - Return an array of time values (double)
  - Return an array of values (double)

I still have to think on how we store this in R.

**Comment by PavelBal** [comment]
In R:

Create a class `Simulation`, having the fields "Paths", "YVals", "XVals" (all naming tbd) `simulateModel(model)` will return an object of `Simulation`. Getting a result can be then done by `getSimulationResults(path, Simulation)`, which will return a list (or lists for multiple paths) with two vectors for time and values. The name of the entry(ies) is the path.

Ideally, we should be able to use the same path construction logic as everywhere, however I am not sure how. Either first call .NET to retrieve all paths (just return the pathts, not the entities themselves) matching the provided construct, and then search of these paths are present in `Simulation$paths`, or...

Maybe we should discuss it on the phone.

**Comment by msevestre** [comment]
There is an implementation available at the moment implemented in #169. Let's reopen a new issue if required
