### ISSUE TITLE
going ahead use a NEWS file to catalog changes

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#613]
Currently, the way a user needs to figure out changes made since the last [release ](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/releases)is to go through all closed GitHub issues since the last release, read them, and then understand both the problem and the implemented solution. This puts a lot of burden on them.

Going ahead, we can instead use `NEWS.md` to keep a log of new changes made to the package.

**Comment by msevestre** [comment]
Well let's start with this update...shall we?
