### ISSUE TITLE
Latest build failing

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#618]

**Comment by msevestre** [comment]
interesting

**Comment by PavelBal** [comment]
Checking it out now

**Comment by PavelBal** [comment]
OK found it, I used `ospUnits$`Concentration (mass)`` in some tests, those are failing as the `(` has been replaced by `[`

**Comment by msevestre** [comment]
cool

**Comment by PavelBal** [comment]
Damn I hate R's stubbornness regarding unicode!
```
ospUnits$`Concentration [mass]`$`µg/l`
```

does not work in tests because tests are run in non-utf!!!! ospUnits$`Concentration [mass]`$`µg/l` is therefore always `NULL`

**Comment by msevestre** [comment]
Just used another unit lol

**Comment by PavelBal** [comment]
Damn I think way too complex :D
