### ISSUE TITLE
How to unload a loaded assembly from R studio

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#63]
@PavelBal AT the moment, I am closing R studio everytime so that I can swap out dlls. Is there a better way?

**Comment by PavelBal** [comment]
There is no way to unload an assembly.

However, you can restart your R session by calling
`.rs.restartR()`

This way it will release the loaded assemblies but retain the environment (variables, loaded functions, etc).

This only works from RStudio, but should be sufficient for development.
