### ISSUE TITLE
Reorder vignettes so that they appear in the right order in docu

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#635]
see https://github.com/Open-Systems-Pharmacology/docs/issues/144#issuecomment-931714363

@Yuri05 How would you like it to be?>

**Comment by IndrajeetPatil** [comment]
You can arrange `vignettes` and `reference` pages by topics using `_pkgdown.yml`.

For an example, see:
https://github.com/IndrajeetPatil/ggstatsplot/blob/6712a5d6e35cae0e571734caf1fbdfc859291aa0/_pkgdown.yml#L73-L102

And the rendered website is here:
https://indrajeetpatil.github.io/ggstatsplot/

Additionally, the `reference` section on the website also needs to be cleaned up such that the functions that belong together should have their own subsection. For example, see: https://indrajeetpatil.github.io/ggstatsplot/reference/index.html
This makes navigation much easier.

This discussion is actually relevant for **all** `R` package websites in the OSP. Unfortunately, I don't know all the functions well enough for me to make these changes, and someone who is more in the weeds with these functions can create the relevant families of functions.

**Comment by Yuri05** [comment]
I would suggest the following order:

1. Introduction to ospsuite
2. Loading a simulation and accessing entities
3. Changing parameters and molecule start values
4. Running a simulation
5. Calculating PK Parameters of simulation outputs
6. Sensitivity analysis
7. Creating individuals
8. Population simulations
9. Efficient calculations
10. Table parameters
11. Dimensions and units

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/135642491-05e8b4a0-0178-4ca3-aa7d-09013b81e560.png)

**Comment by Yuri05** [comment]
very nice!

**Comment by IndrajeetPatil** [comment]
Another cool thing we can do is have a separate entry on homepage from the introductory vignette, which will titled as "Get Started":

![image](https://user-images.githubusercontent.com/11330453/135650041-6b08e3e5-ea2e-4a97-ab2c-02ff1e336e89.png)

If you like this, I can make a PR :)

**Comment by msevestre** [comment]
yes please. HAvign the Getting started more visible is important IMO

**Comment by msevestre** [comment]
awesome!

**Comment by IndrajeetPatil** [comment]
The trick is to have the same name for the vignette as the package name. That vignette will be automatically rendered as "Get Started".
