### ISSUE TITLE
inconsistent behavior between runSimulationBatches and runSimulation

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite-R#646]
[debug_simbatch.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/7340084/debug_simbatch.zip)

Attached in the zip file are two similar simulations.

In the attached script, the output path is set to be the same in each simulation.  

A parameter with the same path is set to the same value in each simulation, first using `simbatch$addRunValues` (for a simulation batch) and then using `setParameterValuesByPath`.  

For both simulations, `runSimulation` runs the simulation as expected after modification of the parameter using `setParameterValuesByPath`.  

However, `runSimulationBatches` produces `NULL` with one of the simulations (when `not_ok_sim_flag <- TRUE`), but not the other one (when `not_ok_sim_flag <- FALSE`).  This is after modification of the parameter using `simbatch$addRunValues`.

In the case of `not_ok_sim_flag <- FALSE` (ie when both `runSimulation` and `runSimulationBatches` run the simulation successfully), the results from the two methods are the same (as expected).

**Comment by msevestre** [comment]
'DERMAL_APPLICATION_AREA|skin_compartment|SC_skin_sublayer|comp10_1|layer1|permeant'  seems to be a molecule. In that case, you need to set InitialValue and not Parameter

**Comment by msevestre** [comment]
I am baffled as to why it would work with the other simulation...

**Comment by msevestre** [comment]
@Yuri05 This happens in SimModel
![image](https://user-images.githubusercontent.com/1041237/137372766-32a5cb89-6f5b-49c8-a7b8-3e38e553c430.png)

No values is being returned for the successful simulation

**Comment by msevestre** [comment]
All right I foudn the issue
This has nothing to do with SimModel. It has do to with the fact that the persistable flag is not updated in batch mode

**Comment by abdullahhamadeh** [comment]
> @abdullahhamadeh Workaround:
 
Just to clarify, does the order they are run in make a difference?

**Comment by msevestre** [comment]
Yes. It does because the first method sets the output properly (e..g what should be exported). So running the simulation is not important but calling the method is. This is a bug in core.

**Comment by msevestre** [comment]
and running simulation should only be done once. Once the simulation flag is set properly, this is persisted so there is no need to do it again

**Comment by msevestre** [comment]
@abdullahhamadeh Check it out here
https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-r/build/artifacts

**Comment by msevestre** [comment]
both bugs should be fixed, compatible with ospsuite v10
