### ISSUE TITLE
Documentation that should not be exported

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#653]
Some functions/enums/R6 classes should not appear in the documentation by using 

`#' @keywords internal`

- AllMatchingMethod
- AllPathsInMethod
- ApiConfig
- Cache
- DotNetWrapper
- encodeUnit
- getNetTask
- getPropertyValue
- getPropertyValues
- ifNotNull
- initPackage
- netEnumName
- ObjectBase
- getDimensionsEnum
- getUnitsEnum
- parameterValueListFrom
- Printable
- toList
- toObjectType
- toPathArray
- toPathString
- .getConcurrentSimulationRunnerResults
- .getPathToPKSimInstallDir
- .getPathToPKSimInstallDirFromFileSystem
- .getPathToPKSimInstallDirFromRegistry
- .ImporterErrorTypeToDataSetErrorType
- .loadDataRepositoryFromPKML

@msevestre please check if you agree

**Comment by IndrajeetPatil** [comment]
These have already moved to the utils package:

Printable
toList
toObjectType
toPathArray
toPathString
ifNotNull

I am exporting PathArray and toPathString for now because they are needed in vignettes.
