### ISSUE TITLE
improve printing of PK parameters for `SensitivityAnalysisResults` object

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#655]
Referring to `C_maxt_maxC_tEndAUC_tEndThalfAUC_infMRTFractionAucLastToInf` in the output here:

```r
# Load simulation
simFilePath <- system.file("extdata", "simple.pkml", package = "ospsuite")
sim <- loadSimulation(simFilePath)

# Create a `SensitivityAnalysis` with all constant and suitable for sensitivity calculations parameters and suitable for sensitivity calculations parameters
sa <- SensitivityAnalysis$new(simulation = sim)

# Run the sensitivity analysis
saResult <- runSensitivityAnalysis(sa)
print(saResult)
#> SensitivityAnalysisResults: 
#>   Number of calculated sensitivities: 72
#>   Available PK parameters: C_maxt_maxC_tEndAUC_tEndThalfAUC_infMRTFractionAucLastToInf
```

A space between two parameters should make it more legible.

**Comment by PavelBal** [comment]
This is a general problem with printing all properties that have more than one entry. Must be fixed somewhere in `Printable`
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/R/printable.R

**Comment by IndrajeetPatil** [comment]
I _think_ setting `sep = " "` should solve this:

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/1578f2524fef2e2d2d3bd7ce55cae34ce491d91c/R/printable.R#L16

Will make a PR if it does.

**Comment by msevestre** [comment]
>Hard to avoid this given how the code is currently structured:

I don't understand. Why can't we fix the issue? All classes implement the printable class. Can't we just create an overload, (or add more parameters to the printLine method as we like to do it in R) to print the stuff properly? Or how should we structure this to make this work?

**Comment by IndrajeetPatil** [comment]
Figured out how to fix this in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/658. There was a bug in the existing code that was throwing me off before 😅

**Comment by IndrajeetPatil** [comment]
I should mention that I have also updated the copy of this function in `{ospsuite.utils}`.
https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/blob/main/R/printable.R
