### ISSUE TITLE
Use `{ospsuite.utils}`

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#660]
Should not we start doing this? @IndrajeetPatil

**Comment by IndrajeetPatil** [comment]
I was thinking that I would get this on CRAN first, and then we start removing the respective functions from here? 

See: https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/issues/4

**Comment by msevestre** [comment]
sounds good

**Comment by msevestre** [comment]
The build is broken

**Comment by IndrajeetPatil** [comment]
?

![image](https://user-images.githubusercontent.com/11330453/146194789-123d6b91-564e-426e-8b07-e291af203a36.png)
