### ISSUE TITLE
Memory overhead for R Wrapper objects

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#67]
@PavelBal Let see if we need to worry about them or not (see discussion in #19 )

**Comment by PavelBal** [comment]
Note to myself - maybe setting
`r_object <- NULL`
will be enough.

**Comment by PavelBal** [comment]
I did some initial profiling and it looks like we should at least put some effort in trying to re-use objects (R or .NET).

Example: 
Getting the same parameter given by its full path 1000 times:

```
  for (i in 1 : 1000){
    parameter <- get_parameters(c("Organism", "Age"), sim)
  }
```

![image](https://user-images.githubusercontent.com/25903040/61873091-577c0480-aee5-11e9-93d9-4cea365ed889.png)

Takes 2.5 seconds, with most of the time (1.5 sec) spent on creating `container_task`.

Getting a set of parameters that match some path:

```
for (i in 1 : 1000){
  parameters <- get_parameters(c("Organism", "liv*", "**", "*norm*"), sim)
}
```

![image](https://user-images.githubusercontent.com/25903040/61873680-d160bd80-aee6-11e9-8c56-179191e06f2e.png)


This takes 47 seconds and consumes quite some memory (that is, however, released after the execution). This time, `container_task` takes 6.5 seconds, 25 seconds are spent for getting the parameters from .NET (`allParametersMatching`), and another 15 seconds (and up to 260 MB) are spent on creating R-object of the type `Parameter`.

Now, creating `container_taks` only once and putting it into the global workspace (later on we could put it somewhere else) within the `init.package`:

`container_task <<- clrCallStatic(typename =  "OSPSuite.R.Api", methodName = "GetContainerTask");`

```
  for (i in 1 : 1000){
    parameter <- get_parameters(c("Organism", "Age"), sim)
  }
```
Gettin 1000 parameters by full path takes less then a second, most of the time for creating R-objects:

![image](https://user-images.githubusercontent.com/25903040/61873650-bf7f1a80-aee6-11e9-9767-743939bac911.png)

```
for (i in 1 : 1000){
  parameters <- get_parameters(c("Organism", "liv*", "**", "*norm*"), sim)
}
```

Getting 1000 parameters that match the given path takes 41 seconds, so we saved "only" 6 seconds (exactly the time that was spent on creating `container_taks`):

![image](https://user-images.githubusercontent.com/25903040/61873834-2dc3dd00-aee7-11e9-89d6-a0870cb7a681.png)

With 16 seconds for creating R-Objects.

**Comment by msevestre** [comment]
this is AWESOME!! Can you write an entry somewhere (wiki for example in the repo) on how to get such profiling results? So cool. Well done

Now: As soon as we have some * in the path, the algorithm I implemented will check the whole tree to be able to compare actual parameter path with actual expression given. That means that in your case, the whole simulation tree will be called 1000 times. That explains the 16sec in the .NET call. I don't think it's that bad since it is very unlikely to do something like that

Also even on the R side, do you think this will be an issue? User can very easily hold a reference to the object that they retrieve to store the value. Even for a PI etc.. That would be retrieved one and passed along as a parameter.

What I learn from that is: Creating .NET <=> R Object is somewhat expensive and we should make sure we do not do it if not required. Having a global for ContainerTask might be a good way to save some time. We could also make the instance singleton in .NET and see if this makes a difference

Last: What version of the code are you using? I updated the code two days ago to use R6 class instead of RC. I'd like to see if this makes a difference

**Comment by msevestre** [comment]
if you take the code from `https://github.com/PavelBal/rDotNet_feasibility/tree/get-parameters` which is using the R6 class, can you try again?

**Comment by PavelBal** [comment]
> this is AWESOME!! Can you write an entry somewhere (wiki for example in the repo) on how to get such profiling results? So cool. Well done

Actually quite easy: https://support.rstudio.com/hc/en-us/articles/218221837-Profiling-with-RStudio
This repo does not have a wiki - maybe you can enable it and we can move all the useful information (e.g. the shortcuts) there?

> Also even on the R side, do you think this will be an issue? User can very easily hold a reference to the object that they retrieve to store the value. Even for a PI etc.. That would be retrieved one and passed along as a parameter.

I don't think users will actually think of holding a reference and re-using it, most of the time they would just call "getParameter()$Value". I don't think it is such a big issue, but we still have to pay attention for ourselves that we do not unnecessaryli generate objects..

> Last: What version of the code are you using? I updated the code two days ago to use R6 class instead of RC. I'd like to see if this makes a difference

Yes, I'm using the last version with R6 classes.

**Comment by msevestre** [comment]
wiki: done

> most of the time they would just call "getParameter()$Value".

In that case there is not much we can do....

**Comment by PavelBal** [comment]
I played around with caching R-objects into a global environment created in `init.package`

`rParameterObjectsCache <<- new.env(hash=T, parent=emptyenv())`

And checking if an R-object already exists for the id of the .NET parameter:


```
to_parameters <- function(netParams) {
  sapply(netParams, function(p){
    p_id <- clrGet(p, "Id")
    
    r_param <- rParameterObjectsCache[[p_id]]
    
    if (is.null(r_param)){
      r_param <- Parameter$new(p)
      rParameterObjectsCache[[p_id]] <<- r_param
    }
    
    return(r_param)
  }
    )
}
```

![image](https://user-images.githubusercontent.com/25903040/61879433-4df99900-aef3-11e9-8383-4bf293ea12df.png)

The time is reduced to 27 seconds and the memory consumption to 60MB (from 180).

Will have to check what implications it has on scenarios where different parameters (and not the same one resp. the same set of parameters) is retrieved multiple times.

**Comment by msevestre** [comment]
I am wondering WHY memory consumption is not the same.... if the objects were released properly, it should not make any difference

>Will have to check what implications it has on scenarios where different parameters (and not the same one resp. the same set of parameters) is retrieved multiple times.

Not sure I understand that. What do you mean?

**Comment by PavelBal** [comment]
> I am wondering WHY memory consumption is not the same.... if the objects were released properly, it should not make any difference

Maybe the objects are released after the 1000x loop? In this case, new objects are created without the cache, but are created only once with...

`Not sure I understand that. What do you mean?`
Well now I'm retrieving the same parameters 1000x. Will have to check how big is the overhead if I retrieve multiple parameters one-by-one..

Also, is it safe to check for the ID of the .NET parameter? Could it change ?

**Comment by msevestre** [comment]
`Id` is safe. No one should change it. We could make it a prop of an object as `get` from the object base wrapper class.

also what does `new.env(hash=T, parent=emptyenv())` do?

**Comment by PavelBal** [comment]
Creating a data structure `Environment` that is best suited for the HashMap-like structure. It also automatically uses the hash of the "keys".

**Comment by msevestre** [comment]
ah I got it. T = TRUE . lol. I though it was the type of the element in the hash. (generic)

**Comment by PavelBal** [comment]
I think we can close this now. Will have to profile from case to case.
