### ISSUE TITLE
API proposal for bridging `{ospsuite}` and `{tlf}` packages

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#674]
Based on discussion with @msevestre, @PavelBal, @pchelle, @Yuri05   

Adopt a functional approach to create plots using `{tlf}` with a few arguments and sensible internal defaults. 

The primary argument would be an R6 object encapsulating both simulated and observed data from `{ospsuite}`.

![plotProposal](https://user-images.githubusercontent.com/11330453/144883501-d519efdf-b4e4-4b49-a914-b6951b70e59d.jpg)

As to which arguments these plots should have remains to be decided (see the comment below with possible arguments).

@PavelBal Sorry creating issue now since need to go to sleep soon 😅

**Comment by IndrajeetPatil** [comment]
Possible arguments:

- xUnit
- yUnit

**Comment by msevestre** [comment]
Here my pseudo code from this morning

```


cb <- CombinedData$new(SimulationResults, DataSet)...needs to be defined
cb.Color red


IN OSPSUITE-R

plotTimeProfile(cb, xUnit="min", yUnit="mg/l",   plotConfiguration){

	1. create TLF dataObject (using, cb converting values from baseUnit to xUnit and yUnit)
	2. Create MetaData on the fly (baseGrid, x, concentration y) specify the unit (xUnit, and yUnit)
	3. Create your PlotConfiguration(TLF) using the properties
	4. observedDataMapping and observedDate (from cb) unit conversion also happpening
	5. color <- red

	return tlf::plotTimeProfile(data, metadata....)


plotPredVsObserved(cb,){


}

**Comment by IndrajeetPatil** [comment]
Steps needed:

- [ ] implement `DataCombined` objects (containing simulation results, observed data, and grouping information)
- [ ] implement `plot*()` functions

**Comment by IndrajeetPatil** [comment]
Plots needed:

- [ ] histogram
- [ ] boxplot
- [ ] DDI plot
- [ ] tornado plot
- [ ] PK ratio plot
- [ ] concentration profile plot
- [ ] observed versus predicted plot
- [ ] residuals versus predicted plot

**Comment by PavelBal** [comment]
- `DataCombined` should allow to set scale factors and offsets for data (x and y values)
- `DataCombined` should have a method `toDataFrame` that returns a data frame with all data sets and additional information specified (like dimension, unit, offsets, scale factors, meta data)

Following plot types are prio one:
### - `individualTimeProfilePlot()`
![image](https://user-images.githubusercontent.com/25903040/145016607-ae291077-5c49-4cb7-8532-90c432800ba7.png)

_Optional arguments_:

- Main title
- x limit
- y limit
- x lin/log
- y lin/log
- x axis label
- y axis label
- x unit
- y unit
- legend on/off
- legend position
- for each data set: 
  - type (symbols, lines, both)
  - symbol type
  - line type
  - color

### - `aggregatedTimeProfilePlot()`
![image](https://user-images.githubusercontent.com/25903040/145016764-c5e036d5-e85e-4bec-905a-4e677baae209.png)

_Optional arguments_:

- Main title
- x limit
- y limit
- x lin/log
- y lin/log
- x axis label
- y axis label
- x unit
- y unit
- legend on/off
- legend position
- for each data set: 
  - type (symbols, lines, both)
  - symbol type
  - line type
  - color
  - **Plot individual or aggregated**
    - By default, simulation results are plotted aggregated, data as individual points. But the user might want to also plot data as quantiles
 - quantiles

### - `predictedVsObservedPlot()`
![image](https://user-images.githubusercontent.com/25903040/145018658-14443721-6444-455b-bba6-a7dbd8e146ff.png)

_Optional arguments_:

- Main title
- axes limit
- axes lin/log
- x axis label
- y axis label
- values unit
- legend on/off
- legend position
- for each data set: 
  - symbol type
  - color
- foldDistance - numerical values for the fold-distance lines to be drawn. Default is 2, multiple fold-distance lines can be specified
- timeDiffThreshold - Allowed difference between observed and simulated time values in minutes. Default is 10 minutes. If for a certain observed point no simulated time point exists within the defined threshold, the value is not considered. Can be discussed if this can be solved differently.

Following plot types are prio two:
### - `residualsVsTimePlot()`
![image](https://user-images.githubusercontent.com/25903040/145019864-d66601a0-4caf-42a4-a189-7c7fc6739174.png)

_Optional arguments_:

Will be specified when we are about to implement this. Especially the objective function (how to calculate residuals).

### - `pkRatioPlot()`
This requires other type of input data, `DataCombined` is not the right concept for this.

### - `guestPlot()`
https://github.com/Open-Systems-Pharmacology/Reporting-Engine/issues/99
This requires other type of input data, `DataCombined` is not the right concept for this.



multi panel

**Comment by PavelBal** [comment]
## Additional requirements:

- Output of plots to PNG (incl. providing resolution and file path)
- Plotting multiple plots in one panel
![image](https://user-images.githubusercontent.com/25903040/145020778-3bd34b92-b0d0-407f-b795-76adbb697672.png)

**Comment by Yuri05** [comment]
@PavelBal 
>DataCombined should allow to set scale factors and offsets for data (x and y values)

scale factors?? is this meant as unit conversion factors or what for?

**Comment by PavelBal** [comment]
> scale factors?? is this meant as unit conversion factors or what for?

More like normalization of data. Use case - observed data is given in % from maximal signal. With scale factors, it will be easy to "convert" simulated results (e.g. plasma concentration) by setting the conversion factor to 1/maxValue. With this we can easily plot such observed data and simulated results together.

Another use case - observed data are heterogenous (example glucagon - different assays have been used measuring different entities). We cannot use the absolute values but are interested in the observer % change - we can normalize the data using the scale factors.

Last but not least - very efficient way to plot data normalized to dose ;)

**Comment by Yuri05** [comment]
ok, thx for the clarification

**Comment by PavelBal** [comment]
@msevestre @IndrajeetPatil 


Basically, `DataCombined` needs to support two scenarios:

1. Adding `DataSet`
    - dataCombined$addDataSets(dataSets, groups = NULL), where `dataSets` is a single `DataSet` or a list of `DataSet` objects, and `groups` is a list of strings defining the groupings. The names under which the `DataSet` will be stored (and used e.g. in the caption) should be the `name` property of the `DataSet`.
2. Adding simulation results. Now it becomes more tricky. The user would not only provide the `SimulationResults` object, but also the paths, and maybe even individual Ids.
    - `dataCombined$addSimulationResults(simulationResults, paths, individualIds = NULL, groups = NULL)`. `individualResults` in this case should be only one object, not a list. Now, what about the names? We could use the path as the name by default, but in that case adding results from different simulation runs will become a problem. The user has to specify the name? E.g.
    - `dataCombined$addSimulationResults(simulationResults, paths, individualIds = NULL, names, groups = NULL)`.

This is also why I would prefer to add data with methods only, and not in the constructor. Otherwise the constructor get way too many arguments. The most simple workflow would then be:

```
dataCombined <- DataCombined$new()
dataCombined$addDataSets(dataSets)
dataCombined$addSimulationResults(simulationResults, "Organism|VenousBlood|Plasma|CompoundA|Concentration")
```

- Every entry (whether it is an added `DataSet` or simulation result) must have a unique name. With this name, the user can set scale factors and offsets.

And now the most important questions - how to store simulation results internally? The easiest way would be to convert them to `DataSet` on adding, but I see @msevestre point that for population simulation that would create just too many `DataSet` objects. We could create a data frame for each output path and populate it with all necessary information (dimension, unit, molecular weight, maybe even organ/compartment).

**Comment by IndrajeetPatil** [comment]
Note to self:

- Add warnings to add*() methods if the names argument provided are already present in the dataset
- For simulationResults, if names is NULL, paths are used internally as unique id

**Comment by PavelBal** [comment]
@IndrajeetPatil 

The argument names in `setDataTransforms` should be in plural, I think

```
x$setDataTransforms(
  names = list("name1", "name2"),
  xOffsets = c(30, 20),
  yOffsets = c(20, 0),
  xScaleFactors = 2,
  yScaleFactors = c(1.5, 2)
)
```

**Comment by IndrajeetPatil** [comment]
To discuss: 

- [ ] Should there be a `$print()` method? If yes, what should it print? (I think we should print only the names of the datasets and the current group map, i.e., basically just print the `$groupMap` binding output.)
- [ ] Which datasets to use in manual examples and vignettes? I couldn't find anything appropriate in `inst/extdata` folder. Can a few of the datasets from `tests/data` folder moved to `inst/extdata`? The largest file (`Stevens_2012_placebo_indiv_results.csv`) is 1.2 MB.
- [ ] Should we have the same `names` argument across three different methods, where it means different things? I've named them like this because Pavel wanted them so. But I personally think that when the argument provides alternate names for datasets (in `$addSimulationResults()` and `$addDatasets()`), the argument can be called `newNames`, while when it is used to filter certain datasets for data transformation (in `$setDataTransformations()`), it can be called `includeNames`.  
- [ ] Active bindings are all getter methods. Should they have a naming pattern of `get*()`?
- [ ] Include some private utility methods as functions in utilities package, since they have a more general scope of application.

**Comment by PavelBal** [comment]
> allows list inputs in $addSimulationResults()

The current signature is 
```
addSimulationResults(simulationResults,
                                    quantitiesOrPaths = NULL,
                                    population = NULL,
                                    individualIds = NULL,
                                    names = NULL,
                                    groups = NULL)
```

`quantitiesOrPaths`, `population`, and `individualIds ` could be different for every `SimulationResult`, so, in case we want to support multiple `SimulationResults`, those arguments should also be lists (resp. lists of lists...). I really do not like such an API, it would be too heavy.

Additionally, if two different `SimulationResults` are added using the same paths, the user **must** provide `names`, otherwise the data will be overwritten (as the default names are the paths..).

**Comment by IndrajeetPatil** [comment]
Sounds perfectly reasonable. 

I just needed to have the rationale written down somewhere for the posterity.  Will include this in the comments.

**Comment by PavelBal** [comment]
> Active bindings are all getter methods. Should they have a naming pattern of get*()?

No, active bindings are **no** methods :D They are accessed without `()`, so I would not name them the the `get` prefix.

**Comment by IndrajeetPatil** [comment]
> active bindings are no methods

Sorry, poor phrasing on my part. 

I mean, these bindings are a quick way to get the precomputed values from the object, which is what usually the getter methods do, and that's why I was thinking of these names. Does that make sense?

**Comment by msevestre** [comment]
I agree with Pavel. 
`obj$name` vs `obj$getName`
The get set nomenclature comes probably from a time (this is me assuming this) where we had no set get built in the language. 

Now if you have a method that returns something, you can call  use a prefix get/retrieve/fetch etc..

**Comment by PavelBal** [comment]
`DataSet` can have an empty name (e.g. create a new one with `dataSet <- DataSet$new()`. Not sure what to do in this situation:

**Comment by msevestre** [comment]
is this a problem ? name can be null (or "") not sure what makes more sense

**Comment by IndrajeetPatil** [comment]
Currently, in this situation, empty dataframes will be returned:

``` r
library(ospsuite)
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000

dataset <- DataSet$new()
myCombDat <- DataCombined$new()
myCombDat$addDataSets(dataset)

myCombDat$toDataFrame()
#> # A tibble: 0 x 14
#> # ... with 14 variables: name <chr>, group <chr>, dataType <chr>,
#> #   xValues <dbl>, xUnit <chr>, xDimension <chr>, yValues <dbl>, yUnit <chr>,
#> #   yDimension <chr>, yErrorValues <dbl>, yErrorType <lgl>, yErrorUnit <lgl>,
#> #   molWeight <lgl>, lloq <lgl>

myCombDat$dataTransformations
#> # A tibble: 0 x 5
#> # ... with 5 variables: name <chr>, xOffsets <dbl>, yOffsets <dbl>,
#> #   xScaleFactors <dbl>, yScaleFactors <dbl>

myCombDat$groupMap
#> # A tibble: 0 x 3
#> # ... with 3 variables: group <chr>, name <chr>, dataType <chr>

myCombDat$names
#> character(0)
```

<sup>Created on 2022-01-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by PavelBal** [comment]
All data added to a `DataCombined` must have some unique identifier (we call it `name`). This allows e.g. to set data transformations for this data set.
We use the `$name` property from `DataSet` when adding a `DataSet` as the default name, for simulation results these are the paths of the added outputs. The user can also set custom names.

So adding a `DataSet` with an empty name will now results with it`s name being empty and therefore... Well, not a unique identifier.

**Comment by IndrajeetPatil** [comment]
> So adding a DataSet with an empty name will now results with it`s name being empty and therefore... Well, not a unique identifier.

I think I am confused because I don't understand the context in which this might occur, or what's the use case for this. But why should something that doesn't exist get a unique identifier? 

My understanding is that if there is no `name` associated with a `DataSet` object, it just means that there is no data in the object to be uniquely identified. Am I wrong in my understanding?

**Comment by msevestre** [comment]
>My understanding is that if there is no name associated with a DataSet object, it just means that there is no data in the object to be uniquely identified. Am I wrong in my understanding?

I agree with this. This is how I understand the object

**Comment by PavelBal** [comment]
```
> myDs <- DataSet$new()
> myDs$setValues(xValues = c(1,2,3), yValues = c(2,3,4))
```

A perfectly valid `DataSet` without a name, no?

**Comment by msevestre** [comment]
>Also - do all DataRepository coming from PKSim/MoBi always have a name?
YEs. This is what is being displayed in the tree. If it's emopty, someone messed around with the pkml file

>Maybe we should make the name a requirement when creating DataSet from scratch?

Yes! but how can you enforce it if you do not want to force the user to specify a name in the constructor.
Alternatively, the name is assigned as a GUID when created and overwritten when created via repo or simresults

**Comment by PavelBal** [comment]
> Yes! but how can you enforce it if you do not want to force the user to specify a name in the constructor.
> Alternatively, the name is assigned as a GUID when created and overwritten when created via repo or simresults

I would be OK forcing the user to specify the name when creating an empty `DataSet`.

**Comment by msevestre** [comment]
Oh is data a parameter in constructor?

**Comment by PavelBal** [comment]
Where? `DataSet`? No, `DataSet` is either created empty or from a `DataRepository`.

**Comment by IndrajeetPatil** [comment]
We need to keep this open till we implement the plotting methods around `DataCombined`.

**Comment by IndrajeetPatil** [comment]
I will keep updating references in this comment to the discussions as they are opened:

- `plotPredictedVsObserved()`: https://github.com/Open-Systems-Pharmacology/OSPSuite-R/discussions/809

**Comment by IndrajeetPatil** [comment]
@PavelBal, @Yuri05, @StephanSchaller   

Out of possible scatter plots, we currently have:

- Observed versus Predicted
- Residuals versus Time

But **not** 

- Residuals versus Predicted

Is it not useful? _tlf_ does support this plot (`plotResVsPred()`), so it should be straightforward to implement in _tlf_ as well.

**Comment by Yuri05** [comment]
I think it is useful :)

**Comment by PavelBal** [comment]
Yes, but very low prio.

**Comment by IndrajeetPatil** [comment]
It's already implemented in #1036.

**Comment by IndrajeetPatil** [comment]
I have updated my top-level comment in this issue with an implementation note, which should be helpful for whoever takes over implementing new plots in `{ospsuite}`.

**Comment by IndrajeetPatil** [comment]
Currently, plots which are supported in `{tlf}`, but have no equivalent in  `{ospsuite}` (either because they were low priority or because they don't belong to the `DataCombined`-based workflow):

- [plotBoxWhisker()](https://www.open-systems-pharmacology.org/TLF-Library/reference/plotBoxWhisker.html)
- [plotDDIRatio()](https://www.open-systems-pharmacology.org/TLF-Library/reference/plotDDIRatio.html)
- [plotHistogram()](https://www.open-systems-pharmacology.org/TLF-Library/reference/plotHistogram.html)
- [plotPKRatio()](https://www.open-systems-pharmacology.org/TLF-Library/reference/plotPKRatio.html)
- [plotTornado()](https://www.open-systems-pharmacology.org/TLF-Library/reference/plotTornado.html)
