### ISSUE TITLE
`System.DllNotFoundException` error while installing the package on GHA

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#676]
I am really close to get the pkgdown GHA working, and all dependencies are downloaded properly, but the package [fails to install](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/runs/4445571712?check_suite_focus=true).

Any ideas on how to avoid this?

```r
* installing *source* package ‘ospsuite’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Assembly '/home/runner/work/_temp/Library/rClr/libs/ClrFacade.dll' doesn't have an entry point.
Error: Error: package or namespace load failed for ‘rClr’:
 .onLoad failed in loadNamespace() for 'rClr', details:
  call: clrCallStatic("Rclr.RDotNetDataConverter", "SetRDotNet", setit)
  error: Type:    System.DllNotFoundException
Message: System.Native assembly:<unknown assembly> type:<unknown type> member:(null)
Method:  
Stack trace:
  at (wrapper managed-to-native) Interop+Sys.LChflagsCanSetHiddenFlag()
  at Interop+Sys..cctor () [0x00000] in <533173d24dae460899d2b10975534bb0>:0 

Execution halted
ERROR: lazy loading failed for package ‘ospsuite’
* removing ‘/home/runner/work/_temp/Library/ospsuite’
```

The key part of GitHub yaml that downloads dependencies is the following:

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/02b8a343a8d8018a497ade36b796366eb7b66702/.github/workflows/pkgdown.yaml#L45-L50

**Comment by IndrajeetPatil** [comment]
Btw, this GitHub action is set up for `ubuntu`, and so I am using the `ubuntu` binaries for `{rClr}`.

**Comment by msevestre** [comment]
@IndrajeetPatil Then you are in for a lot of pain.... you need to install mono etc..

**Comment by msevestre** [comment]
@Yuri05 Don't you have some docker image with everything installed that could be used here?

**Comment by PavelBal** [comment]
Same question as Michael - what are you trying to do?

**Comment by Yuri05** [comment]
>Don't you have some docker image with everything installed that could be used here?

Yes, for Ubuntu18 and CentOS7 we have docker images with all prerequisites (Mono, etc.) for R3 and R4
https://github.com/orgs/Open-Systems-Pharmacology/packages 
(**base-rX.Y.Z-XXX** e.g. **base-r3.6.3-bionic**)

For Ubuntu20 it's not possible anymore to install that old version of Mono whih for some reason is required by rClr

**Comment by IndrajeetPatil** [comment]
> what are you trying to do?

I am trying to use `github-actions` to build the package website after each commit. But, for that to happen, the action should first 
- successfully download all dependencies (no problem here)
- install the package (this is the step where I get this error) 

>  you need to install mono etc.

Hmm, I have no idea what this is, but I will do some research.

> For Ubuntu20 it's not possible anymore to install that old version of Mono which for some reason is required by rClr

🤦‍♂️  I am indeed using `ubuntu-latest`.

I don't know how to do this using a Docker image, though. So, need to figure out a solution which does not rely on a Docker image.

I will see how I can install mono on ubuntu.

**Comment by Yuri05** [comment]
If you downgrade to 18.04 instead of ubuntu-latest: you can see the installations steps e.g. here
https://github.com/Open-Systems-Pharmacology/Docker-Base-Images/blob/main/.github/workflows/install_mono_net_packages_bionic.sh 
(not all of that is required by the ospsuite-R, e.g. all things related to MPI)
The whole installation takes a while (7-8 Minutes or so), so if you install it as part of a GitHub Action - the image should be cashed.

**Comment by PavelBal** [comment]
Not all functionalities work on Linux, so I am not sure using a Linux version for building the website is the way to go..

**Comment by Yuri05** [comment]
>Not all functionalities work on Linux, so I am not sure using a Linux version for building the website is the way to go..

Good point.

**Comment by IndrajeetPatil** [comment]
Closing this for we are no longer pursuing GHA CI/CD for R packages that rely on `.NET` code.
