### ISSUE TITLE
export `getContainerTask()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#677]
Currently, `{esqlabsR}` needs to rely on this internal function using `:::`, and this function can't be included in utilities package because it contains `{rClr}` code. So the only feasible solution at the moment is for `{ospsuite}` to start exporting this function.

**Comment by Yuri05** [comment]
`getContainerTask ` is required for calling of further OSPSuite.Core functions 
Shouldn't we create wrappers in ospsuite-R for **those functions** instead?
`getContainerTask `and similiar OSPSuite.Core functionality is usually really internal and should not be exported as public.

**Comment by PavelBal** [comment]
Wow-wow, let's discuss such things before implementing.

We already talked about exposing `getContainerTask()` and I think we agreed on not doing this. This is too low-level and I don't think any user would ever use it. I don't see a problem in referencing it via `:::`.

**Comment by IndrajeetPatil** [comment]
I am queasy using `:::` for the [following reason](https://cran.r-project.org/doc/manuals/r-release/R-exts.pdf), but I guess since we ourselves maintain `{ospsuite}`, there is unlikely to be a change that we won't have an advance notice about. And, we don't plan to submit `{esqlabsR}` to CRAN, so `R CMD Check` is not of concern either. 

![image](https://user-images.githubusercontent.com/11330453/145186559-91ef521d-588d-44e7-a7f2-5b1691815efe.png)
