### ISSUE TITLE
destructor methods for R6 classes, if specified, should be private

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#680]
cf. https://r6.r-lib.org/articles/Introduction.html#other-topics

Next version of `R6` will start warning, and then it won't support public finalizer methods, so better to avoid using them from now on.

![image](https://user-images.githubusercontent.com/11330453/145198733-25ed0db3-eecc-46df-85b0-c506581af3d2.png)

There are two instances of public finalizer methods:

1. `dot-net-wrapper`

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/e8db640572e1bcb4d8a7a7fa317b1385a6533f53/R/dot-net-wrapper.R#L27-L30

2. `simulation-batch`

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/f19aef1b0572bccfd89e6e1da85946fb721e0d41/R/simulation-batch.R#L71-L76

**Comment by IndrajeetPatil** [comment]
If I am not mistaken, the subclass doesn't inherit the private methods, right? 

Since `finalize()` is now a private method of `DotNetWrapper`, I think `super$finalize()` here needs to be removed:

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/84b7ea7d4bdbe72c5aacd34dfa8e7829d769b857/R/simulation-batch.R#L13-L18

**Comment by PavelBal** [comment]
> If I am not mistaken, the subclass doesn't inherit the private methods, right?

Can you test this? If this is the case, having a destructor as a private method is not good for inheritance :( Idea of super$finalize() is that we do not duplicate code and only take care of cleaning implementation-specific fields..

**Comment by msevestre** [comment]
Yep this is surprising to me as well...
Can we check that the base finalizer is called automatically then?

**Comment by PavelBal** [comment]
Could put `print("Finalizing")` in base class to test it :D

**Comment by IndrajeetPatil** [comment]
> If I am not mistaken, the subclass doesn't inherit the private methods, right?

If I am doing this right, the subclass does seem to inherit private methods, so we not do anything here.

``` r
library(R6)

parenv <- new.env()
parenv$peekaboo <- FALSE

bird <- R6Class(
  "bird",
  private = list(finalize = function() peekaboo <<- TRUE),
  parent_env = parenv
)

flyingBird <- R6Class(
  "flyingBird",
  inherit = bird,
  private = list(finalize = function() super$finalize())
)

pigeon <- flyingBird$new()
rm(pigeon)
gc()
#>           used (Mb) gc trigger (Mb) max used (Mb)
#> Ncells  664620 35.5    1247172 66.7  1239877 66.3
#> Vcells 1157369  8.9    8388608 64.0  2481392 19.0

# this should be true if destructor in parent class was called
parenv$peekaboo
#> [1] TRUE
```

<sup>Created on 2022-02-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by IndrajeetPatil** [comment]
And this is not special behaviour of destructor methods. The subclass inherits all private methods from the super or parent class:

``` r
library(R6)

bird <- R6Class(
  "bird",
  private = list(fly = function() print("it's flying"))
)

flyingBird <- R6Class(
  "flyingBird",
  inherit = bird,
  public = list(fly = function() super$fly())
)

pigeon <- flyingBird$new()

pigeon$fly()
#> [1] "it's flying"
```

<sup>Created on 2022-02-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
