### ISSUE TITLE
Update to the latest core

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#684]
@msevestre There has been a bug in core for creating default importer configuration for a file that @abdelr fixed some time ago, but I don't think it is in the core version of ospsuite-r. I wanted to update the core but then realized that we should also change the version of the package to 11, no? Either way, could you update it (and make a separate PR so I can see and learn how to do it in future).

**Comment by Yuri05** [comment]
>we should also change the version of the package to 11, no?

already done
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/659/files

**Comment by IndrajeetPatil** [comment]
Can this be closed?

**Comment by PavelBal** [comment]
The core is still outdated. When trying to use the latest core, I get 

`Message: Could not load file or assembly 'Autofac, Version=5.2.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The system cannot find the file specified.`

I tried to get Autofac 5.2 from nuget and copy it to the lib folder, but it doesn't help.

**Comment by msevestre** [comment]
>ither way, could you update it (and make a separate PR so I can see and learn how to do it in future).

sorry miss this. I'll check it out. The version of packages used needs to be exactly the same as in core. 
And even that, does not ensure that it will work. There is still some stuff that I don't understand regarding what package is loading where and how
