### ISSUE TITLE
add `$toDataFrame()` public member methods to relevant objects

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#685]
# Proposal

Currently, we are breaking the encapsulation by having the following methods as (global) functions, and not as relevant object's member functions:

- `dataSetToDataFrame()`
- `pkAnalysesAsDataFrame()`
- `populationAsDataFrame()`

I would propose that we **also** (so that we remain backward compatible) add these as public methods for the relevant objects (note that I am adopting a consistent naming schema for the member functions):

- `DataSet$toDataFrame()`
- `pkAnalyses$toDataFrame()`
- `Population$toDataFrame()`

Given that we already have the necessary functions written down, implementing these should be quite quick and straightforward.

Edit: Following setters and getters terminology, `getDataFrame()` might also work.

**Comment by IndrajeetPatil** [comment]
(Creating this issue after got burned by spending an hour on implementing a data frame method that I didn't know exist 😅 )

**Comment by IndrajeetPatil** [comment]
Oh, also, it might be worth having a similar method for `SimulationResults` object?

**Comment by msevestre** [comment]
>we are breaking the encapsulation

For the sake of discussion, why do you think we are breaking encapsulation?

Let's think about the following scenario?
Say we want to allow export toJson, toXml, toMD etc... would you implement all these methods in the object?

**Comment by IndrajeetPatil** [comment]
> why do you think we are breaking encapsulation?

If we consider instances of classes as data here (does that make sense?), the relevant functions for this data (toDataFrame) are no longer encapsulated with that data.

> Say we want to allow export toJson, toXml, toMD etc... would you implement all these methods in the object?

I would say, yes?

Because, otherwise, if something about the data (here `DataSet` object) changes, we would need to update **all** functions (toJson, toXml, toMD, etc.) that use that data, right?

(New to OO thinking, so feel free to shoot down anything that doesn't make sense to you.)

**Comment by msevestre** [comment]
We used to implement all of this export method at the object level until we realized that this was not the object's concern and that our code was getting so complicated because of this.  
Take the object `Parameter`. A parameter object role is to hold a value, a unit, calculate a formula etc.. But exporting to whatever, his definitely not the concern of the parameter. Of course it is tied to the data, but to function properly, the object does not need to know how to export to markdown. This is someone's else job... Say we want to export to latex (why!?) then suddenly you would have to change ALL your object to support export to latex. Not their problem

So in general, serialization is done outside of the object. Object holds data and behavior associated to the data. (Beware of anemic model when there are only data and no behavior). 

Now, toDataFrame.... I am ok to have it in the object if it's easier. But if you need to instantiate services etc.. to make it work, then this is probably not the place.

**Comment by IndrajeetPatil** [comment]
> Now, toDataFrame.... I am ok to have it in the object if it's easier.

Thanks for being open to the suggestion.

> Of course it is tied to the data, but to function properly, the object does not need to know how to export

Absolutely! And that's a fair point. 

But, I think, at least in the context of R, where dataframes are a lifeblood for most things, _at least_ the dataframe method should live in the object. Everything else follows from it! (So we don't need to support any other method.)

For example, here is a demo with `DataCombined`'s getter method, and how you can convert to it whatever your heart desires:

``` r
library(ospsuite)
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000

# create a new dataset object
dataSet <- DataSet$new()
dataSet$setValues(
  xValues = c(1, 2, 3, 4, 5),
  yValues = c(10, 20, 30, 40, 50),
  yErrorValues = c(0, 1, 2, 3, 0)
)
dataSet$yErrorUnit <- ospUnits$`Concentration [mass]`$`pg/l`
dataSet$yErrorType <- DataErrorType$ArithmeticStdDev

# create an instance of class
# keep sim results as NULL
myCombDat <- DataCombined$new()
myCombDat$setDataSet(dataSet)

# extract a dataframe
(df <- myCombDat$getDataFrame())
#>   name xValues yValues yErrorValues xDimension xUnit           yDimension yUnit
#> 1            1      10        0e+00       Time     h Concentration (mass)  mg/l
#> 2            2      20        1e+09       Time     h Concentration (mass)  mg/l
#> 3            3      30        2e+09       Time     h Concentration (mass)  mg/l
#> 4            4      40        3e+09       Time     h Concentration (mass)  mg/l
#> 5            5      50        0e+00       Time     h Concentration (mass)  mg/l
#>         yErrorType yErrorUnit molWeight lloq
#> 1 ArithmeticStdDev       pg/l        NA   NA
#> 2 ArithmeticStdDev       pg/l        NA   NA
#> 3 ArithmeticStdDev       pg/l        NA   NA
#> 4 ArithmeticStdDev       pg/l        NA   NA
#> 5 ArithmeticStdDev       pg/l        NA   NA

# now I can do anything with this
# convert to yaml
yaml::as.yaml(df)
#> [1] "name:\n- ''\n- ''\n- ''\n- ''\n- ''\nxValues:\n- 1.0\n- 2.0\n- 3.0\n- 4.0\n- 5.0\nyValues:\n- 9.9999997\n- 19.9999995\n- 29.9999992\n- 39.999999\n- 49.9999987\nyErrorValues:\n- 0.0\n- 1.0e+09\n- 2.0e+09\n- 3.0000001e+09\n- 0.0e+00\nxDimension:\n- Time\n- Time\n- Time\n- Time\n- Time\nxUnit:\n- h\n- h\n- h\n- h\n- h\nyDimension:\n- Concentration (mass)\n- Concentration (mass)\n- Concentration (mass)\n- Concentration (mass)\n- Concentration (mass)\nyUnit:\n- mg/l\n- mg/l\n- mg/l\n- mg/l\n- mg/l\nyErrorType:\n- ArithmeticStdDev\n- ArithmeticStdDev\n- ArithmeticStdDev\n- ArithmeticStdDev\n- ArithmeticStdDev\nyErrorUnit:\n- pg/l\n- pg/l\n- pg/l\n- pg/l\n- pg/l\nmolWeight:\n- .na\n- .na\n- .na\n- .na\n- .na\nlloq:\n- .na\n- .na\n- .na\n- .na\n- .na\n"

# convert to XML
XML::asXMLNode(df)
#> c(&quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;)c(1, 2, 3, 4, 5)c(9.99999974737875, 19.9999994947575, 29.9999992421363, 39.999998989515, 49.9999987368938)c(0, 999999997.475243, 1999999994.95049, 3000000106.11257, 0)c(&quot;Time&quot;, &quot;Time&quot;, &quot;Time&quot;, &quot;Time&quot;, &quot;Time&quot;)c(&quot;h&quot;, &quot;h&quot;, &quot;h&quot;, &quot;h&quot;, &quot;h&quot;)c(&quot;Concentration (mass)&quot;, &quot;Concentration (mass)&quot;, &quot;Concentration (mass)&quot;, &quot;Concentration (mass)&quot;, &quot;Concentration (mass)&quot;)c(&quot;mg/l&quot;, &quot;mg/l&quot;, &quot;mg/l&quot;, &quot;mg/l&quot;, &quot;mg/l&quot;)c(&quot;ArithmeticStdDev&quot;, &quot;ArithmeticStdDev&quot;, &quot;ArithmeticStdDev&quot;, &quot;ArithmeticStdDev&quot;, &quot;ArithmeticStdDev&quot;)c(&quot;pg/l&quot;, &quot;pg/l&quot;, &quot;pg/l&quot;, &quot;pg/l&quot;, &quot;pg/l&quot;)c(NA, NA, NA, NA, NA)c(NA, NA, NA, NA, NA)

# convert to json
jsonlite::toJSON(df)
#> [{"name":"","xValues":1,"yValues":10,"yErrorValues":0,"xDimension":"Time","xUnit":"h","yDimension":"Concentration (mass)","yUnit":"mg/l","yErrorType":"ArithmeticStdDev","yErrorUnit":"pg/l"},{"name":"","xValues":2,"yValues":20,"yErrorValues":999999997.4752,"xDimension":"Time","xUnit":"h","yDimension":"Concentration (mass)","yUnit":"mg/l","yErrorType":"ArithmeticStdDev","yErrorUnit":"pg/l"},{"name":"","xValues":3,"yValues":30,"yErrorValues":1999999994.9505,"xDimension":"Time","xUnit":"h","yDimension":"Concentration (mass)","yUnit":"mg/l","yErrorType":"ArithmeticStdDev","yErrorUnit":"pg/l"},{"name":"","xValues":4,"yValues":40,"yErrorValues":3000000106.1126,"xDimension":"Time","xUnit":"h","yDimension":"Concentration (mass)","yUnit":"mg/l","yErrorType":"ArithmeticStdDev","yErrorUnit":"pg/l"},{"name":"","xValues":5,"yValues":50,"yErrorValues":0,"xDimension":"Time","xUnit":"h","yDimension":"Concentration (mass)","yUnit":"mg/l","yErrorType":"ArithmeticStdDev","yErrorUnit":"pg/l"}]

# etc.
```

<sup>Created on 2021-12-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
> But if you need to instantiate services etc.. to make it work, then this is probably not the place.

Thanks for the tip! I will keep it in mind if I ever work on something like this.

**Comment by msevestre** [comment]
>at least in the context of R, where dataframes are a lifeblood for most things,

I think this is the key element. Here. This definitely belong to the object. No question

**Comment by IndrajeetPatil** [comment]
Cool. I will add those member functions then.

I personally prefer `$getDataFrame()`, but maybe you (plural) prefer `$toDataFrame()`?

**Comment by msevestre** [comment]
get => implies a getter and therefor assume NO computation whatsoever (at least the expecation)
to => implies some conversion and may not be instantaenous.

I would stick with to

**Comment by PavelBal** [comment]
Why we have it as a function and not a method of the `DataSet` - the function allows to create a data frame from multiple `DataSet` objects.
