### ISSUE TITLE
Add artifacts without version number to enable usage as permalink

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#698]
Create **additional** artifacts **ospsuite.zip** and **ospsuite_<LinuxDistribution>.tar.gz** (without the version number), so that they can e used in the permalinks to the latest built package version (s. the discussion in Open-Systems-Pharmacology/OSPSuite.ReportingEngine#592)

**Comment by Yuri05** [comment]
need to rename the windows package `ospsuite_windows.zip`=>`ospsuite.zip` (otherwise it cannot be installed under windows).

**Comment by msevestre** [comment]
I don't get it. Didn't you merge exactly the opposit? WHAT?

**Comment by Yuri05** [comment]
lol
`install.packages('ospsuite_windows.zip')` crashes
`install.packages('ospsuite.zip')` works
So I renamed **ospsuite_windows.zip** to **ospsuite.zip** :)
