### ISSUE TITLE
Feature: Change parameter formula

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#7]
Do we want to have an option to change values of parameters to new formula? If yes, how should this work (including defining new aliases).

**Comment by PavelBal** [comment]
@msevestre One may want to change the formular depending on the simulated scenario (e.g, static/dynamic effect).

I agree that the potential implementation could be not easy. That's why I wanted to hear from others how big the demand for such a feature would be.

**Comment by msevestre** [comment]
>One may want to change the formular depending on the simulated scenario (e.g, static/dynamic effect).

that could be done with a flag in the formula itself using a ternary operator for example

**Comment by PavelBal** [comment]
Of course - if the user has the original MoBi-File :)

But if we will implement loading PKML that can be opened by MoBi again, this will be no problem any more.

**Comment by msevestre** [comment]
yes. The pkml is the minimal required structure to be compatible with PKSim and MoBi. We can safely assume that this is our minmal viable structure

**Comment by msevestre** [comment]
It was discussed somewhere that this is not something we were going to do
