### ISSUE TITLE
Error: package or namespace load failed for ‘ospsuite’

### ISSUE THREAD

**Issue by luoqinhuan** [Open-Systems-Pharmacology/OSPSuite-R#707]
After installing R6, stringr, rClr and ospsuite for the corresponding version, I failed to load package 'opsuite'.
The error is shown below
![image](https://user-images.githubusercontent.com/70244013/147338523-9191d077-dc24-4b48-a6c2-3ba15367433b.png)

**Comment by luoqinhuan** [comment]
Here is the sessionInfo of my R environment
![image](https://user-images.githubusercontent.com/70244013/147338574-708dc36e-9fb5-40b3-9bc0-45cccf120be5.png)

**Comment by Yuri05** [comment]
Can you try [this](https://github.com/Open-Systems-Pharmacology/Forum/discussions/932#discussioncomment-979592)?

**Comment by luoqinhuan** [comment]
Thanks for your advice. I solved my problems.

**Comment by Yuri05** [comment]
>I solved my problems.

@luoqinhuan Can you tell us how? It might help other users in case they face the same problem in the future.

**Comment by luoqinhuan** [comment]
I just used 32-bit R rather than 64-bit and everything works out  following the suggestions shown in [this](https://github.com/Open-Systems-Pharmacology/Forum/discussions/932#discussioncomment-979592)
