### ISSUE TITLE
Make DotNetWrapper$ref read-only and override for classes if necessary

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#710]
The reference to the .NET object in `DotNetWrapper` class is exposed as a public field. I propose to make this field read-only and override this behavior for classes when it should be possible.

Why? Changing `$ref` can destroy the connection between objects. Consider the `Simulation`-class and it's constructor:

```
    #' @description
    #' Initialize a new instance of the class
    #' @param ref Reference to .NET simulation object
    #' @param sourceFile (Optional) File used to load the simulation
    #' @return A new `Simulation` object.
    initialize = function(ref, sourceFile = NULL) {
      super$initialize(ref)
      private$.sourceFile <- sourceFile
      private$.buildConfiguration <- rClr::clrGet(self$ref, "BuildConfiguration")
      private$.settings <- SimulationSettings$new(rClr::clrGet(private$.buildConfiguration, "SimulationSettings"))
    }
```

Changing `$ref` after initialization would make `private$.buildConfiguration` (and as the consequence `private$.settings`) invalid.

**Comment by msevestre** [comment]
Are you sure we are not using it as a setter somewhere?

**Comment by PavelBal** [comment]
I just checked the code and we are only setting `$ref` in the constructors so far. However, it COULD be used and would lead to unforeseen consequences.

The problem came up while writing a function that would set `$ref` of `DataImporterConfiguration` and we had to spend some time to understand why it was not working as expected... By making `$ref` read-only, we could avoid the concept being misused.

**Comment by msevestre** [comment]
Agreed. Let's do this. I just wanted to make sure we were not replying on this somewhere

**Comment by msevestre** [comment]
PR coming
