### ISSUE TITLE
API Update: LoadDataSetsFromExcel should support configuration file path

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#721]
At the moment we have
```
dataSet <- loadDataSetsFromExcel(
  xlsFilePath = getTestDataFilePath("CompiledDataSetStevens2012.xlsx"),
  importerConfiguration = DataImporterConfiguration$new(getTestDataFilePath("ImporterConfiguration.xml"))
)
```

I think it would be good to have an overload that takes just a configuration file path

e.g.
```
dataSet <- loadDataSetsFromExcel(
  xlsFilePath = getTestDataFilePath("CompiledDataSetStevens2012.xlsx"),
  importerConfigurationFilePath = getTestDataFilePath("ImporterConfiguration.xml")
)
```

Thoughts @IndrajeetPatil @PavelBal

**Comment by PavelBal** [comment]
And either `importerConfiguration` or `importerConfigurationFilePath` must be not emtpy, but not both? Yeah could be doable, though I do not like such signatures..

**Comment by msevestre** [comment]
Yep or imporConfiguration is either an object or a string to which case we load it from file

**Comment by PavelBal** [comment]
This is implemented.
