### ISSUE TITLE
DataCombined: Following the examples in tests, I get a column with NA and "".

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#726]
![image](https://user-images.githubusercontent.com/1041237/151347838-0afc2af6-d29a-4e74-b998-26b7be6c9380.png)
@IndrajeetPatil @PavelBal 
It's because the import returns "" for those empty meta data. It does not make sense to me. It should be NA as "" is not a valid value.
Is this a bug in DataSet?

**Comment by msevestre** [comment]
```R
$Stevens_2012_placebo.Sita_dist
DataSet: 
   Name: Stevens_2012_placebo.Sita_dist 
   X dimension: Time 
   X unit: min 
   Y dimension: Fraction 
   Y unit: % 
   Error type: ArithmeticStdDev 
   Error unit: % 
   Molecular weight: 
   LLOQ: 
   Meta data: 
$Source
[1] "tests/data/CompiledDataSetStevens2012.xlsx"

$Sheet
[1] "Stevens_2012_placebo"

$Organ
[1] ""

$Compartment
[1] ""

$Molecule
[1] ""

$`Group Id`
[1] "Sita_dist"
```

**Comment by PavelBal** [comment]
This is related to https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1429

At this stage, I would say the R implementation is correct.

btw, why 
>"" is not a valid value.

its an empty string, no?

**Comment by msevestre** [comment]
It does not make sense to me to defined a meta data 'organ' and say it has no value (empty)
Rather they should not be a meta data organ and it should be NA in the Colum. Or not even there at all since it's not set.

**Comment by msevestre** [comment]
This is just my opinion.

**Comment by PavelBal** [comment]
> It does not make sense to me to defined a meta data 'organ' and say it has no value (empty)
Rather they should not be a meta data organ and it should be NA in the Colum. Or not even there at all since it's not set.

Agree, but this must be fixed in Core.

**Comment by msevestre** [comment]
Yep agreed. CLosing here
