### ISSUE TITLE
API Question addSimulationResults: Group is based on lexical order of quantity paths...

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#728]
should it be a dictionary instead? e.g. key: path, value: group?
Logic based on order is always suspicious to me.

**Comment by PavelBal** [comment]
You mean, using a data structure "Map" instead of a data frame?

**Comment by msevestre** [comment]
No sorry
I need to do sthg like
cd$addSimilationResults(simRes, group= list ("A","B"))

And internally, it means that I only have 2 selected output , and the first one will get A and the second one will get B

I think this is not transparent at all and I would have expected the grouping to be defined using a map/dictionary/hash(not sure what it's called in R) with key being the path and value the group. That way, the order does not matter

**Comment by IndrajeetPatil** [comment]
> I think this is not transparent at all

To get a better idea of what you are expecting, what would the transparent API look like?

> defined using a map/dictionary/hash

R has only ordered data structures, none of the unordered ones. But I know you are using `{hash}` package throughout the ecosystem to define such data structures from R. 

So, yes, doable. But I'd really like to see the alternative API that motivates this change because it's going to involve a complete rewrite of this function.

**Comment by msevestre** [comment]
>To get a better idea of what you are expecting, what would the transparent API look like?

Sure:
This is what we have (assuming I have 3 outputs in my simulations with path)
"outputPath1", "outputPath2", "outputPath3"
```
myCombDat$addSimulationResults(
    simResults,
    groups = list("distal", "proximal", "total")
  )
```

The user needs to know that "distal" is going to be mapped to "outputPath1", "proximal" to "outputPath2" etc.. this is done implicitely and is based only on the order of the quantityPaths returned by the simulation (what happens if PKSim adds another outputs that  couldshifts the order for instance.. your code will fail. This happens often, as soon as we had a new observer etc)

Instead, I would suggest to be explicit
```
myCombDat$addSimulationResults(
    simResults,
    groups =  hash("outputPath1": "distal", "outputPath2":,"proximal", "outputPath3": "total")
  )
```

This would have the benefit of 

- Being clear what is mapped to what
- Being independent of the order of the outputPath
- Allowing you to also avoid having to do stuff like this

```
 myCombDat$addSimulationResults(
    simResults,
    groups = list(NULL, NaN, "distal", "proximal", "total")
  )
```
where you have to add placeholder to NOT group some outputs

Also it would specify which quantity you are interested in and therefor not have to specifcy "quantitiesOrPaths"

There is no guarantee that simResults$allQuantityPaths will always return the same order. I would like to emphasis this

**Comment by PavelBal** [comment]
> R has only ordered data structures, none of the unordered ones. But I know you are using {hash} package throughout the ecosystem to define such data structures from R.

We are actually misusing `enum `sometimes ;) Or named lists.

OK then I would propose the following change: groups cannot be assigned in the `add` methods but must be explicitly defined in `setGroups` method. E.g.

`myComDat$setGroups(list("path1" = "distal", "path2" = proximal))`

To remove data  from a group:

`myComDat$setGroups(list("name" = NA))`
