### ISSUE TITLE
Error when loading ospsuite package. Was working before

### ISSUE THREAD

**Issue by rodolfofetz** [Open-Systems-Pharmacology/OSPSuite-R#729]
I was using the ospsuite package on R a few weeks ago, but I tried to run the same code and got a error message when loading the package, 
I have R6, stringr, readr and rClr installed and loaded,
I also installed Rtools for the package instalation from the zip file, 
R version 4.1.2, Rstudio 2021.09.2 and Windows 10 21H1.

when I run the code:
`library(ospsuite)`

The error appear in the console:
`Error: package or namespace load failed for ‘ospsuite’:
 .onLoad failed in loadNamespace() for 'ospsuite', details:
  call: rClr::clrCall(dimensionTask, "AllAvailableUnitNamesFor", enc2utf8(dimension))
  error: Type:    System.Collections.Generic.KeyNotFoundException
Message: Dimension 'CV mmHg*sÂ²/ml' not available in DimensionFactory.
Method:  OSPSuite.Core.Domain.UnitSystem.IDimension Dimension(System.String)
Stack trace:
   at OSPSuite.Core.Domain.UnitSystem.DimensionFactory.Dimension(String name)
   at OSPSuite.R.Services.DimensionTask.DimensionByName(String dimensionName)
   at OSPSuite.R.Services.DimensionTask.AllAvailableUnitNamesFor(String dimensionName)`

Does anyone had the same problem and found a way to fix it?

**Comment by PavelBal** [comment]
In your "Language"-settings, when you click on "Administrative language settings" and then "Change system locale", make sure that the checkbox "Beta: unicode..." is UNselected.

![image](https://user-images.githubusercontent.com/25903040/151566583-9371f19b-77df-448e-ac8d-fbec941730ff.png)

**Comment by rodolfofetz** [comment]
> In your "Language"-settings, when you click on "Administrative language settings" and then "Change system locale", make sure that the checkbox "Beta: unicode..." is UNselected.
> 
> ![image](https://user-images.githubusercontent.com/25903040/151566583-9371f19b-77df-448e-ac8d-fbec941730ff.png)

Yes, it was unselected, 
maybe the problem started after I updated the R version, 
I'll try this weekend on another laptop with an older version.

**Comment by msevestre** [comment]
Make sure to use a 64 bit version of R
4.1 works normally. But the message shows that the unit is not parsed properly so it could really be an encoding issue

**Comment by BaronvonderHeyden** [comment]
i have the same

> Make sure to use a 64 bit version of R 4.1 works normally. But the message shows that the unit is not parsed properly so it could really be an encoding issue

I have the same issue, do use a 64 bit version and no version of R (also not 4.1) makes the error go away.

**Comment by msevestre** [comment]
in fact, 
>System.Collections.Generic.KeyNotFoundException Message: Dimension 'CV mmHg*sÂ²/ml' not available in DimensionFactory

is very weird. Either is the message wrong, or something very funky is going on as this is not a dimension but a unit

**Comment by PavelBal** [comment]
No, we actually have such a dimension

![image](https://user-images.githubusercontent.com/25903040/151787077-456587ea-3293-419f-8c4a-233821c96261.png)

**Comment by PavelBal** [comment]
We have such a problem on a machine right now and it works in R console but not RStudio. Trying to load dimension.xml with e.g. the XML library in RSudio returns messed up unicode strings, so it has nothing to do with any rClr stuff.

**Comment by msevestre** [comment]
>No, we actually have such a dimension

we do! Crazy...but why?

**Comment by PavelBal** [comment]
@rodolfofetz @BaronvonderHeyden It seems to be a bug in the latest version of RStudio. Please download and install the previous version (RStudio 2021.09.1+372).

**Comment by rodolfofetz** [comment]
> @rodolfofetz @BaronvonderHeyden It seems to be a bug in the latest version of RStudio. Please download and install the previous version (RStudio 2021.09.1+372).

Thanks! That was the problem, I downloaded the RStudio 2021.09.1+372 and it worked just fine.

**Comment by msevestre** [comment]
Crazy....well done
