### ISSUE TITLE
getOSPSuiteSetting: enum instead of string?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#730]
At the moment `getOSPSuiteSetting` function takes a string as argument and it's not clear what are possible values for the `settingName`
The online help does not provide this information.
Should we define an **enum** for the `settingName `instead?

<img width="450" src="https://user-images.githubusercontent.com/25061876/151599083-e8d81f6f-6e8b-4f63-8510-f878af770668.png">

**Comment by msevestre** [comment]
Yes!!!!
