### ISSUE TITLE
runSimulations error when simulations are loaded from cache

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite-R#733]
When simulations are loaded from cache, the _parallel_ run function `runSimulations` returns the error 

```
Error in names(simulationResults) <- names(resultsIdSimulationIdMap) : 
  'names' attribute [2] must be the same length as the vector [1]
```

Currently preventing [this RE PR](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/pull/677) from building.
[cache-parallel-bug.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/7975698/cache-parallel-bug.zip)

**Comment by msevestre** [comment]
Checking this out

**Comment by msevestre** [comment]
I can reproduce with a test...

**Comment by msevestre** [comment]
I can only reproduce if I am running the very SAME INSTANCE of a simulation multiple times... While this should not crash, because people are allowed to waste CPU time, I am wondering why we need this in the RE?

**Comment by msevestre** [comment]
Actually it should be an error. Results are cached by sim id. So it does not make sense at all to run two identical simulations. Going to make sure ospsuite.core throws an error

**Comment by abdelr** [comment]
You should not have the exact copy of a simulation. If you need to run a single simulation with different parameters set then you should use a simulation batch. You could even mix (simulations and batches) so I see no need for having exactly the same simulation twice.

**Comment by msevestre** [comment]
Not a copy. Same instance. Copy is fine with me (as long as they don't have the same id..but then something is really wrong!!)

**Comment by abdullahhamadeh** [comment]
> I am wondering why we need this in the RE?

It was an example in one of the vignettes.  The simulations in that example are indeed loaded from the same file and the parameters are identical, but they have different output paths.

**Comment by msevestre** [comment]
They don't .. same instance...one is overwritting the outputs of the other...unless you are managing that in a different way than using the outputs from core...

**Comment by abdullahhamadeh** [comment]
> They don't .. same instance...one is overwritting the outputs of the other...unless you are managing that in a different way than using the outputs from core...

A commit in the [PR](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/pull/677) changed `loadFromCache` for the RE simulation runs from `FALSE` to `TRUE`.  When that happened the vignette ran the same instance.   I have restored `loadFromCache` to `FALSE` in that PR.

**Comment by msevestre** [comment]
I think we should change the vignettes so that is does not do sthg that does not make sense
