### ISSUE TITLE
Check for unnecessary tests for the Utils-package

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#739]
After the utils package has been cleaned up, check all tests in OSPSuite-R whether we have some residual tests for removed functionality.

**Comment by IndrajeetPatil** [comment]
I am pretty sure I had moved all the relevant tests to the utility package as well, but I'll double-check.

**Comment by PavelBal** [comment]
Actually those tests should fail, right :D
