### ISSUE TITLE
encodeUnit to Utils

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#741]
I think this can be moved to utils

**Comment by IndrajeetPatil** [comment]
This relies on `ospsuiteEnv`, so not a good idea to move this to utils.

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/a50f374e0919ff42e9c324e60a2348f066d5d9a8/R/utilities.R#L25

**Comment by PavelBal** [comment]
I think the following can be moved to env of the utils:

```
# Separator defined in OSPSuite.Core.
ospsuiteEnv$pathSeparator <- "|"
```

```
# Default values for the formatNumerics() helper function
ospsuiteEnv$formatNumericsDigits <- 5
ospsuiteEnv$formatNumericsSmall <- 2
```

```
# Specifies the symbol used for µ. This will be set by the .NET layer
ospsuiteEnv$muSymbol <- "µ"
```


@msevestre what do you think, these are "global" settings, right?
