### ISSUE TITLE
Conventions for naming columns in `*DataFrame()` outputs

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#758]
AFAIK, we aren't currently following any case consistently while naming columns in dataframe outputs.

I thought we were following `lowerCamel`, but that's clearly not the case (except for `dataSetToDataFrame()` function):

``` r
library(ospsuite)

simPath <- system.file("extdata", "simple.pkml", package = "ospsuite")
sim <- loadSimulation(simPath)
results <- runSimulations(sim)

simData <- simulationResultsToDataFrame(results)
pkData <- pkAnalysesAsDataFrame(calculatePKAnalyses(results))

names(simData)
#> [1] "paths"            "IndividualId"     "Time"             "simulationValues"
#> [5] "unit"             "dimension"        "TimeUnit"         "TimeDimension"   
#> [9] "molWeight"
names(pkData)
#> [1] "IndividualId" "QuantityPath" "Parameter"    "Value"        "Unit"
```

Additionally, we are sometimes not internally consistent while referring to the same underlying construct: 
For example, the same construct is called `paths` or `QuantityPath`.

```
unique(simData$paths)
#> [1] "Organism|Liver|A" "Organism|Liver|B" "Organism|A"       "Organism|B"
unique(pkData$QuantityPath)
#> [1] "Organism|B"       "Organism|A"       "Organism|Liver|A" "Organism|Liver|B"
```

<sup>Created on 2022-02-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Maybe this is too little too late, and we will have to live with it, or maybe this is intentional. Not sure, but thought I'd create an issue nonetheless to keep this in mind, and attend to it now or in the future.

**Comment by msevestre** [comment]
Isn't simulationResultsToDataFrame a new method?

**Comment by IndrajeetPatil** [comment]
> Isn't simulationResultsToDataFrame a new method?

Yes, that's the one for which names can be easily changed (if we want) because it's unlikely to be being used in the wild and so less to be a breaking change.

**Comment by IndrajeetPatil** [comment]
Actually, there doesn't seem to be any consistent naming schema here.

For examples, column names in the output from `dataSetToDataFrame()` are a mix of casing conventions:

```r
      "name",
      "xValues",
      "yValues",
      "yErrorValues",
      "xDimension",
      "xUnit",
      "yDimension",
      "yUnit",
      "yErrorType",
      "yErrorUnit",
      "molWeight",
      "lloq",
      "Sheet",
      "Study Id",
      "Organ",
      "Compartment",
      "Species",
      "Gender",
      "Molecule",
      "Route",
      "Subject Id",
      "Dose"
```

So `pkAnalysesAsDataFrame()` and `populationToDataFrame()` are the exception in that they adopt a casing convention (UpperCamelCase) in naming its columns.

We will just have to live with this inconsistency.

**Comment by PavelBal** [comment]
`dataSetToDataFrame()` appends columns for all meta data entries in the `DataSet`. As the user can manually add any kind of meta data, there is no way to have all column names following the same convention.

**Comment by IndrajeetPatil** [comment]
Sure, but if I am not mistaken, the columns which are in our control don't follow UpperCamel case either:

```r
"name", "molWeight", "lloq"
```
