### ISSUE TITLE
Creating individual does not work when portable version of ospsuite 10 is available?

### ISSUE THREAD

**Issue by Sulav1** [Open-Systems-Pharmacology/OSPSuite-R#761]
I have PKSIM 10 installed as a portable and I also have ospsuite R package 10.0.72. Many functionalities of R package worked properly. However, creating individual throws an error : 
![image](https://user-images.githubusercontent.com/53556270/153026766-640411d0-99fc-4ee8-9bc5-b18b13fdf65c.png)

The problem persisted when the path was added using `initPKSim` 
```
initPKSim(pksimFolderPath = 'path_2_portable_PKSIM/PK-Sim 10.0.257')
```
and following error was thrown

![image](https://user-images.githubusercontent.com/53556270/153027463-ca4744a0-a2a0-45ac-8d56-d829eb2dbc19.png)

**Comment by msevestre** [comment]
You needed the absolute path. What I see here is not a valid path as far as I can tell

**Comment by msevestre** [comment]
so it works in my machine with the portable version so this is something else. 
Can you start PK-Sim first of all?

**Comment by IndrajeetPatil** [comment]
@Sulav1 Do you still see this issue after upgrading to `ospsuite 11`?
