### ISSUE TITLE
Refactor `DataImporterConfiguration`

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#763]
See discussion in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/705#discussion_r801608149

The R class implements too many .NET manipulations. This probably should be done in .NET.

**Comment by Yuri05** [comment]
Is this issue still valid?

**Comment by PavelBal** [comment]
It was Michaels wish to refactor... I would say - `DataImporterConfiguration` works, let's not touch it...
