### ISSUE TITLE
DataSet constructor

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#767]
`DataSet` can get either a ref or a name to create an empty DS... which is just a bad signature because 

```
ds1 <- ospsuite::DataSet$new("ds1")

Error in private$.dataRepository$baseGrid : 
$ operator is invalid for atomic vectors
3.
private$.initializeCache() at data-set.R#202
2.
initialize(...)
1.
ospsuite::DataSet$new("ds1")
```

This happens because the first argument should be `ref` and the second is `name`. As the user would only use `name` as an argument when creating a DataSet from scratch, I would propose to either 

1) Swap the arguments in the constructor, such that `name` is the first and `ref` the second, so `DataSet$new("ds1")`, would work as expected, or
2) Only allow `ref` in the constructor and create a function for an empty data set, or a function `createDataSet(xValues, yvalues, yError)`.

I vote for Nr.1 as for me it is easier to have an overview of what I can do with the object in the object, and not to have to look through all available functions in the package.

@msevestre please give your feedback.

**Comment by msevestre** [comment]
@PavelBal Yes to 1
I think we have a utility class anyways for data set etc.. so we having a method that creates the stuff for you is not that bad anyways (following the idea that we can support user in a functional way as much as possible)

**Comment by msevestre** [comment]
WTF. How did you create the new branch? Did you sync with develop first?
This is exactly why we have this line in the git attribute. It should not change anything

**Comment by PavelBal** [comment]
@msevestre whats with this branch? https://github.com/Open-Systems-Pharmacology/OSPSuite-R/tree/748-add-git-attribute

**Comment by msevestre** [comment]
What do you mean? It was merged right? but clearly I don't understand anymore. Either all files have the wrong ending on github or ...
