### ISSUE TITLE
re-export enum

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#768]
I don't know why this is not re-imported, but I think we should to this. Only problems with `enum` in third-party code since it has been moved to utils.

**Comment by PavelBal** [comment]
Or re-export... whatever.

**Comment by IndrajeetPatil** [comment]
All of these were re-exported in the [initial PR](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/commit/796d6d4ffc72828a2778ab2dccd883b21556e16c), but we later decided to remove them to have a cleaner separation between the `{ospsuite.utils}` package and the `{ospsuite}` package.

It's a simple matter of adding `re-exports.R` file to the package to re-export them again, if we decide to do so:

```r
#' @export
#' @importFrom ospsuite.utils "%||%"
ospsuite.utils::`%||%`

#' @export
#' @importFrom ospsuite.utils enum
ospsuite.utils::enum

#' @export
#' @importFrom ospsuite.utils enumGetValue
ospsuite.utils::enumGetValue

#' @export
#' @importFrom ospsuite.utils enumHasKey
ospsuite.utils::enumHasKey

#' @export
#' @importFrom ospsuite.utils enumKeys
ospsuite.utils::enumKeys

#' @export
#' @importFrom ospsuite.utils enumPut
ospsuite.utils::enumPut

#' @export
#' @importFrom ospsuite.utils enumRemove
ospsuite.utils::enumRemove

#' @export
#' @importFrom ospsuite.utils enumValues
ospsuite.utils::enumValues

#' @export
#' @importFrom ospsuite.utils enumGetKey
ospsuite.utils::enumGetKey
```

**Comment by msevestre** [comment]
What's the reason to reeport everuything? Can't people just import at the top like we do in ospsuite-r

**Comment by PavelBal** [comment]
@msevestre The answer is here..

**Comment by msevestre** [comment]
Ok fair enough
