### ISSUE TITLE
Conventions for naming dataframe methods

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#779]
Is there some hidden logic to how we are naming the dataframe methods? 

Why do some methods have `To`, while others have `As` in their names?

``` r
library(ospsuite)
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000

grep(
  "dataframe",
  getNamespaceExports("ospsuite"),
  ignore.case = TRUE,
  value = TRUE
)
#> [1] "dataSetToDataFrame"           "pkAnalysesAsDataFrame"       
#> [3] "simulationResultsToDataFrame" "populationAsDataFrame"
```

<sup>Created on 2022-02-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by PavelBal** [comment]
No, I think this originates from different coders having implemented these functions... We should have a better communication here and adhere to some conventions. Not sure how to fix this now.

The same goes for "save..." and "export..." functions.

**Comment by IndrajeetPatil** [comment]
> Not sure how to fix this now.

I guess we can have aliases for these functions. 
That's the only way out of this if we want to have consistent naming schema **and** not break backward compatibility:

```r
"dataSetToDataFrame"    
"dataSetAsDataFrame"    

"pkAnalysesToDataFrame"       
"pkAnalysesAsDataFrame"   
    
"simulationResultsToDataFrame" 
"simulationResultsAsDataFrame" 

"populationAsDataFrame"
"populationToDataFrame"
```

**Comment by msevestre** [comment]
No please. let's agree on one way , keep the old one as aliases for compatibility and moving forward, only one
When were dataset and sinresults introduced? V11? In that case, we are not breaking anything by renaming them
Alternatively, we can agree on using To from now on and have the aliases for the other "as" with a warning that they are deprecated and will be removed in v12

**Comment by msevestre** [comment]
Now we are maybe not consistent here as well but at least the mental model is clear ☺️

**Comment by IndrajeetPatil** [comment]
Only `simulationResultsToDataFrame()` was introduced in v11. 
`dataSetToDataFrame()` has been there for a few versions, I think.

Since these are methods that convert an object of one type _to_ another type, I would vote for the `*To*()` pattern.

Okay, so with aliases to preserve backward compatibility, we will have:

```r
"dataSetToDataFrame"    

"simulationResultsToDataFrame" 

"pkAnalysesToDataFrame"       
"pkAnalysesAsDataFrame"   
    
"populationToDataFrame"
"populationAsDataFrame"
```

With deprecation warnings for `pkAnalysesAsDataFrame()` and `populationAsDataFrame()`.

**Comment by msevestre** [comment]
Sounds good to me
