### ISSUE TITLE
Update dimensions submodule to the latest version

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#783]
is outdated

**Comment by IndrajeetPatil** [comment]
Out of curiosity, why it needs to be updated if both are at commit `067cccc`?

**Comment by Yuri05** [comment]
The current state:
![grafik](https://user-images.githubusercontent.com/25061876/155484712-4d3ba841-0911-4ed2-aa81-cfb294275f12.png)

USed state:
![grafik](https://user-images.githubusercontent.com/25061876/155484807-35e64431-a700-41ed-a7b1-3888e17dcf1b.png)

**Comment by IndrajeetPatil** [comment]
Strange, I don't see any commit from 3 months ago in the respective [repo](https://github.com/Open-Systems-Pharmacology/OSPSuite.Dimensions/tree/067cccc17df5677782f3c292d0fa0ae4e4295ef1), nor do I see any other branch with such a commit:

![image](https://user-images.githubusercontent.com/11330453/155486065-db518cfe-1a27-4561-8921-eb978fb2613c.png)

**Comment by msevestre** [comment]
4f2fb13

You are looking at an outdated branch. 
I'll update

**Comment by IndrajeetPatil** [comment]
Thanks, now I see it.
