### ISSUE TITLE
How to create deep copies of `R6` classes in `{ospsuite}`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#789]
I have checked this only with `DataSet` class, and not sure if it's the same case for other `R6` classes. Here is the issue:

Usually, with `R6` classes, if I don't want to have shallow clones, I can set `deep = TRUE`:

``` r
library(R6)

Person <- R6Class(
  "Person",
  public = list(
    name = NULL,
    addName = function(name) self$name <- name
  )
)

Indra <- Person$new()
Indra$addName("Indra")
Indra$name
#> [1] "Indra"

Juri <- Indra$clone(deep = TRUE)
Juri$addName("Juri")
Juri$name
#> [1] "Juri"

Indra$name
#> [1] "Indra"
```

But this doesn't work with `R6` classes in _ospsuite_:

```r
library(ospsuite)

Indra <- DataSet$new(name = "Indra")
Indra$name
#> [1] "Indra"

Juri <- Indra$clone(deep = TRUE)
Juri$name <- "Juri"
Juri$name
#> [1] "Juri"

Indra$name
#> [1] "Juri"
```

<sup>Created on 2022-02-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Any way around this? Or this is by design?

**Comment by PavelBal** [comment]
Most of the R6 classes in ospsuite are wrappers around implementations in .NET. They store a reference to a .NET object and most properties are set in this .NET object. E.g. for `DataSet`: we first create an object of the `DataSet` class implemented in .NET, and assign the reference to it in the R6 class ´DataSet`. `name` is then a property of the .NET object.

When you are cloning the R6 object, it retains the reference to the same .NET object, so from now on both R6 `DataSet` objects share the same .NET object. Changing the name in one of the R6 objects changes the name in the .NET object - and therefore this is the value you will get for both R6 objects.

Cloning a wrapper around .NET object would require explicit cloning of the .NET object and assigning the clone to the new R6 object. This could be done if R6 classes allow to override the clone method. Question is, if this overhead is justified.

**Comment by msevestre** [comment]
Cloning won't work at all with .NET object. That's why any clone operation should be forbidden. I was hopping setting CLONEABLE to false would do this

**Comment by IndrajeetPatil** [comment]
First, thanks @PavelBal for the succinct and insightful explanation for how these objects are working! This wasn't clear to me even after reading the docs for individual `R6` objects 😅

> I was hopping setting CLONEABLE to false would do this

Indeed, something strange is happening here. 

This property is indeed set to `FALSE` for most R6 objects in the package (including `DataSet`), and yet `$clone()` method is available for these objects. HOW?!

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/5d38780e0c65b6c2f4c2fcee5634630d6a232bee/R/data-set.R#L17

This shouldn't be the case:

# `cloneable = TRUE`

``` r
library(R6)

Duck <- R6Class(
  "Duck",
  private = list(quack = function() print("Quack Quack")),
  cloneable = TRUE
)

myDuck <- Duck$new()

myDuck$clone()
#> <Duck>
#>   Public:
#>     clone: function (deep = FALSE) 
#>   Private:
#>     quack: function ()
```

# `cloneable = FALSE`

```r
Duck <- R6Class(
  "Duck",
  private = list(quack = function() print("Quack Quack")),
  cloneable = FALSE
)

myDuck <- Duck$new()

myDuck$clone()
#> Error in eval(expr, envir, enclos): attempt to apply non-function
```

<sup>Created on 2022-03-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by PavelBal** [comment]
Super weird. We should investigate this.

**Comment by PavelBal** [comment]
Ah-ah! It looks like the `cloneable` flag cannot be overridden in class implementations and the value of the parent class is used! ALL our classes inherit from `Printable`, and `Printable` does not define `cloneable = FALSE`. If I remove inheritance from `Printable`, then `cloneable = FALSE` works.

This should be changed in `Printable`!

**Comment by PavelBal** [comment]
I think it makes sense to have "clonable" for some classes that do not have any reference to .NET like `DataCombined`. We should check how it will work with Printable having `FALSE` for `cloneable`. In worst case maybe have two `Printable` implementations, one cloneable and one not...

But this is clearly a wrong design of inheritance here.

**Comment by IndrajeetPatil** [comment]
Good catch! I have created an issue in the utilities package to track this.

> But this is clearly a wrong design of inheritance here.

Agreed! Also, not something that is well-documented in `R6`.

If we think this is worthwhile, we can definitely make a feature request in `{R6}` package to rectify the current inheritance design for `R6` classes, and see if they are open to it.

**Comment by PavelBal** [comment]
> If we think this is worthwhile, we can definitely make a feature request in {R6} package to rectify the current inheritance design for R6 classes, and see if they are open to it.

Yes I think this is justified. Can you do this?

**Comment by IndrajeetPatil** [comment]
Will do!

**Comment by IndrajeetPatil** [comment]
Done: https://github.com/r-lib/R6/issues/247

**Comment by IndrajeetPatil** [comment]
Closed in https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/commit/a2cd3dc3e18358becb9c144281186940bd9297e2

**Comment by IndrajeetPatil** [comment]
Cloning will no longer work:

``` r
library(ospsuite)
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000

Indra <- DataSet$new(name = "Indra")
Indra$name
#> [1] "Indra"

Juri <- Indra$clone()
#> Error in eval(expr, envir, enclos): attempt to apply non-function
```

<sup>Created on 2022-03-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by IndrajeetPatil** [comment]
I have fixed this issue upstream in `{R6}`: https://github.com/r-lib/R6/pull/267

**Comment by PavelBal** [comment]
@IndrajeetPatil Cool!
