### ISSUE TITLE
R-version

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#79]
Package must be compiled with R 3.5.2

**Comment by PavelBal** [comment]
Why?

**Comment by msevestre** [comment]
@Yuri05 CI does not work with 3.5.2 unfortunately
https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-r/builds/26274201

Why does it have to be compiled with 3.5.2? Isn't it more important that it runs with 3.5.2?

**Comment by msevestre** [comment]
@Yuri05 Does not work also with 3.5.3

**Comment by msevestre** [comment]
For now let's stick with what we have. Tester should test in 3.5.2
