### ISSUE TITLE
Changing repo settings

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#793]
Whoever has the permission to do so, I wanted to request changing two settings for this repo:

1. Providing a prompt to update PRs, which is super useful to stay updated with the `develop` branch.

![image](https://user-images.githubusercontent.com/11330453/155755355-0130a08c-c9c7-450d-a37b-4c0e1648cdc8.png)

2. Add branch protection rules for the `develop` branch.

![image](https://user-images.githubusercontent.com/11330453/155755894-5fc1cc4e-d39d-432c-9495-8d679541e410.png)

**Comment by msevestre** [comment]
done

**Comment by IndrajeetPatil** [comment]
Thanks!
