### ISSUE TITLE
Implement setParameters

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#80]
This method should take a reference to parameters and values and update all values at once

In theory, it could also take an array of path and get the corresponding parameters and update the value..

@KatrinCoboeken @Yuri05 @PavelBal 
Can we define the signature of such a function?

**Comment by msevestre** [comment]
see some discussion here https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/19 but this is mostly for the getParameters

**Comment by PavelBal** [comment]
Let's call the function `setParametersValues(params, vals)`
- `params` array of parameter objects retrieved by `getParameters()`
- `vals` array of numeric values
- `length(params) == length(vals)`

- Do we need a function `getParametersValues(paths, simulation)`, that returns e.g. a list of Parameter path <-> parameter value based on the provided path? I.e. return not the objects `Parameter`, but just their values? I see pros and cons.

Pros - get all values without having to iterate (or `lapply`) over the parameter objects
Cons - just another function in addition to `getParameters()`.

What do you think @msevestre @KatrinCoboeken ?

**Comment by msevestre** [comment]
> Pros - get all values without having to iterate (or lapply) over the parameter objects

I don't see this as a problem at all unless the user is writing very poor code. I have yet to understand a real case scenario where making a loop, even over 500 parameters, would really im impact performance 

I think it is very useful to have help functions if they are 
1/documented
2/useful for 90% of the use cases

**Comment by msevestre** [comment]
I still don't really get the use case of how this method `setParametersValues(params, vals)` will be used.  Can you explain?

**Comment by PavelBal** [comment]
> I have yet to understand a real case scenario where making a loop, even over 500 parameters, would really im impact performance

I wasn't thinking about performance, more about 

> unless the user is writing very poor code

:)

> use case of how this method setParametersValues(params, vals)

Well, actually I just proposed to name the function `setParamtersValues` instead of `setParameters`, the rest is the same as defined in the first comment?

The use-case would be:

- Load a csv-file with columns "Parameter paths" and "Parameter values"
- `params <- getParameters(parameter_paths)`
- `setParametersValues(params, parameter_values)`

**Comment by PavelBal** [comment]
Should we still allow to do:

```
param1 <- getParameter(paramPath, sim)
param1$value <- 4
```
? Would be equal to 

`setParametersValues(param, 4)`

**Comment by msevestre** [comment]
Yes absolutely. I think all our `convenience` methods such as `setParameterVAlues` should not prevent users to use OOP
In fact, `setParametersValues` will use `param$value` underneath the hood right? Not sure how to prevent it from being used

**Comment by PavelBal** [comment]
Fixed with #120
