### ISSUE TITLE
Add `$calculateResiduals()` method to `DataCombined` object

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#803]
We will need to compute residuals between observed and simulated data for plotting. 

So, the question is: 

- Should we carry out this calculation only inside the plotting functions where residuals are needed? 

or

- Should the `DataCombined` object have a `$computeResiduals()` method that keeps up-to-date information on residuals in a dedicated column in `private$.dataCombined` dataframe?

I'd vote for the second option because this way the users have flexibility in terms of how and where they can use the residuals data. If, instead, we do this only inside the plotting functions, the users will not have access to this data directly. 

Also, in terms of implementation, I was thinking that `$computeResiduals()` will be a private method that updates residuals every time new datasets are added. Users can access this data, of course, through `toDataFrame()` public method.

(Note that the users will need this information regardless of whether they use _tlf_ for plotting or create custom plots.)

**Comment by PavelBal** [comment]
Second option. Furthermore, we might want to implement different approaches for calculation of the residuals in future.

And let's call it `calculateResiduals`. And we need to specify this properly.

**Comment by Yuri05** [comment]
I would suggest to propagate residuals calculation from the **OSPSuite.Core** to R:
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/5bebd8f05de1a790f65ba8f0febefb974699c496/src/OSPSuite.Core/Domain/Services/ParameterIdentifications/ResidualCalculator.cs#L70
It takes care of log/lin scale, proper handling of small values in log scale, weights, [different LLOQ handling options](https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/parameter-identification#handling-of-lloq-values) etc.
@msevestre

**Comment by PavelBal** [comment]
There are pros and cons.

Pros: its already in .NET

Cons: DataCombined has lost any connection to .NET objects, so we would have to prepare all the data in DataCombined to be sent to .NET. Furthermore, having it in R would allow us to be more agile in implementing more types of residual calculation, or even allow the user to pass his own function how to calculate the residual between two values.

**Comment by Yuri05** [comment]
>Cons: DataCombined has lost any connection to .NET objects, so we would have to prepare all the data in DataCombined to be sent to .NET. 

You could create a wrapper for that in .NET using only simple types, e.g.
`residuals = calculateResiduals(simTimes, simValues, obsTimes, obsValues, weights, lloq, residualScale, lloqHandlingOption, ...)`

>having it in R would allow us to be more agile in implementing more types of residual calculation, or even allow the user to pass his own function how to calculate the residual between two values.

You can combine both, e.g. call either .NET implementation or R implementation based on the passed residual type:
```
if residualType in {A, B, C, ...}
  calculateResiduals(...) # ==> .NET
else
  myCalculateResiduals(...) # ==> R

```

**Comment by PavelBal** [comment]
> You can combine both, e.g. call either .NET implementation or R implementation based on the passed residual type:

Yes, I think this is something we should implement.

**Comment by IndrajeetPatil** [comment]
Instead of the suggested solution, should we be implementing something similar to what's used in the reporting engine for calculating residuals?

https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/22c6167925f97488f9fd8d6b3e395ac202bce39b/R/utils.R#L1-L18
