### ISSUE TITLE
Add function to interpolate predicted data

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#804]
As mentioned in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/674#issuecomment-987833373, `DataCombined` object needs to provide data for creating predicted versus observed plot. 

![image](https://user-images.githubusercontent.com/11330453/156888921-65c4b140-253a-40f9-971a-7b5e6118db78.png)

For such a plot, the data needs to be _paired_. That is, at a given time (`xValues`), there needs to be a _single_ pair of `yValues` for observed and simulated data.

The `$toObsVsPredDataFrame()` public method for `DataCombined` will provide such a dataframe.

**Comment by IndrajeetPatil** [comment]
My thinking behind why this function should be a class member method and not an internal function called by `plotPredictedVsObserved()`:

- If the function is called only internally by `plotPredictedVsObserved()`, the users won't have access to the dataframe which was used to create the plot. This might not be an issue in general, but in this particular case it is kind of important that they can access the dataframe. This is because, depending on the matching threshold chosen, there can be a significant loss of data. Providing users with a way to extract dataframe can give them real-time feedback about whether the chosen threshold is appropriate.

- Giving a class member method affords users more flexibility in terms of what they wish to do with this dataframe further. They  can visualize it in their own way, they can rename columns to their own liking and save it to an Excel sheet, etc. But, if the function is used only internally, they will never be exposed to the paired dataframe and will have to do this themselves, and it's not that straightforward to do so.

**Comment by Yuri05** [comment]
From https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/674#issuecomment-987833373 (by @PavelBal )
<details><summary><b>Option 1: obtain simulation value using threshold</b></summary>
<br>

![grafik](https://user-images.githubusercontent.com/25061876/157279919-e2a19dbd-d1a7-40c5-b20c-197500048a5b.png)
</details>

From: https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/806#issuecomment-1060869562 (by @Yuri05)
<details><summary><b>Option 2: obtain simulation value using interpolations</b></summary>

My expectation is: if observed time value is not in the list of simulated time values, then the **observed time is kept** and **simulated value for this observed time is interpolated**.

E.g. if my simulated (predicted) data is
time|value
-|-
0|0
2|4
4|8

and my observed data is 
time|value
-|-
1| 1.9
3| 6.1
4| 8.2

then I would expect the outcome
time|predicted|observed
-|-|-
1|**2** (= `(0+4)/2`)|1.9
3|**6** (= `(4+8)/2`)|6.1
4|8|8.2

</details>

I'm not sure why we need such a threshold (maybe @PavelBal can comment on this), but if it is really required I would suggest the following:
* as per default, the threshold must be set = 0
* if the threshold is = 0: use the option 2 (interpolate)
* if the threshold is >0: use the option 1 (closest point within the threshold)

**Comment by msevestre** [comment]
I do not understand the threshold concept either.

**Comment by IndrajeetPatil** [comment]
See: https://github.com/Open-Systems-Pharmacology/OSPSuite-R/discussions/809

**Comment by IndrajeetPatil** [comment]
@Yuri05 I can't seem to get this to work properly; the graphs look nothing like what they looked in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/806#issue-1161574090.

To illustrate the problems encountered, here is a more minimal, yet realistic, example of the datasets encountered while testing this feature. Realistic examples would have hundreds of rows and many more datasets and groupings, so you can scale the complexity of this approach accordingly when you think of the following questions.

Note that there can be multiple datasets grouped under the same label. For example, here 5 different datsets (3 simulated, 2 observed) are assigned to two different groups.

# Simulated (predicted) data:

group|name|time|value
--|--|-|-
"groupA" | "data1" | 0 | 0
"groupA" | "data1" | 2 | 1.2
"groupA" | "data1" | 4 | 1.5
"groupA" | "data1" | 6 | 2.8
"groupA" | "data2" | 0 | 1.7
"groupA" | "data2" | 1 | 2.2
"groupA" | "data2" | 2 | 2.1
"groupA" | "data2" | 3 | 3.2
"groupB" | "data3" | 0 | 1.1
"groupB" | "data3" | 1 | 1.3
"groupB" | "data3" | 2 | 1.9

# Observed data:

group|name|time|value
--|--|-|-
"groupA" | "data4" | 0 | 1.2
"groupA" | "data4" | 2.5 | 2.3
"groupA" | "data4" | 4 | 2
"groupA" | "data4" | 6 | 8
"groupB" | "data5" | 2.5 | 2.2
"groupB" | "data5" | 4 | 3.5
"groupB" | "data5" | 10 | 4

# Questions

1. For `groupA`, time = 0 in observed data is exactly matched by two different observations at time = 0 in simulated data. Which one should be retained, the one in `data1` or `data2`?
2. For `groupB` in observed data, `time = 10` is not matched by any time measurement in simulated data. When an exact match can't be found, we are supposed to interpolate. How? It's the last observation, and no next observation exists. (If you say, we should be using lagged observations, then the same question would apply to the first non-matched time observation.)
3. For `groupA`, time = 2.5 in observed data is not exactly matched by simulated data. How to interpolate here? Focus on `data1, time = 2`, so the interpolated value is `(1.2 + 1.5) / 2`, or focus on `data2, time = 2`, so the interpolated value is `(2.1 + 3.2) / 2`. Both are equally acceptable, and yet we would need to choose one.
4. What are the appropriate data structures for carrying out these operations? `DataCombined` returns a long format dataframe. I can extract two wide format dataframes from this, each corresponding to observed and simulated dataframe. But these dataframes have completely different dimensions. Comparing time measurements and interpolation between these two dataframes requires that they be joined together, but this creates all possible combinations of rows. If we decide to just focus on raw vectors of time measurements and values, then we lose out on all the other important details in the dataframe (error types, units, etc.).

**Comment by msevestre** [comment]
A quick question so that I understand. Isn't grouping just used to have similar color, shapes etc..? If you have two observed data sets, my assumption is that you will want to plot them both and not just pick one of them.  (E.g multiple individual data sets for a given output)

**Comment by IndrajeetPatil** [comment]
> If you have two observed data sets, my assumption is that you will want to plot them both and not just pick one of them

Yes, definitely! 

As far as I can see, that's not what saying in my comment. Most of my questions are about interpolation implementation in the presence of multiple groups and multiple datasets.

All observed datasets will always be included, yes, but the complications arise if an exact match is not found for them and multiple simulated datasets are present.

**Comment by Yuri05** [comment]
@IndrajeetPatil 
1) Here in fact you have several data sets in one table, which apparently must be grouped by the `{group, name}` combination of the attributes. This information must be stored as part of the object, otherwise it is impossible to match the data.
2) In the observed data table you have combinations of `{group, name}` which are different from those in the simulated data table - which does not make sense for me.

My expectation would be:
* The information, which attributes (columns) are used for grouping is available and saved in the object
* Then for each combination of those attributes: 
  * extract 1 data set for this combination from the simulated table
  * extract 1 data set for this combination from the observed table
  * Use interpolation for the pair of exracted data sets

Which would not produce any match for the example above, because you have **data1**, **data2**, **data3** for  the name in simulated, and **data4**, **data5** for observed.
But if your observed data would look like this:

group|name|time|value
--|--|-|-
"groupA" | "data1" | 0 | 1.2
"groupA" | "data1" | 2.5 | 2.3
"groupA" | "data1" | 4 | 2
"groupA" | "data1" | 6 | 8
"groupB" | "data3" | 2.5 | 2.2
"groupB" | "data3" | 4 | 3.5
"groupB" | "data3" | 10 | 4

Then: 
* {groupA, data1}
  * simulated

group|name|time|value
--|--|-|-
"groupA" | "data1" | 0 | 0
"groupA" | "data1" | 2 | 1.2
"groupA" | "data1" | 4 | 1.5
"groupA" | "data1" | 6 | 2.8

  * Observed:
  
group|name|time|value
--|--|-|-
"groupA" | "data1" | 0 | 1.2
"groupA" | "data1" | 2.5 | 2.3
"groupA" | "data1" | 4 | 2
"groupA" | "data1" | 6 | 8

And then apply interpolation to **these** datasets. And so on.

**Comment by msevestre** [comment]
> which apparently must be grouped by the {group, name}

Shouldn't this be grouped by `group` and nothing else? Otherwise, this will become very confusing don't you think?

**Comment by Yuri05** [comment]
> Shouldn't this be grouped by group and nothing else? Otherwise, this will become very confusing don't you think?

Maybe I should read the spec of the DataCombined object once to understand what use cases should be supported... 😄 
But at least in the example by @IndrajeetPatil above grouping only by "group" would lead to data sets with non-unique time values. No idea then how calculate residuals for such values

**Comment by msevestre** [comment]
Yep. That's why I'd like to understand the use case as well.. should we have a meeting today?

**Comment by IndrajeetPatil** [comment]
> should we have a meeting today?

Could work for me, but maybe it's a bit late in CET to organize an impromptu meeting today? 

Maybe Monday (or any other day next week) is better?

**Comment by PavelBal** [comment]
Following pairs are created (== read "will be plotted as a single point):

- For each group:
  - For each simulated data (makes really sense for only one simulated data per group in this case, but technically this should be supported):
    - Calculate the distance (resp. create a pair, or draw a symbol) for each data point in all observed data sets within the group.

This should resolve most of the questions here.

Remaining question - how to interpolate.


E.g. if my simulated (predicted) data is
time|value
-|-
0|0
2|4
4|8

and my observed data is 
time|value
-|-
1| 1.9
3| 6.1
3.5|7
4| 8.2
5|1

Interpolation:
Linear interpolation as described by Newton:

![image](https://user-images.githubusercontent.com/25903040/158180672-7bfadec3-e533-4a0c-ac9a-2429f95feafd.png)


time|predicted|observed
-|-|-
1|`0 + 4 * (1 - 0)/(2 - 0)` = **2**|1.9
3|`4 * (4 - 3)/(4 - 2) + 8 * (3 - 2)/(4 - 2)` = **6**|6.1
3.5|`4 * (4 - 3.5)/(4 - 2) + 8 * (3.5 - 2)/(4 - 2)` = **7**|7
4|**8** (match, no interpolation)|8.2
5|`na`|1

I am sure there must be some built-in functions in R for this. This bears potential probles as every interpolation if the sampling rate of simulated results is lower that that of observed data, which is a very rare use case. However, we have to pay attention that we do not **extrapolate**, and the data point at x = 5 is not matched to anything.

This is also the problem of pure intrapolation - if the last data point is 4.1, it get's lost, while we could safely match it to the simulated point of x = 4. This could be solved by having a combination of interpolation **and** a threshold, but honestly - let's not bother and intrapolate only. For points that cannot be matched to anything (i.e., would require extrapolation), issue a warning.

**Comment by IndrajeetPatil** [comment]
I am not sure what you are doing at `obsTime = 3.5` in your example. There are only 3 values in simulated data, and  `obsTime = 3.5` is at third position, so you are extra-polating and, as you mention, we shouldn't be extrapolating. 

---

Is this something in the ballpark of what you had in mind?

``` r
.createPairedData <- function(obsTime, obsValue, simTime, simValue) {
  # Initialize to `NA`, and not 0.
  predValue <- rep(NA_real_, length(obsTime))

  # Figure out time points where both observed and simulated data were sampled.
  obsExactMatchIndices <- which(obsTime %in% simTime)
  simExactMatchIndices <- which(simTime %in% obsTime)
  obsNoExactMatchIndices <- which(!obsTime %in% simTime)

  # For exactly matched time points, there is no need for interpolation.
  predValue[obsExactMatchIndices] <- simValue[simExactMatchIndices]

  # For time points that are not matched, the simulated data needs to be
  # interpolated. This is because simulated data is typically sampled at a
  # higher frequency than the observed data.
  #
  # Interpolation is carried out using the Newton–Raphson method.
  for (idx in obsNoExactMatchIndices) {
    # If index is the same as the length of the vector, then `idx + 1` will be
    # out-of-bounds. So loop only if the index is less than the length of the
    # vector.
    #
    # Note that this does *not* mean that the value at the last index
    # in `predValue` vector is always going to be `NA`. It is also possible
    # that there is an exact match at this time point.
    if (idx < length(predValue)) {
      # f(x) =
      predValue[idx] <-
        # f0 * ((x1 - x) / (x1 - x0)) +
        simValue[idx] * ((simTime[idx + 1] - obsTime[idx]) / (simTime[idx + 1] - simTime[idx])) +
        # f1 * ((x - x0) / (x1 - x0))
        simValue[idx + 1] * ((obsTime[idx] - simTime[idx]) / (simTime[idx + 1] - simTime[idx]))
    }
  }

  # Time points at which predicted values can't be interpolated, and need to be
  # extrapolated.
  #
  # This will happen in rare case scenarios where simulated data is sampled at a
  # lower frequency than observed data.
  predValueMissingIndices <- which(is.na(predValue))

  # Warn the user about failure to interpolate.
  if (length(predValueMissingIndices) > 0) {
    warning(
      "Predicted values couldn't be interpolated at following time points:\n",
      paste(obsTime[predValueMissingIndices], sep = ", "),
      call. = FALSE
    )
  }

  # Link observed and interpolated predicted for each observed time point using
  # a data frame.
  pairedData <- dplyr::tibble(
    "obsTime" = obsTime,
    "obsValue" = obsValue,
    "predValue" = predValue
  )

  return(pairedData)
}

.createPairedData(
  obsTime = c(1, 3, 3.5, 4, 5),
  obsValue = c(1.9, 6.1, 7, 8.2, 1),
  simTime = c(0, 2, 4),
  simValue = c(0, 4, 8)
)
#> Warning: Predicted values couldn't be interpolated at following time points:
#> 3.55
#> # A tibble: 5 x 3
#>   obsTime obsValue predValue
#>     <dbl>    <dbl>     <dbl>
#> 1     1        1.9         2
#> 2     3        6.1         6
#> 3     3.5      7          NA
#> 4     4        8.2         8
#> 5     5        1          NA
```

<sup>Created on 2022-05-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by IndrajeetPatil** [comment]
I will also create another variant with the built-in `approx()` function to see how much difference it makes.

**Comment by PavelBal** [comment]
> I am not sure what you are doing at obsTime = 3.5 in your example. 

Intrapolating between the available points 2 and 4.

> There are only 3 values in simulated data, and obsTime = 3.5 is at third position, so you are extra-polating and, as you mention, we shouldn't be extrapolating.

I don't get it, what does it have to do with the positition? The simulated x range is between 0 and 4, so getting the y values for x = 3.5 is not an extrapolation.

**Comment by IndrajeetPatil** [comment]
> I don't get it, what does it have to do with the positition?

Because the x0, x1, f0, f1, etc. are referring to positions of elements in a vector. Or at least that's how interpret them.
At any rate, I have fixed this issue.

---

One more thing that I need your input on is to decide when do we consider that observed and simulated time points are the same?

For example, currently, `simTime = 2.3564` and `obsTime = 2.3563` are considered different time points and won't be exactly matched. But this is going to depend on the tolerance we choose. So what should the tolerance be?

``` r
simTime = 2.3564
obsTime = 2.3563

dplyr::near(simTime, obsTime)
#> [1] FALSE
dplyr::near(simTime, obsTime, tol = 0.001)
#> [1] TRUE
```

<sup>Created on 2022-05-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by IndrajeetPatil** [comment]
> I don't get it, what does it have to do with the positition?

Because the x0, x1, f0, f1, etc. are referring to positions of elements in a vector. Or at least that's how interpret them.
At any rate, I have fixed this issue.

---

One more thing that I need your input on is to decide when do we consider that observed and simulated time points are the same?

For example, currently, `simTime = 2.3564` and `obsTime = 2.3563` are considered different time points and won't be exactly matched. But this is going to depend on the tolerance we choose. So what should the tolerance be?

``` r
simTime = 2.3564
obsTime = 2.3563

dplyr::near(simTime, obsTime)
#> [1] FALSE
dplyr::near(simTime, obsTime, tol = 0.001)
#> [1] TRUE
```

<sup>Created on 2022-05-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by PavelBal** [comment]
I vote for tolerance = 0.001.

Can be change in the future, if someone has a better idea.

**Comment by IndrajeetPatil** [comment]
Shouldn't the tolerance depend on the time unit for measurements?

Something like the following (e.g.):

```r
thresholdByTimeUnit <- list(
  s = 10,
  min = 0.1,
  h = 0.01,
  `day(s)` = 0.001,
  `week(s)` = 0.0001,
  `month(s)` = 0.000001,
  `year(s)` = 0.00000001,
  ks = NA # no idea what this unit it
)
```

**Comment by PavelBal** [comment]
Yes I like the idea. Would make the threshold more tolerant, though, e.g., 1 minute, 0.1 hours, and so on..
