### ISSUE TITLE
Cannot initPKSim()

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#805]
PK-Sim nightly, latest ospsuite-r:

```
> initPKSim()
Error in rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce") : 
  Type:    System.Reflection.ReflectionTypeLoadException
Message: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Method:  System.RuntimeType[] GetTypes(System.Reflection.RuntimeModule)
Stack trace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at OSPSuite.Utility.Container.AssemblyScanner.scanTypesInAssembly(Assembly assembly)

Type:    System.TypeLoadException
Message: Method 'CalculateFor' in type 'PKSim.Core.Model.UnknownDistributionFormula' from assembly 'PKSim.Core, Version=11.0.90.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method:  
Stack trace:
```

I really need to get this running... Any idea what is going on?

**Comment by PavelBal** [comment]
Works if I install the package from zip downloaded from AppVeyor, but not if I build the package from source. What could it be?

**Comment by msevestre** [comment]
>Message: Method 'CalculateFor' in type 'PKSim.Core.Model.UnknownDistributionFormula' from assembly 'PKSim.Core, Version=11.0.90.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
M

Somehow your local is using an outaded version of ospsuite.core.dll.
Can you wipe out your local repo and grab it again from github? (don't forget to initialize submodule)

**Comment by PavelBal** [comment]
Yes, will have to.. thanks
