### ISSUE TITLE
How to make sure observed and simulated data have the same units?

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#822]
In order to plot them together for a comparison, these datasets need to be using the same units. While experimenting with datasets to create plots, here is what I have seen.

Pseudocode to generate `DataCombined` object and a dataframe:

```r
myCombDat <- DataCombined$new()
myCombDat$addSimulationResults(simResults)
myCombDat$addDataSets(dataSet)

df <- myCombDat$toDataFrame()

obsData <- dplyr::filter(df, dataType == "observed")
simData <- dplyr::filter(df, dataType == "simulated")
```

# Possibility-1

```r
> unique(obsData$yErrorUnit)
[1] "%"
> unique(simData$yErrorUnit)
[1] NA
```

# Possibility-2

```r
> unique(obsData$yErrorUnit)
[1] "%"
> unique(simData$yErrorUnit)
[1] ""
```

So here are my questions:

- Should `$toDataFrame()` be returning a dataframes where the observed and simulated data are already in the same units? This way, every single plotting function wouldn't have to do these checks and carry out unit conversions.
- Are there other possibilities than the ones I have seen?
- What to do when unit column is `NA`, like in Possibility-1?
- Are there any helper functions in the package to take care of unit conversions instead of doing them manually?

**Comment by IndrajeetPatil** [comment]
I am wondering what the best API to make the unit conversion is. There are two options:

# Change units inside plotting functions

In this API, the plotting functions receive a `DataCombined` object, extract dataframe internally, change units internally, and this dataframe will be used for plotting.

```r
# ... plotting related arguments
plotIndividualTimeProfile(dataCombined, ..., xUnit = NULL, yUnit = NULL)
plotPopulationTimeProfile(dataCombined, ..., xUnit = NULL, yUnit = NULL)
plotPredictedVsObserved(dataCombined,   ..., xUnit = NULL, yUnit = NULL)
plotResidualsVsPredicted(dataCombined,  ..., xUnit = NULL, yUnit = NULL)
...

```

- **Pros**: More flexible. The units can be specified differently for each plot, although I am not sure if this is something that is done often.
- **Cons**: The same routine is repeated across each plotting function and makes the signature slightly bulkier.

# Change units in `DataCombined` object

In this API, users use the class member method to set units:

```r
dataCombined$setUnits(xUnit, yUnit)
```

So that the plotting functions don't need to do this any more since they will receive a dataframe from the object which already have the data in desired units:

```r
# ... plotting related arguments
plotIndividualTimeProfile(dataCombined, ...)
plotPopulationTimeProfile(dataCombined, ...)
plotPredictedVsObserved(dataCombined,   ...)
plotResidualsVsPredicted(dataCombined,  ...)
```

- **Pros**: Avoid repetition. A single setter call makes sure that none of the plotting functions would need to do this conversion.
- **Cons**: Not flexible. If the users want different plots to have different units (is this a realistic worry?), they will need to do `$setUnits()` before each plot.

**Comment by PavelBal** [comment]
The units should be an argument of the plotting functions and not changed in `DataCombined`, so first option.

**Comment by IndrajeetPatil** [comment]
Is Possibility-1 a realistic possibility? 

I came across it in some example datasets, but the only thing we can do in such case is to produce error, since `toUnit()` can't handle `NA` anyway, and understandably so.

``` r
ospsuite::toUnit(
  quantityOrDimension =  "Time",
  values = c(15, 30, 60),
  targetUnit = "min",
  sourceUnit = NA_character_
)
#> Error in rClr::clrCall(dimensionTask, "ConvertToBaseUnit", dimension, : Type:    System.MissingMethodException
#> Message: Could not find a suitable instance method ConvertToBaseUnit on type OSPSuite.R.Services.DimensionTask for method parameters String, Object, Double[]
#> Method:  Void ThrowMissingMethod(System.Type, System.String, System.String, System.Type[])
#> Stack trace:
#>    at Rclr.ReflectionHelper.ThrowMissingMethod(Type classType, String methodName, String modifier, Type[] types)
#>    at Rclr.ClrFacade.InternalCallInstanceMethod(Object obj, String methodName, Boolean tryUseConverter, Object[] arguments)
```

<sup>Created on 2022-03-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

So `unitConverter()` will fail if there are **any** `NA`s present in `xUnit` or `yUnit` columns of data frame returned by `DataCombined$toDataFrame()`.

**Comment by PavelBal** [comment]
Simulated results never have an error, and therefore no `$yErrorUnit` property. You would therefore never end up trying to convert y error values...

The unit cannot be `NA`. If it is - something whent wrong and there is a bug in the underlying implementation.

**Comment by IndrajeetPatil** [comment]
Ready for review. Current behaviour:

``` r
library(ospsuite)
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000

# small dataframe to illustrate the conversion
(df <- dplyr::tibble(
  xValues = c(15, 30, 60), xUnit = "min", xDimension = "Time",
  yValues = c(0.25, 45, 78), yUnit = c("", "%", "%"), yDimension = c("Fraction", "Fraction", "Fraction"),
  molWeight = c(12.5, 10, 5)
))
#> # A tibble: 3 x 7
#>   xValues xUnit xDimension yValues yUnit yDimension molWeight
#>     <dbl> <chr> <chr>        <dbl> <chr> <chr>          <dbl>
#> 1      15 min   Time          0.25 ""    Fraction        12.5
#> 2      30 min   Time         45    "%"   Fraction        10  
#> 3      60 min   Time         78    "%"   Fraction         5

ospsuite:::.unitConverter(df)
#> # A tibble: 3 x 7
#>   xValues xUnit xDimension yValues yUnit yDimension molWeight
#>     <dbl> <chr> <chr>        <dbl> <chr> <chr>          <dbl>
#> 1      15 min   Time          0.25 ""    Fraction        12.5
#> 2      30 min   Time          0.45 ""    Fraction        10  
#> 3      60 min   Time          0.78 ""    Fraction         5
ospsuite:::.unitConverter(df, xUnit = ospUnits$Time$h)
#> # A tibble: 3 x 7
#>   xValues xUnit xDimension yValues yUnit yDimension molWeight
#>     <dbl> <chr> <chr>        <dbl> <chr> <chr>          <dbl>
#> 1    0.25 h     Time          0.25 ""    Fraction        12.5
#> 2    0.5  h     Time          0.45 ""    Fraction        10  
#> 3    1    h     Time          0.78 ""    Fraction         5
ospsuite:::.unitConverter(df, yUnit = ospUnits$Fraction$`%`)
#> # A tibble: 3 x 7
#>   xValues xUnit xDimension yValues yUnit yDimension molWeight
#>     <dbl> <chr> <chr>        <dbl> <chr> <chr>          <dbl>
#> 1      15 min   Time            25 %     Fraction        12.5
#> 2      30 min   Time            45 %     Fraction        10  
#> 3      60 min   Time            78 %     Fraction         5
ospsuite:::.unitConverter(df, xUnit = ospUnits$Time$h, yUnit = ospUnits$Fraction$`%`)
#> # A tibble: 3 x 7
#>   xValues xUnit xDimension yValues yUnit yDimension molWeight
#>     <dbl> <chr> <chr>        <dbl> <chr> <chr>          <dbl>
#> 1    0.25 h     Time            25 %     Fraction        12.5
#> 2    0.5  h     Time            45 %     Fraction        10  
#> 3    1    h     Time            78 %     Fraction         5
```

<sup>Created on 2022-03-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by msevestre** [comment]
I think NULL vs NA is in this case the same. We use NULL to specify no sourceUnit present. We could support NA as well. When I implemented this function, it was meant to be. " No sourceUbit provided". 
JavaScript has the same problem with null and undefined. This is a massive pain
