### ISSUE TITLE
`DataCombined` - signature for `setGroups`

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#827]
The method `$setGroups` requires a named list, where the name of the list element is the name of the data in `DataCombined` object, and the value is the name of the group it should be assigned to. Initially it looked like a convenient signature for me, but now I have my doubts.

First problem - I do not know how to use variables as names when constructing a list? so:

```
outputPath <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
aciclovirData <- DataCombined$new()
aciclovirData$addSimulationResults(simulationResults = simulationResults,
                                   quantitiesOrPaths = outputPath)

aciclovirData$setGroups(list(outputPath = "Aciclovir PSV")) # THIS WON'T WORK
```

Second problem - I do not  know how to quickly assign multiple data set to groups within the method call, without creating a list before:

```
obsData <- lapply(c("ObsDataAciclovir_1.pkml",
                    "ObsDataAciclovir_2.pkml",
                    "ObsDataAciclovir_3.pkml"),
                  \(x){loadDataSetFromPKML(getTestDataFilePath(x))})
obsDataNames <- c("Aciclovir data 1", "Aciclovir data 2", "Aciclovir data 3")
aciclovirData <- DataCombined$new()
aciclovirData$addDataSets(obsData, obsDataNames)


aciclovirData$setGroups(obsDataNames = "Aciclovir") ##HOW?
```

Proposal of another signature: `$setGroups(dataSetNames, groups)`

where `dataSetNames` and `groups` must have the same lenghts, or `groups` is only one string, in this case it will be applied to all groups. The above described workflows would then look like:

```
outputPath <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
aciclovirData <- DataCombined$new()
aciclovirData$addSimulationResults(simulationResults = simulationResults,
                                   quantitiesOrPaths = outputPath)

aciclovirData$setGroups(outputPath, "Aciclovir_ PSV")
```

and

```
obsData <- lapply(c("ObsDataAciclovir_1.pkml",
                    "ObsDataAciclovir_2.pkml",
                    "ObsDataAciclovir_3.pkml"),
                  \(x){loadDataSetFromPKML(getTestDataFilePath(x))})
obsDataNames <- c("Aciclovir data 1", "Aciclovir data 2", "Aciclovir data 3")
aciclovirData <- DataCombined$new()
aciclovirData$addDataSets(obsData, obsDataNames)


aciclovirData$setGroups(obsDataNames, "Aciclovir")

#OR
aciclovirData$setGroups(obsDataNames, c("Aciclovir", NULL, "Aciclovir"))

#OR
aciclovirData$setGroups(obsDataNames, c("Aciclovir 1", "Aciclovir 2, "Aciclovir 2"))
```

**Comment by PavelBal** [comment]
Please give me your feedback. I am really not happy with the current signature (or just do not know how to use it).

**Comment by msevestre** [comment]
> - I do not know how to use variables as names when constructing a list

What about [[ ]] ?
I think that this is the syntax to create list with dynamic keys

> without creating a list before:

What's wrong with this? Creating a variable will probably make the code much more readable anyways.

I don't mind relying on two lists . But having to fill entries with NULL is not good from  my point of view
. You should not have to specify parameters for things that do not change.

**Comment by PavelBal** [comment]
> What's wrong with this? Creating a variable will probably make the code much more readable anyways.

I don't mind creating lists, but it seems like an overhead for simple assignments. I created some examples with the current implementation (named list as argument, `aciclovirData`), and the pseudo-code version (`aciclovirDataAlt`):

### Assign to group by name string.
```
#current
aciclovirData$setGroups(groups = list("Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)" = "Aciclovir PVB"))

#alternative
aciclovirDataAlt$setGroups(names = "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)", groups = "Aciclovir PVB")
```

### Assign to group by name from variable
```
outputPath <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"

#current
groups <- list()
groups[[outputPath]] <- "Aciclovir"
aciclovirData$setGroups(groups = groups)

#alternative
aciclovirDataAlt$setGroups(names = outputPath, groups = "Aciclovir PVB")
```

### Assign multiple data sets to a group/groups
```
names <- lapply(obsData, \(x){x$name})

#current
groups <- list("Aciclovir", "Aciclovir", "Aciclovir")
names(groups) <- names
aciclovirData$setGroups(groups = groups)

#alternative
aciclovirDataAlt$setGroups(names = names, groups = c("Aciclovir PVB", "Aciclovir PVB", "Aciclovir PVB"))
```


> But having to fill entries with NULL is not good from my point of view
. You should not have to specify parameters for things that do not change.

`NULL` means "no group" (e.g. remove from existing grouping) and not "do not change".

**Comment by PavelBal** [comment]
Ok then, let's implement it this way. @IndrajeetPatil

**Comment by IndrajeetPatil** [comment]
So, if I understand the discussion correctly, the new API for `$setGroups()` will be:

To set groupings-

```r
$setGroups(names = c(...),    groups = c(...))
$setGroups(names = list(...), groups = list(...)) # also acceptable
``` 

To remove groupings-

```r
$setGroups(names = c(name1, name2),    groups = c(NA, NA))
$setGroups(names = list(name1, name2), groups = list(NA, NA)) # also acceptable
$setGroups(names = list(name1, name2), groups = list(NULL, NULL)) # also acceptable
```

**Comment by msevestre** [comment]
Also 

To set groupings-

```r
$setGroups(names = "A",    groups = "B")
``` 

To remove groupings-

```r
$removeGroups(names = c(name1, name2))
```

**Comment by IndrajeetPatil** [comment]
R doesn't have scalars, so 

```r
$setGroups(names = "A",    groups = "B")
```  

is the same thing as 

```r
$setGroups(names = c("A"),    groups = c("B"))
```

🙃

> To remove groupings

Okay, another method then.

**Comment by PavelBal** [comment]
I would call the method `removeFromGroups` instead of `removeGroups`, what do you think? `removeGroups` sounds like "remove the whole group", but it should only remove the specified data sets (from their groups).

**Comment by IndrajeetPatil** [comment]
How about? Verbose but hard to misunderstand.

```r
$removeGroupAssignment()
```

The plural of group in `removeFromGroups` makes that name a bit iffy.

**Comment by PavelBal** [comment]
> `$removeGroupAssignment() `

Fine with me.

**Comment by IndrajeetPatil** [comment]
Closed in favour of https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/853
