### ISSUE TITLE
About signature for `toUnit()` function

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#837]
Is it just me or the signature for `toUnit()` function

```r
toUnit(quantityOrDimension, values, targetUnit, molWeight, sourceUnit, molWeightUnit)
```

should instead be?

```r
toUnit(quantityOrDimension, values, targetUnit, sourceUnit, molWeight, molWeightUnit)
```

As a new user, I was constantly befuddled by the fact that the target and source unit parameters were not in succession.

**Comment by PavelBal** [comment]
Yeah we did not have the argument `sourceUnit` in the first implementation (it was always assumed to be in base unit. To not to break existing code, we decided not to change the order of the arguments.

**Comment by msevestre** [comment]
yep that

**Comment by IndrajeetPatil** [comment]
Hmm, so we need to live with this order for the rest of the eternity? Pity.

**Comment by msevestre** [comment]
no I don't think so. 
I think most people use named argument anyways
And if not, this will crash as the argument have different types
I am ok to change this

**Comment by msevestre** [comment]
specifrically because we are introducing some braking changes

**Comment by PavelBal** [comment]
@IndrajeetPatil Please also open an issue in esqlabs-r to check the code using `toUnit`.

**Comment by IndrajeetPatil** [comment]
I checked all instances of [usage](https://github.com/esqLABS/esqlabsR/search?q=toUnit), and nowhere does _esqlabsR_ uses positional argument matching. 

So this change doesn't break anything in _esqlabsR_! 🙌

**Comment by IndrajeetPatil** [comment]
I also went through [usage instances](https://github.com/search?p=1&q=org%3AOpen-Systems-Pharmacology+toUnit&type=Code) in the OSP organization, and none of them will break either!
