### ISSUE TITLE
Do not export functions/classes that should not be accessed directly

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#85]
I suggest that users should not have access to the classes defined in `domain.R`. All manipulations should be performed through calling public functions.

Therefore, remove the `@export`-tag from the documentation of the classes.

**Comment by msevestre** [comment]
I disagree. Parameter, container, simulation are definitely part of the public API
Parameter is what is returned from the getParameters

Now can you not export a base class such as ObjectBase when it's used by an exported class?

In that case, we can remove export of all base class indeed or whatever class is meanyto be internal such as ApiConfig

**Comment by PavelBal** [comment]
You can remove everything from export and still use the objects, you simply cannot create new ones. Example: I did not export any of the classes

```
> Parameter$new
Error: object 'Parameter' not found
> ospsuite::Parameter$new
Error: 'Parameter' is not an exported object from 'namespace:ospsuite'
```

I still can call `getParameters` and retrieve their values:

```
>   parameters <- getParameters(c("Organism", "Liver", "Intracellular", "Volume"), sim)
> parameter <- parameters[[1]]
> parameter$value
[1] 1.585139
> parameter
[1] "Parameter 'S1|Organism|Liver|Intracellular|Volume' has a value of 1.58513870418047"
```

**Comment by msevestre** [comment]
Oh ok. Weird. You can access non exported object then.... mystery of R;-)

Agree with you in that case.

**Comment by PavelBal** [comment]
Not exporting objects means that they cannot be used outside of the package. Within the package, you still have access.

**Comment by msevestre** [comment]
Ok. But we want to use them outside of the package. E.g. in einem script.

Highly confused now;-)

**Comment by PavelBal** [comment]
E.g., if we do not export the class definition `Simulation`, then we will not be able to do

`mySim <- Simulation$new`

Instead, we will do

`mySim <- loadSimulation(path)`

That's it.

**Comment by msevestre** [comment]
> Not exporting objects means that they cannot be used outside of the package. 

Ok so we can USE them but we cannot instantiate them? Correct?

**Comment by PavelBal** [comment]
Yes.
