### ISSUE TITLE
`DataCombined`: group = NULL for a data set should remove the data set from the group

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#851]
This should work like this:

```
dc <- DataCombined$new()
dc$addSimulationResults(simulationResults = simulationResults,
                                   quantitiesOrPaths = outputPath)
#the data set is without a group
dc$setGroups(groups = list("Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)" = "Aciclovir PVB"))
#Data set is now assigned to the group "Aciclovir PVB"
dc$setGroups(groups = list("Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)" = NULL))

#Data set is without a group again
```

**Comment by IndrajeetPatil** [comment]
You need to use `NA` to remove an existing grouping.

This is what you had [suggested](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/728#issuecomment-1023355462):

> To remove data from a group:
>
> myComDat$setGroups(list("name" = NA))

**Comment by msevestre** [comment]
NULL or NA should both work don't think? 
Whatever is not a valid "string" should be a delete operation, no?

**Comment by IndrajeetPatil** [comment]
Sure, we can get `NULL` to work, but I was explaining why the current API is the way it is.

> Whatever is not a valid "string" should be a delete operation, no?

Currently, `NA` of any type is converted to `NA_character_`.
And we can also do the same for `NULL`.

We shouldn't be converting anything else to a delete operation, and should produce an error instead.

e.g. `$setGroups(list("x" = 1L))` should lead to an error, and not a delete operation.

**Comment by IndrajeetPatil** [comment]
Closing in favor of #853 since it's part of it.
