### ISSUE TITLE
Revert Always return tibble for ToDataFrame functions #841

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#857]
This is what I was talking about all the time - a tiblle is NOT a data frame! esqlabsR is now broken exactly because of this - some code there expected a data frame but the subsetting does not work any more because it is different between df and tibble.

This is a breaking change that is not justified.

**Comment by msevestre** [comment]
Can you show an example? I keep hearing that they are completely interchangeable (e.g. a method expecting a Data frame should work with a Tibble)

**Comment by IndrajeetPatil** [comment]
Subsetting with `data.frame` has some undesirable properties that `tibble` gets rid of, so, whenever possible, we should be using tibbles.

The solution is simple: All instances of `df[, "col"]` should be replaced with `df[["col"]]`. 

If you don't want to do that, you can just wrap the `tibble` outputs with `as.data.frame()`, and that will return a `data.frame` again.

cf. https://adv-r.hadley.nz/vectors-chap.html#safe-subsetting

![image](https://user-images.githubusercontent.com/11330453/161545179-31944908-0aa8-4f02-8db6-0a267905f8be.png)

**Comment by IndrajeetPatil** [comment]
https://github.com/esqLABS/esqlabsR/pull/199 fixes the breakages.

**Comment by PavelBal** [comment]
> Can you show an example? I keep hearing that they are completely interchangeable (e.g. a method expecting a Data frame should work with a Tibble)

```
>df <- ospsuite::dataSetToDataFrame(dataSets)
>tapply(df[, "yValues"], df[, "xValues"], mean)

Error in tapply(df[, "yValues"], df[, "xValues"], mean) : 
  arguments must have same length
```

With the data frame (and this is what the function name implies, that it returns a data frame):

```
> df <- as.data.frame(df)
> tapply(df[, "yValues"], df[, "xValues"], mean)
1 2 3 4 5 
```


So no, they are not interchangeable.

We had this discussion already, and I completely disagree if a function that is called `xxxToDataFrame` returns something that has other synthax as a data frame.

This PR does break a code that already uses the function, thats a fact.

**Comment by msevestre** [comment]
>This PR does break a code that already uses the function, thats a fact.

I am not disagreeing on this. 

I feel that tibble overall is a better abstraction (even for me as a user, I can see table printed in a much nicer way etc..)

Suggestion:

For each `xxToDataFrame` method that we have, 

-1 rename to xxToTibble
-2 add a xxToDataTable that does nothing more than as.data.frame(tibble)

That way we are compatible and we can use tibble if we feel like it

thoughts?

**Comment by PavelBal** [comment]
> -1 rename to xxToTibble
> -2 add a xxToDataTable that does nothing more than as.data.frame(tibble)

I guess you mean `xxToTibble` and `xxToDataFrame`. Yes, this way it is consistent in naming and should not lead to any confusions.

@IndrajeetPatil I think we can implement it like this.

**Comment by IndrajeetPatil** [comment]
> That way we are compatible and we can use tibble if we feel like it

Sure, sounds like a good compromise.

> tapply(df[, "yValues"], df[, "xValues"], mean)

Subsetting this way is a code smell, IMO. 
A data frame is a list of atomic vectors with equal lengths. If you want an atomic vector back from subsetting, `[[` makes this intent clear. Using `[` is confusing because it returns a sublist, which you will see if you set `drop = FALSE`. Indeed, this is a source of bugs where people think they are getting a data frame back from `[`, but instead they are getting an atomic vector.

``` r
# bad ---------------
mtcars[, "am"] # unclear intent: vector or data frame?
#>  [1] 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1

mtcars$am # allows partial matching
#>  [1] 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1

# okay ---------------
getElement(mtcars, "am") # too verbose
#>  [1] 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1

# good ---------------
mtcars[["am"]] # clear intent and future proof
#>  [1] 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1
```

<sup>Created on 2022-04-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by PavelBal** [comment]
> but instead they are getting an atomic vector.

I think this was the intention.

**Comment by IndrajeetPatil** [comment]
That intent is not clear from using `[` subsetting, which is used both for getting an atomic vector and data frames back. 

With `[[`, there is no doubt.
