### ISSUE TITLE
Call initPackage() from loadSimulation and create hidden env

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#86]
We will probably have to deal with some global entities now and then. As discussed in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/64, I propose to use a hidden environment `.ospsuiteEnv` for this purpose that will be created upon initialization of the package.

Also, I don't like that the user has to explicitly call `initPackage()`. I would call `initPackage()` as part of `loadSimulation` or other potential functions that will be called first. `initPackage` will only be called once:

```
loadSimulation <- function(pkmlSimulationFile) {
  if (!exists(".ospsuiteEnv") || (.ospsuiteEnv$isInitialized == FALSE)){
    .ospsuiteEnv <<- new.env()
    .ospsuiteEnv$isInitialized <- TRUE
    initPackage()
  }
...
```

**Comment by msevestre** [comment]
What about in package load? Isn't it a good place for this?

I agree about the call of initpackage. Muss gekapselt werden

**Comment by PavelBal** [comment]
Yes, we actually can use `.onLoad()` for creating the `.ospsuiteEnv` and calling `initPackage()`.

**Comment by msevestre** [comment]
Why is the ospsuiteEnv required? I am sure we will need one but i don't think this is required for this use case.

If this is for global stuff, ggplot uis doing it like so
https://github.com/tidyverse/ggplot2/blob/7ed8930c1385935e875465efaa7d72a552d08612/R/ggplot-global.R

**Comment by PavelBal** [comment]
Yes, it is not required for the current use-case, but I think we will need it sooner or later.

ggplot is doing it the same way, but the don't create it within a function (thus `<-` instead of `<<-`)
 and I think they are not using the `.` prefix because its not exported.... Fair enogh, we can also do it.

**Comment by msevestre** [comment]
I am going to read more about env today and we can have a chat next week maybe?

**Comment by PavelBal** [comment]
> I am going to read more about env today and we can have a chat next week maybe?

Yes, lets.
