### ISSUE TITLE
Parameter path not included in sensitivity analysis results

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite-R#885]
A sensitivity analysis result for a given parameter path, output path and pk parameter typically looks like this:

![image](https://user-images.githubusercontent.com/18409098/164513835-cf794157-5a06-4746-a61a-6b16ce95cd4d.png)

and the CSV results look like this:

![image](https://user-images.githubusercontent.com/18409098/164515457-9cec4924-7fd1-4ef8-b27b-773448b626a0.png)

This is sensitivity with respect to a parameter with path `DERMAL_APPLICATION_AREA|skin_compartment|SC_skin_sublayer|SC_total_thickness`

When we are writing scripts we usually don't have the parameter name beforehand, but we do have the path.  Also it is not obvious how to go from a path to a name.

Can we either:

1- return the parameter path along with the results, as a field alongside `Parameter name` (and a separate column in the CSV)

or 
 
2 - provide a function from which to get the parameter name from the parameter path?  eg something like:
```
parameterName <- parameterNameFromPath(parameterPath = "DERMAL_APPLICATION_AREA|skin_compartment|SC_skin_sublayer|SC_total_thickness")  
```
which would then return `skin_compartment-SC_skin_sublayer-SC_total_thickness`

Related: the `SensitivityAnalysisResults` class method `pkParameterSensitivityValueFor` would also benefit if we can optionally specify the parameter path if we don't have the name.  ie instead of
```sensitivityResults$pkParameterSensitivityValueFor(pkParameterName = ### ,outputPath = ### ,parameterName = ###)```

we have 
```sensitivityResults$pkParameterSensitivityValueFor(pkParameterName = ### , outputPath = ###, parameterNameOrPath = ###)```

Of course if we go with option 2 above we can leave this function as is and simply do
```sensitivityResults$pkParameterSensitivityValueFor(pkParameterName = ### , outputPath = ### , parameterName = parameterNameFromPath(parameterPath) )```

**Comment by msevestre** [comment]
Yeah I think that makes sense. Allow to find by path or my sensitivity parameter name
I just reverted something along the lines in a PR for ospsuite.core. I think we need to support both

**Comment by msevestre** [comment]
here
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/pull/1605

**Comment by msevestre** [comment]
@abdullahhamadeh there is now
`sensitivityResults$pkParameterSensitivityValueFor(pkParameterName = ### , outputPath = ###, parameterName = ###, parameterPath) and one of parmaeterName or parameterPath needs to be specified
