### ISSUE TITLE
Make package work again after breaking change in R API on Sensitivity analysis

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#889]
@IndrajeetPatil Do you want to check this out? We could discuss this you and I if you want.

after the renaming of some of our methods to be explicit about parameter (SA parameter name vs ParameterPath), the code in ospsuite-r needs to be updated and potentially new API methods created to help support new features

**Comment by msevestre** [comment]
FYI @PavelBal @Yuri05 .

**Comment by msevestre** [comment]
see also #886 and #885

**Comment by IndrajeetPatil** [comment]
> @IndrajeetPatil Do you want to check this out? We could discuss this you and I if you want.

Yepp, sounds good.

**Comment by msevestre** [comment]
@IndrajeetPatil Let's work on that tomorrow
