### ISSUE TITLE
Use the most frequent unit for default conversion in `.unitConverter()` 

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#891]
Instead of the current approach of using the _first_ encountered unit in the column.

As suggested by @msevestre here: https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/876#discussion_r856348349

**Comment by IndrajeetPatil** [comment]
Will not be part of #876; will be addressed in a separate PR.

**Comment by PavelBal** [comment]
(very) low prio.
