### ISSUE TITLE
Decouple R lib version from PK-Sim

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#898]
When working with the development version of the package, it is a huge pain to synchronize DLLs used in R and by PK-Sim. Moreover, it makes versioning almost impossible (different version of the r package require different PK sim versions).

Maybe we should think about how we could make creation of individuals and populations work without the need to always update PK-Sim.

**Comment by PavelBal** [comment]
Sure, but we will probably always use the unreleased version :) Would make life of developers also easier when updating the DLLs.

**Comment by msevestre** [comment]
yeah but this is not possible. You need to have compatible version of ospsuite.core. Hopefully, eventually one will be able to work without always needed the latest and greatest. But if you do, then you need to be ready to feel the pain.
