### ISSUE TITLE
Build time needs drastic improvement

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#909]
Almost 20 min on each PR, or update to PR. This takes way too much of our resources. We need faster feedback from CI

What can we remove from the default appveyor build and run nightly

Obviously Coverage. What about vignettes? Should we generate this only on nighty?
Anything else

This should be done consistently across all our R packages but ospsuite-r and reporting engine are the most important one ATM

**Comment by IndrajeetPatil** [comment]
Yeah, I agree. 20 minutes is too long to wait.

We can move code coverage and vignette builds to nightly. We have good enough code coverage that we don't need to rely on vignette to check if everything is working as expected.

**Comment by msevestre** [comment]
is it possible to exclude some tests as well? Somehow? I'd like to not run the PKSim specific tests on each commit (installing pksim etc..)

**Comment by IndrajeetPatil** [comment]
We can add `testthat::skip_on_appveyor()` to those tests.

**Comment by msevestre** [comment]
this is not what I need. I want to skip them on appveyor only on the PR, not on the nighlty

**Comment by IndrajeetPatil** [comment]
Ah, then no, nothing comes to me off the top of my head.

**Comment by Yuri05** [comment]
Maybe something like this:
set an environment variable XYZ in **non nigthly** builds and use 
`skip_if(<env variable XYZ is defined>)`
https://testthat.r-lib.org/reference/skip.html

**Comment by msevestre** [comment]
good idea!

**Comment by msevestre** [comment]
I don't see wehre I can check for this
However
skip_on_ci() skips on continuous integration systems like GitHub Actions, travis, and appveyor (using the CI env var).

I can set CI on non nightly build to true ad skip on CI

**Comment by msevestre** [comment]
@IndrajeetPatil Is there a way to time the tests? I think some of our importer tests are also pretty long (or simulations or whatever) and we could run them only once per day

**Comment by msevestre** [comment]
ok I am down to 8min from 20, Not great but better that what we had before. I would like to remove any tests that last more than a few seconds
