### ISSUE TITLE
Ensure that entities (Container, Parameter etc...) cannot be renamed

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#92]
I do not see any real use case for that. It can only lead to problems  but I'd like to know what other people think

I am talking about Parameter, Container etc..
@Yuri05 @StephanSchaller @PavelBal 

At the moment it is possible.

**Comment by StephanSchaller** [comment]
To update the name from R is possible?

I can see use cases, where people may want to adjust names of entities (only because the have not thought through naming their entities wisely to begin with) but besides that I do not see a use-case.

**Comment by Yuri05** [comment]
I would NOT allow it. Renaming of entities could invalidate the model and should be done in a modelling tool (e.g. MoBi)

**Comment by msevestre** [comment]
Agreed. This can only lead to corrupted stuff. REnaming entry accodingly
