### ISSUE TITLE
the version of ospsuite.utils and the version of  OSPSuite do not match.

### ISSUE THREAD

**Issue by BoYang1225** [Open-Systems-Pharmacology/OSPSuite-R#922]
In the process of install the latest ospsuite in R under windows, the version of ospsuite.utils and the version of  OSPSuite do not match，causing the failure of installing.What should I do to solve the problem?Here is the tips as follows:

* installing *source* package 'ospsuite' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  载入了名字空间'ospsuite.utils' 1.2.0，但需要的是>= 1.3.0
Calls: <Anonymous> ... withCallingHandlers -> loadNamespace -> namespaceImport -> loadNamespace
停止执行
ERROR: lazy loading failed for package 'ospsuite'
* removing 'D:/R/R/R-4.1.2/library/ospsuite'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/yangb/AppData/Local/Temp/RtmpqOWKQZ/file76042581d5c/ospsuite_11.0.0.tar.gz’ had non-zero exit status

**Comment by BoYang1225** [comment]
I change the 'ospsuite.utils'  package to 'OSPSuite.RUtils',but another error Appeared.And I have no idea to deal the problem.

Error: package or namespace load failed for 'ospsuite':
 loadNamespace()里算'ospsuite'时.onLoad失败了，详细内容：
  调用: rClr::clrCall(dimensionTask, "AllAvailableUnitNamesFor", enc2utf8(dimension))
  错误: 
错误: loading failed
停止执行
ERROR: loading failed

**Comment by msevestre** [comment]
Where did you get the ospsuite_11.0.0 package from?

**Comment by msevestre** [comment]
Make you sure you use
https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-r/artifacts/ospsuite.zip
and

https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-rutils/artifacts/ospsuite.utils.zip

you might also need
https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/tlf-library/artifacts/tlf.zip

Note: this packages are not officially released yet

**Comment by BoYang1225** [comment]
No.The packages I want to install is not the ospsuite_11.0.0 package,but the ospsuite_10.0.072 package.


| |
杨波
|
|
***@***.***
|
On 5/6/2022 03:42，Michael ***@***.***> wrote：

Where did you get the ospsuite_11.0.0 package from?

**Comment by BoYang1225** [comment]
Thanks a lot.The packages that you sent to me can be successfully installed.It help me a lot.thanks again for your prompt reply!


| |
杨波
|
|
***@***.***
|
On 5/6/2022 03:44，Michael ***@***.***> wrote：

Make you sure you use
https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-r/artifacts/ospsuite.zip
and

https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-rutils/artifacts/ospsuite.utils.zip

you might also need
https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/tlf-library/artifacts/tlf.zip

Note: this packages are not officially released yet

**Comment by BoYang1225** [comment]
The  packages can be installed with no error.But as is shown in the picture,when I use the 'ospsuite',it doesn't work.What should I do? 
| |
杨波
|
|
***@***.***
|
On 5/6/2022 03:44，Michael ***@***.***> wrote：

Make you sure you use
https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-r/artifacts/ospsuite.zip
and

https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-rutils/artifacts/ospsuite.utils.zip

you might also need
https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/tlf-library/artifacts/tlf.zip

Note: this packages are not officially released yet

**Comment by msevestre** [comment]
Pictures attached to email do not work. 
If you want to use the released version of the suite, please install the version here (10.0.72, which is not what you were trying to install at the beginning of your thread)

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/releases/tag/v10.0.72


THis version do not rely on ospsuite.utils

**Comment by BoYang1225** [comment]
> Pictures attached to email do not work. If you want to use the released version of the suite, please install the version here (10.0.72, which is not what you were trying to install at the beginning of your thread)
> 
> https://github.com/Open-Systems-Pharmacology/OSPSuite-R/releases/tag/v10.0.72
> 
> THis version do not rely on ospsuite.utils



> when I write the command "library(ospsuite)"in R.An error occured:
Error: package or namespace load failed for 'ospsuite':
loadNamespace()里算'ospsuite'时.onLoad失败了，详细内容：
调用: rClr::clrCall(dimensionTask, "AllAvailableUnitNamesFor", enc2utf8(dimension))
错误:
错误: loading failed
停止执行
ERROR: loading failed

**Comment by IndrajeetPatil** [comment]
@msevestre We also need to do new release for _ospsuite.utils_ (https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/issues/109) before _ospsuite_ `v11` is released because `v11` relies on _ospsuite.utils_ `1.3.0`.
