### ISSUE TITLE
Type not found: OSPSuite.R.Api

### ISSUE THREAD

**Issue by BoYang1225** [Open-Systems-Pharmacology/OSPSuite-R#923]
sim <- loadSimulation("D:/R/R/R-4.1.2/library/ospsuite/extdata/Aciclovir.pkml")
what should I do to solve the problem?

Type not found: OSPSuite.R.Api
Error in rClr::clrCallStatic("OSPSuite.R.Api", paste0("Get", taskName)) : 
  Type:    System.ArgumentException
Message: Type not found: OSPSuite.R.Api
Method:  System.Object CallStaticMethod(System.String, System.String, System.Object[])
Stack trace:
   在 Rclr.ClrFacade.CallStaticMethod(String typename, String methodName, Object[] arguments)

**Comment by msevestre** [comment]
It looks like the package is not loaded properly.
did you get any error when installing the package?

Do you have the ospsuite installed? If yes, can you start PKSim without problem?
You can download a zip version of PKSim by using the following link

https://github.com/Open-Systems-Pharmacology/PK-Sim/releases/download/v10.0.257/pk-sim-portable-setup.10.0.257.zip

**Comment by BoYang1225** [comment]
> 看起来包未正确加载。安装软件包时是否出现任何错误？
> 
> 您是否安装了 ospsuite？如果是，您可以毫无问题地启动PKSim吗？您可以使用以下链接下载 PKSim 的 zip 版本
> 
> https://github.com/Open-Systems-Pharmacology/PK-Sim/releases/download/v10.0.257/pk-sim-portable-setup.10.0.257.zip

I can  start PKSim without problem.However, I can use the ospsuite package only with 32-bit R not 64-bit R.

library(ospsuite)
载入需要的程辑包：rClr
Loading the dynamic library for Microsoft .NET runtime...
Loaded Common Language Runtime version 4.0.30319.42000

**Comment by BoYang1225** [comment]
> Reference in
 I can successfully install the package with help of link below.But I can not use the package with 64 bit of R.
https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-r/artifacts/ospsuite.zip

64 bit of R:
 library(ospsuite)
载入需要的程辑包：rClr
Loading the dynamic library for Microsoft .NET runtime...
Loaded Common Language Runtime version 4.0.30319.42000

Error: package or namespace load failed for ‘ospsuite’:
 loadNamespace()里算'ospsuite'时.onLoad失败了，详细内容：
  调用: rClr::clrCall(dimensionTask, "AllAvailableUnitNamesFor", enc2utf8(dimension))
  错误: Type:    System.Collections.Generic.KeyNotFoundException
Message: Dimension 'CV mmHg*s虏/ml' not available in DimensionFactory.
Method:  OSPSuite.Core.Domain.UnitSystem.IDimension Dimension(System.String)
Stack trace:
   在 OSPSuite.Core.Domain.UnitSystem.DimensionFactory.Dimension(String name)
   在 OSPSuite.R.Services.DimensionTask.DimensionByName(String dimensionName)
   在 OSPSuite.R.Services.DimensionTask.AllAvailableUnitNamesFor(String dimensionName)


32 bit of R:
library(ospsuite)
载入需要的程辑包：rClr
Loading the dynamic library for Microsoft .NET runtime...
Loaded Common Language Runtime version 4.0.30319.42000

**Comment by BoYang1225** [comment]
And I have no ideas to deal with the problem.

**Comment by Yuri05** [comment]
@BoYang1225 Can you try the following:
* Start MoBi (if you did not install OSP Suite 10: just download and unzip [mobi-portable-setup.10.0.122.zip](https://github.com/Open-Systems-Pharmacology/MoBi/releases/download/v10.0.122/mobi-portable-setup.10.0.122.zip) then start **MoBi.exe** from the unzipped folder)
* Create new project (File => New => Amount based reactions)
<img width="400" src="https://user-images.githubusercontent.com/25061876/167255340-275e026d-c633-4e55-897a-8f4784c240bb.png">

* In the "**Building Blocks**" panel: Expand "**Spatial Structures**" and double click on "**Organism**". Then on the right, click on the "**Organism**" node in the tree, and then on the "**Parameters**" Tab.
* Finally, try to change the dimension of the "Volume" parameter and navigate to the dimension "**CV mmHg*s²/ml**" 
Is the dimension name shown correctly? Or do you see that the ² character was replaced by something else?

![grafik](https://user-images.githubusercontent.com/25061876/167255547-93281007-93ea-41e7-9f24-98b5ca5b8ec9.png)

**Comment by BoYang1225** [comment]
> @BoYang1225 Can you try the following:
> 
> * Start MoBi (if you did not install OSP Suite 10: just download and unzip [mobi-portable-setup.10.0.122.zip](https://github.com/Open-Systems-Pharmacology/MoBi/releases/download/v10.0.122/mobi-portable-setup.10.0.122.zip) then start **MoBi.exe** from the unzipped folder)
> * Create new project (File => New => Amount based reactions)
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/25061876/167255340-275e026d-c633-4e55-897a-8f4784c240bb.png">
> 
> * In the "**Building Blocks**" panel: Expand "**Spatial Structures**" and double click on "**Organism**". Then on the right, click on the "**Organism**" node in the tree, and then on the "**Parameters**" Tab.
> * Finally, try to change the dimension of the "Volume" parameter and navigate to the dimension "**CV mmHg*s²/ml**"
>   Is the dimension name shown correctly? Or do you see that the ² character was replaced by something else?
> 
> ![grafik](https://user-images.githubusercontent.com/25061876/167255547-93281007-93ea-41e7-9f24-98b5ca5b8ec9.png)

OK.I will try it tomorrow.

**Comment by PavelBal** [comment]
Should be same as here:

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/922

Solved by addition of remark to README:

- Loading `ospsuite` might fail if your systems locale is not set to *English*, e.g.: 

```ibrary(ospsuite)
载入需要的程辑包：rClr
Loading the dynamic library for Microsoft .NET runtime...
Loaded Common Language Runtime version 4.0.30319.42000

Error: package or namespace load failed for ‘ospsuite’:
loadNamespace()里算'ospsuite'时.onLoad失败了，详细内容：
调用: rClr::clrCall(dimensionTask, "AllAvailableUnitNamesFor", enc2utf8(dimension))
错误: Type: System.Collections.Generic.KeyNotFoundException
Message: Dimension 'CV mmHg*s虏/ml' not available in DimensionFactory.
...
```

On Windows, set `Settings > Language > Administrative language settings > Current language for non-Unicode programs` 
to `English (United States)` and reboot.


Please re-open if the problem persists.
