### ISSUE TITLE
Documenting plotting functions using `DataCombined`

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#927]
Part 2 of #756 

Adding examples to the manual; and more detailed examples of workflow in a vignette.

- [ ] `plotIndividualTimeProfile()`
- [ ] `plotPopulationTimeProfile()`
- [ ] `plotResidualsVsTime()`
- [ ] `plotObservedVsSimulated()`

**Comment by PavelBal** [comment]
Will not happen for v11.
