### ISSUE TITLE
UnitConverter cannot convert x values to weeks

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#928]
```
# load the simulation
sim <- loadTestSimulation("MinimalModel")
simResults <- importResultsFromCSV(
  simulation = sim,
  filePaths = getTestDataFilePath("Stevens_2012_placebo_indiv_results.csv")
)
# create a new instance and add datasets
myCombDat <- DataCombined$new()
myCombDat$addSimulationResults(
  simResults,
  quantitiesOrPaths = c(
    "Organism|Lumen|Stomach|Dapagliflozin|Gastric retention",
    "Organism|Lumen|Stomach|Dapagliflozin|Gastric emptying",
    "Organism|Lumen|Stomach|Metformin|Gastric retention"
  )
)

#Change x-axis units to weeks
plotConfiguration <- ospsuite::DefaultPlotConfiguration$new()
plotConfiguration$xUnit <- ospUnits$Time$`week(s)`

# Try to plot
plotIndividualTimeProfile(myCombDat, plotConfiguration)

Error in rClr::clrCall(dimensionTask, "ConvertToBaseUnit", dimension, : 
Type: OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Unit 'min' is not defined in dimension 'Age in years'.
Method: Double[] convertToBaseUnit(OSPSuite.Core.Domain.UnitSystem.IDimension, System.String, System.Nullable`1[System.Double], Double[])
Stack trace:
at OSPSuite.R.Services.DimensionTask.convertToBaseUnit(IDimension dimension, String displayUnit, Nullable`1 molWeight, Double[] valuesInDisplayUnit)
at OSPSuite.R.Services.DimensionTask.ConvertToBaseUnit(String dimensionName, String displayUnit, Double[] valuesInDisplayUnit)
8.
rClr::clrCall(dimensionTask, "ConvertToBaseUnit", dimension, 
sourceUnit, values) at utilities-units.R#195
7.
toUnit(quantityOrDimension = xTargetDim, values = xData$xValues, 
targetUnit = xTargetUnit, sourceUnit = xData$xUnit[[1]]) at utilities-units.R#541
6.
.xUnitConverter(data, xTargetUnit, xTargetDim) at utilities-units.R#484
5.
.f(.x[[i]], ...)
4.
map(.x, .f, ...)
3.
purrr::map_dfr(.x = xDataList, .f = function(data) .xUnitConverter(data, 
xTargetUnit, xTargetDim)) at utilities-units.R#484
2.
.unitConverter(df, defaultPlotConfiguration$xUnit, defaultPlotConfiguration$yUnit) at plot-individual-time-profile.R#30
1.
plotIndividualTimeProfile(myCombDat, plotConfiguration)
```

**Comment by IndrajeetPatil** [comment]
But [here](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/892#issuecomment-1108687137) you had mentioned that if we don't use `getDimensionForUnit()`:

> Otherwise we might get a mismatch between the dimension and the unit in the output df.

Is that not an issue anymore?

Note to self: Revert change made [here](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/892/commits/3bcf66f18193551b5991714e4e03d1379107a3df).

**Comment by PavelBal** [comment]
> Is that not an issue anymore?

I don't think it will really be an issue as the dimension is not really used anywhere, right?

**Comment by IndrajeetPatil** [comment]
We use them to create axes labels for profile plots:

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/94d6f6ad622a486569f5c6ef96a14ad72b8609b9/R/utilities-plotting.R#L138-L141

**Comment by IndrajeetPatil** [comment]
Minimal reproducible example:

``` r
df <- dplyr::tibble(
  xValues = c(15, 0.5, 60),
  xUnit = c("min", "h", "min"),
  xDimension = "Time",
  yValues = c(0.25, 45, 78),
  yUnit = c("", "%", "%"),
  yDimension = c("Fraction", "Fraction", "Fraction"),
  yErrorValues = c(0.01, 5, 8),
  yErrorUnit = c("", "%", "%"),
  molWeight = c(10, 10, 10)
)

ospsuite:::.unitConverter(df, xUnit = ospsuite::ospUnits$Time$`week(s)`)
#> Error in rClr::clrCall(dimensionTask, "ConvertToBaseUnit", dimension, : Type:    OSPSuite.Utility.Exceptions.OSPSuiteException
#> Message: Unit 'h' is not defined in dimension 'Age in years'.
#> Method:  Double[] convertToBaseUnit(OSPSuite.Core.Domain.UnitSystem.IDimension, System.String, System.Nullable`1[System.Double], Double[])
#> Stack trace:
#>    at OSPSuite.R.Services.DimensionTask.convertToBaseUnit(IDimension dimension, String displayUnit, Nullable`1 molWeight, Double[] valuesInDisplayUnit)
#>    at OSPSuite.R.Services.DimensionTask.ConvertToBaseUnit(String dimensionName, String displayUnit, Double valueInDisplayUnit)
```

<sup>Created on 2022-05-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by msevestre** [comment]
The dimension is not the right one it seems. weeks(s) is present in two dimensions
Can you retrieve the dimension by name (e.g Time) instead of from the unit?

**Comment by PavelBal** [comment]
@msevestre maybe you have an idea how to solve this.

Let's say we add a data set with the dimension "Concentration (molar"):

```
# Create a data set
concDataSet <- DataSet$new(name = "Concentration data set")
concDataSet$setValues(1, 1)
concDataSet$yDimension <- ospDimensions$`Concentration (molar)`
concDataSet$molWeight <- 1


# Create DataCombined and add the data set
myCombDat <- DataCombined$new()
myCombDat$addDataSets(concDataSet)
```

The unit is `µmol/l`. Now, in the plot configuration, we can define `mg/l` as the unit we want the data to be plotted in:

```
plotConfiguration <- ospsuite::DefaultPlotConfiguration$new()
plotConfiguration$yUnit <- ospUnits$`Concentration [mass]`$`mg/l`
```

We tried to get  the *target*  dimension using 

```
  xTargetDim <- getDimensionForUnit(xTargetUnit)
  yTargetDim <- getDimensionForUnit(yTargetUnit)
```

so we can pass the dimension as the caption of the y-axis. Unfortunately, this does not work for the dimension `Time`, as 

```
> getDimensionForUnit(ospUnits$Time$`week(s)`)
[1] "Age in years"
```

With the fix, we do not retrieve the target dimension, but this results in confusing y-axis caption like "Concentration (molar) [mg/l]" (and could even be "Amount [g]".

Any idea how to overcome this?

**Comment by msevestre** [comment]
Isn't the problem simply that using the dimension name as label is maybe not the right tool? It seems to me that this should be a property of the `plotConfiguration`: e.g. "yCaption" or sthg like this and we add automatically the unit after the property?

**Comment by PavelBal** [comment]
The user can define a custom caption, yes. But by default, it is rather handy that the dimension is shown as the caption.

Probably in >90% of use cases having just "Concentration" instead of "Concentration (molar)" would solve the problem. Actually, PK-Sim and MoBi are somehow doing it. Is there some kind of a "simplified name" of a dimension?

BTW, Pk-Sim shows "Amount [g]" if gramm is selected as unit, which is not entirelly correct :D 

![image](https://user-images.githubusercontent.com/25903040/168038615-984568da-4db8-4345-b717-581e580857ef.png)

**Comment by msevestre** [comment]
Probably the easiest way at this stage is to hard code this e.g.
No caption provided and dimension is concentration molar or mass, then caption is Concentration
PKSim and Mobi do this at the dimension conversion level when we create this MergedDimenstion to convert one from the other I believe
