### ISSUE TITLE
Setting a grouping in `DataCombined` when adding a data set

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#937]
I cannot remember - why (and where) did we decide to **not** allow setting the group property in the `add` methods?

So instead of 

```
  currentDataCombined$addSimulationResults(simulationResults = simulatedScenarios[[scenarioName]]$results,
                                           quantitiesOrPaths = OutputPaths$bOH_production_fraction_liv,
                                           names = "4ßOH liver production fraction simulated")
  currentDataCombined$setGroups(names = "4ßOH liver production fraction simulated", groups = "liver")
```

it would be 

```
  currentDataCombined$addSimulationResults(simulationResults = simulatedScenarios[[scenarioName]]$results,
                                           quantitiesOrPaths = OutputPaths$bOH_production_fraction_liv,
                                           names = "4ßOH liver production fraction simulated",
                                           groups = "liver"
)
```

I find it not convenient to do it in two steps, as I have to keep track of the names and repeat them in the code.

**Comment by IndrajeetPatil** [comment]
cf. https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/728#issuecomment-1023355462

**Comment by IndrajeetPatil** [comment]
I think this should be easy to implement. 

But we should also retain the `$setGroups()` method. This way, even if I didn't want to group when I added datasets using `$add*()` methods, I still have a method to add groupings later on if I wish to do so instead of having to start over by adding datasets once again.
