### ISSUE TITLE
Replace "Concentration (molar)" and "Concentration (mass)" by "Concentration" in plot axis labels

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#938]
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/928#issuecomment-1124755911

**Comment by IndrajeetPatil** [comment]
Follow up in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/974
