### ISSUE TITLE
Update to latest Roxygen: Local issue

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#949]
@IndrajeetPatil Any idea what this means?
Error in cli::style_hyperlink(paste0(basename(file), ":", line), paste0("file://",  : 
  unused argument (params = c(line = line, col = 1))
Calls: suppressPackageStartupMessages ... roxy_tag_parse.roxy_tag_title -> warn_roxy_tag -> paste0 -> link_to -> paste0
Execution halted

I needed to update ROxygen to 7.2 because of latest change 
Now I can't generate docs locally. Any help appreciated

**Comment by msevestre** [comment]
warning during installation

package ‘glue’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘glue’
Warning in install.packages :
  problem copying C:\Users\Michael\Documents\R\win-library\4.1\00LOCK\glue\libs\x64\glue.dll to C:\Users\Michael\Documents\R\win-library\4.1\glue\libs\x64\glue.dll: Permission denied
Warning in install.packages :
  restored ‘glue’
package ‘cli’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘cli’
Warning in install.packages :
  problem copying C:\Users\Michael\Documents\R\win-library\4.1\00LOCK\cli\libs\x64\cli.dll to C:\Users\Michael\Documents\R\win-library\4.1\cli\libs\x64\cli.dll: Permission denied
Warning in install.packages :
  restored ‘cli’

How do I give R studio the right to overwrite stuff?

**Comment by IndrajeetPatil** [comment]
Yeah, this is a bit of a pain in the ass.

You can try to update the packages in a fresh RStudio session without any R script open that might load any of these packages.

If that doesn't work, then you need to uninstall them manually using the _Packages_ pane in the IDE and then reinstall them to the latest version.

<img width="531" alt="Screenshot 2022-05-14 at 18 55 09" src="https://user-images.githubusercontent.com/11330453/168441327-9712b731-2d49-4690-9124-94ec26d34f07.png">

**Comment by msevestre** [comment]
ok that worked after a reboot, closing, deleting , reinstalling etc...
