### ISSUE TITLE
Should we rename simulation to model in the R rewrite?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#95]
So that it is consistent with what we are implementing for the modularization

* Model (instead of Simulation)
* loadModel (instead of loadSimulation)

Now I am not sure if you `simulate(model)` ? or `run(model)`

Let's discuss

/cc @Yuri05

**Comment by PavelBal** [comment]
Let's do `simulate(model)`. What will it return? Respectively - are the results written in the same .NET object that also represents the model?

**Comment by msevestre** [comment]
The problem is that we have a difference of nomenclature internally and I am starting to wonder if we should stick with the current naming for now. The Osmose stuff won't be out for at least a year if not more.

We simulate a simulation at the moment. The results are not stored in the object directly. This is what we will return from the simulate call.

The question is: what do we return? I want to avoid converting object back and forth between .net and r

**Comment by PavelBal** [comment]
> The results are not stored in the object directly. This is what we will return from the simulate call.

Does this mean that we **have to** store all the results in R after calling `simulate` (or `run` or whatever), because we have no access to them later?

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/60

in .NET it works as follow

```
var data = simulationRunner.Simulate(simulation);

// data is a structure with one entry per output. Each entry is a double array in disguise called QuantityValues 
```

All described in #60

**Comment by msevestre** [comment]
We could store the resulting data in the R simulation. (this is what is done in MoBi in PKSim). Each simulation stores its own data

**Comment by PavelBal** [comment]
Before we proceed with coding - did we now decide to keep the "simulation" nomenclature?

I personally prefer `model` and then `simulate(model)`.

**Comment by msevestre** [comment]
Cleary @Yuri05 does not have an opinion. Closing for now
Once we have a better understanding of the new pkml mobi structure, we will be able to revisit the implementation
