### ISSUE TITLE
"Save plot to file" configuration

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#964]
The current workflow to create plots is:

1. Create `DataCombined` object and populate with data
2. Create `DefaultPlotConfiguration` object and define settings for a plot
3. Create ggplot2 object with `plotIndividualTimeProfile` with the `DataCombined` and `DefaultPlotConfiguration`
4. Create `PlotGridConfiguration` to combine multiple plots to one figure
5. Create ggplot2 object with `plotGrid`

The last step is to save the generated plots into a file using `ggsave`. We might want to have a reusable configuration for the following parameters:

- outputFolderPath
- fileFormat = "png",
- saveFileWidth = 16,
- saveFileHeight = 9,
- saveFileDimensionUnits = "cm",
- saveFileDpi = 300
- scale
- ???

**Comment by IndrajeetPatil** [comment]
This functionality already exists in _tlf_:
https://www.open-systems-pharmacology.org/TLF-Library/reference/ExportConfiguration.html
