### ISSUE TITLE
ospsuite v11 release

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#971]
With _tlf_ and _ospsuite.utils_ pre-releases out, I think we are also ready for _ospsuite_ release. 

No outstanding issues from my end that block this release. 

Please comment if you see something that needs to be dealt with before this release.

**Comment by Yuri05** [comment]
(Pre)release created:
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/releases/tag/v11.0.123

Also created new tags of the ospsuite-r Docker images with the version 11.0.123

**Comment by IndrajeetPatil** [comment]
Awesome! Thanks.

**Comment by msevestre** [comment]
Don't we need to update the doc website to use the expected version? Eg. the tagged version?

**Comment by IndrajeetPatil** [comment]
I am a bit mystified by how we are versioning package releases.

For example, _ospsuite_ package version in `DESCRIPTION` file on the `main`-branch is `11.0.0`.

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/cf12170361587eb66b6866cbcbc20f2d32dcd6ff/DESCRIPTION#L4

But the pre-release version is [11.0.123](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/releases/tag/v11.0.123), which doesn't match with the one in `DESCRIPTION`. 

The _pkgdown_ docs get their package version from this file as well, so if we want to have the docs with the same version as the pre-release, we need to bump the package version in `DESCRIPTION` to pre-release version first.

**Comment by Yuri05** [comment]
Appveyor package build **patches the DESCRIPTION file** every time the new build is created and replaces the 3rd version number with the current (appveyor) build number. Done so to automatically increment the build number with every new build.

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/277c76df20dd7bdf77645963b49f4ef130203547/appveyor-nightly.yml#L38

Which calls:
https://github.com/Open-Systems-Pharmacology/build-scripts/blob/53de3bec323595b9997c153d2876fb4ccd5fb5a8/R.rb#L4-L12

When creating documentaion manually (like here in the ospsuite-R) - you could temporarily set the build number in the DESCRIPTION file to the desired number (e.g. 123 for the current 11.0 release), create the documentation and then set the build number in DESCRIPTION back to 0.
During the development it does not matter, so no need for that. 
Only when creating the final documentation before the next package release. 

Don't know if there is a better way of doing this.

**Comment by Yuri05** [comment]
I mean, calling pkgdown could be also done on AppVeyor in every nightly build (then no need of "manual version patching) - but the build time will increase then.
@msevestre

**Comment by Yuri05** [comment]
@IndrajeetPatil Can you do this?
* change the version locally temporarily to 11.0.23
* generate the docs
* reset the version back to 12.0.0.9000
* Commit

Then we should have the right version on the website
