### ISSUE TITLE
Nightly build broken (due to a stochastic test?) 

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#974]
Of course, the first time the nightly build fails is after release 🤦 

I am not sure why a test that [passed in a PR](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/968) is now failing on [nightly](https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-r).

My best guess that there is some stochastic element here that makes `.createAxesLabels()` produce the `yLabel` to be sometimes `"Concentration [µmol/l]"`, while other times `"Concentration [mg/l]"` in the context of this specific test:

``` r
library(ospsuite)
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000
options(tibble.width = Inf)

concDataSet <- DataSet$new(name = "Concentration data set")
concDataSet$setValues(1, 1)
concDataSet$yDimension <- ospDimensions$`Concentration (molar)`
concDataSet$molWeight <- 1

amountDataSet <- DataSet$new(name = "Amount data set")
amountDataSet$setValues(1, 1)
amountDataSet$yDimension <- ospDimensions$`Concentration (mass)`
amountDataSet$molWeight <- 1

myCombDat <- DataCombined$new()
myCombDat$addDataSets(c(concDataSet, amountDataSet))

(df <- myCombDat$toDataFrame())
#> # A tibble: 2 x 14
#>   name                   group dataType xValues xUnit xDimension yValues yUnit 
#>   <chr>                  <chr> <chr>      <dbl> <chr> <chr>        <dbl> <chr> 
#> 1 Amount data set        <NA>  observed       1 h     Time          1.00 mg/l  
#> 2 Concentration data set <NA>  observed       1 h     Time          1    µmol/l
#>   yDimension            yErrorValues yErrorType yErrorUnit molWeight  lloq
#>   <chr>                        <dbl>      <dbl>      <dbl>     <dbl> <dbl>
#> 1 Concentration (mass)            NA         NA         NA         1    NA
#> 2 Concentration (molar)           NA         NA         NA         1    NA

(df <- ospsuite:::.unitConverter(df))
#> # A tibble: 2 x 14
#>   name                   group dataType xValues xUnit xDimension yValues yUnit 
#>   <chr>                  <chr> <chr>      <dbl> <chr> <chr>        <dbl> <chr> 
#> 1 Amount data set        <NA>  observed       1 h     Time         1000. µmol/l
#> 2 Concentration data set <NA>  observed       1 h     Time            1  µmol/l
#>   yDimension            yErrorValues yErrorType yErrorUnit molWeight  lloq
#>   <chr>                        <dbl>      <dbl> <chr>          <dbl> <dbl>
#> 1 Concentration (mass)            NA         NA µmol/l             1    NA
#> 2 Concentration (molar)           NA         NA µmol/l             1    NA

ospsuite:::.createAxesLabels(df, tlf::TimeProfilePlotConfiguration$new())
#> $xLabel
#> [1] "Time [h]"
#> 
#> $yLabel
#> [1] "Concentration [µmol/l]"
```

<sup>Created on 2022-05-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by PavelBal** [comment]
The axis labels in this case should be just "Concentration", you have implemented this?

**Comment by IndrajeetPatil** [comment]
Really? So no unit in the axes labels?

In https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/938, you specified that:

> Replace "Concentration (molar)" and "Concentration (mass)" by "Concentration" in plot axis labels

But there was no discussion about whether the unit should also be removed from axis label.

I will make that change then.

**Comment by PavelBal** [comment]
Wait STOP, I didn't get it right. The unit should of course stay!

**Comment by PavelBal** [comment]
How can it be stochastic?

**Comment by IndrajeetPatil** [comment]
Yeah, that's what I am trying to investigate. 

My hunch is that this has something to do with which unit is picked up when there is a tie for the most frequent unit.

**Comment by Yuri05** [comment]
I just retriggered the build manually - and all tests passed...
![grafik](https://user-images.githubusercontent.com/25061876/169798079-b019e3c6-b958-497b-9568-d375c9f08c3c.png)
https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-r/builds/43629828

>My hunch is that this has something to do with which unit is picked up when there is a tie for the most frequent unit.
Probably something like that (if in the test we have the same number of points in [mg/l] and [µmol/l])

**Comment by IndrajeetPatil** [comment]
@Yuri05 What `$yLabel` do you get if you run the code in my [comment ](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/974#issue-1244873459) above?

**Comment by Yuri05** [comment]
```
> (df <- myCombDat$toDataFrame())
# A tibble: 2 x 14
  name                   group dataType xValues xUnit xDimension yValues yUnit  yDimension            yErrorValues
  <chr>                  <chr> <chr>      <dbl> <chr> <chr>        <dbl> <chr>  <chr>                        <dbl>
1 Amount data set        NA    observed       1 h     Time          1.00 mg/l   Concentration (mass)            NA
2 Concentration data set NA    observed       1 h     Time          1    µmol/l Concentration (molar)           NA
  yErrorType yErrorUnit molWeight  lloq
       <dbl>      <dbl>     <dbl> <dbl>
1         NA         NA         1    NA
2         NA         NA         1    NA

> (df <- ospsuite:::.unitConverter(df))
# A tibble: 2 x 14
  name                   group dataType xValues xUnit xDimension yValues yUnit  yDimension            yErrorValues
  <chr>                  <chr> <chr>      <dbl> <chr> <chr>        <dbl> <chr>  <chr>                        <dbl>
1 Amount data set        NA    observed       1 h     Time         1000. µmol/l Concentration (mass)            NA
2 Concentration data set NA    observed       1 h     Time            1  µmol/l Concentration (molar)           NA
  yErrorType yErrorUnit molWeight  lloq
       <dbl> <chr>          <dbl> <dbl>
1         NA µmol/l             1    NA
2         NA µmol/l             1    NA

> ospsuite:::.createAxesLabels(df, tlf::TimeProfilePlotConfiguration$new())
$xLabel
[1] "Time [h]"

$yLabel
[1] "Concentration [µmol/l]"
```

**Comment by Yuri05** [comment]
by the way: the test failed again in the manually triggered build while executed for the second time within the code coverage...

**Comment by IndrajeetPatil** [comment]
Wow, `"Concentration [µmol/l]"` is what I see locally as well, but it fails in the PR: https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/976

And `"Concentration [mg/l]"` is what we have in the nightly build, and that also fails.

Definitely stochastic.

![RyanReynoldsFacepalmGIF](https://user-images.githubusercontent.com/11330453/169804216-0b3e3da8-2f41-469f-89c0-c67b730b4d39.gif)

**Comment by Yuri05** [comment]
I would suggest to **add the 2nd data row** to the "Concentration mass" data set (which is in [mg/l]).
Then the most frequent unit should always return [mg/l].

Having 1 row in [µmol/l] and 1 row in [mg/l] - the most frequent unit is in fact undefined
(still I would expect that R always returns the same unit though)

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/277c76df20dd7bdf77645963b49f4ef130203547/tests/testthat/test-utilities-plotting.R#L31-L51

Some questions/remarks on the test:
* Let's rename `amountDataSet  `to `concentrationMassDataSet ` (and to be consistent: `concDataSet  `=> `concentrationMolarDataSet `)
* For both data sets units are not explicitly set. For the molar concentration returned unit is then [µmol/l] - which I can understand, because it's the OSP internal base unit for the dimension "Concentration (molar)". 
But why is the default unit for the "Concentration (mass)" data set [mg/l]? This is not the OSP internal unit - so where does it come from?

**Comment by msevestre** [comment]
Isn't it the internal default **display** unit?

**Comment by Yuri05** [comment]
>Isn't it the default unit? (Doesn't have to be the base unit)

Probably yes :)

**Comment by IndrajeetPatil** [comment]
Indeed:

``` r
library(ospsuite)
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000
options(tibble.width = Inf)

concentrationMassDataSet  <- DataSet$new(name = "Amount data set")
concentrationMassDataSet $setValues(1, 1)
concentrationMassDataSet $yDimension <- ospDimensions$`Concentration (mass)`
concentrationMassDataSet $molWeight <- 1

dataSetToTibble(concentrationMassDataSet )
#> # A tibble: 1 x 12
#>   name            xValues yValues yErrorValues xDimension xUnit
#>   <chr>             <dbl>   <dbl>        <dbl> <chr>      <chr>
#> 1 Amount data set       1    1.00           NA Time       h    
#>   yDimension           yUnit yErrorType yErrorUnit molWeight  lloq
#>   <chr>                <chr>      <dbl>      <dbl>     <dbl> <dbl>
#> 1 Concentration (mass) mg/l          NA         NA         1    NA
```

<sup>Created on 2022-05-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
