### ISSUE TITLE
`plotIndividualTimeProfile` - multiple observed data within one group should get different symbols

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#980]
![RIF 20mg qd 14d_DC](https://user-images.githubusercontent.com/25903040/169998225-1f894123-97fe-4ba1-a722-28ae0dbde2a2.PNG)

Panel B - there are two observed data sets, both having the same symbols. They should have different symbols.

In the legend, only one entry should be shown, using the symbol of the first observed data (so basically the legend should not change).

**Comment by IndrajeetPatil** [comment]
Minimal reproducible example:

``` r
library(ospsuite)
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000

dataSet1 <- DataSet$new(name = "Dataset1")
dataSet1$setValues(1, 1)
dataSet1$yDimension <- ospDimensions$`Concentration (molar)`
dataSet1$molWeight <- 1

dataSet2 <- DataSet$new(name = "Dataset2")
dataSet2$setValues(2, 2)
dataSet2$yDimension <- ospDimensions$`Concentration (mass)`
dataSet2$molWeight <- 1

dataSet3 <- DataSet$new(name = "Dataset3")
dataSet3$setValues(1, 3)
dataSet3$yDimension <- ospDimensions$`Concentration (mass)`
dataSet3$molWeight <- 1

myCombDat <- DataCombined$new()
myCombDat$addDataSets(
  c(dataSet1, dataSet2, dataSet3),
  groups = c("myGroup", "myGroup", "myGroup")
)

plotIndividualTimeProfile(myCombDat)
#> Warning: Removed 3 rows containing missing values (geom_segment).
#> Removed 3 rows containing missing values (geom_segment).
```

![](https://i.imgur.com/t4PVO1o.png)

<sup>Created on 2022-05-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by IndrajeetPatil** [comment]
@pchelle can correct me if I am mistaken about this, but AFAIK this is currently not possible with _tlf_.

The color, shape, linetype, etc. are all currently mapped to group. That is, each group will get its own color, shape, linetype, etc. But there is no way to further specify any mapping _within each group_, which is what needs to happen here.

I am not sure, but maybe adding `shape` to time-profile data mappings might make it possible? Currently, it doesn't support that:

```r
TimeProfileDataMapping$new(
  x = NULL,
  y = NULL,
  ymin = NULL,
  ymax = NULL,
  group = NULL,
  color = NULL,
  fill = NULL,
  linetype = NULL
)
```

If it is supported, maybe we can do something like the following to support the current FR:

```r
TimeProfileDataMapping$new(
  color = "group", # each group gets its own color
  shape = "name", # each datasets gets its own shape
  linetype = "group"
)
```

**Comment by IndrajeetPatil** [comment]
@PavelBal Can you confirm that the legend for the plot should look something like this? 

The way _ggplot2_ is designed, all aesthetic mappings are shown in the legend.

![image](https://user-images.githubusercontent.com/11330453/172601996-20e2d29e-c1d2-47e5-ad89-a406e998a4b2.jpeg)

**Comment by PavelBal** [comment]
No, in this case, only three legend entries should be present, one per grouping. The presented symbol should be the first symbol used in the grouping.

**Comment by IndrajeetPatil** [comment]
IINM, the latter plot is what you have in mind, right? That is, use two separate visual encodings but only show one in the legend?

``` r
library(tidyverse)

df <- dplyr::tibble(
  xValues = rep(c(0, 1, 2, 3, 4), 4),
  yValues = sample.int(20, 20), 
  group = c(rep("myGroup1", 10), rep("myGroup2", 10)), 
  name = c(rep("data1", 5),  rep("data2", 5), rep("data3", 5),  rep("data4", 5))
)

ggplot(df, aes(xValues, yValues, color = group, shape = name)) + 
  geom_point(size = 3)
```

![](https://i.imgur.com/MpkixhS.png)

``` r

ggplot(df, aes(xValues, yValues, color = group, shape = name)) + 
  geom_point(size = 3) +
  guides(shape = "none")
```

![](https://i.imgur.com/DDJtRWm.png)

<sup>Created on 2022-07-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by PavelBal** [comment]
Yes.

**Comment by IndrajeetPatil** [comment]
But isn't that confusing? 

Looking at this plot, the legend gives you no clue as to what the shapes are representing, or which shape represents which dataset.

![image](https://user-images.githubusercontent.com/11330453/180476499-47c258c2-5058-44fe-b7fd-f2ffa7f3798f.png)

**Comment by PavelBal** [comment]
Sometimes it is not necessary to see the exact names of the data sets but just to see wich points belong to a data set (e.g., data from 10 individuals... we don't want to see 10 entries in the legend, it is sufficient to see which points belong to the same individual).

If the user wants to see directly which points belong to which data set, he can just assign them to a separate groups ;)

**Comment by IndrajeetPatil** [comment]
Got it!

cc @pchelle

**Comment by IndrajeetPatil** [comment]
With #1054

``` r
library(ospsuite)
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000

dataSet1 <- DataSet$new(name = "Dataset1")
dataSet1$setValues(1, 1)
dataSet1$yDimension <- ospDimensions$`Concentration (molar)`
dataSet1$molWeight <- 1

dataSet2 <- DataSet$new(name = "Dataset2")
dataSet2$setValues(2, 1)
dataSet2$yDimension <- ospDimensions$`Concentration (mass)`
dataSet2$molWeight <- 1

dataSet3 <- DataSet$new(name = "Dataset3")
dataSet3$setValues(1, 3)
dataSet3$yDimension <- ospDimensions$`Concentration (mass)`
dataSet3$molWeight <- 1

myCombDat <- DataCombined$new()
myCombDat$addDataSets(
  c(dataSet1, dataSet2, dataSet3),
  groups = "myGroup"
)

plotIndividualTimeProfile(myCombDat)
#> Warning: Removed 3 rows containing missing values (geom_segment).
#> Removed 3 rows containing missing values (geom_segment).
```

![](https://i.imgur.com/c05HwjC.png)

<sup>Created on 2022-07-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
