### ISSUE TITLE
`plotIndividualTimeProfile` strange axis ticks if axis scaling is log

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#981]
![RIF 20mg qd 14d_DC](https://user-images.githubusercontent.com/25903040/169998662-281f216d-bf09-4e5f-aa27-11f2e95fdcff.PNG)

Panel d - this is not what a user would expect (e.g. compare how PK-Sim presents such numbers).

**Comment by IndrajeetPatil** [comment]
cc @pchelle

**Comment by Yuri05** [comment]
@PavelBal But RE plot is in **log** scale and PK-Sim plot is in **lin** scale, right?
