### ISSUE TITLE
Snake case for methods and fields of R6 objects

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#99]
According to https://adv-r.hadley.nz/:

> By convention, methods and fields use `snake_case`

I would propose to stick to this convention. We can still name the non-OOP functions with `camelCase`. This way, it is easier to distinguish between functions and functions of objects.

**Comment by PavelBal** [comment]
@msevestre @ju-rgen

**Comment by PavelBal** [comment]
I think we agreed on NOT to. Closing.

**Comment by ju-rgen** [comment]
I am confused - so we stick to camelCase, right?

**Comment by PavelBal** [comment]
@ju-rgen Right.
