### ISSUE TITLE
Not working in R version 4.2.0 (2022-04-22) -- "Vigorous Calisthenics"

### ISSUE THREAD

**Issue by sandrinecharles** [Open-Systems-Pharmacology/OSPSuite-R#991]
Dear colleagues, I did not find the way to use your OSPSuite-R from Mac OS X Monterey (version 12.3.1), where I am using the R version 4.2.0 (2022-04-22) -- "Vigorous Calisthenics". Any idea to help and assist me?

**Comment by msevestre** [comment]
Hi @sandrinecharles ,

MacOS is not supported at the moment. Only windows and Linux (Ubuntu and CentOS). There are docker images provided to get you going on Linux.
