### ISSUE TITLE
Function `IsExplicitFormulaByPath`

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#997]
Various scenarios require checking if a value of a quantity is given by an explicit formula or a constant. As we found out, getting this property from path using the `ContainerTask` and `IsExplicitFormulaByPath` method is much more efficient than actually creating the quantity objects.

So far, `IsExplicitFormulaByPath` has only been used experimentally in `esqlabsR` package for calculating the steady-state of a simulation. Now, the parameter identification package also requires this function. I have been using the `:::` reference to get the container task and call the .NET method:

```
task <- ospsuite:::getContainerTask()
isFormulaExplicit <- rClr::clrCall(task, "IsExplicitFormulaByPath", simulation$ref, enc2utf8(path))
```

However, I do not want to use this approuch in the "official" package, so I would vote for creating and exporting a `isExplicitFormulaByPath`-function.

@msevestre

**Comment by PavelBal** [comment]
@msevestre any objections?

**Comment by msevestre** [comment]
No objections. 
Any reason for `However, I do not want to use this approuch in the "official" package,` 

Are there other methods that should be exported like this as well?

**Comment by PavelBal** [comment]
> Any reason for However, I do not want to use this approuch in the "official" package,

I want to avoid using `:::` to access not exposed functions of the package. As you once said, accessing `:::` is a misuse of the API ;) 

> Are there other methods that should be exported like this as well?

Nothing we require currently.
